from __future__ import annotations


def render_research_core(project_id: str) -> str:
    """Render the only user-owned scientific semantics module.

    The default body is deliberately semantics-neutral: one CUSTOM root only keeps
    a freshly-created project structurally valid. Authors may replace the entire
    function with arbitrary Python that returns any valid ResearchPortfolio.
    """
    if type(project_id) is not str or not project_id.strip():
        raise ValueError("research core project_id must be non-empty")
    return f'''"""USER-OWNED scientific semantics.

This is the generated user-owned entrypoint. You may keep all scientific code
here or import arbitrary package-local modules/subpackages that you own.

Replace the entire body of build_research() with the real research core. You may
construct any number of ResearchPrograms, any DAG, any definitions, CUSTOM
semantics, Method/Memory/Participant/Runtime programs, Machine-backed methods,
benchmarks, experiments, analyses, or cross-program dependencies. The project
scaffold does not prescribe scientific topology or source layout.

Everything outside this file is platform shell: packaging, validation, execution
wiring, scheduling, evidence, artifacts, checkpoint/recovery and live revision
control remain Noetrium-owned.
"""
from noetrium import api


def _bootstrap():
    """Minimal pure executable used only until the author replaces this core."""
    return None


def build_research() -> api.ResearchPortfolio:
    # Executable semantics-neutral bootstrap only. Replace this entire body.
    portfolio = api.ResearchPortfolioBuilder({project_id!r})
    program = portfolio.program({project_id!r})
    program.custom_definition("bootstrap", implementation=_bootstrap)
    program.custom_node("root", definitions=("bootstrap",))
    return portfolio.freeze()


__all__ = ["build_research"]
'''


def render_research_module(project_id: str) -> str:
    """Render platform-owned shell around the unconstrained user semantic core."""
    if type(project_id) is not str or not project_id.strip():
        raise ValueError("research module project_id must be non-empty")
    return f'''"""AUTO-GENERATED Research OS shell. Do not edit this file."""
from noetrium import api
from .core import build_research as _build_research


PORTFOLIO = _build_research()
if not isinstance(PORTFOLIO, api.ResearchPortfolio):
    raise TypeError("build_research() must return noetrium.api.ResearchPortfolio")
if PORTFOLIO.portfolio_id != {project_id!r}:
    raise ValueError(
        "build_research() portfolio_id must match the project identity"
    )

PROGRAMS = PORTFOLIO.programs

__all__ = ["PORTFOLIO", "PROGRAMS"]
'''


def render_generated_test_module(package: str, project_id: str) -> str:
    if type(package) is not str or not package.strip():
        raise ValueError("generated test package must be non-empty")
    if type(project_id) is not str or not project_id.strip():
        raise ValueError("generated test project_id must be non-empty")
    return f'''import unittest

from noetrium import api
from {package}.research import PORTFOLIO, PROGRAMS


class GeneratedProjectTests(unittest.TestCase):
    def test_user_core_builds_top_level_research_os_contract(self):
        self.assertIsInstance(PORTFOLIO, api.ResearchPortfolio)
        self.assertEqual(PORTFOLIO.portfolio_id, {project_id!r})
        self.assertEqual(PROGRAMS, PORTFOLIO.programs)

    def test_scaffold_does_not_impose_scientific_topology(self):
        self.assertTrue(PROGRAMS)
        self.assertEqual(PROGRAMS, PORTFOLIO.programs)
        self.assertEqual(
            len({{program.program_id for program in PROGRAMS}}),
            len(PROGRAMS),
        )


if __name__ == "__main__":
    unittest.main()
'''


__all__ = [
    "render_generated_test_module",
    "render_research_core",
    "render_research_module",
]
