from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path
from typing import Callable, Iterator, ParamSpec, Protocol, TypeVar

from noetrium_platform.evidence.observability.api import EventEnvelope
from noetrium_platform.foundation.kernel.kernel import JsonDocument
from noetrium_platform.infrastructure.reliability.failure.api import FailureEnvelope
from noetrium_platform.infrastructure.reliability.diagnostics.api.records import (
    DiagnosticObjectRecord, OperationInvocationRecord, StateWriterRecord,
)

from .ledger import VerifiedLedgerCut, VerifiedLedgerSlice
from .mutation import MutationRecord

P = ParamSpec("P")
T = TypeVar("T")


class ForensicWriteActorPort(Protocol):
    @property
    def actor_id(self) -> str: ...

    def call(
        self,
        operation: str,
        fn: Callable[P, T],
        /,
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> T: ...


class ForensicLedgerPort(Protocol):
    @property
    def cached_tail(self) -> tuple[int, str]: ...
    def append(self, payload: dict[str, object]) -> str: ...
    def find_payload(self, field: str, value: str) -> dict[str, object] | None: ...
    def verify(self) -> tuple[int, str]: ...
    def verified_payloads_after(self, offset: int) -> VerifiedLedgerSlice: ...
    def verified_cut_after(self, offset: int) -> VerifiedLedgerCut: ...
    def iter_verified_payload_batches(
        self, cut: VerifiedLedgerCut, *, batch_size: int = 512
    ) -> Iterator[tuple[JsonDocument, ...]]: ...


class ForensicIndexReadSessionPort(Protocol):
    def locate(self, object_id: str) -> DiagnosticObjectRecord | None: ...
    def last_writer(self, run_id: str, state_name: str) -> StateWriterRecord | None: ...
    def around(
        self, *, run_id: str, timestamp: float, seconds: float = 30.0
    ) -> tuple[DiagnosticObjectRecord, ...]: ...
    def recent_state_writers(
        self, *, run_id: str, before: float, limit: int = 12
    ) -> tuple[StateWriterRecord, ...]: ...
    def related_to(self, object_id: str, *, limit: int = 100) -> tuple[DiagnosticObjectRecord, ...]: ...
    def operation_invocation(self, invocation_id: str) -> OperationInvocationRecord | None: ...
    def unclosed_operations(
        self, *, run_id: str | None = None, limit: int = 100
    ) -> tuple[OperationInvocationRecord, ...]: ...
    def operations_open_at(
        self, *, run_id: str, timestamp: float, limit: int = 100
    ) -> tuple[OperationInvocationRecord, ...]: ...


class ForensicIndexPort(ForensicIndexReadSessionPort, Protocol):
    def add_event(self, event: EventEnvelope) -> None: ...
    def add_failure(self, failure: FailureEnvelope) -> None: ...
    def add_mutation(self, mutation: MutationRecord) -> None: ...
    def add_raw_payload(self, kind: str, payload: dict[str, object]) -> None: ...
    def project_event(self, event: EventEnvelope, *, rows: int, tail_hash: str) -> None: ...
    def project_events_batch(self, items: tuple[tuple[EventEnvelope, int, str], ...]) -> None: ...
    def project_failure(self, failure: FailureEnvelope, *, rows: int, tail_hash: str) -> None: ...
    def project_mutation(self, mutation: MutationRecord, *, rows: int, tail_hash: str) -> None: ...
    def set_freshness(self, ledger: str, rows: int, tail_hash: str) -> None: ...
    def set_read_barrier(self, callback: Callable[[], None]) -> None: ...
    def read_session(self) -> AbstractContextManager[ForensicIndexReadSessionPort]: ...
    def freshness(self) -> dict[str, tuple[int, str]]: ...
    def close(self) -> None: ...


class ForensicEventWriteLanePort(Protocol):
    def append(self, event: EventEnvelope) -> str: ...
    def flush(self) -> None: ...
    def critical_call(self, fn: Callable[[], T]) -> T: ...
    def backlog(self) -> int: ...


class ForensicCriticalWriteLanePort(Protocol):
    def append_owned(self, obj: object) -> str: ...


class ForensicWriterLeasePort(Protocol):
    def release(self) -> None: ...


class ForensicStorePort(Protocol):
    @property
    def root(self) -> Path: ...
    @property
    def failures(self) -> ForensicLedgerPort: ...
    @property
    def events(self) -> ForensicLedgerPort: ...
    @property
    def mutations(self) -> ForensicLedgerPort: ...
    @property
    def index(self) -> ForensicIndexPort: ...
    def append_event(self, event: EventEnvelope) -> str: ...
    def append_failure(self, failure: FailureEnvelope) -> str: ...
    def append_failure_once(self, failure: FailureEnvelope) -> tuple[bool, str | None]: ...
    def append_mutation(self, mutation: MutationRecord) -> str: ...
    def flush_projections(self) -> None: ...
    def projection_backlog(self) -> int: ...
    def verify_all(self) -> dict[str, tuple[int, str]]: ...
    def index_freshness(
        self,
    ) -> tuple[bool, dict[str, tuple[int, str]], dict[str, tuple[int, str]]]: ...


__all__ = [
    "ForensicCriticalWriteLanePort",
    "ForensicEventWriteLanePort",
    "ForensicIndexPort",
    "ForensicIndexReadSessionPort",
    "ForensicLedgerPort",
    "ForensicStorePort",
    "ForensicWriterLeasePort",
    "ForensicWriteActorPort",
]
