from __future__ import annotations
from ..api.contracts import MetricDefinition, MetricKind


def definitions() -> tuple[MetricDefinition, ...]:
    C=MetricKind.COUNTER; G=MetricKind.GAUGE; H=MetricKind.HISTOGRAM
    return (
        MetricDefinition("python.gc.pause",H,"seconds",("generation","component"),"Python GC pause duration"),
        MetricDefinition("python.gc.collections",C,"count",("generation","component"),"Python GC collections"),
        MetricDefinition("python.gc.collected",C,"count",("generation","component"),"Python objects collected"),
        MetricDefinition("python.gc.uncollectable",C,"count",("generation","component"),"Python uncollectable objects"),
        MetricDefinition("python.memory.rss",G,"bytes",("component",),"Process resident memory"),
        MetricDefinition("python.memory.vms",G,"bytes",("component",),"Process virtual memory"),
        MetricDefinition("python.event_loop.lag",H,"seconds",("component","loop"),"Event-loop scheduling lag"),
        MetricDefinition("python.executor.queue",G,"count",("component","executor"),"Executor queued work"),
        MetricDefinition("network.connect.latency",H,"seconds",("service","endpoint_class","result"),"Connection establishment latency"),
        MetricDefinition("network.dns.latency",H,"seconds",("service","result"),"DNS resolution latency"),
        MetricDefinition("network.bytes.rx",C,"bytes",("service","endpoint_class"),"Network receive bytes"),
        MetricDefinition("network.bytes.tx",C,"bytes",("service","endpoint_class"),"Network transmit bytes"),
        MetricDefinition("network.errors",C,"count",("service","stage","kind"),"Network errors by stage"),
        MetricDefinition("model.scheduler.iteration",H,"seconds",("model","engine","replica"),"Model scheduler iteration time"),
        MetricDefinition("model.scheduler.decode_batch",H,"requests",("model","engine","replica"),"Decode batch request count"),
        MetricDefinition("model.scheduler.prefill_batch",H,"requests",("model","engine","replica"),"Prefill batch request count"),
        MetricDefinition("model.scheduler.tokens",H,"tokens",("model","engine","replica","phase"),"Scheduled token count"),
        MetricDefinition("model.prefix_cache.bytes",G,"bytes",("model","engine","replica"),"Prefix cache resident bytes"),
        MetricDefinition("model.weights.bytes",G,"bytes",("model","engine","replica"),"Loaded model weight bytes"),
        MetricDefinition("model.cuda_graph.hit",C,"count",("model","engine","replica"),"CUDA graph reuse count"),
        MetricDefinition("model.cuda_graph.miss",C,"count",("model","engine","replica"),"CUDA graph miss count"),
        MetricDefinition("model.oom",C,"count",("model","engine","replica","stage"),"Model-serving OOM events"),
        MetricDefinition("gpu.ecc.errors",C,"count",("gpu","kind"),"GPU ECC error count"),
        MetricDefinition("gpu.xid.errors",C,"count",("gpu","class"),"GPU Xid error count"),
        MetricDefinition("gpu.pcie.replay",C,"count",("gpu",),"PCIe replay counter"),
        MetricDefinition("gpu.throttle.active",G,"ratio",("gpu","reason"),"GPU throttling active indicator"),
        MetricDefinition("storage.fsync.latency",H,"seconds",("store","kind"),"Durable fsync latency"),
        MetricDefinition("storage.queue.depth",G,"count",("store","kind"),"Storage queue depth"),
        MetricDefinition("storage.write_amplification",G,"ratio",("store",),"Observed write amplification"),
        MetricDefinition("telemetry.batch.size",H,"count",("sink",),"Telemetry write batch size"),
        MetricDefinition("telemetry.flush.latency",H,"seconds",("sink","result"),"Telemetry flush latency"),
        MetricDefinition("telemetry.raw.bytes",C,"bytes",("family","retention"),"Raw observability bytes appended"),
        MetricDefinition("telemetry.raw.records",C,"count",("family","retention"),"Raw observability records appended"),
        MetricDefinition("telemetry.verify.duration",H,"seconds",("family","result"),"Raw observability verification duration"),
        MetricDefinition("prompt.block.count",H,"count",("role","bundle"),"Typed prompt block count"),
        MetricDefinition("prompt.compile.bytes",H,"bytes",("role","bundle"),"Compiled prompt bytes"),
        MetricDefinition("prompt.schema.validation",H,"seconds",("role","schema","result"),"Output-schema validation duration"),
        MetricDefinition("prompt.publication.duration",H,"seconds",("role","result"),"Prompt generation publication duration"),
        MetricDefinition("prompt.promotion.duration",H,"seconds",("role","result"),"Prompt promotion transaction duration"),
        MetricDefinition("llm.time_to_headers",H,"seconds",("role","model","endpoint"),"Transport time to response headers"),
        MetricDefinition("llm.stream.first_byte",H,"seconds",("role","model","endpoint"),"Time to first response byte"),
        MetricDefinition("llm.stream.gap",H,"seconds",("role","model","endpoint"),"Inter-chunk stream gap"),
        MetricDefinition("method.materialize.bytes",H,"bytes",("method","generation","mode"),"Materialized state bytes"),
        MetricDefinition("method.materialize.records",H,"count",("method","generation","mode"),"Materialized record count"),
        MetricDefinition("method.evolution.stage.latency",H,"seconds",("method","stage","result"),"Evolution stage latency"),
        MetricDefinition("method.evolution.candidate.count",C,"count",("method","result"),"Evolution candidates generated/evaluated"),
        MetricDefinition("method.evolution.generation.age",G,"seconds",("method","generation_class"),"Current method generation age"),
        MetricDefinition("environment.effect.reconcile.latency",H,"seconds",("environment","effect_class","result"),"Environment effect reconciliation latency"),
        MetricDefinition("environment.observation.age",G,"seconds",("environment","observation_class"),"Age of authoritative environment observation"),
        MetricDefinition("study.checkpoint.age",G,"seconds",("condition","kind"),"Age of most recent verified checkpoint"),
        MetricDefinition("study.resume.duration",H,"seconds",("condition","result"),"Exact study resume duration"),
        MetricDefinition("study.comparability.valid",G,"ratio",("condition","pair_type"),"Paired comparability proof validity ratio"),
    )
