from __future__ import annotations

from pathlib import Path
from typing import Protocol

from noetrium_platform.foundation.scope.api import ScopeIdentity
from .contracts import (
    ManagedModelAsset, ModelAcquisitionReceipt, ModelAssetMode, ModelAssetStats, ModelAssetUsage,
    ModelConfigSummary, ModelSourceSpec, ModelStoragePoolStatus,
)


class ModelAssetStoragePort(Protocol):
    def pools(self) -> tuple[ModelStoragePoolStatus, ...]: ...
    def target(self, model_id: str, *, pool_id: str = "default") -> Path: ...
    def materialize(self, model_id: str, source: Path, mode: ModelAssetMode, *, pool_id: str = "default") -> Path: ...
    def remove(self, asset: ManagedModelAsset) -> bool: ...


class ModelSourceBackend(Protocol):
    backend_id: str
    def acquire(self, model_id: str, spec: ModelSourceSpec) -> ModelAcquisitionReceipt: ...


class ModelAssetReferencePort(Protocol):
    """Cross-subsystem query used by the asset authority without importing deployment contracts."""

    def references(self, model_id: str) -> tuple[str, ...]: ...
    def active_references(self, model_id: str) -> tuple[str, ...]: ...


class ModelAssetLookupPort(Protocol):
    def model(self, model_id: str) -> ManagedModelAsset: ...


class ModelAssetUsagePort(Protocol):
    def usage(self, model_id: str) -> ModelAssetUsage: ...


class ModelAssetManagementPort(ModelAssetLookupPort, Protocol):
    def fetch_model(self, model_id: str, scope: ScopeIdentity, spec: ModelSourceSpec, *, family: str = "", notes: str = "", tags: tuple[str, ...] = ()) -> ManagedModelAsset: ...
    def register_model(self, model_id: str, scope: ScopeIdentity, source: Path, *, mode: str = "reference", family: str = "", notes: str = "", tags: tuple[str, ...] = (), storage_pool: str = "default") -> ManagedModelAsset: ...
    def storage_pools(self) -> tuple[ModelStoragePoolStatus, ...]: ...
    def models(self, *, tags: tuple[str, ...] = (), family: str | None = None) -> tuple[ManagedModelAsset, ...]: ...
    def source_backends(self) -> tuple[str, ...]: ...
    def model_stats(self, model_id: str) -> ModelAssetStats: ...
    def model_config(self, model_id: str) -> ModelConfigSummary | None: ...
    def model_usage(self, model_id: str) -> ModelAssetUsage: ...
    def unregister_model(self, model_id: str, *, delete_managed_files: bool = False) -> bool: ...


__all__ = ["ModelAssetLookupPort", "ModelAssetManagementPort", "ModelAssetStoragePort", "ModelAssetUsagePort", "ModelSourceBackend"]
