"""Frontier 2026 wave 10: memory, multimodal, and embodied agent reproductions.

Paper-private semantics stay in research authoring. Reported paper numbers are provenance only;
Noetrium results require benchmark execution receipts in the Machine Journal.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id: str; title: str; venue: str; paper_uri: str; benchmarks: tuple[str,...]; protocol: tuple[str,...]; metrics: tuple[str,...]; baselines: tuple[str,...]; ablations: tuple[str,...]; phases: tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id,implementation_version="2026-paper-protocol",schema_version=self.method_id+".phase-workflow.v1",phases=tuple(AgentPhaseSpec(*p) for p in self.phases),max_cycles=16,configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations},evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"),metric_names=self.metrics,artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self): return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)
def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze benchmark/model/environment cuts and random seeds","run method and matched baselines under identical budgets","persist episode-level Machine Journal receipts and aggregate result tables","separate paper-reported references from Noetrium-measured results")
REPRODUCTIONS=(
R("samem_findings_acl2026","SAMem: State-Aware Memory as a Fine-Grained Memory for LLM Agents in Decision-Making","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.722/",("decision-making-suite",),COMMON+("reproduce state-conditioned thought memory and compare against task-level experiential retrieval",),("task_success","decision_accuracy","steps","retrieval_precision","token_count"),("no memory","task-level experiential memory","global retrieval memory"),("no state key","task-only key","random experience retrieval"),(("observe","samem.observe","Encode current decision state."),("index","samem.index","Store state-specific reasoning thoughts."),("retrieve","samem.retrieve","Retrieve experiences aligned to current state."),("reason","samem.reason","Condition reasoning on fine-grained memory."),("act","samem.act","Execute decision."),("update","samem.update","Write outcome-grounded state memory."))),
R("agentocr_acl2026","AgentOCR: Reimagining Agent History via Optical Self-Compression","ACL 2026","https://aclanthology.org/2026.acl-long.230/",("agentic-multiturn-suite",),COMMON+("reproduce rendered visual history, segment optical caching and compression-aware adaptive rate selection",),("task_success","text_tokens","visual_tokens","cache_hit_rate","latency","compression_ratio"),("text history","fixed summarization","fixed optical compression"),("no segment cache","fixed compression rate","text-only history"),(("segment","agentocr.segment","Partition observation-action history into hashable segments."),("render","agentocr.render","Render accumulated history into compact visual representation."),("cache","agentocr.cache","Reuse unchanged optical segments."),("select_rate","agentocr.rate","Agent selects compression rate."),("reason","agentocr.reason","Reason over optical history and current state."),("reward","agentocr.reward","Score task utility jointly with compression efficiency."))),
R("lightmem_acl2026","Lightweight LLM Agent Memory with Small Language Models","ACL 2026","https://aclanthology.org/2026.acl-long.588/",("locomo","longmemeval"),COMMON+("reproduce SLM-driven retrieval/writing plus offline long-term consolidation under bounded online compute",),("accuracy","memory_recall","memory_precision","online_latency","token_cost","consolidation_cost"),("retrieval-only memory","LLM-operated memory","full-context prompting"),("no offline consolidation","LLM instead of SLM","no candidate filtering"),(("query","lightmem.query","Construct compact retrieval query."),("retrieve","lightmem.retrieve","Retrieve candidate memories."),("filter","lightmem.filter","SLM filters candidates online."),("answer","lightmem.answer","Answer with bounded memory context."),("write","lightmem.write","SLM selects reusable information to store."),("consolidate","lightmem.offline","Consolidate long-term memory off the online path."))),
R("metacognitive_memory_findings_acl2026","Learning How to Remember: A Meta-Cognitive Management Method for Structured and Transferable Agent Memory","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.1535/",("agent-memory-transfer-suite",),COMMON+("reproduce structured transferable memory plus meta-cognitive management across source and transfer tasks",),("task_success","transfer_gain","memory_precision","memory_recall","token_count"),("flat episodic memory","retrieval memory","no-memory agent"),("no meta-cognitive manager","unstructured memory","no cross-task transfer"),(("observe","metamem.observe","Observe trajectory and outcome."),("reflect","metamem.reflect","Extract reusable experience."),("structure","metamem.structure","Organize experience into transferable memory."),("manage","metamem.manage","Meta-cognitively decide retain/update/discard."),("retrieve","metamem.retrieve","Recall task-relevant structured memory."),("transfer","metamem.transfer","Apply memory to new task families."))),
R("experience_following_acl2026","How Memory Management Impacts LLM Agents: An Empirical Study of Experience-Following Behavior","ACL 2026","https://aclanthology.org/2026.acl-long.27/",("agent-memory-behavior-suite",),COMMON+("factor memory addition/deletion and task-memory similarity to reproduce experience-following effects",),("task_success","output_similarity","experience_following_rate","memory_utility","error_propagation"),("no memory","append-only memory","retrieval memory"),("disable addition","disable deletion","low-similarity memories"),(("seed","expfollow.seed","Construct controlled experience memory."),("add","expfollow.add","Apply memory-addition policy."),("delete","expfollow.delete","Apply memory-deletion policy."),("retrieve","expfollow.retrieve","Retrieve by controlled task similarity."),("act","expfollow.act","Produce agent decision."),("measure","expfollow.measure","Measure output imitation and long-term performance."))),
R("visual_inception_acl2026","Visual Inception: Compromising Long-term Planning in Agentic Recommenders via Multimodal Memory Poisoning","ACL 2026","https://aclanthology.org/2026.acl-long.954/",("agentic-recsys-memory-safety",),COMMON+("reproduce benign-versus-triggered multimodal memory conditions and CognitiveGuard defense without operationalizing real-world abuse",),("recommendation_utility","attack_success_rate","defense_detection_rate","false_positive_rate","planning_shift"),("clean memory","undefended multimodal memory","text-only memory"),("no defense reflection","no detector","no visual memory"),(("ingest","visual_inception.ingest","Ingest controlled benchmark multimodal memories."),("retrieve","visual_inception.retrieve","Retrieve memory during recommendation planning."),("detect","visual_inception.detect","CognitiveGuard screens anomalous influence."),("reflect","visual_inception.reflect","Re-evaluate suspect memory evidence."),("plan","visual_inception.plan","Produce recommendation plan."),("score","visual_inception.eval","Measure utility and benchmark attack/defense outcomes."))),
R("ovsegdt_cvpr2026","OVSegDT: Segmenting Transformer for Open-Vocabulary Object Goal Navigation","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/html/Zemskova_OVSegDT_Segmenting_Transformer_for_Open-Vocabulary_Object_Goal_Navigation_CVPR_2026_paper.html",("hm3d-ovon",),COMMON+("reproduce RGB-only goal-mask conditioning, entropy-adaptive imitation/RL balancing and segmentation auxiliary objective",),("success_rate","spl","collisions","sample_efficiency","segmentation_iou"),("paper navigation baseline","imitation-only policy","fixed IL/RL schedule"),("no goal-mask encoder","no EALM","no segmentation auxiliary loss"),(("perceive","ovsegdt.rgb","Encode RGB observation."),("ground","ovsegdt.mask","Ground free-form goal into binary mask."),("encode","ovsegdt.transformer","Fuse goal mask and visual history."),("balance","ovsegdt.ealm","Adapt imitation/RL weighting from policy entropy."),("act","ovsegdt.policy","Predict navigation action."),("learn","ovsegdt.loss","Optimize navigation and auxiliary segmentation objectives."))),
R("agentsafe_cvpr2026","AGENTSAFE: Benchmarking the Safety of Embodied Agents on Hazardous Instructions","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/html/Ying_AGENTSAFE_Benchmarking_the_Safety_of_Embodied_Agents_on_Hazardous_Instructions_CVPR_2026_paper.html",("safe-thor","safe-verse"),COMMON+("reproduce 45 scenarios, 1,350 tasks and 9,900 instructions with perception/planning/execution diagnosis",),("hazard_recognition","safe_plan_rate","safe_execution_rate","task_utility","stage_failure_rate"),("paper VLM suite","paper embodied workflows","refusal baseline"),("perception-only diagnosis","planning-only diagnosis","outcome-only scoring"),(("perceive","agentsafe.perceive","Interpret simulated embodied scene and instruction."),("recognize","agentsafe.hazard","Recognize benchmark-defined hazards."),("plan","agentsafe.plan","Produce constrained high-level plan."),("map","agentsafe.adapter","Map high-level actions to SAFE-THOR controls."),("execute","agentsafe.execute","Execute in adversarial simulation sandbox."),("diagnose","agentsafe.diagnose","Score perception, planning and execution failure stages."))),
R("fantasyvln_cvpr2026","FantasyVLN: Unified Multimodal Chain-of-Thought Reasoning for Vision-and-Language Navigation","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/html/Zuo_FantasyVLN_Unified_Multimodal_Chain-of-Thought_Reasoning_for_Vision-and-Language_Navigation_CVPR_2026_paper.html",("vln-suite",),COMMON+("reproduce unified multimodal CoT navigation and compare textual versus imagined-visual reasoning under matched budgets",),("success_rate","spl","navigation_error","cot_tokens","latency"),("textual CoT navigation","multimodal imagined-observation CoT","non-CoT navigator"),("text-only reasoning","no multimodal CoT","no long-horizon reasoning supervision"),(("observe","fantasyvln.observe","Encode panoramic visual state and instruction."),("ground","fantasyvln.ground","Ground instruction entities and landmarks."),("reason","fantasyvln.mmcot","Generate unified multimodal navigation reasoning."),("compress","fantasyvln.efficient","Control multimodal reasoning token growth."),("act","fantasyvln.navigate","Select next navigation action."),("update","fantasyvln.history","Update trajectory context for next step."))),
R("sage_cvpr2026","SAGE: Scalable Agentic 3D Scene Generation for Embodied AI","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/html/Xia_SAGE_Scalable_Agentic_3D_Scene_Generation_for_Embodied_AI_CVPR_2026_paper.html",("sage-10k","embodied-policy-transfer"),COMMON+("reproduce task-conditioned scene generation, multi-critic self-refinement and downstream policy scaling evaluation",),("physical_validity","semantic_plausibility","visual_realism","generation_success","policy_success"),("rule-based scene generation","single-generator pipeline","no-critic generation"),("no semantic critic","no physical critic","no iterative refinement"),(("interpret","sage.intent","Parse embodied task into scene requirements."),("layout","sage.layout","Generate candidate spatial layout."),("compose","sage.objects","Compose task-relevant objects."),("criticize","sage.critics","Evaluate semantics, realism and physical stability."),("refine","sage.refine","Adaptively select tools and repair scene."),("deploy","sage.simulator","Export simulator-ready scene and evaluate trained policy."))),
)
PROGRAMS={r.method_id:r.program() for r in REPRODUCTIONS}
STUDY_SPECS={r.method_id:r.study() for r in REPRODUCTIONS}
__all__=["REPRODUCTIONS","PROGRAMS","STUDY_SPECS"]
