"""Frontier wave 12: ten peer-reviewed 2025-2026 agent lineage reproductions.

Paper-private semantics stay in research authoring. Reference claims are provenance only;
Noetrium claims require benchmark execution receipts recorded by the Machine Journal.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id: str; title: str; venue: str; paper_uri: str; benchmarks: tuple[str,...]; protocol: tuple[str,...]; metrics: tuple[str,...]; baselines: tuple[str,...]; ablations: tuple[str,...]; phases: tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id, implementation_version="paper-protocol", schema_version=self.method_id+".phase-workflow.v1", phases=tuple(AgentPhaseSpec(*p) for p in self.phases), max_cycles=32, configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations}, evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"), metric_names=self.metrics, artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self): return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)

def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze paper-faithful benchmark/model/environment cuts and seeds","run method and matched baselines under identical interaction/compute budgets","persist episode-level Machine Journal receipts and aggregate metric artifacts","keep paper-reported reference values separate from Noetrium-measured results")
REPRODUCTIONS=(
R("nitrogen_cvpr2026","NitroGen: An Open Foundation Model for Generalist Gaming Agents","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/html/Magne_NitroGen_An_Open_Foundation_Model_for_Generalist_Gaming_Agents_CVPR_2026_paper.html",("nitrogen-multigame",),COMMON+("pretrain on the released large-scale video-action corpus; evaluate cross-game and unseen-game transfer",),("task_success","cross_game_success","unseen_game_transfer","action_accuracy","episode_return"),("scratch behavior cloning","single-game policy","no-pretraining transfer"),("no internet-scale pretraining","single-game data","no action extraction pipeline"),(("observe","nitrogen.observe","Encode game frames and task context."),("align","nitrogen.actions","Align gameplay video with extracted player actions."),("pretrain","nitrogen.pretrain","Behavior-clone a unified vision-action policy across games."),("act","nitrogen.act","Predict native game controls."),("adapt","nitrogen.adapt","Fine-tune policy on an unseen game."),("evaluate","nitrogen.eval","Measure cross-game generalization and transfer."))),
R("adam_iclr2025","ADAM: An Embodied Causal Agent in Open-World Environments","ICLR 2025","https://proceedings.iclr.cc/paper_files/paper/2025/hash/392aae924264f2c56d1895b232bb46b6-Abstract-Conference.html",("minecraft-open-world","minecraft-modified-prior-free"),COMMON+("learn causal world knowledge from interaction from scratch and test modified-Minecraft robustness",),("task_success","causal_graph_accuracy","planning_efficiency","generalization_success","interaction_steps"),("LLM Minecraft agent","memory-only planner","prior-knowledge planner"),("no causal graph","no memory pool","no multimodal perception"),(("perceive","adam.perceive","Ground multimodal Minecraft state."),("interact","adam.interact","Execute actions and record transitions."),("induce","adam.causal","Update the growing causal world graph."),("plan","adam.plan","Decompose goals using causal dependencies."),("act","adam.act","Execute planned action through controller."),("remember","adam.memory","Persist causal and episodic evidence for future tasks."))),
R("wormi_icml2025","World Model Implanting for Test-time Adaptation of Embodied Agents","ICML 2025","https://proceedings.mlr.press/v267/yoo25a.html",("virtualhome","alfworld"),COMMON+("evaluate zero/few-shot unseen-domain adaptation while composing independently learned world models at test time",),("task_success","zero_shot_success","few_shot_success","retrieval_accuracy","adaptation_cost"),("LLM-only embodied agent","single world model","fine-tuned adaptation"),("no world-model retrieval","single retrieved model","no compound attention"),(("abstract","wormi.abstract","Encode current trajectory into retrieval representation."),("retrieve","wormi.retrieve","Retrieve domain world models by prototype similarity."),("implant","wormi.implant","Compose selected world models at test time."),("align","wormi.attend","Fuse world-wise representations with compound attention."),("reason","wormi.reason","Reason over fused predictive knowledge."),("act","wormi.act","Execute action and continue adaptation without retraining."))),
R("larm_icml2025","LARM: Large Auto-Regressive Model for Long-Horizon Embodied Intelligence","ICML 2025","https://proceedings.mlr.press/v267/li25dj.html",("long-horizon-embodied-exploration",),COMMON+("train direct autoregressive action generation with referee feedback under long-horizon sparse rewards",),("task_success","episode_return","action_accuracy","reward_density","inference_cost"),("classic RL","giant-LLM agent","small autoregressive policy without referee"),("no referee RL","text-action decoding","short-horizon training"),(("observe","larm.observe","Encode embodied observation and goal."),("predict","larm.predict","Autoregressively predict next executable action."),("execute","larm.execute","Apply action to environment."),("judge","larm.referee","Use giant-LLM referee to evaluate long-horizon progress."),("credit","larm.credit","Convert referee assessment into non-vanishing training feedback."),("update","larm.update","Optimize lightweight direct-action policy."))),
R("tango_cvpr2025","TANGO: Training-free Embodied AI Agents for Open-world Tasks","CVPR 2025","https://openaccess.thecvf.com/content/CVPR2025/html/Ziliotto_TANGO_Training-free_Embodied_AI_Agents_for_Open-world_Tasks_CVPR_2025_paper.html",("open-set-objectnav","multimodal-lifelong-navigation","open-eqa"),COMMON+("evaluate the same training-free primitive composition across three open-world embodied tasks",),("success_rate","spl","qa_accuracy","navigation_steps","llm_calls"),("task-specific embodied agent","direct LLM action agent","primitive policy without composition"),("no memory exploration","no PointGoal primitive","no in-context examples"),(("observe","tango.observe","Parse multimodal world state and task."),("compose","tango.compose","LLM composes executable navigation/reasoning primitives."),("explore","tango.memory","Run memory-based exploration primitive."),("navigate","tango.pointgoal","Invoke PointGoal navigation toward composed target."),("reason","tango.reason","Integrate observations for task-specific answer or subgoal."),("act","tango.act","Execute composed primitive program without fine-tuning."))),
R("adaptagent_acl2025","AdaptAgent: Adapting Multimodal Web Agents with Few-Shot Learning from Human Demonstrations","ACL 2025","https://aclanthology.org/2025.acl-long.1008/",("multimodal-web-unseen-sites",),COMMON+("adapt to held-out websites with at most two human demonstrations and compare proprietary/open-weight backbones",),("task_success","few_shot_gain","demo_efficiency","action_accuracy","token_cost"),("zero-shot web agent","large-scale fine-tuned web agent","prompt-only demonstration agent"),("zero demonstrations","no multimodal grounding","single demonstration representation"),(("observe","adaptagent.observe","Ground webpage screenshot and instruction."),("ingest","adaptagent.demo","Encode one or two human demonstrations."),("retrieve","adaptagent.retrieve","Select demonstration evidence for current state."),("adapt","adaptagent.adapt","Condition policy on few-shot behavior evidence."),("act","adaptagent.act","Execute grounded web action."),("reflect","adaptagent.reflect","Update local task context after action outcome."))),
R("reflectool_acl2025","ReflecTool: Towards Reflection-Aware Tool-Augmented Clinical Agents","ACL 2025","https://aclanthology.org/2025.acl-long.663/",("clinicalagent-bench",),COMMON+("reproduce CAB's 18 tasks across five clinical dimensions and separate memory-building from reflection-aware inference",),("task_accuracy","tool_selection_accuracy","tool_execution_success","reflection_gain","memory_reuse"),("tool agent without reflection","no-memory clinical agent","scenario-specific clinical agent"),("no long-term tool memory","no reflection stage","no successful-process storage"),(("observe","reflectool.observe","Parse clinical task and available signals."),("select","reflectool.select","Choose domain-specific clinical tool."),("execute","reflectool.execute","Run tool and capture structured evidence."),("remember","reflectool.memory","Store successful solving process and tool experience."),("reflect","reflectool.reflect","Critique intermediate tool use against accumulated experience."),("answer","reflectool.answer","Produce evidence-grounded clinical task output."))),
R("kg_agent_acl2025","KG-Agent: An Efficient Autonomous Agent Framework for Complex Reasoning over Knowledge Graph","ACL 2025","https://aclanthology.org/2025.acl-long.468/",("complex-kgqa-in-domain","complex-kgqa-out-domain"),COMMON+("fine-tune on the code-form reasoning instructions and evaluate autonomous multi-hop tool use in/out of domain",),("answer_accuracy","reasoning_steps","tool_accuracy","ood_accuracy","token_cost"),("large-LLM KG reasoner","prompted tool agent","program-only KGQA"),("no knowledge memory","no code instruction tuning","fixed tool sequence"),(("parse","kgagent.parse","Convert question into reasoning state."),("select","kgagent.select","Autonomously select KG tool."),("execute","kgagent.execute","Execute programmatic operation over KG."),("update","kgagent.memory","Update knowledge memory with tool evidence."),("reason","kgagent.reason","Continue multi-hop reasoning from updated state."),("answer","kgagent.answer","Terminate with evidence-supported answer."))),
R("toolmaker_acl2025","LLM Agents Making Agent Tools","ACL 2025","https://aclanthology.org/2025.acl-long.1266/",("toolmaker-15-tasks",),COMMON+("build tools from paper-code repositories and validate them against the benchmark's unit-test suites",),("unit_test_pass_rate","task_success","tool_build_success","repair_iterations","setup_time"),("human-authored tool","one-shot generated tool","manual repository integration"),("no closed-loop repair","no dependency installation","no paper-code grounding"),(("inspect","toolmaker.inspect","Inspect task description and paper-code repository."),("install","toolmaker.install","Resolve and install executable dependencies."),("synthesize","toolmaker.synthesize","Generate LLM-compatible tool wrapper."),("test","toolmaker.test","Execute benchmark unit tests."),("repair","toolmaker.repair","Diagnose failures and self-correct implementation."),("publish","toolmaker.publish","Expose validated tool interface to agent."))),
R("maporl_acl2025","MAPoRL: Multi-Agent Post-Co-Training for Collaborative Large Language Models with Reinforcement Learning","ACL 2025","https://aclanthology.org/2025.acl-long.1459/",("collaborative-reasoning-suite",),COMMON+("post-train collaborating agents from verifier rewards while preserving matched model and discussion budgets",),("final_accuracy","team_reward","discussion_gain","agreement_rate","token_cost"),("single-agent RL","frozen multi-agent discussion","independent post-training"),("no discussion","no verifier reward","single shared response"),(("propose","maporl.propose","Agents independently generate candidate responses."),("discuss","maporl.discuss","Agents exchange critiques and evidence."),("aggregate","maporl.aggregate","Collaboratively construct final response."),("verify","maporl.verify","Score final response with verifier."),("credit","maporl.credit","Assign verifier reward to collaborative trajectories."),("update","maporl.update","Post-co-train participating policies with RL."))),
)
PROGRAMS={r.method_id:r.program() for r in REPRODUCTIONS}
STUDY_SPECS={r.method_id:r.study() for r in REPRODUCTIONS}
__all__=["REPRODUCTIONS","PROGRAMS","STUDY_SPECS"]
