from __future__ import annotations

from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec


def _paper(method_id, title, venue, uri, benchmarks, phases, metrics, ablations, protocol):
    spec = PaperStudySpec(method_id=method_id, title=title, venue=venue, paper_uri=uri, benchmark_ids=benchmarks, protocol=protocol, metrics=metrics, ablations=ablations)
    method = AgentMethodSpec(
        method_id=method_id,
        implementation_version="2026-paper-protocol",
        schema_version=f"{method_id}.phase-workflow.v1",
        phases=tuple(AgentPhaseSpec(*row) for row in phases),
        max_cycles=128,
        configuration={"paper_uri": uri, "venue": venue, "benchmark_ids": benchmarks, "protocol": protocol, "ablations": ablations},
        evidence_obligations=(f"{method_id}.phase-transcript", f"{method_id}.model-tool-receipts", f"{method_id}.metric-artifacts"),
        metric_names=metrics,
        artifact_kinds=(f"{method_id}_trajectory", f"{method_id}_experiment_manifest"),
    )
    return method.compile(), spec


PAPERS = {}
def _add(key, *args): PAPERS[key] = _paper(key, *args)

_add("worldmm_cvpr2026", "WorldMM: Dynamic Multimodal Memory Agent for Long Video Reasoning", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Yeo_WorldMM_Dynamic_Multimodal_Memory_Agent_for_Long_Video_Reasoning_CVPR_2026_paper.html", ("longvideobench", "videomme", "mlvu", "lvbench", "egoschema"), (("index_multiscale", "worldmm.episodic", "Index factual events at multiple temporal scales."), ("update_semantics", "worldmm.semantic", "Continuously consolidate high-level conceptual knowledge."), ("preserve_visual", "worldmm.visual", "Retain detailed visual evidence without text-only abstraction."), ("adaptive_retrieve", "worldmm.retrieve", "Iteratively choose memory source and temporal granularity."), ("sufficiency", "worldmm.control", "Stop retrieval when evidence is sufficient."), ("answer", "worldmm.reason", "Reason over gathered multimodal evidence.")), ("accuracy", "average_accuracy", "retrieval_steps", "visual_evidence_usage"), ("text-only memory", "single temporal scale", "no semantic memory", "no adaptive retrieval"), ("run all five reported long-video QA benchmarks", "preserve episodic-semantic-visual memory separation", "measure accuracy-efficiency tradeoff and reported ablations"))
_add("octmem_agent_cvpr2026", "Memory-Augmented Scene Understanding and Exploration for Open-World Aerial Object-Goal Navigation", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Zhou_Memory-Augmented_Scene_Understanding_and_Exploration_for_Open-World_Aerial_Object-Goal_Navigation_CVPR_2026_paper.html", ("uav-on",), (("observe_rgbd", "octmem.perception", "Acquire aerial RGB-D observation."), ("update_octree", "octmem.memory", "Incrementally aggregate observations into adaptive hierarchical 3D memory."), ("query_instruction", "octmem.query", "Extract task-relevant scene and exploration tokens."), ("select_frontier", "octmem.explore", "Select unexplored frontier from hierarchical memory."), ("navigate", "octmem.navigate", "Execute aerial object-goal navigation.")), ("success_rate", "spl", "navigation_error", "exploration_efficiency"), ("no octree memory", "flat map", "no instruction-guided query"), ("evaluate UAV-ON official split", "retain RGB-D partial observability and aerial action space", "report success and path efficiency against published baselines"))
_add("glmap_cvpr2026", "Multi-Scale Gaussian-Language Map for Zero-shot Embodied Navigation and Reasoning", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_Multi-Scale_Gaussian-Language_Map_for_Zero-shot_Embodied_Navigation_and_Reasoning_CVPR_2026_paper.html", ("objectnav", "instnav", "sqa"), (("project_geometry", "glmap.geometry", "Construct explicit 3D geometry from observations."), ("estimate_gaussians", "glmap.gaussian", "Analytically estimate Gaussian parameters without gradient optimization."), ("attach_language", "glmap.semantic", "Attach instance- and region-level language semantics."), ("query_map", "glmap.query", "Query dual-modality map for task evidence."), ("render_evidence", "glmap.render", "Render task-relevant images by Gaussian splatting."), ("reason_act", "glmap.agent", "Navigate or answer from map evidence.")), ("success_rate", "spl", "localization_accuracy", "sqa_accuracy"), ("single-scale semantics", "no Gaussian rendering", "no explicit geometry"), ("run ObjectNav, InstNav and SQA", "preserve zero-shot large-model interface", "measure localization, navigation and contextual reasoning"))
_add("evonav_cvpr2026", "History to Future: Evolving Agent with Experience and Thought for Zero-shot Vision-and-Language Navigation", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Dai_History_to_Future_Evolving_Agent_with_Experience_and_Thought_for_CVPR_2026_paper.html", ("r2r-ce",), (("observe", "evonav.perceive", "Ground current continuous-environment observation."), ("future_cot", "evonav.future", "Predict future actions and landmarks."), ("history_coe", "evonav.history", "Summarize trajectory and scene history into corrective experience."), ("evolve_decision", "evonav.reason", "Fuse future thought and historical experience."), ("navigate", "evonav.act", "Execute zero-shot navigation decision.")), ("success_rate", "spl", "navigation_error", "oracle_success_rate"), ("no F-CoT", "no H-CoE", "naive LLM reasoning"), ("run simulator protocol and reported real-world evaluation", "preserve zero-shot setting", "reproduce component ablations and navigation metrics"))
_add("socialnav_cvpr2026", "SocialNav: Training Human-Inspired Foundation Model for Socially-Aware Embodied Navigation", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Chen_SocialNav_Training_Human-Inspired_Foundation_Model_for_Socially-Aware_Embodied_Navigation_CVPR_2026_paper.html", ("socnav",), (("social_reason", "socialnav.brain", "Infer high-level social norms and traversability."), ("plan", "socialnav.plan", "Translate social reasoning into navigation intent."), ("generate_trajectory", "socialnav.action", "Generate low-level socially compliant trajectory."), ("safe_grpo", "socialnav.rl", "Optimize navigation and social-compliance rewards."), ("execute", "socialnav.env", "Execute trajectory in embodied environment.")), ("success_rate", "social_compliance_rate", "spl", "collision_rate"), ("no cognitive activation", "no expert trajectory pyramid", "no SAFE-GRPO"), ("reproduce imitation-learning then SAFE-GRPO stages", "evaluate navigation and social compliance separately", "retain hierarchical brain-action semantics"))
_add("navgrpo_cvprf2026", "Trajectory-Diversity-Driven Robust Vision-and-Language Navigation", "CVPR Findings 2026", "https://openaccess.thecvf.com/content/CVPR2026F/html/Li_Trajectory-Diversity-Driven_Robust_Vision-and-Language_Navigation_CVPRF_2026_paper.html", ("r2r", "reverie"), (("sample_group", "navgrpo.rollout", "Explore diverse navigation trajectories."), ("score_group", "navgrpo.reward", "Score goal-directed outcomes within trajectory group."), ("relative_update", "navgrpo.optimize", "Apply group-relative policy optimization without value network."), ("perturb", "navgrpo.robustness", "Apply execution perturbations."), ("navigate", "navgrpo.policy", "Execute learned robust policy.")), ("spl", "success_rate", "robust_spl", "perturbation_recovery"), ("imitation only", "no trajectory diversity", "no relative optimization"), ("evaluate R2R and REVERIE unseen splits", "run early-stage perturbation stress tests", "compare ScaleVLN baseline and report SPL deltas"))
_add("longvideo_r1_cvpr2026", "LongVideo-R1: Smart Navigation for Low-cost Long Video Understanding", "CVPR 2026", "https://openaccess.thecvf.com/content/CVPR2026/html/Qiu_LongVideo-R1_Smart_Navigation_for_Low-cost_Long_Video_Understanding_CVPR_2026_paper.html", ("longvideobench", "videomme", "mlvu"), (("read_summary", "longvideo.summary", "Start from top-level visual summaries."), ("infer_clip", "longvideo.reason", "Infer most informative next clip."), ("inspect_clip", "longvideo.tool", "Navigate to and inspect selected video context."), ("sufficiency", "longvideo.stop", "Halt once sufficient evidence is acquired."), ("answer", "longvideo.answer", "Answer from selectively gathered evidence.")), ("qa_accuracy", "frames_processed", "navigation_steps", "accuracy_per_frame"), ("exhaustive search", "no RL", "no hierarchical summaries"), ("preserve SFT then RL training protocol", "evaluate reported long-video benchmarks", "measure QA accuracy versus inference cost"))
_add("magma_acl2026", "MAGMA: A Multi-Graph based Agentic Memory Architecture for AI Agents", "ACL 2026", "https://aclanthology.org/2026.acl-long.1709/", ("locomo",), (("encode", "magma.memory", "Represent each memory item in orthogonal graph views."), ("classify_query", "magma.policy", "Infer relational evidence needs."), ("traverse", "magma.retrieve", "Policy-guide traversal over semantic, temporal, causal and entity graphs."), ("construct_context", "magma.context", "Build structured evidence context with transparent paths."), ("answer", "magma.reason", "Reason over graph-grounded evidence.")), ("accuracy", "retrieval_recall", "retrieval_precision", "context_tokens"), ("semantic graph only", "no temporal graph", "no causal graph", "no entity graph", "similarity retrieval"), ("evaluate LoCoMo protocol", "retain orthogonal graph representations", "report retrieval and answer metrics with graph ablations"))
_add("ama_acl2026", "AMA: Adaptive Memory via Multi-Agent Collaboration", "ACL Findings 2026", "https://aclanthology.org/2026.findings-acl.152/", ("locomo",), (("construct", "ama.constructor", "Construct hierarchical memories at multiple granularities."), ("route", "ama.retriever", "Adapt retrieval granularity to query complexity."), ("judge", "ama.judge", "Verify relevance, sufficiency and logical consistency."), ("iterate", "ama.retriever", "Retrieve again when evidence is insufficient."), ("refresh", "ama.refresher", "Update or remove conflicting outdated memory."), ("answer", "ama.reason", "Answer from consistency-checked evidence.")), ("accuracy", "token_consumption", "retrieval_iterations", "conflict_resolution_accuracy"), ("fixed granularity", "no judge", "no refresher", "full context"), ("evaluate published long-context benchmark suite", "preserve constructor-retriever-judge-refresher collaboration", "measure quality and token reduction"))
_add("apex_mem_acl2026", "APEX-MEM: Agentic Semi-Structured Memory with Temporal Reasoning for Long-Term Conversational AI", "ACL 2026", "https://aclanthology.org/2026.acl-long.749/", ("locomo",), (("append_event", "apex.store", "Append temporally grounded entity-centric event without destructive overwrite."), ("plan_retrieval", "apex.agent", "Select retrieval tools from query intent."), ("retrieve_graph", "apex.graph", "Traverse domain-agnostic property graph."), ("resolve_temporal", "apex.temporal", "Resolve conflicting or evolving facts at query time."), ("summarize", "apex.context", "Produce compact relevant memory summary."), ("answer", "apex.reason", "Answer while preserving temporal evolution.")), ("accuracy", "temporal_accuracy", "conflict_resolution_accuracy", "context_tokens"), ("vector retrieval", "no temporal resolution", "destructive update", "single retrieval tool"), ("evaluate long-term conversational protocol", "preserve append-only temporal history", "score temporal conflict resolution and answer quality"))

__all__ = ["PAPERS"]
