"""Frontier 2026 wave 11: Minecraft, VLA/world-model, web, RL, and multi-agent reproductions.

Paper-private semantics remain in research authoring. Paper-reported results are provenance only;
Noetrium-measured claims require benchmark execution receipts in the Machine Journal.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id: str; title: str; venue: str; paper_uri: str; benchmarks: tuple[str,...]; protocol: tuple[str,...]; metrics: tuple[str,...]; baselines: tuple[str,...]; ablations: tuple[str,...]; phases: tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id,implementation_version="2026-paper-protocol",schema_version=self.method_id+".phase-workflow.v1",phases=tuple(AgentPhaseSpec(*p) for p in self.phases),max_cycles=24,configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations},evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"),metric_names=self.metrics,artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self): return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)
def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze benchmark/model/environment cuts and random seeds","run method and matched baselines under identical budgets","persist episode-level Machine Journal receipts and aggregate result tables","keep paper-reported references separate from Noetrium-measured results")
REPRODUCTIONS=(
R("xenon_iclr2026","Experience-based Knowledge Correction for Robust Planning in Minecraft","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/df20e06b04dfc499a1a698796abb0856-Abstract-Conference.html",("minecraft-long-horizon",),COMMON+("inject controlled prior errors and sparse binary feedback; reproduce dependency and action-knowledge correction",),("task_success","dependency_accuracy","action_validity","planning_steps","token_cost"),("uncorrected LLM planner","prompt-feedback planner","experience retrieval planner"),("no adaptive dependency graph","no failure-aware action memory","correct-prior oracle"),(("observe","xenon.observe","Read Minecraft state and sparse feedback."),("plan","xenon.plan","Plan from current dependency/action knowledge."),("execute","xenon.execute","Execute Minecraft action."),("correct_graph","xenon.graph","Revise item dependencies from successful experience."),("correct_action","xenon.action_memory","Revise executable-action knowledge from failures."),("replan","xenon.replan","Replan with corrected knowledge."))),
R("fast_thinkact_cvpr2026","Fast-ThinkAct: Efficient Vision-Language-Action Reasoning via Verbalizable Latent Planning","CVPR 2026","https://research.nvidia.com/labs/twn/publication/cvpr_2026_fastthinkact/",("robot-manipulation-suite","long-horizon-vla"),COMMON+("match teacher/student data and evaluate latency, long-horizon planning, adaptation and recovery",),("task_success","inference_latency","planning_tokens","recovery_success","few_shot_gain"),("explicit-CoT VLA","no-reasoning VLA","teacher reasoning policy"),("no latent planning","no preference objective","no teacher distillation"),(("perceive","fastthinkact.perceive","Encode scene and instruction."),("distill","fastthinkact.distill","Distill teacher reasoning into latent plan."),("plan","fastthinkact.latent","Produce compact verbalizable latent reasoning."),("align","fastthinkact.preference","Preference-align trajectory planning."),("act","fastthinkact.act","Decode latent plan into robot action."),("recover","fastthinkact.recover","Revise plan after execution failure."))),
R("xl_vla_cvpr2026","XL-VLA: Cross-Hand Latent Representation for Vision-Language-Action Models","CVPR 2026","https://xl-vla.github.io/",("dexterous-cross-embodiment",),COMMON+("pretrain on pooled multi-hand demonstrations and evaluate held-out hand-task transfer",),("task_success","transfer_success","adaptation_samples","action_error","cross_hand_gain"),("per-hand VLA","explicit-action pooled VLA","single-hand pretraining"),("no shared latent action","single embodiment","no target adaptation"),(("encode","xlvla.observe","Encode language and visual state."),("project","xlvla.latent","Map embodiment actions into shared latent action space."),("pool","xlvla.pool","Learn from pooled multi-hand demonstrations."),("predict","xlvla.predict","Predict embodiment-invariant latent action."),("decode","xlvla.decode","Decode latent action for target hand."),("adapt","xlvla.adapt","Adapt to unseen hand-task configuration."))),
R("agent_world_model_icml2026","Agent World Model: Infinity Synthetic Environments for Agentic Reinforcement Learning","ICML 2026","https://www.microsoft.com/en-us/research/publication/agent-world-model-infinity-synthetic-environments-for-agentic-reinforcement-learning/",("awm-synthetic-envs","multi-turn-tool-use"),COMMON+("generate executable database-backed environments; train only on synthetic environments and test OOD",),("task_success","ood_success","reward_accuracy","environment_consistency","interaction_latency"),("benchmark-specific training","LLM-simulated environment","no synthetic RL"),("no database state","reduced environment diversity","no environment validation"),(("specify","awm.spec","Specify task domain and tools."),("generate","awm.generate","Generate code-driven environment and database."),("validate","awm.validate","Validate transitions and observable state."),("interact","awm.interact","Collect multi-turn tool trajectories."),("reward","awm.reward","Compute reward from executable state."),("train","awm.rl","Train agent and evaluate OOD transfer."))),
R("agent_jit_icml2026","Agent JIT Compilation for Latency-Optimizing Web Agent Planning and Scheduling","ICML 2026","https://mast.stanford.edu/pubs/jit_planner/",("web-app-suite",),COMMON+("reproduce multi-plan compilation, invariant validation and Monte-Carlo parallel scheduling on five web apps",),("task_accuracy","wall_latency","llm_calls","tool_errors","parallel_speedup"),("Browser-Use","OpenAI CUA","sequential compiled plan"),("no plan validation","no invariant protocol","no JIT scheduler"),(("compile","jit.plan","Compile task into candidate executable plans."),("validate","jit.validate","Check tool specs and state invariants."),("cost","jit.cost","Estimate candidate execution cost."),("select","jit.select","Select minimum-cost valid plan."),("schedule","jit.schedule","Explore parallel schedules with Monte Carlo latency estimates."),("execute","jit.execute","Execute plan while enforcing pre/postconditions."))),
R("evomas_icml2026","EvoMAS: Evolutionary Generation of Multi-Agent Systems","ICML 2026","https://openreview.net/forum?id=ic0AGRIkmY",("bbeh","swe-bench-verified","workbench"),COMMON+("evolve structured MAS configurations with trace-conditioned mutation/crossover and experience memory",),("task_score","pass_at_1","executability","runtime_robustness","token_cost"),("human-designed MAS","EvoAgent","single agent"),("no crossover","no trace feedback","no experience memory"),(("seed","evomas.seed","Select initial MAS configurations."),("execute","evomas.execute","Run candidate systems and capture traces."),("evaluate","evomas.evaluate","Score task outcome and robustness."),("mutate","evomas.mutate","Apply feedback-conditioned configuration mutation."),("crossover","evomas.crossover","Recombine promising structured configurations."),("remember","evomas.memory","Update evolutionary experience memory."))),
R("hiper_icml2026","HiPER: Hierarchical Plan-Execute RL for Multi-Turn LLM Agents","ICML 2026","https://openreview.net/forum?id=RJWQcgd3hX",("alfworld","webshop"),COMMON+("train high-level subgoal and low-level action policies jointly under sparse delayed rewards",),("success_rate","return","long_horizon_success","advantage_variance","sample_efficiency"),("flat agent RL","best prior ALFWorld RL","best prior WebShop RL"),("no persistent subgoals","flat advantage estimation","fixed subgoal switching"),(("observe","hiper.observe","Observe environment and persistent subgoal."),("plan","hiper.plan","Select or retain high-level subgoal."),("execute","hiper.execute","Choose low-level action conditioned on subgoal."),("transition","hiper.switch","Decide when to switch subgoals."),("credit","hiper.hae","Estimate hierarchical advantages at two timescales."),("update","hiper.rl","Jointly optimize planner and executor."))),
R("lmac_icml2026","LMAC: LLM-Guided Communication for Cooperative Multi-Agent Reinforcement Learning","ICML 2026","https://saaangjun.github.io/LMAC/",("cooperative-marl-suite",),COMMON+("learn/refine communication protocols under partial observability using explicit state-awareness criteria",),("team_return","state_reconstruction","knowledge_disparity","message_cost","sample_efficiency"),("no communication","standard learned communication","full-state oracle"),("no LLM protocol design","no state-awareness objective","fixed protocol"),(("observe","lmac.observe","Each agent observes local partial state."),("design","lmac.protocol","LLM proposes communication protocol."),("communicate","lmac.message","Agents exchange protocol-constrained messages."),("reconstruct","lmac.state","Reconstruct shared latent state."),("measure","lmac.awareness","Measure state awareness and inter-agent disparity."),("refine","lmac.refine","Iteratively refine protocol from criterion feedback."))),
R("evocf_icml2026","EvoCF: Multi-Agent Collaboration via Agentic Memory-Driven Evolutionary Counterfactual Planning","ICML 2026","https://openreview.net/",("multi-agent-embodied-suite",),COMMON+("reproduce failure-derived symbolic constraints, counterfactual plan evolution and memory-grounded ranking",),("task_success","plan_executability","constraint_violations","coordination_cost","planning_iterations"),("one-shot LLM planner","retrieval planner","non-evolutionary multi-agent planner"),("no symbolic constraint induction","no counterfactual mutation","no memory-grounded evaluator"),(("execute","evocf.execute","Execute collaborative embodied plan."),("induce","evocf.constraints","Induce reusable symbolic constraints from failures."),("retrieve","evocf.memory","Retrieve relevant prior collaboration evidence."),("mutate","evocf.counterfactual","Generate rule-conditioned counterfactual plans."),("evaluate","evocf.evaluate","Rank candidates with memory-grounded evidence."),("select","evocf.select","Execute best constraint-aware collaboration plan."))),
R("lac_wm_icml2026","Cross-Embodiment Robot Foundation World Models with Latent Actions","ICML 2026","https://openreview.net/",("cross-embodiment-robot-world-model",),COMMON+("pretrain across increasing embodiment counts and adapt world model to held-out robots",),("prediction_error","downstream_success","adaptation_gain","embodiment_scaling","sample_efficiency"),("explicit-action-conditioned world model","single-embodiment world model","target-only training"),("no latent action space","one source embodiment","no cross-embodiment pretraining"),(("observe","lacwm.observe","Encode robot transition context."),("infer","lacwm.latent","Infer unified latent action representation."),("predict","lacwm.world","Predict future state conditioned on latent action."),("scale","lacwm.pretrain","Pretrain across heterogeneous embodiments."),("adapt","lacwm.adapt","Adapt world model to unseen embodiment."),("evaluate","lacwm.eval","Measure prediction and downstream transfer scaling."))),
)
PROGRAMS={r.method_id:r.program() for r in REPRODUCTIONS}
STUDY_SPECS={r.method_id:r.study() for r in REPRODUCTIONS}
__all__=["REPRODUCTIONS","PROGRAMS","STUDY_SPECS"]
