"""Frontier 2026 wave 09: ten peer-reviewed agent reproduction specifications.

Paper-private semantics remain in research authoring. No paper-specific concept is added to the platform kernel.
Paper-reported results are provenance only; Noetrium-measured results require benchmark execution receipts.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id: str; title: str; venue: str; paper_uri: str; benchmarks: tuple[str,...]; protocol: tuple[str,...]; metrics: tuple[str,...]; baselines: tuple[str,...]; ablations: tuple[str,...]; phases: tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id, implementation_version="2026-paper-protocol", schema_version=self.method_id+".phase-workflow.v1", phases=tuple(AgentPhaseSpec(*p) for p in self.phases), max_cycles=16, configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations}, evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"), metric_names=self.metrics, artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self):
        return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)

def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze benchmark/model/environment cuts and random seeds","run paper method and matched baselines under identical budgets","persist episode-level Machine Journal receipts and aggregate result tables","keep paper-reported reference results separate from Noetrium-measured results")

REPRODUCTIONS=(
R("memory_r1_acl2026","Memory-R1: Enhancing Large Language Model Agents to Manage and Utilize Memories via Reinforcement Learning","ACL 2026","https://aclanthology.org/2026.acl-long.583/",("locomo","msc","longmemeval"),COMMON+("reproduce outcome-driven PPO/GRPO memory-manager and answer-agent training from the paper's 152 training QA pairs",),("qa_f1","accuracy","memory_recall","memory_precision","token_count","training_return"),("full context","retrieval memory","non-RL memory agent"),("no memory-manager RL","no answer-agent RL","fixed retrieval"),(("observe","memory_r1.observe","Read query and interaction history."),("manage","memory_r1.manager","Select memory write/update/delete/retrieve operations."),("retrieve","memory_r1.retrieve","Expose compact task-relevant memory."),("answer","memory_r1.answer","Generate answer conditioned on managed memory."),("reward","memory_r1.reward","Score downstream outcome."),("optimize","memory_r1.rl","Update memory and answer policies with outcome-driven RL."))),
R("amata_acl2026","AMATA: Adaptive Multi-Agent Trajectory Alignment for Knowledge-Intensive Question Answering","ACL 2026","https://aclanthology.org/2026.acl-long.359/",("knowledge-intensive-qa-5bench",),COMMON+("reproduce six-agent structured trajectories, intra-trajectory preference learning and dependency-aware inter-agent DPO",),("exact_match","f1","factuality","token_count","trajectory_preference_accuracy"),("single-agent RAG","multi-agent QA","trajectory alignment baseline"),("no intra-trajectory preference","no dependency learning","uniform agent weighting"),(("decompose","amata.customize","Customize specialist agents to the question."),("retrieve","amata.tools","Acquire external evidence."),("collaborate","amata.trajectory","Execute six-agent structured trajectory."),("rank","amata.intra","Learn objective-oriented intra-trajectory preferences."),("harmonize","amata.inter","Align cross-agent dependencies with preference optimization."),("answer","amata.synthesize","Synthesize grounded final answer."))),
R("me_agent_findings_acl2026","Me-Agent: A Personalized Mobile Agent with Two-Level User Habit Learning for Enhanced Interaction","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.1211/",("user-fingertip","mobile-agent-general"),COMMON+("evaluate ambiguous personalized instructions separately from general mobile instruction execution",),("task_success","personalization_accuracy","habit_recall","action_steps","latency"),("non-personalized mobile agent","flat preference memory","full-history prompting"),("no long-term preference memory","no app-specific memory","no habit learning"),(("observe","me_agent.mobile","Observe mobile UI and ambiguous instruction."),("recall_global","me_agent.global_memory","Retrieve long-term user habits."),("recall_app","me_agent.app_memory","Retrieve app-specific habits."),("resolve","me_agent.personalize","Resolve instruction using hierarchical preferences."),("act","me_agent.execute","Execute mobile actions."),("update","me_agent.learn","Update two-level habit memory from outcome."))),
R("agentic_neural_network_findings_acl2026","Self-Evolving Multi-Agent Systems via Textual Backpropagation","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.483/",("multi-agent-reasoning-suite",),COMMON+("reproduce layered forward construction and textual-backpropagation optimization of agent teams",),("task_accuracy","token_cost","agent_count","optimization_gain","convergence_steps"),("static multi-agent topology","single agent","manual workflow"),("no textual backpropagation","fixed aggregation","fixed agent teams"),(("decompose","ann.forward","Dynamically decompose task into layer subtasks."),("construct","ann.team","Construct cooperative agent teams and aggregation per layer."),("execute","ann.forward_pass","Run layered multi-agent forward trajectory."),("critique","ann.loss","Convert outcome errors into textual optimization signals."),("backprop","ann.textual_bp","Propagate textual feedback through teams."),("evolve","ann.update","Revise prompts/roles/topology for the next episode."))),
R("sema_rag_findings_acl2026","SEMA-RAG: A Self-Evolving Multi-Agent Retrieval-Augmented Generation Framework for Medical Reasoning","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.917/",("medical-qa-5bench",),COMMON+("reproduce Interpreter/Explorer/Arbiter roles and sufficiency-driven iterative retrieval across five benchmarks and matched backbones",),("accuracy","evidence_recall","retrieval_rounds","sufficiency_score","token_count"),("single-round RAG","single-agent iterative RAG","strongest paper baseline"),("no interpreter","no sufficiency feedback","no arbiter"),(("interpret","sema.interpreter","Map question to clinically grounded schema."),("query","sema.query","Construct evidence-seeking query."),("explore","sema.explorer","Retrieve evidence iteratively."),("judge_sufficiency","sema.sufficiency","Decide whether evidence chain is sufficient."),("adjudicate","sema.arbiter","Resolve conflicting evidence and candidate answers."),("answer","sema.answer","Produce grounded medical answer."))),
R("mass_rag_findings_acl2026","MASS-RAG: Multi-Agent Synthesis Retrieval-Augmented Generation","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.480/",("rag-qa-4bench",),COMMON+("reproduce role-specialized evidence summarization, extraction, reasoning and synthesis under matched retrieval contexts",),("accuracy","f1","evidence_precision","evidence_recall","token_count"),("single-agent RAG","vanilla RAG","single-view evidence processing"),("no summarizer agent","no extractor agent","no dedicated synthesis"),(("retrieve","mass_rag.retrieve","Retrieve heterogeneous evidence."),("summarize","mass_rag.summarizer","Create compact evidence view."),("extract","mass_rag.extractor","Extract answer-bearing evidence."),("reason","mass_rag.reasoner","Reason over retrieved documents."),("compare","mass_rag.compare","Expose complementary intermediate views."),("synthesize","mass_rag.synthesis","Integrate views into final grounded answer."))),
R("mac_reasoner_findings_acl2026","MAC-Reasoner: A Multi-Agent Collaborative Framework for Enhancing Logical Reasoning in Large Language Models","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.233/",("logical-reasoning-4bench",),COMMON+("evaluate three backbone LLMs on four benchmarks with solver-derived Logic-Augmented Context",),("accuracy","program_execution_rate","constraint_violation_rate","correction_rate","tokens"),("chain-of-thought","neuro-symbolic solver pipeline","single-agent program reasoning"),("no solver context","no conflict attention","no translator agent"),(("translate","mac.translator","Translate problem into executable symbolic program."),("execute","mac.solver","Run symbolic solver."),("augment","mac.context","Transform solver state into Logic-Augmented Context."),("detect","mac.conflict","Identify violated constraints and conflicts."),("reason","mac.agent","Reason with heightened attention to conflicts."),("answer","mac.final","Return verified answer."))),
R("plan_rewardbench_acl2026","Aligning Agents via Planning: A Benchmark for Trajectory-Level Reward Modeling","ACL 2026","https://aclanthology.org/2026.acl-long.1062/",("plan-rewardbench",),COMMON+("evaluate trajectory judges across safety refusal, tool irrelevance/unavailability, complex planning and robust error recovery",),("pairwise_accuracy","hard_negative_accuracy","safety_accuracy","planning_accuracy","recovery_accuracy"),("pointwise reward model","outcome-only judge","generic preference judge"),("remove rule perturbations","remove minimal-edit negatives","remove natural-rollout negatives"),(("rollout","planrm.rollout","Load validated positive tool trajectory."),("perturb","planrm.negative","Construct confusable hard-negative trajectory."),("inspect","planrm.judge","Judge full trajectory rather than isolated response."),("compare","planrm.preference","Choose preferred trajectory."),("stratify","planrm.eval","Report performance by four planning families."))),
R("conflict_aware_memory_acl2026","Conflict-Aware Memory for Embodied Agents: Enhancing Vector Data Quality via Detection Rules","ACL 2026","https://aclanthology.org/2026.acl-long.1306/",("embodied-planning-memory",),COMMON+("reproduce conflict detection rules for semantically conflicting text and highly similar images before planner retrieval",),("grammatical_accuracy","interpretation_accuracy","task_success","conflict_detection_f1","retrieval_precision"),("basic LLM planner","vector-memory planner","uncorrected vector index"),("no conflict rules","text rules only","image rules only"),(("encode","cdr.memory","Project embodied text/image experiences into vector memory."),("detect","cdr.rules","Detect contextual semantic and visual conflicts."),("repair","cdr.index","Correct memory index structure."),("retrieve","cdr.retrieve","Retrieve conflict-aware planning evidence."),("plan","cdr.planner","Generate executable embodied task plan."),("execute","cdr.embodied","Execute and record outcome."))),
R("faer_findings_acl2026","FAER: Benchmarking VLMs for Failure-Aware Embodied Reasoning","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.948/",("faer",),COMMON+("reproduce 3,323 episodes spanning 3 scenes, 65 tasks and 83 objects; evaluate 16 VLMs and 4 LLMs where available",),("failure_detection_f1","false_negative_rate","failure_category_accuracy","description_score","correction_accuracy"),("paper VLM suite","paper LLM suite","chance/majority baseline"),("detection only","no temporal context","no visual observation"),(("observe","faer.visual","Consume long-horizon embodied execution observations."),("detect","faer.detect","Detect abnormal execution event."),("categorize","faer.category","Classify high-level failure."),("describe","faer.describe","Explain failure grounded in trajectory."),("correct","faer.correct","Propose corrective action or plan."),("score","faer.eval","Score all four failure-aware capabilities and false negatives."))),
)
PROGRAMS={r.method_id:r.program() for r in REPRODUCTIONS}
STUDY_SPECS={r.method_id:r.study() for r in REPRODUCTIONS}
__all__=["REPRODUCTIONS","PROGRAMS","STUDY_SPECS"]
