from __future__ import annotations

from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.reproductions.frontier_2026.study import PaperStudySpec


def _paper(method_id,title,venue,uri,benchmarks,phases,metrics,ablations,protocol):
    phase_specs=tuple(AgentPhaseSpec(name, capability, description) for name,capability,description in phases)
    spec=PaperStudySpec(method_id=method_id,title=title,venue=venue,paper_uri=uri,benchmark_ids=benchmarks,protocol=protocol,metrics=metrics,ablations=ablations)
    method=AgentMethodSpec(
        method_id=method_id,
        implementation_version="2026-paper-protocol",
        schema_version=f"{method_id}.phase-workflow.v1",
        phases=phase_specs,
        max_cycles=128,
        configuration={"paper_uri":uri,"venue":venue,"benchmark_ids":benchmarks,"protocol":protocol,"ablations":ablations},
        evidence_obligations=(f"{method_id}.phase-transcript",f"{method_id}.model-tool-receipts",f"{method_id}.metric-artifacts"),
        metric_names=metrics,
        artifact_kinds=(f"{method_id}_trajectory",f"{method_id}_experiment_manifest"),
    )
    return method.compile(),spec

PAPERS={}
def _add(key,*args): PAPERS[key]=_paper(key,*args)

_add("echo_cvpr2026","Experience Transfer for Multimodal LLM Agents in Minecraft Game","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/",("minecraft",),(("observe","echo.perception","Ground current Minecraft state in multimodal observations."),("describe_context","echo.csd","Build the Contextual State Descriptor."),("retrieve_transfer","echo.memory","Retrieve reusable structural, attribute, procedural, functional and interaction experience."),("analogize","echo.ical","Infer candidate knowledge by in-context analogy."),("verify","echo.verify","Validate transferred knowledge through environment interaction."),("consolidate","echo.memory","Write verified transferable experience back to memory.")),("unlock_speed","item_unlock_count","transfer_success","interaction_steps"),("no memory","no CSD","no ICAL","no verification"),("reproduce learning-from-scratch Minecraft item unlocking","preserve active transfer rather than passive retrieval","report unlock speed and chain-unlock behavior"))
_add("pred_eqa_cvpr2026","Predict Before You Explore: Predictive Planning with Specialized Memory for Embodied Question Answering","CVPR 2026","https://openaccess.thecvf.com/content/CVPR2026/",("openeqa","express-bench"),(("parse_question","predeqa.question","Extract evidence requirements."),("predict_evidence","predeqa.predictor","Predict likely evidence locations."),("branch_plan","predeqa.planner","Construct compact hierarchical exploration branches."),("navigate","predeqa.navigation","Execute the selected branch."),("update_specialized_memory","predeqa.memory","Separate planning priors from question evidence."),("correct_prediction","predeqa.correction","Correct future exploration from observed prediction error."),("answer","predeqa.answer","Answer from accumulated evidence.")),("answer_accuracy","navigation_efficiency","spl","evidence_recall"),("reactive planning","monolithic memory","no prediction correction"),("evaluate OpenEQA and Express-Bench","preserve prediction-correction loop","separate planning and evidence memory"))
_add("m3_agent_iclr2026","Seeing, Listening, Remembering, and Reasoning: A Multimodal Agent with Long-Term Memory","ICLR 2026","https://proceedings.iclr.cc/",("m3-bench-robot","m3-bench-web","videomme-long"),(("perceive_av","m3.perception","Ingest streaming visual and audio observations."),("update_episode","m3.episodic","Update entity-centric episodic memory."),("update_semantics","m3.semantic","Consolidate entity-centric semantic memory."),("retrieve","m3.retrieve","Retrieve multimodal memories relevant to the instruction."),("reason","m3.reason","Perform multi-turn memory-grounded reasoning."),("answer","m3.answer","Emit grounded answer.")),("accuracy","robot_accuracy","web_accuracy","videomme_long_accuracy"),("no episodic memory","no semantic memory","no RL","text-only memory"),("evaluate all three reported benchmarks","preserve audio-visual streaming and entity-centric organization","compare prompting and memory baselines"))
_add("memoryagentbench_iclr2026","Evaluating Memory in LLM Agents via Incremental Multi-Turn Interactions","ICLR 2026","https://proceedings.iclr.cc/",("memoryagentbench",),(("ingest_turn","mab.ingest","Incrementally ingest each interaction."),("memory_action","mab.memory","Invoke the evaluated agent's native memory policy."),("query","mab.query","Issue benchmark query at the specified turn."),("score","mab.score","Score the target memory competency.")),("accurate_retrieval","test_time_learning","long_range_understanding","selective_forgetting","overall"),("full context","RAG","external memory","tool memory"),("preserve incremental multi-turn presentation","score four cognitive competencies separately","avoid static long-context substitution"))
_add("mikasa_iclr2026","Memory, Benchmark & Robots: A Benchmark for Solving Complex Tasks with Reinforcement Learning","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/1088fffae5f2aa8c8324e4f45f62248d-Abstract-Conference.html",("mikasa-base","mikasa-robo"),(("observe_partial","mikasa.observe","Receive partial observation."),("update_memory","mikasa.memory","Update evaluated recurrent/external memory."),("policy","mikasa.policy","Choose control action."),("step_robot","mikasa.env","Advance tabletop manipulation environment."),("score_memory_skill","mikasa.score","Attribute result to memory-intensive skill class.")),("success_rate","return","memory_skill_success","sample_efficiency"),("memoryless","recurrent memory","transformer memory","oracle state"),("run MIKASA-Base and all 32 MIKASA-Robo tasks","stratify by memory-task taxonomy","keep partial observability intact"))
_add("personalalign_acl2026","PersonalAlign: Hierarchical Implicit Intent Alignment for Personalized GUI Agent with Long-Term User-Centric Records","ACL 2026","https://aclanthology.org/2026.acl-long.1669/",("androidintent",),(("read_intent","personalalign.intent","Parse vague user instruction and current state."),("retrieve_records","personalalign.memory","Retrieve long-term user records."),("resolve_preference","personalalign.preference","Infer omitted preference hierarchically."),("infer_routine","personalalign.routine","Infer latent routine from user state."),("act_or_suggest","personalalign.agent","Execute personalized GUI action or proactive suggestion.")),("preference_accuracy","routine_accuracy","task_success","suggestion_quality"),("no records","flat retrieval","explicit-only intent","no proactive routine"),("evaluate 775 preferences and 215 routines","preserve user-specific record boundaries","separate vague-instruction resolution from proactive suggestion"))
_add("learnact_acl2026","LearnAct: Few-Shot Mobile GUI Agent with a Unified Demonstration Benchmark","ACL 2026 Findings","https://aclanthology.org/2026.findings-acl.1491/",("learngui-offline","learngui-online"),(("encode_demo","learnact.demo","Parse visual demonstration."),("extract_knowledge","learnact.extract","Extract reusable action knowledge."),("retrieve_knowledge","learnact.retrieve","Retrieve demonstration knowledge for current state."),("reason","learnact.reason","Condition action reasoning on retrieved knowledge."),("act","learnact.act","Execute mobile GUI action.")),("offline_score","online_success_rate","task_success","demo_gain"),("zero-shot","one-shot","two-shot","three-shot","no retrieval"),("run 2252 offline and 101 online LearnGUI tasks","stratify by shot count and backbone","retain visual demonstrations rather than textualizing them"))
_add("infiguiagent_eacl2026","InfiGUIAgent: A Multimodal Generalist GUI Agent with Native Reasoning and Reflection","EACL 2026","https://aclanthology.org/2026.eacl-long.45/",("screenspot","androidcontrol","gui-odyssey"),(("understand_gui","infigui.perception","Ground GUI elements from pixels."),("hierarchical_reason","infigui.reason","Decompose multi-step task hierarchically."),("act","infigui.action","Emit grounded GUI action."),("expect","infigui.expectation","Predict expected post-action state."),("reflect","infigui.reflection","Compare observation with expectation and revise reasoning.")),("grounding_accuracy","task_success","step_success","reflection_recovery"),("no hierarchical reasoning","no expectation reflection","stage1 only"),("evaluate grounding and multi-step interaction separately","preserve native expectation-reflection loop","report stage-wise training ablations"))
_add("agemem_acl2026","Agentic Memory: Learning Unified Long-Term and Short-Term Memory Management for Large Language Model Agents","ACL 2026","https://aclanthology.org/2026.acl-long.981/",("longmemeval","locomo"),(("observe","agemem.observe","Read current interaction."),("choose_memory_action","agemem.policy","Jointly choose store/retrieve/update/summarize/discard or task action."),("execute_memory_tool","agemem.memory","Apply selected STM/LTM operation."),("reason","agemem.reason","Reason over managed working context."),("act","agemem.act","Produce task action or answer.")),("task_score","memory_tool_accuracy","context_efficiency","long_horizon_score"),("separate STM/LTM controllers","no memory tools","no step-wise GRPO","SFT only"),("preserve unified policy over memory and task actions","reproduce three-stage progressive RL treatments","measure task and memory-operation outcomes"))
_add("magnet_acl2026","MAGNET: Towards Adaptive GUI Agents with Memory-Driven Knowledge Evolution","ACL 2026","https://aclanthology.org/2026.acl-long.1299/",("androidworld",),(("observe_gui","magnet.perception","Observe current UI under distribution shift."),("retrieve_stationary","magnet.stationary","Map visual features to stable functional semantics."),("retrieve_procedural","magnet.procedural","Retrieve stable task intent across workflows."),("act","magnet.action","Execute grounded GUI action."),("evolve_memory","magnet.evolution","Refine frequently accessed stationary and procedural knowledge.")),("task_success","distribution_shift_success","grounding_accuracy","adaptation_gain"),("no memory","stationary only","procedural only","no evolution"),("evaluate AndroidWorld online adaptation","include offline distribution-shift evaluation","preserve dual-level memory and access-driven evolution"))

PROGRAMS={k:v[0] for k,v in PAPERS.items()}
SPECS={k:v[1] for k,v in PAPERS.items()}
__all__=["PAPERS","PROGRAMS","SPECS"]
