"""Frontier wave 15: published agent lineage reproductions across memory, Minecraft, multimodal, tool planning, and multi-agent systems.

Paper-reported results are provenance only. Measured Noetrium results require bound benchmark execution receipts and result artifacts.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id: str; title: str; venue: str; paper_uri: str
    benchmarks: tuple[str,...]; protocol: tuple[str,...]; metrics: tuple[str,...]
    baselines: tuple[str,...]; ablations: tuple[str,...]; phases: tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id, implementation_version="paper-protocol", schema_version=self.method_id+".phase-workflow.v1", phases=tuple(AgentPhaseSpec(*p) for p in self.phases), max_cycles=64, configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations}, evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"), metric_names=self.metrics, artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self):
        return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)

def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze paper-faithful benchmark/model/environment/split/seed identities","run method and matched baselines under identical budgets","persist episode-level Machine Journal receipts plus metric/result artifacts","keep paper reference values distinct from Noetrium measured values")

REPRODUCTIONS=(
R("m2pa_findings_acl2025","M2PA: A Multi-Memory Planning Agent for Open Worlds Inspired by Cognitive Theory","Findings ACL 2025","https://aclanthology.org/2025.findings-acl.1191/",("m2pa-minecraft-50","m2pa-obtain-diamond-lifelong"),COMMON+("reproduce 50-task zero-shot Minecraft evaluation and exploratory lifelong ObtainDiamond protocol",),("task_success","planning_success","memory_retrieval_accuracy","replanning_count","lifelong_success"),("Voyager-style agent","single-memory planner","paper open-world baselines"),("no working memory","no episodic memory","no semantic memory","no metacognition"),(("perceive","m2pa.perceive","Ground current Minecraft state."),("retrieve","m2pa.memory","Retrieve coordinated multi-level memories."),("plan","m2pa.plan","Construct a goal-conditioned plan from memory and world state."),("execute","m2pa.execute","Execute grounded skills."),("reflect","m2pa.reflect","Diagnose execution and planning failures."),("consolidate","m2pa.consolidate","Update reusable memories from experience."))),
R("metagent_p_findings_acl2025","Metagent-P: A Neuro-Symbolic Planning Agent with Metacognition for Open Worlds","Findings ACL 2025","https://aclanthology.org/2025.findings-acl.1169/",("metagent-p-minecraft-long-horizon",),COMMON+("reproduce Minecraft long-term tasks and step-wise open-world self-evolution",),("task_success","replanning_count","plan_validity","human_relative_success","exploration_progress"),("LLM planner","symbolic planner","paper Minecraft agents"),("no multimodal memory","no symbolic verification","no metacognitive monitor","no reflection"),(("perceive","metagent_p.perception","Fuse multimodal world observations."),("plan","metagent_p.planning","Generate hierarchical neuro-symbolic plan."),("verify","metagent_p.verify","Verify plan constraints before execution."),("execute","metagent_p.execute","Execute verified skills."),("monitor","metagent_p.monitor","Monitor discrepancy and confidence."),("reflect","metagent_p.reflect","Regulate/replan and consolidate experience."))),
R("agentic_plan_caching_neurips2025","Agentic Plan Caching: Test-Time Memory for Fast and Cost-Efficient LLM Agents","NeurIPS 2025","https://proceedings.neurips.cc/paper_files/paper/2025/hash/9549f7d06700f0966d5f938f1d11022a-Abstract-Conference.html",("apc-real-world-agent-applications",),COMMON+("reproduce test-time extraction, matching, adaptation and reuse of structured plans across the paper applications",),("task_score","cost","latency","cache_hit_rate","plan_reuse_rate"),("no cache","semantic cache","context cache"),("no template extraction","no keyword matching","no lightweight adaptation","cold cache"),(("solve","apc.solve","Execute a task and obtain a successful plan."),("extract","apc.extract","Extract reusable structured plan template."),("index","apc.index","Index template by task-relevant keywords."),("match","apc.match","Match new request against cached plans."),("adapt","apc.adapt","Adapt cached template to current context."),("execute","apc.execute","Execute adapted plan and record cost/latency."))),
R("t1_neurips2025","T1: A Tool-Oriented Conversational Dataset for Multi-Turn Agentic Planning","NeurIPS 2025 Datasets and Benchmarks","https://proceedings.nips.cc/paper_files/paper/2025/hash/965605e3b223f3a157d6d6bb64bc9592-Abstract-Datasets_and_Benchmarks_Track.html",("t1-nine-domain",),COMMON+("reproduce all nine domains, multi-turn inter-tool dependencies, caching and dynamic replanning",),("task_success","tool_selection_accuracy","dependency_validity","replanning_accuracy","cache_reuse_accuracy"),("open-weight LLM baselines","proprietary LLM baselines","T1-Agent variants"),("no short-term cache","no long-term cache","no replanning","single-turn"),(("understand","t1.intent","Track multi-turn user state."),("plan","t1.plan","Construct dependency-aware tool plan."),("resolve","t1.dependencies","Resolve inter-tool inputs/outputs."),("reuse","t1.cache","Choose cached result reuse versus recomputation."),("execute","t1.execute","Execute tool sequence."),("replan","t1.replan","Dynamically revise plan after new turns/effects."))),
R("membench_findings_acl2025","MemBench: Towards More Comprehensive Evaluation on the Memory of LLM-based Agents","Findings ACL 2025","https://aclanthology.org/2025.findings-acl.989/",("membench",),COMMON+("reproduce factual/reflective memory under participation/observation scenarios and long noisy histories",),("effectiveness","efficiency","capacity","retrieval_quality","answer_accuracy"),("agent memory baselines","long-context baseline","retrieval baseline"),("factual-only","reflective-only","participation-only","observation-only"),(("interact","membench.interact","Replay the prescribed participation or observation scenario."),("encode","membench.encode","Allow the evaluated memory system to store observations."),("query","membench.query","Issue factual or reflective memory query."),("retrieve","membench.retrieve","Retrieve memory under the configured history load."),("answer","membench.answer","Produce the benchmark answer."),("score","membench.score","Measure effectiveness, efficiency and capacity."))),
R("crab_findings_acl2025","CRAB: Cross-environment Agent Benchmark for Multimodal Language Model Agents","Findings ACL 2025","https://aclanthology.org/2025.findings-acl.1113/",("crab-benchmark-v0",),COMMON+("reproduce 120 desktop/mobile tasks, graph-based fine-grained evaluation, six MLMs and single/multi-agent configurations",),("completion_ratio","graph_completion","subtask_score","steps","token_cost"),("six paper MLM baselines","single-agent configuration","multi-agent configurations"),("desktop-only","mobile-only","binary evaluator","single-agent-only"),(("observe","crab.observe","Capture multimodal state from active device."),("plan","crab.plan","Plan across environment boundaries."),("act","crab.act","Issue grounded GUI/device action."),("handoff","crab.handoff","Coordinate configured agents/environments."),("evaluate","crab.graph_eval","Evaluate achieved nodes in task graph."),("aggregate","crab.aggregate","Aggregate completion and fine-grained scores."))),
R("agent_rewardbench_acl2025","Agent-RewardBench: Towards a Unified Benchmark for Reward Modeling across Perception, Planning, and Safety in Real-World Multimodal Agents","ACL 2025","https://aclanthology.org/2025.acl-long.857/",("agent-rewardbench",),COMMON+("reproduce perception/planning/safety evaluation across seven real-world agent scenarios with step-level rewards",),("reward_accuracy","step_reward_accuracy","preference_accuracy","scenario_macro_average","safety_accuracy"),("ten source-model families","general MLLM reward baselines","specialized reward models"),("no perception scenarios","no planning scenarios","no safety scenarios","trajectory-only scoring"),(("load","arb.load","Load verified trajectory step and scenario identity."),("perceive","arb.perception","Evaluate perceptual grounding reward."),("plan","arb.planning","Evaluate planning-step reward."),("safety","arb.safety","Evaluate safety-sensitive reward."),("score","arb.score","Compare reward judgment to benchmark labels."),("aggregate","arb.aggregate","Aggregate by dimension/scenario/model."))),
R("openagent_acl2025","Enhancing Open-Domain Task-Solving Capability of LLMs via Autonomous Tool Integration from GitHub","ACL 2025","https://aclanthology.org/2025.acl-long.1136/",("openact-339",),COMMON+("reproduce OpenAct 339 questions across seven domains and OpenAgent autonomous specialized-tool integration",),("success_rate","tool_integration_success","answer_accuracy","tool_failures","cost"),("LLM baselines","tool-agent baselines","manual tool integration"),("no hierarchy","no human experience","no self experience","fixed tools"),(("analyze","openagent.analyze","Identify domain-specific capability requirement."),("discover","openagent.discover","Locate candidate specialized tool implementation."),("integrate","openagent.integrate","Integrate tool into hierarchical agent execution."),("delegate","openagent.delegate","Assign subtasks to specialized subordinate agents."),("execute","openagent.execute","Solve OpenAct query using integrated tools."),("learn","openagent.experience","Update bi-level human/self experience for tool flaws."))),
R("msi_agent_emnlp2024","MSI-Agent: Incorporating Multi-Scale Insight into Embodied Agents for Superior Planning and Decision-Making","EMNLP 2024","https://aclanthology.org/2024.emnlp-main.38/",("msi-embodied-planning",),COMMON+("reproduce task-specific and high-level insight generation/retrieval for embodied planning",),("task_success","planning_score","insight_relevance","steps","token_cost"),("base embodied LLM agent","single-scale insight strategy","paper insight baseline"),("no experience selector","no insight generator","no insight selector","task-specific-only"),(("select_experience","msi.experience","Select relevant historical experiences."),("generate","msi.generate","Generate task-specific and generalized insights."),("store","msi.store","Persist insights with scale identity."),("select_insight","msi.select","Retrieve relevant multi-scale insights."),("plan","msi.plan","Condition embodied plan on selected insight."),("execute","msi.execute","Act and collect outcome for subsequent insight formation."))),
R("mam_findings_acl2025","MAM: Modular Multi-Agent Framework for Multi-Modal Medical Diagnosis via Role-Specialized Collaboration","Findings ACL 2025","https://aclanthology.org/2025.findings-acl.1298/",("mam-multimodal-medical-suite",),COMMON+("reproduce public text/image/audio/video diagnostic datasets with GP, specialists, radiologist, assistant and director roles",),("diagnostic_accuracy","macro_f1","modality_score","collaboration_gain","cost"),("modality-specific medical LLMs","unified multimodal medical LLM","single-agent baseline"),("no role specialization","no specialist team","no radiologist","no director"),(("triage","mam.gp","General practitioner summarizes case and routes evidence."),("specialize","mam.specialists","Specialists independently analyze domain evidence."),("image","mam.radiologist","Radiologist interprets visual evidence."),("assist","mam.assistant","Medical assistant consolidates records and knowledge."),("deliberate","mam.collaborate","Exchange role-specialized findings."),("decide","mam.director","Director integrates evidence into final diagnosis."))),
)

def all_reproductions()->tuple[Reproduction,...]: return REPRODUCTIONS
