from __future__ import annotations

from .action_identity import (
    ActionIdentityViolation,
    ActionSemanticIdentity,
    require_action_recovery_handle_identity,
    require_action_result_identity,
    require_effect_receipt_digest,
    require_reconciliation_identity,
    require_recovery_handle_reconciliation_identity,
)
from .errors import (
    ActionNotApplied,
    ActionRecoveryRequired,
    ActionSafetyCapabilityMissing,
    ActionScientificCommitContradiction,
    EnvironmentCapabilityUnsupported,
)
from .contracts import (
    EnvironmentAssignmentIdentity,
    EnvironmentAssignmentIsolationPort,
    EnvironmentAssignmentIsolationReceipt,
    ActionReconciliationDisposition,
    ActionReconciliationResult,
    ActionRequest,
    ActionResult,
    DurablePreparedActionSession,
    EnvironmentIdentity,
    EnvironmentImplementation,
    EnvironmentSession,
    Observation,
    SystemIdentity,
    SystemPort,
    SystemSpec,
    action_request_digest,
)
from noetrium_platform.foundation.kernel.kernel import ExecutionContext
from noetrium_platform.foundation.kernel.kernel.operation import EffectClass, EffectCertainty, EffectReceipt
from .conformance import (
    EnvironmentConformanceProbe,
    EnvironmentProviderConformanceReceipt,
    verify_environment_provider_conformance,
)
from .provider import (
    EnvironmentCapability,
    EnvironmentDiagnosticsPort,
    EnvironmentProviderCapabilities,
    EnvironmentProviderPort,
    EnvironmentSessionDiagnostics,
    EnvironmentSessionServices,
)
from .interaction import (
    EnvironmentActionLifecycle,
    EnvironmentActionPhase,
    EnvironmentCapabilityDescriptor,
    EnvironmentCoordinationPort,
    EnvironmentCoordinationReceipt,
    EnvironmentCoordinationRequest,
    EnvironmentQuery,
    EnvironmentQueryKind,
    EnvironmentQueryPort,
    EnvironmentQueryResult,
    EnvironmentRawEventReceipt,
    EnvironmentRawEventRecord,
    EnvironmentRawRecordSinkPort,
)
from .state_machine import (
    JsonScalar,
    JsonInput,
    JsonMutableValue,
    JsonValue,
    StateMachineDynamicsIdentity,
    StateMachineDynamicsPort,
    StateMachineEnvironmentSpec,
    StateTransition,
    freeze_json_mapping,
    thaw_json,
    thaw_json_mapping,
)

__all__ = [
    "SystemIdentity", "SystemSpec", "SystemPort", "ExecutionContext",
    "EffectClass", "EffectCertainty", "EffectReceipt",
    "ActionIdentityViolation", "ActionNotApplied", "ActionRecoveryRequired",
    "ActionReconciliationDisposition", "ActionReconciliationResult",
    "ActionRequest", "ActionResult", "ActionSafetyCapabilityMissing",
    "ActionScientificCommitContradiction", "ActionSemanticIdentity",
    "EnvironmentAssignmentIdentity",
    "EnvironmentAssignmentIsolationPort",
    "EnvironmentAssignmentIsolationReceipt",
    "EnvironmentCapabilityUnsupported", "EnvironmentCapability",
    "EnvironmentConformanceProbe", "EnvironmentProviderConformanceReceipt",
    "verify_environment_provider_conformance",
    "EnvironmentDiagnosticsPort", "EnvironmentProviderCapabilities",
    "EnvironmentProviderPort", "EnvironmentSessionDiagnostics",
    "EnvironmentSessionServices",
    "EnvironmentActionLifecycle", "EnvironmentActionPhase",
    "EnvironmentCapabilityDescriptor",
    "EnvironmentCoordinationPort", "EnvironmentCoordinationReceipt",
    "EnvironmentCoordinationRequest",
    "EnvironmentQuery", "EnvironmentQueryKind", "EnvironmentQueryPort",
    "EnvironmentQueryResult",
    "EnvironmentRawEventReceipt", "EnvironmentRawEventRecord",
    "EnvironmentRawRecordSinkPort",
    "DurablePreparedActionSession", "EnvironmentIdentity",
    "EnvironmentImplementation", "EnvironmentSession", "Observation",
    "action_request_digest", "require_action_recovery_handle_identity",
    "require_action_result_identity", "require_effect_receipt_digest",
    "require_reconciliation_identity", "require_recovery_handle_reconciliation_identity",
    "JsonScalar", "JsonInput", "JsonMutableValue", "JsonValue",
    "StateMachineDynamicsIdentity", "StateMachineDynamicsPort",
    "StateMachineEnvironmentSpec", "StateTransition",
    "freeze_json_mapping", "thaw_json", "thaw_json_mapping",
]
