from __future__ import annotations

from .catalog import FailureCatalog, FailureSpec
from .contracts import RecoveryAction, RiskLevel

DEFAULT_FAILURE_CATALOG = FailureCatalog((
    FailureSpec(
        "MODEL_SERVING", "PROCESS_EXIT", "runtime", RecoveryAction.RESTART_EXACT_MODEL,
        description="Model serving process exited outside the expected service lifecycle.",
        owner="service_os",
        diagnostic_focus=("process_identity","exit_code","stdout_tail","stderr_tail"),
        operator_checks=("runtime-status","crash-bundle-verify"),
    ),
    FailureSpec(
        "MODEL_SERVING", "REQUEST_TIMEOUT", "request", RecoveryAction.RETRY_OPERATION,
        description="A model request exceeded its frozen request deadline without identity drift.",
        owner="model_os",
        diagnostic_focus=("queue_wait","ttft","provider_attempt","request_deadline"),
        operator_checks=("telemetry-query","debug-snapshot"),
    ),
    FailureSpec(
        "MODEL_SERVING", "IDENTITY_DRIFT", "identity", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        scientific_validity_risk=RiskLevel.CRITICAL,
        description="Live model/runtime identity differs from the frozen scientific model stack.",
        owner="runtime_manager",
        diagnostic_focus=("stack_digest","heartbeat_identity","qualification_digest","runtime_manifest"),
        operator_checks=("runtime-status","release-verify"),
    ),
    FailureSpec(
        "LLM_CONTRACT", "OUTPUT_CONTRACT", "decode", RecoveryAction.RETRY_OPERATION,
        description="LLM output failed the declared structured output contract after transport succeeded.",
        owner="llm_runtime",
        diagnostic_focus=("prompt_digest","response_digest","parse_error","schema_validation"),
        operator_checks=("debug-snapshot","telemetry-query"),
    ),
    FailureSpec(
        "PROMPT", "REQUEST_IDENTITY_DRIFT", "pre_transport", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        comparability_risk=RiskLevel.CRITICAL,
        description="Prompt generation/bundle/request identity changed between resolution and transport.",
        owner="prompt_os",
        diagnostic_focus=("generation_id","bundle_digest","request_digest","execution_contract"),
        operator_checks=("debug-snapshot","release-verify"),
    ),
    FailureSpec(
        "ENVIRONMENT", "EFFECT_UNKNOWN", "act", RecoveryAction.RECONCILE_EFFECT,
        description="Environment side effect may have occurred but acknowledgement is not authoritative.",
        owner="environment_runtime",
        diagnostic_focus=("effect_id","effect_receipt","environment_generation","post_effect_observation"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "ENVIRONMENT", "ACTION_SAFETY_CAPABILITY_MISSING", "preflight", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        scientific_validity_risk=RiskLevel.CRITICAL,
        description="Crash-durable side-effect execution was requested but the Environment does not expose a durable opaque prepare/reconcile action recovery capability.",
        owner="environment_runtime",
        diagnostic_focus=("environment_id","durable_action_recovery_capability","journal_durability","environment_abi"),
        operator_checks=("runtime-status","release-verify"),
    ),
    FailureSpec(
        "ENVIRONMENT", "ACTION_RECOVERY_PREPARATION_FAILURE", "recovery_prepare", RecoveryAction.RETRY_OPERATION,
        description="Environment failed to create the durable opaque recovery handle before PREPARED; no external action is authorized yet.",
        owner="environment_runtime",
        diagnostic_focus=("action_id","request_digest","provider_schema","environment_generation"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "PLATFORM", "EFFECT_RECOVERY_ANCHOR_MISSING", "recovery_anchor_guard", RecoveryAction.RESTORE_CHECKPOINT,
        comparability_risk=RiskLevel.CRITICAL, scientific_validity_risk=RiskLevel.CRITICAL,
        description="A crash-durable non-terminal action exists, but the scientific run was not restored from a verified pre-cycle checkpoint anchor.",
        owner="run_runtime",
        diagnostic_focus=("intent_id","decision_cycle_id","checkpoint_id","journal_phase"),
        operator_checks=("debug-snapshot","timeline","runtime-status"),
    ),
    FailureSpec(
        "PLATFORM", "PENDING_EFFECT_RECOVERY_REQUIRED", "pending_effect_guard", RecoveryAction.RECONCILE_EFFECT,
        comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="A prior non-terminal external action exists in the same run/lifetime; a new external action is blocked until recovery resolves it.",
        owner="run_runtime",
        diagnostic_focus=("run_id","lifetime_id","pending_intent_id","journal_phase"),
        operator_checks=("debug-snapshot","timeline","runtime-status"),
    ),
    FailureSpec(
        "PLATFORM", "EFFECT_ALREADY_CONSUMED", "replay_guard", RecoveryAction.RECONCILE_METHOD_STATE,
        comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="The exact action intent is already marked CONSUMED by method scientific state; external action and method completion must not be replayed.",
        owner="run_runtime",
        diagnostic_focus=("intent_id","decision_cycle_id","task_id","journal_phase"),
        operator_checks=("debug-snapshot","timeline","last-writer"),
    ),
    FailureSpec(
        "ENVIRONMENT", "ACTION_NOT_APPLIED", "recovery_decision", RecoveryAction.REPLAN_ACTION,
        comparability_risk=RiskLevel.LOW, scientific_validity_risk=RiskLevel.LOW,
        description="Authoritative reconciliation proved the intended action was not applied; method completion is blocked and a new action decision is required.",
        owner="run_runtime",
        diagnostic_focus=("action_id","decision_cycle_id","effect_certainty","reconciliation_proof"),
        operator_checks=("timeline","debug-snapshot"),
    ),
    FailureSpec(
        "ENVIRONMENT", "EFFECT_RECONCILIATION_FAILURE", "reconcile", RecoveryAction.RECONCILE_EFFECT,
        comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="Environment action/effect reconciliation failed or remained uncertain; blind action replay is forbidden.",
        owner="environment_runtime",
        diagnostic_focus=("action_id","effect_id","environment_generation","reconciliation_capability"),
        operator_checks=("debug-snapshot","timeline","runtime-status"),
    ),
    FailureSpec(
        "PLATFORM", "EFFECT_INTENT_PREPARE_FAILURE", "effect_journal_prepare", RecoveryAction.RETRY_OPERATION,
        data_integrity_risk=RiskLevel.LOW,
        description="Durable effect intent preparation failed before the provider side-effect boundary was entered.",
        owner="effect_intent_journal",
        diagnostic_focus=("intent_id","request_digest","journal_durability","storage_error"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "PLATFORM", "EFFECT_INTENT_POST_EFFECT_RECORD_FAILURE", "effect_journal_post_effect", RecoveryAction.RECONCILE_EFFECT,
        data_integrity_risk=RiskLevel.MEDIUM, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="External effect returned or was reconciled, but its durable journal transition could not be confirmed.",
        owner="effect_intent_journal",
        diagnostic_focus=("intent_id","request_digest","effect_digest","journal_phase"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "PLATFORM", "EFFECT_INTENT_TERMINAL_RECORD_FAILURE", "effect_journal_terminal", RecoveryAction.COMMIT_ONLY,
        data_integrity_risk=RiskLevel.MEDIUM, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="A terminal effect-journal state (CONSUMED or NOT_APPLIED) could not be durably recorded; replaying the external effect is forbidden.",
        owner="effect_intent_journal",
        diagnostic_focus=("intent_id","request_digest","journal_phase","storage_error"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "STATE", "VERSION_CONFLICT", "commit", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Authoritative aggregate version/generation changed before optimistic commit.",
        owner="state_store",
        diagnostic_focus=("aggregate_id","expected_version","actual_version","last_writer"),
        operator_checks=("last-writer","timeline"),
    ),
    FailureSpec(
        "EVIDENCE", "CHAIN_CORRUPTION", "verify", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        data_integrity_risk=RiskLevel.CRITICAL, scientific_validity_risk=RiskLevel.CRITICAL,
        description="Authoritative evidence hash chain failed structural or digest verification.",
        owner="forensics",
        diagnostic_focus=("ledger","row_number","prev_hash","row_hash","tail_hash"),
        operator_checks=("verify-evidence","index-status"),
    ),
    FailureSpec(
        "METHOD", "TASK_COMPLETION_RECONCILIATION_FAILURE", "completion_reconcile", RecoveryAction.RECONCILE_METHOD_STATE,
        data_integrity_risk=RiskLevel.MEDIUM, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="Method authoritative task-completion reconciliation failed while recovering a non-terminal external action.",
        owner="method_plugin",
        diagnostic_focus=("method_id","completion_key","checkpoint_id","journal_phase"),
        operator_checks=("debug-snapshot","timeline","last-writer"),
    ),
    FailureSpec(
        "PLATFORM", "CROSS_COMPONENT_COMMIT_CONTRADICTION", "commit_consistency", RecoveryAction.QUARANTINE_RUN,
        data_integrity_risk=RiskLevel.CRITICAL, comparability_risk=RiskLevel.CRITICAL, scientific_validity_risk=RiskLevel.CRITICAL,
        description="Method authority proves task completion committed while authoritative Environment reconciliation says the corresponding action was not applied or is inconsistent.",
        owner="run_runtime",
        diagnostic_focus=("completion_key","intent_id","request_digest","effect_digest","checkpoint_id"),
        operator_checks=("debug-snapshot","timeline","last-writer","verify-evidence"),
    ),
    FailureSpec(
        "METHOD", "TASK_COMPLETION_IDEMPOTENCY_MISSING", "preflight", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        scientific_validity_risk=RiskLevel.CRITICAL,
        description="Crash-durable external-effect execution requires Method.task_completed to expose a stable idempotency key.",
        owner="method_plugin",
        diagnostic_focus=("method_id","task_completion_idempotency","task_key","journal_durability"),
        operator_checks=("runtime-status","release-verify"),
    ),
    FailureSpec(
        "METHOD", "SERVING_FAILURE", "recall", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Method memory-serving path failed during query planning, snapshot or retrieval.",
        owner="method_plugin",
        diagnostic_focus=("method_id","session_id","architecture_generation","serving_stage"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "METHOD", "INGEST_FAILURE", "ingest", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Method evidence ingestion failed before the component boundary returned success.",
        owner="method_plugin",
        diagnostic_focus=("method_id","session_id","evidence_sequence","input_digest"),
        operator_checks=("debug-snapshot","timeline","last-writer"),
    ),
    FailureSpec(
        "PARTICIPANT", "RESOLUTION_FAILURE", "resolve", RecoveryAction.MANUAL_DIAGNOSIS,
        data_integrity_risk=RiskLevel.NONE, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="A frozen participant runtime binding could not be resolved to a runnable handle before session acquisition.",
        owner="participant_resolution",
        diagnostic_focus=("role","implementation_digest","configuration_digest","resolver"),
        operator_checks=("runtime-status","release-verify","debug-snapshot","timeline"),
    ),
    FailureSpec(
        "METHOD", "SESSION_OPEN_FAILURE", "session_open", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Method session construction failed before a usable session handle was returned.",
        owner="method_plugin",
        diagnostic_focus=("method_id","configuration_digest","session_id","constructor_stage"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "METHOD", "SESSION_CLOSE_FAILURE", "session_close", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Method session cleanup failed after partial or complete study execution.",
        owner="method_plugin",
        diagnostic_focus=("method_id","session_id","pending_observations","cleanup_stage"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "ENVIRONMENT", "SESSION_OPEN_FAILURE", "session_open", RecoveryAction.RESTART_COMPONENT,
        description="Environment session construction failed before a usable session handle was returned.",
        owner="environment_runtime",
        diagnostic_focus=("environment_id","configuration_digest","session_id","transport_stage"),
        operator_checks=("runtime-status","debug-snapshot","timeline"),
    ),
    FailureSpec(
        "ENVIRONMENT", "SESSION_CLOSE_FAILURE", "session_close", RecoveryAction.RESTART_COMPONENT,
        description="Environment session cleanup failed after partial or complete study execution.",
        owner="environment_runtime",
        diagnostic_focus=("environment_id","session_id","transport_state","cleanup_stage"),
        operator_checks=("runtime-status","debug-snapshot","timeline"),
    ),
    FailureSpec(
        "ENVIRONMENT", "OBSERVE_FAILURE", "observe", RecoveryAction.RESTART_COMPONENT,
        description="Environment observation failed before an authoritative observation was returned.",
        owner="environment_runtime",
        diagnostic_focus=("environment_id","environment_generation","transport_state","observation_stage"),
        operator_checks=("debug-snapshot","runtime-status","timeline"),
    ),
    FailureSpec(
        "PLATFORM", "OPERATION_SEMANTIC_POLICY_VIOLATION", "operation_policy", RecoveryAction.BLOCK_SCIENTIFIC_USE,
        data_integrity_risk=RiskLevel.NONE, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="A protected component operation was constructed without its required logical replay identity.",
        owner="research_kernel",
        diagnostic_focus=("operation_id","operation_type","operation_payload_digest","operation_idempotency_key"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "PLATFORM", "OPERATION_FAILURE", "component_boundary", RecoveryAction.MANUAL_DIAGNOSIS,
        description="A component operation failed without a more specific registered taxonomy mapping.",
        owner="research_kernel",
        diagnostic_focus=("component_id","operation_id","operation_type","cause_type"),
        operator_checks=("debug-snapshot","timeline"),
    ),
    FailureSpec(
        "METHOD", "EVOLUTION_POST_COMMIT_UNCERTAIN", "evolution_post_commit", RecoveryAction.RECONCILE_METHOD_STATE,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.HIGH, scientific_validity_risk=RiskLevel.HIGH,
        description="Task completion committed, but evolution/adoption completion is uncertain; blind replay is forbidden.",
        owner="method_evolution",
        diagnostic_focus=("task_key","architecture_generation","evolution_stage","authoritative_adoption_state"),
        operator_checks=("debug-snapshot","last-writer","timeline"),
    ),
    FailureSpec(
        "METHOD", "EVOLUTION_FAILURE", "evolution", RecoveryAction.MANUAL_DIAGNOSIS,
        description="Self-evolution pipeline failed before a scientifically valid adoption completed.",
        owner="method_evolution",
        diagnostic_focus=("evolution_stage","candidate_id","base_generation","prepared_generation"),
        operator_checks=("debug-snapshot","last-writer"),
    ),
    FailureSpec(
        "METHOD", "OBSERVATION_DELIVERY", "post_commit_observability", RecoveryAction.REPLAY_OBSERVATION,
        description="Scientific mutation committed, but its observability outbox delivery failed.",
        owner="method_api",
        diagnostic_focus=("observation_id","session_revision","outbox_pending","sink_error"),
        operator_checks=("debug-snapshot","telemetry-query"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_SIGNAL", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="Model service terminated by an operating-system signal.", owner="service_os",
        diagnostic_focus=("signal","pid","start_identity","stdout_tail","stderr_tail"),
        operator_checks=("runtime-status","crash-bundle-verify"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_OOM", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="Model service exited because host/GPU memory allocation failed.", owner="model_os",
        diagnostic_focus=("gpu_memory","kv_cache","batch_size","context_tokens","stderr_tail"),
        operator_checks=("runtime-status","telemetry-query","crash-bundle-verify"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_GPU_DRIVER", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="GPU driver/device failure (for example Xid) terminated or invalidated model serving.", owner="model_os",
        diagnostic_focus=("gpu_xid","device_id","driver_state","process_identity","stderr_tail"),
        operator_checks=("runtime-status","telemetry-query","crash-bundle-verify"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_HEARTBEAT_LOSS", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="Model service stopped producing a valid heartbeat within the frozen freshness window.", owner="service_os",
        diagnostic_focus=("heartbeat_age","pid","start_identity","stack_digest","qualification_digest"),
        operator_checks=("runtime-status","timeline"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_ERROR", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="Model serving process reported a classified internal service error before exit.", owner="model_os",
        diagnostic_focus=("service_error_code","stderr_tail","request_id","replica_id"),
        operator_checks=("crash-bundle-verify","debug-snapshot"),
    ),
    FailureSpec(
        "MODEL_SERVING", "MODEL_SERVICE_UNKNOWN_EXIT", "service_process_exit", RecoveryAction.RESTART_EXACT_MODEL,
        data_integrity_risk=RiskLevel.LOW, comparability_risk=RiskLevel.MEDIUM, scientific_validity_risk=RiskLevel.MEDIUM,
        description="Model service exited abnormally but available evidence did not match a classified crash type.", owner="service_os",
        diagnostic_focus=("exit_code","signal","stdout_tail","stderr_tail","process_identity"),
        operator_checks=("crash-bundle-verify","debug-snapshot","runtime-status"),
    ),
))


__all__ = ["DEFAULT_FAILURE_CATALOG"]
