from __future__ import annotations
from typing import Protocol
from noetrium_platform.research.execution.command.api import CommandId
from noetrium_platform.infrastructure.reliability.effect.api import EffectReconciliationProof
from .contracts import (
    EffectId,
    OperationEffectCertainty,
    OperationEffectProfile,
    OperationFailure,
    OperationId,
    OperationSnapshot,
)

class OperationConflict(RuntimeError): pass
class OperationCorruption(RuntimeError): pass

class OperationStorePort(Protocol):
    @property
    def durability(self)->str: ...
    def create_or_get(self,snapshot:OperationSnapshot)->tuple[OperationSnapshot,bool]: ...
    def load(self,operation_id:OperationId)->OperationSnapshot|None: ...
    def compare_and_swap(self,expected_version:int,snapshot:OperationSnapshot)->OperationSnapshot: ...

class OperationSubmissionPort(Protocol):
    def submit(self,command_id:CommandId,*,operation_id:OperationId,
               parent_operation_id:OperationId|None=None,
               effect_profile:OperationEffectProfile=OperationEffectProfile.NONE,
               effect_id:EffectId|None=None,effect_request_id:str|None=None,
               effect_request_digest:str|None=None,now_unix:float|None=None)->tuple[OperationSnapshot,bool]: ...

class OperationAdmissionPort(Protocol):
    """Narrow scheduling/admission transition surface; no generic state mutation."""
    def queue(self,operation_id:OperationId,*,now_unix:float|None=None)->OperationSnapshot: ...
    def admit(self,operation_id:OperationId,*,now_unix:float|None=None)->OperationSnapshot: ...

class OperationRecoveryPort(Protocol):
    """Narrow read/reconciliation authority for proof-driven workflow recovery."""
    def require(self,operation_id:OperationId)->OperationSnapshot: ...
    def recover_interrupted(self,operation_id:OperationId)->OperationSnapshot: ...
    def reconcile_effect(self,operation_id:OperationId,proof:EffectReconciliationProof)->OperationSnapshot: ...
    def complete(self,operation_id:OperationId,*,result_digest:str|None=None,
                 effect_certainty:OperationEffectCertainty|None=None)->OperationSnapshot: ...

class OperationLifecyclePort(Protocol):
    """Narrow operation-state authority consumed by workflow runtime."""
    def require(self,operation_id:OperationId)->OperationSnapshot: ...
    def begin_execution(self,operation_id:OperationId)->OperationSnapshot: ...
    def request_cancel(self,operation_id:OperationId,reason:str)->OperationSnapshot: ...
    def recover_interrupted(self,operation_id:OperationId)->OperationSnapshot: ...
    def mark_effect_unknown(self,operation_id:OperationId,*,failure:OperationFailure|None=None)->OperationSnapshot: ...
    def reconcile_effect(self,operation_id:OperationId,proof:EffectReconciliationProof)->OperationSnapshot: ...
    def complete(self,operation_id:OperationId,*,result_digest:str|None=None,
                 effect_certainty:OperationEffectCertainty|None=None)->OperationSnapshot: ...
    def fail(self,operation_id:OperationId,failure:OperationFailure)->OperationSnapshot: ...

__all__=["OperationAdmissionPort","OperationConflict","OperationCorruption","OperationLifecyclePort","OperationRecoveryPort","OperationStorePort","OperationSubmissionPort"]
