from __future__ import annotations

from typing import Protocol, runtime_checkable

from .contracts import ProgramSpec, ProjectManifest, WorkspaceSpec


@runtime_checkable
class PortfolioCatalogPort(Protocol):
    def register_workspace(self, spec: WorkspaceSpec) -> None: ...
    def register_program(self, spec: ProgramSpec) -> None: ...
    def register_project(self, manifest: ProjectManifest) -> None: ...
    def workspace(self, workspace_id: str) -> WorkspaceSpec: ...
    def program(self, program_id: str) -> ProgramSpec: ...
    def project(self, project_id: str) -> ProjectManifest: ...
    def projects(self, *, program_id: str | None = None) -> tuple[ProjectManifest, ...]: ...


__all__ = ["PortfolioCatalogPort"]
