""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
Stable aggregate contract facade derived from generated contract families.
"""
from __future__ import annotations

from . import json as _source_0
from . import discovery as _source_1
from . import agent as _source_2
from . import environment as _source_3
from . import model as _source_4
from . import participant as _source_5
from . import project as _source_6
from . import research as _source_7
from . import server as _source_8
from . import session as _source_9
from .systems import SYSTEM_FACADES, SYSTEM_KEYS

_SOURCE_NAMES = ('json', 'discovery', 'agent', 'environment', 'model', 'participant', 'project', 'research', 'server', 'session')
_JSON_CANONICAL = ('CanonicalDecodingError', 'CanonicalDecodingFailureKind', 'CanonicalEncodingError', 'DigestValidationError', 'JsonDocument', 'JsonInput', 'JsonMutableValue', 'JsonObject', 'JsonScalar', 'JsonValue', 'Sha256Digest', 'canonical_bytes', 'canonical_digest', 'canonical_text', 'freeze_json', 'require_sha256', 'strict_finite_json_bytes', 'strict_finite_json_digest', 'strict_finite_json_text', 'strict_json_loads', 'thaw_json')
_SOURCES = tuple((_name, globals()[f'_source_{_index}']) for _index, _name in enumerate(_SOURCE_NAMES))
_owners: dict[str, str] = {}
_exports: list[str] = []

def _qualified(owner: str, name: str) -> str:
    return owner.replace('-', '_') + '__' + name

for _owner_name, _module in _SOURCES:
    for _name in _module.__all__:
        _value = getattr(_module, _name)
        if _name not in _owners:
            globals()[_name] = _value
            _owners[_name] = _owner_name
            _exports.append(_name)
            continue
        _previous_owner = _owners[_name]
        _current = globals()[_name]
        if _current is _value:
            continue
        if _name in _JSON_CANONICAL:
            if _previous_owner == 'json':
                continue
            if _owner_name == 'json':
                globals()[_name] = _value
                _owners[_name] = 'json'
                continue
        _old_alias = _qualified(_previous_owner, _name)
        _new_alias = _qualified(_owner_name, _name)
        if _old_alias not in globals():
            globals()[_old_alias] = _current
            _exports.append(_old_alias)
        globals()[_new_alias] = _value
        if _new_alias not in _exports:
            _exports.append(_new_alias)
        raise RuntimeError(
            f'top-level contract symbol collision requires explicit canonical source: {_name}: '
            f'{_previous_owner} vs {_owner_name}'
        )

__all__ = tuple(dict.fromkeys((*_exports, 'SYSTEM_FACADES', 'SYSTEM_KEYS')))

del _exports, _owners
