"""Stable, explicit contract surface for Noetrium downstream authors.

Submodules remain available for discoverability; this package re-exports only
the names intentionally declared by each public contract family.
"""

from .agent import (
    AgentIdentity,
    AgentImplementation,
    AgentSession,
    AgentSnapshot,
    AgentTurnRequest,
    AgentTurnResult,
    AgentActionExecutorPort,
    AgentActionSequence,
    AgentActionStep,
    AgentActionSummary,
    AgentCognitionError,
    AgentCompletionPort,
    AgentDiagnosticsPort,
    AgentEvidencePort,
    AgentGoal,
    AgentLoopCheckpoint,
    AgentLoopResult,
    AgentLoopTerminationReason,
    AgentMemoryContext,
    AgentMemoryPort,
    AgentModeDecision,
    AgentModeDisposition,
    AgentObservation,
    AgentObservationPort,
    AgentPlannerPort,
    AgentPlanningRequest,
    AgentProgressPort,
    AgentReactiveModePort,
    AgentReceiptCheckpoint,
    AgentSafetyDecision,
    AgentSafetyDisposition,
    AgentSafetySupervisorPort,
    AgentSkillCatalogPort,
    AgentSkillDescription,
    AgentSkillLibraryPort,
    AgentSkillRecord,
    AgentSkillSelection,
    AgentStepReceipt,
    action_summary_payload,
)
from .json import (
    CanonicalDecodingError,
    CanonicalDecodingFailureKind,
    CanonicalEncodingError,
    DigestValidationError,
    JsonDocument,
    JsonInput,
    JsonMutableValue,
    JsonObject,
    JsonScalar,
    JsonValue,
    Sha256Digest,
    canonical_bytes,
    canonical_digest,
    canonical_text,
    freeze_json,
    require_sha256,
    strict_finite_json_bytes,
    strict_finite_json_digest,
    strict_finite_json_text,
    strict_json_loads,
    thaw_json,
)
from .research import (
    CompiledResearchPlan,
    ExperimentRunner,
    ExperimentRunnerPort,
    ResearchBindingContribution,
    BenchmarkTaskSet,
    TaskDefinition,
    ResearchMethodHost,
    ResearchMethodHostPort,
    ResearchPlanDiff,
    ResearchStudyDefinition,
    RunArtifactKind,
    RunArtifactSnapshotReceipt,
    RunControlAction,
    RunControlActionFailure,
    RunControlConflict,
    RunControlError,
    RunControlEventReceipt,
    RunControlIntegrityError,
    RunControlNotFound,
    RunControlPhase,
    RunControlPort,
    RunControlReceipt,
    RunControlReceiptReference,
    RunControlRecordKind,
    RunControlRequest,
    RunControlStaleGeneration,
    RunControlTarget,
    RunControlTransitionOutcome,
    RunEvidenceValidity,
    RunExecutionOutcome,
    RunOutcomeProjection,
    RunScientificValidity,
    RunTaskOutcome,
    DerivedEvidenceArtifact,
    EvidenceBundleManifest,
    EvidenceBundleReceipt,
    EvidenceBundleStatus,
    EvidenceStreamDescriptor,
    compile_research_plan,
    diff_research_plans,
    resolve_research_requirements,
    BoundStudyUnitExecutionPort,
    BoundStudyVariantExecutionPort,
    ExperimentPlan,
    StudyAssignment,
    StudyConcurrencyPolicy,
    StudyExecutionUnit,
    StudyMatrixExecutionReport,
    StudyMetricAggregate,
    StudyMetricObservation,
    StudyProtocol,
    StudyVariantExecutionPort,
    StudyVariantSpec,
    VariantBinding,
    VariantKind,
    MeasurementRecord,
    MeasurementValue,
    MeasurementValueKind,
    TrialMatrixExecutionReport,
    BasicStudyMetricAggregator,
    DeterministicStudyAssignment,
    StudyMatrixExecutor,
    ResearchFigureFactory,
    AggregationFunction,
    AggregationSpec,
    BaselineRegistryPort,
    BaselineSpec,
    CsvTableReader,
    DataColumn,
    DataTable,
    EvaluationContext,
    EvaluationStage,
    FigureCategory,
    FigureCell,
    FigureKind,
    FigureOutputFormat,
    FigurePoint,
    FigureSeries,
    FigureSpec,
    FigureStyle,
    GroupComparison,
    InferenceResult,
    MultipleComparisonMethod,
    MultipleComparisonResult,
    JsonlTableReader,
    MetricSummary,
    MeasurementRecordTableAdapter,
    MissingValuePolicy,
    PairedComparison,
    RenderedResearchPackage,
    ResearchEvaluation,
    ResearchLifecycle,
    ResearchReport,
    ScientificStatistics,
    SplitStrategy,
    StandardTableRenderer,
    PdfFigureRenderer,
    PublicationFigureRenderer,
    StudyObservationTableAdapter,
    SvgFigureRenderer,
    TablePipeline,
)
from .project import (
    PROJECT_MANIFEST_SCHEMA,
    ProgramSpec,
    ProjectCapabilityRequirement,
    ProjectConfigurationReference,
    ProjectIdentity,
    ProjectManifest,
    ProjectManifestDecodeError,
    ProjectManifestFacet,
    ProjectManifestFacetChange,
    ProjectManifestFacetDiff,
    ProjectManifestIdentityFacets,
    ProjectMethodRequirement,
    ProjectProviderBinding,
    ProjectRequirementCardinality,
    ProjectSpec,
    ProjectToolProvenance,
    WorkspaceSpec,
    decode_project_manifest_bytes,
    decode_project_manifest_document,
    diff_project_manifest_facets,
    encode_project_manifest,
    project_manifest_document,
    project_manifest_identity_facets,
)
from .participant import (
    MethodIdentity,
    MethodProgramIdentity,
    MethodSnapshot,
    MethodTaskCompletionReceipt,
    MethodTaskOutcome,
    RecallRequest,
    RecallResult,
    AgentProjectDefinition,
    MethodProjectDefinition,
    ParticipantBindingDiagnostic,
    ParticipantBindingDiagnosticCode,
    ParticipantBindingDiagnosticSeverity,
    ParticipantProjectBindingError,
    ParticipantProviderProfile,
    ParticipantRequirement,
    ParticipantRequirementContribution,
    ProjectParticipantBinding,
    ProjectParticipantProviderPort,
)
from .model import (
    ModelBindingDiagnostic,
    ModelBindingDiagnosticCode,
    ModelBindingDiagnosticSeverity,
    ModelCapabilityRequirement,
    ModelProjectBindingError,
    ModelProjectDefinition,
    ModelProviderProfile,
    ProjectModelBinding,
    ProjectModelClientPort,
    ProjectModelProviderPort,
    ProjectModelRequest,
    ProjectModelResponse,
)
from .environment import (
    ActionRequest,
    ActionResult,
    EnvironmentAssignmentIdentity,
    EnvironmentAssignmentIsolationPort,
    EnvironmentAssignmentIsolationReceipt,
    EnvironmentCapability,
    EnvironmentCapabilityUnsupported,
    EnvironmentDiagnosticsPort,
    EnvironmentIdentity,
    EnvironmentImplementation,
    EnvironmentProviderCapabilities,
    EnvironmentProviderPort,
    EnvironmentSession,
    EnvironmentSessionDiagnostics,
    EnvironmentSessionServices,
    Observation,
)

__all__ = [
    "AgentIdentity", "AgentImplementation", "AgentSession", "AgentSnapshot",
    "AgentTurnRequest", "AgentTurnResult",
    "AgentActionExecutorPort", "AgentActionSequence", "AgentActionStep",
    "AgentActionSummary", "AgentCognitionError", "AgentCompletionPort",
    "AgentDiagnosticsPort", "AgentEvidencePort", "AgentGoal",
    "AgentLoopCheckpoint", "AgentLoopResult", "AgentLoopTerminationReason",
    "AgentMemoryContext", "AgentMemoryPort", "AgentModeDecision",
    "AgentModeDisposition", "AgentObservation", "AgentObservationPort",
    "AgentPlannerPort", "AgentPlanningRequest", "AgentProgressPort",
    "AgentReactiveModePort", "AgentReceiptCheckpoint", "AgentSafetyDecision",
    "AgentSafetyDisposition", "AgentSafetySupervisorPort",
    "AgentSkillCatalogPort", "AgentSkillDescription", "AgentSkillLibraryPort",
    "AgentSkillRecord", "AgentSkillSelection", "AgentStepReceipt",
    "action_summary_payload",
    "CanonicalDecodingError", "CanonicalDecodingFailureKind",
    "CanonicalEncodingError", "DigestValidationError", "JsonDocument",
    "JsonInput", "JsonMutableValue", "JsonObject", "JsonScalar", "JsonValue",
    "Sha256Digest", "canonical_bytes", "canonical_digest", "canonical_text",
    "freeze_json", "require_sha256", "strict_finite_json_bytes",
    "strict_finite_json_digest", "strict_finite_json_text", "strict_json_loads",
    "thaw_json",
    "CompiledResearchPlan", "ExperimentRunner", "ExperimentRunnerPort",
    "ResearchBindingContribution", "BenchmarkTaskSet", "TaskDefinition",
    "ResearchMethodHost", "ResearchMethodHostPort",
    "ResearchPlanDiff", "ResearchStudyDefinition", "compile_research_plan",
    "diff_research_plans", "resolve_research_requirements",
    "BoundStudyUnitExecutionPort", "BoundStudyVariantExecutionPort", "ExperimentPlan",
    "StudyAssignment", "StudyConcurrencyPolicy", "StudyExecutionUnit",
    "StudyMatrixExecutionReport", "StudyMetricAggregate", "StudyMetricObservation",
    "StudyProtocol", "StudyVariantExecutionPort", "StudyVariantSpec", "VariantBinding",
    "VariantKind", "MeasurementRecord", "MeasurementValue", "MeasurementValueKind",
    "TrialMatrixExecutionReport", "BasicStudyMetricAggregator", "DeterministicStudyAssignment",
    "StudyMatrixExecutor", "ResearchFigureFactory", "AggregationFunction", "AggregationSpec", "BaselineRegistryPort",
    "BaselineSpec", "CsvTableReader", "DataColumn", "DataTable", "EvaluationContext",
    "EvaluationStage", "FigureCategory", "FigureCell", "FigureKind", "FigureOutputFormat", "FigurePoint",
    "FigureSeries", "FigureSpec", "FigureStyle", "GroupComparison", "InferenceResult", "JsonlTableReader",
    "MetricSummary", "MeasurementRecordTableAdapter", "MissingValuePolicy",
    "PairedComparison", "RenderedResearchPackage", "ResearchEvaluation", "ResearchLifecycle", "ResearchReport",
    "ScientificStatistics", "SplitStrategy",
    "StandardTableRenderer", "PdfFigureRenderer", "PublicationFigureRenderer", "StudyObservationTableAdapter", "SvgFigureRenderer", "TablePipeline",
    "RunArtifactKind", "RunArtifactSnapshotReceipt", "RunControlAction",
    "RunControlActionFailure", "RunControlConflict", "RunControlError",
    "RunControlEventReceipt", "RunControlIntegrityError", "RunControlNotFound",
    "RunControlPhase", "RunControlPort", "RunControlReceipt",
    "RunControlReceiptReference", "RunControlRecordKind", "RunControlRequest",
    "RunControlStaleGeneration", "RunControlTarget", "RunControlTransitionOutcome",
    "RunEvidenceValidity", "RunExecutionOutcome", "RunOutcomeProjection",
    "RunScientificValidity", "RunTaskOutcome", "DerivedEvidenceArtifact",
    "EvidenceBundleManifest", "EvidenceBundleReceipt", "EvidenceBundleStatus",
    "EvidenceStreamDescriptor",
    "PROJECT_MANIFEST_SCHEMA", "ProgramSpec", "ProjectCapabilityRequirement",
    "ProjectConfigurationReference", "ProjectIdentity", "ProjectManifest",
    "ProjectManifestDecodeError", "ProjectManifestFacet",
    "ProjectManifestFacetChange", "ProjectManifestFacetDiff",
    "ProjectManifestIdentityFacets", "ProjectMethodRequirement",
    "ProjectProviderBinding", "ProjectRequirementCardinality", "ProjectSpec",
    "ProjectToolProvenance", "WorkspaceSpec",
    "decode_project_manifest_bytes", "decode_project_manifest_document",
    "diff_project_manifest_facets", "encode_project_manifest",
    "project_manifest_document", "project_manifest_identity_facets",
    "MethodIdentity", "MethodProgramIdentity", "MethodSnapshot",
    "MethodTaskCompletionReceipt", "MethodTaskOutcome", "RecallRequest",
    "RecallResult",
    "AgentProjectDefinition", "MethodProjectDefinition",
    "ParticipantBindingDiagnostic", "ParticipantBindingDiagnosticCode",
    "ParticipantBindingDiagnosticSeverity", "ParticipantProjectBindingError",
    "ParticipantProviderProfile", "ParticipantRequirement",
    "ParticipantRequirementContribution", "ProjectParticipantBinding",
    "ProjectParticipantProviderPort",
    "ModelBindingDiagnostic", "ModelBindingDiagnosticCode",
    "ModelBindingDiagnosticSeverity", "ModelCapabilityRequirement",
    "ModelProjectBindingError", "ModelProjectDefinition", "ModelProviderProfile",
    "ProjectModelBinding", "ProjectModelClientPort", "ProjectModelProviderPort",
    "ProjectModelRequest", "ProjectModelResponse",
    "ActionRequest", "ActionResult",
    "EnvironmentAssignmentIdentity",
    "EnvironmentAssignmentIsolationPort",
    "EnvironmentAssignmentIsolationReceipt",
    "EnvironmentCapability",
    "EnvironmentCapabilityUnsupported", "EnvironmentDiagnosticsPort",
    "EnvironmentIdentity", "EnvironmentImplementation",
    "EnvironmentProviderCapabilities", "EnvironmentProviderPort",
    "EnvironmentSession", "EnvironmentSessionDiagnostics",
    "EnvironmentSessionServices", "Observation",
]

from .discovery import (
    DownstreamApiModule,
    DownstreamCapabilityCatalog,
    DownstreamSystemSurface,
    load_downstream_capability_catalog,
)

__all__ += [
    "DownstreamApiModule",
    "DownstreamCapabilityCatalog",
    "DownstreamSystemSurface",
    "load_downstream_capability_catalog",
]

from .session import *  # noqa: F401,F403
from .session import __all__ as _session_contracts
from .server import *  # noqa: F401,F403
from .server import __all__ as _server_contracts
from .systems import SYSTEM_FACADES, SYSTEM_KEYS

__all__ += list(dict.fromkeys((
    *_session_contracts,
    *_server_contracts,
    "SYSTEM_FACADES",
    "SYSTEM_KEYS",
)))
