""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
Convenience facade: model
Sources are selected by canonical registry roots and declared compatibility planes; symbol lists are never hand-maintained.
"""
from __future__ import annotations

from noetrium.contracts.systems import model as _surface_0

_SOURCES = (('model', '_surface_0'),)
_CANONICAL_OWNERS = {}
_EXCLUDED = frozenset(('CONTRACT', 'contract'))
_owners: dict[str, str] = {}
_exports: list[str] = []

def _qualified(system_key: str, name: str) -> str:
    return system_key.replace('/', '__').replace('-', '_') + '__' + name

for _system_key, _module_name in _SOURCES:
    _module = globals()[_module_name]
    for _name in _module.__all__:
        if '__' in _name or _name in _EXCLUDED:
            continue
        _value = getattr(_module, _name)
        if _name not in _owners:
            globals()[_name] = _value
            _owners[_name] = _system_key
            _exports.append(_name)
            continue
        _owner = _owners[_name]
        _current = globals()[_name]
        if _current is _value:
            continue
        _owner_alias = _qualified(_owner, _name)
        _new_alias = _qualified(_system_key, _name)
        if _owner_alias not in globals():
            globals()[_owner_alias] = _current
            _exports.append(_owner_alias)
        globals()[_new_alias] = _value
        if _new_alias not in _exports:
            _exports.append(_new_alias)
        _canonical = _CANONICAL_OWNERS.get(_name)
        if _canonical is None:
            raise RuntimeError(
                f'convenience facade symbol collision requires canonical owner: {_name}: '
                f'{_owner} vs {_system_key}'
            )
        if _canonical == _system_key:
            globals()[_name] = _value
            _owners[_name] = _system_key
        elif _canonical != _owner:
            raise RuntimeError(
                f'invalid canonical owner for {_name}: {_canonical}; observed {_owner}, {_system_key}'
            )

__all__ = tuple(_exports)

del _exports, _owners
