""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
Convenience facade: research
Sources are selected by canonical registry roots and declared compatibility planes; symbol lists are never hand-maintained.
"""
from __future__ import annotations

from noetrium.contracts.systems import experimentation as _surface_0
from noetrium.contracts.systems import experimentation__branch as _surface_1
from noetrium.contracts.systems import experimentation__catalog as _surface_2
from noetrium.contracts.systems import experimentation__checkpoint as _surface_3
from noetrium.contracts.systems import experimentation__evaluation as _surface_4
from noetrium.contracts.systems import experimentation__experiment as _surface_5
from noetrium.contracts.systems import experimentation__run as _surface_6
from noetrium.contracts.systems import experimentation__run__control as _surface_7
from noetrium.contracts.systems import experimentation__run__identity as _surface_8
from noetrium.contracts.systems import experimentation__run__lifecycle as _surface_9
from noetrium.contracts.systems import experimentation__run__manifest as _surface_10
from noetrium.contracts.systems import experimentation__study as _surface_11
from noetrium.contracts.systems import experimentation__variant as _surface_12
from noetrium.contracts.systems import experimentation__workbench as _surface_13
from noetrium.contracts.systems import experimentation__workload as _surface_14
from noetrium_platform.research.experimentation.study import runtime as _extra_0
from noetrium_platform.research.experimentation.workbench import providers as _extra_1
from noetrium_platform.research.experimentation.workbench import runtime as _extra_2

_SOURCES = (('experimentation', '_surface_0'), ('experimentation/branch', '_surface_1'), ('experimentation/catalog', '_surface_2'), ('experimentation/checkpoint', '_surface_3'), ('experimentation/evaluation', '_surface_4'), ('experimentation/experiment', '_surface_5'), ('experimentation/run', '_surface_6'), ('experimentation/run/control', '_surface_7'), ('experimentation/run/identity', '_surface_8'), ('experimentation/run/lifecycle', '_surface_9'), ('experimentation/run/manifest', '_surface_10'), ('experimentation/study', '_surface_11'), ('experimentation/variant', '_surface_12'), ('experimentation/workbench', '_surface_13'), ('experimentation/workload', '_surface_14'), ('experimentation/study/runtime', '_extra_0'), ('experimentation/workbench/providers', '_extra_1'), ('experimentation/workbench/runtime', '_extra_2'))
_CANONICAL_OWNERS = {'ExperimentPlan': 'experimentation/study'}
_EXCLUDED = frozenset(('CONTRACT', 'contract'))
_owners: dict[str, str] = {}
_exports: list[str] = []

def _qualified(system_key: str, name: str) -> str:
    return system_key.replace('/', '__').replace('-', '_') + '__' + name

for _system_key, _module_name in _SOURCES:
    _module = globals()[_module_name]
    for _name in _module.__all__:
        if '__' in _name or _name in _EXCLUDED:
            continue
        _value = getattr(_module, _name)
        if _name not in _owners:
            globals()[_name] = _value
            _owners[_name] = _system_key
            _exports.append(_name)
            continue
        _owner = _owners[_name]
        _current = globals()[_name]
        if _current is _value:
            continue
        _owner_alias = _qualified(_owner, _name)
        _new_alias = _qualified(_system_key, _name)
        if _owner_alias not in globals():
            globals()[_owner_alias] = _current
            _exports.append(_owner_alias)
        globals()[_new_alias] = _value
        if _new_alias not in _exports:
            _exports.append(_new_alias)
        _canonical = _CANONICAL_OWNERS.get(_name)
        if _canonical is None:
            raise RuntimeError(
                f'convenience facade symbol collision requires canonical owner: {_name}: '
                f'{_owner} vs {_system_key}'
            )
        if _canonical == _system_key:
            globals()[_name] = _value
            _owners[_name] = _system_key
        elif _canonical != _owner:
            raise RuntimeError(
                f'invalid canonical owner for {_name}: {_canonical}; observed {_owner}, {_system_key}'
            )

__all__ = tuple(_exports)

del _exports, _owners
