"""Public parent-level Execution orchestration contracts."""

from .intent import ExecutionIntentPort, ExecutionIntentReceipt, ExecutionOperationIntent
from .program_execution import (
    ExecutableProgramIdentity,
    ExecutableProgramSourcePublicationPort,
    PublishedExecutableProgramSource,
    ProgramExecutionPort,
    ProgramExecutionRecoveryPort,
    ProgramExecutionReconciliationDisposition,
    ProgramExecutionReconciliationResult,
    ProgramExecutionReceipt,
    ProgramExecutionRequest,
    ProgramExecutionStatus,
)
from .status import DeploymentStatusIdentity

__all__ = [
    "DeploymentStatusIdentity",
    "ExecutionIntentPort",
    "ExecutionIntentReceipt",
    "ExecutionOperationIntent",
    "ExecutableProgramIdentity",
    "ExecutableProgramSourcePublicationPort",
    "PublishedExecutableProgramSource",
    "ProgramExecutionPort",
    "ProgramExecutionRecoveryPort",
    "ProgramExecutionReconciliationDisposition",
    "ProgramExecutionReconciliationResult",
    "ProgramExecutionReceipt",
    "ProgramExecutionRequest",
    "ProgramExecutionStatus",
]

# Parent-facing execution contracts. Higher layers import only this facade.
from noetrium_platform.research.execution.decision.cycle_identity import (
    DecisionCycleIdentity,
    DecisionCycleIdentityProvider,
)
from noetrium_platform.research.execution.decision.cycle_result import DecisionCycleResult
from noetrium_platform.capabilities.api import EpisodeSpec
from noetrium_platform.research.execution.machines.api import (
    EvaluationConcern,
    ExperimentConcern,
    ExperimentProgramBuilder,
    MachineEvent,
    ProgramHandlerRegistry,
    ProgramNodeRequest,
    ProgramNodeResult,
    ProgramRule,
    ProgramRuleSet,
    ResearchHostOperation,
    ResearchMachineRunPort,
    ResearchMachineSessionPort,
    ResearchProgram,
    ResearchProgramHost,
    RuleDispatchMode,
    RunConcern,
    RuntimeConcern,
    RuntimeProgramBuilder,
    UnhandledEventPolicy,
    build_rule_handlers,
    compile_rule_program,
)
from noetrium_platform.research.execution.machines.program import core_program_handlers
from noetrium_platform.research.execution.operation.api import (
    EffectReconciliationOutcome,
    EffectReconciliationVerdict,
)
from noetrium_platform.research.execution.policy.api import ExecutionPriority
from noetrium_platform.research.execution.workflow.api import (
    AgentMethodSpec,
    AgentPhaseSpec,
    MethodProgramBuilder,
    MethodWorkflow,
    AsyncOperationDispatchPort,
    EffectIntentOperationPort,
    MethodAgentLoopPort,
    MethodChildMachinePort,
    MethodMachinePort,
    MethodObservationPort,
    MethodProgram,
    MethodRunResult,
    MethodRunStatus,
    MethodRuntimeContext,
    plan_method_runtime_binding,
    MethodRuntimePortInventory,
    MethodRuntimePort,
    MethodSchemaPort,
    OperationDispatchPort,
    TrialCycleExecution,
    WorkflowSurfaceBindingContext,
    WorkflowSurfaceFactory,
    WorkflowSurfaceReuseScope,
    analyze_method_runtime_requirements,
    workflow_surface_id,
    workflow_surface_reuse_scope,
    ExecutionTrialProtocolKind,
    ExecutionTrialProtocolPort,
    require_execution_trial_protocol,
    MethodEvidenceFactoryPort,
    MethodRuntimeBinderPort,
)

_PARENT_FACADE_EXPORTS = (
    "MethodRuntimeBinderPort",
    "MethodEvidenceFactoryPort",
    "require_execution_trial_protocol",
    "ExecutionTrialProtocolPort",
    "ExecutionTrialProtocolKind",
    "AsyncOperationDispatchPort",
    "DecisionCycleIdentity",
    "DecisionCycleIdentityProvider",
    "DecisionCycleResult",
    "EffectIntentOperationPort",
    "EffectReconciliationOutcome",
    "EffectReconciliationVerdict",
    "EvaluationConcern",
    "ExecutionPriority",
    "ExperimentConcern",
    "ExperimentProgramBuilder",
    "MachineEvent",
    "MethodAgentLoopPort",
    "MethodChildMachinePort",
    "MethodMachinePort",
    "MethodObservationPort",
    "MethodProgram",
    "MethodRunResult",
    "MethodRunStatus",
    "MethodRuntimeContext",
    "MethodRuntimePort",
    "MethodRuntimePortInventory",
    "MethodSchemaPort",
    "OperationDispatchPort",
    "ProgramHandlerRegistry",
    "ProgramNodeRequest",
    "ProgramNodeResult",
    "ProgramRule",
    "ProgramRuleSet",
    "ResearchHostOperation",
    "ResearchMachineSessionPort",
    "ResearchMachineRunPort",
    "ResearchProgram",
    "ResearchProgramHost",
    "RuleDispatchMode",
    "RunConcern",
    "RuntimeConcern",
    "RuntimeProgramBuilder",
    "TrialCycleExecution",
    "UnhandledEventPolicy",
    "WorkflowSurfaceBindingContext",
    "WorkflowSurfaceFactory",
    "WorkflowSurfaceReuseScope",
    "analyze_method_runtime_requirements",
    "build_rule_handlers",
    "compile_rule_program",
    "core_program_handlers",
    "plan_method_runtime_binding",
    "workflow_surface_id",
    "workflow_surface_reuse_scope",
)

__all__ = tuple(__all__) + _PARENT_FACADE_EXPORTS

from .participants import (
    BoundParticipant,
    BoundParticipants,
    CapabilityDescriptor,
    CapabilityPort,
    CapabilityRequest,
    CapabilityResult,
    ParticipantCheckpoint,
    ParticipantCheckpointOperationsPort,
    ParticipantCheckpointRef,
    ParticipantImplementationIdentity,
    ParticipantResolutionPort,
    ParticipantRuntimeBinding,
    ParticipantSessionBinding,
    ParticipantSessionLifecyclePort,
    ParticipantSessionRuntimeIdentity,
    ProjectParticipantBinding,
    capability_request_digest,
)

_EXECUTION_PARTICIPANT_EXPORTS = (
    "BoundParticipant",
    "BoundParticipants",
    "CapabilityDescriptor",
    "CapabilityPort",
    "CapabilityRequest",
    "CapabilityResult",
    "ParticipantCheckpoint",
    "ParticipantCheckpointOperationsPort",
    "ParticipantCheckpointRef",
    "ParticipantImplementationIdentity",
    "ParticipantResolutionPort",
    "ParticipantRuntimeBinding",
    "ParticipantSessionBinding",
    "ParticipantSessionLifecyclePort",
    "ParticipantSessionRuntimeIdentity",
    "ProjectParticipantBinding",
    "capability_request_digest",
)

__all__ = tuple(__all__) + _EXECUTION_PARTICIPANT_EXPORTS

from .platform import (
    ArtifactContentIdentity,
    ArtifactReference,
    ArtifactReferencePort,
    ArtifactRegistryPort,
    BindingProof,
    CompositionSubject,
    ComputeLeaseGuardFactoryPort,
    ComputeLeaseGuardPort,
    ComputeRequirement,
    ComputeSchedulerPort,
    GpuSharingMode,
    ProjectCapabilityRequirement,
    ProjectConfigurationReference,
    ProjectManifest,
    ProjectMethodRequirement,
    ProjectModelBinding,
    ProjectModelBindingSet,
    ProjectProviderBinding,
    ProjectRequirementCardinality,
    QualifiedModelEndpointBinding,
    ResearchDimension,
    ResearchDimensionKind,
    ResearchQuerySourceError,
    ResearchResultKind,
    ResearchResultQuery,
    ResearchResultRecord,
    ResearchResultReference,
    ResearchSourceDisposition,
    ResearchSourceSnapshot,
    ScopeIdentity,
    ScopeKind,
    ScopeRegistryPort,
    is_absolute_target_path,
    source_cut,
)

_EXECUTION_PLATFORM_EXPORTS = ('ArtifactContentIdentity', 'ArtifactReference', 'ArtifactReferencePort', 'ArtifactRegistryPort', 'BindingProof', 'CompositionSubject', 'ComputeLeaseGuardFactoryPort', 'ComputeLeaseGuardPort', 'ComputeRequirement', 'ComputeSchedulerPort', 'GpuSharingMode', 'ProjectCapabilityRequirement', 'ProjectConfigurationReference', 'ProjectManifest', 'ProjectMethodRequirement', 'ProjectModelBinding', 'ProjectModelBindingSet', 'ProjectProviderBinding', 'ProjectRequirementCardinality', 'QualifiedModelEndpointBinding', 'ResearchDimension', 'ResearchDimensionKind', 'ResearchQuerySourceError', 'ResearchResultKind', 'ResearchResultQuery', 'ResearchResultRecord', 'ResearchResultReference', 'ResearchSourceDisposition', 'ResearchSourceSnapshot', 'ScopeIdentity', 'ScopeKind', 'ScopeRegistryPort', 'is_absolute_target_path', 'source_cut')
__all__ = tuple(__all__) + _EXECUTION_PLATFORM_EXPORTS

from noetrium_platform.capabilities.api import (
    ActionKind,
    ActionSpec,
    AgentGoal,
    EmbodiedActionCommand,
    EmbodimentKind,
    EmbodimentSpec,
    EnvironmentSpec,
    ExecutionEnvironmentKind,
    GuardDecision,
    GuardVerdict,
    SensorModality,
    SensorSpec,
)

_EXECUTION_AUTHORING_EXPORTS = (
    "ActionKind",
    "ActionSpec",
    "AgentGoal",
    "AgentMethodSpec",
    "AgentPhaseSpec",
    "EmbodiedActionCommand",
    "EmbodimentKind",
    "EmbodimentSpec",
    "EnvironmentSpec",
    "ExecutionEnvironmentKind",
    "GuardDecision",
    "GuardVerdict",
    "MethodProgramBuilder",
    "MethodWorkflow",
    "SensorModality",
    "SensorSpec",
)
__all__ += _EXECUTION_AUTHORING_EXPORTS
from noetrium_platform.capabilities.api import (
    EnvironmentCapability,
    EnvironmentProviderPort,
    MethodIdentity,
    MethodRuntimeIdentity,
)
from noetrium_platform.foundation.kernel.kernel import ExecutionContext, JsonValue

# Canonical static layer ABI.
__all__ = [
    'DeploymentStatusIdentity',
    'ExecutionIntentPort',
    'ExecutionIntentReceipt',
    'ExecutionOperationIntent',
    'ExecutableProgramIdentity',
    'ExecutableProgramSourcePublicationPort',
    'PublishedExecutableProgramSource',
    'ProgramExecutionPort',
    'ProgramExecutionRecoveryPort',
    'ProgramExecutionReconciliationDisposition',
    'ProgramExecutionReconciliationResult',
    'ProgramExecutionReceipt',
    'ProgramExecutionRequest',
    'ProgramExecutionStatus',
    'MethodRuntimeBinderPort',
    'MethodEvidenceFactoryPort',
    'require_execution_trial_protocol',
    'ExecutionTrialProtocolPort',
    'ExecutionTrialProtocolKind',
    'AsyncOperationDispatchPort',
    'DecisionCycleIdentity',
    'DecisionCycleIdentityProvider',
    'DecisionCycleResult',
    'EffectIntentOperationPort',
    'EffectReconciliationOutcome',
    'EffectReconciliationVerdict',
    'EvaluationConcern',
    'ExecutionPriority',
    'ExperimentConcern',
    'ExperimentProgramBuilder',
    'MachineEvent',
    'MethodAgentLoopPort',
    'MethodChildMachinePort',
    'MethodMachinePort',
    'MethodObservationPort',
    'MethodProgram',
    'MethodRunResult',
    'MethodRunStatus',
    'MethodRuntimeContext',
    'MethodRuntimePort',
    'MethodRuntimePortInventory',
    'MethodSchemaPort',
    'OperationDispatchPort',
    'ProgramHandlerRegistry',
    'ProgramNodeRequest',
    'ProgramNodeResult',
    'ProgramRule',
    'ProgramRuleSet',
    'ResearchHostOperation',
    'ResearchProgram',
    'ResearchProgramHost',
    'RuleDispatchMode',
    'RunConcern',
    'RuntimeConcern',
    'RuntimeProgramBuilder',
    'TrialCycleExecution',
    'UnhandledEventPolicy',
    'WorkflowSurfaceBindingContext',
    'WorkflowSurfaceFactory',
    'WorkflowSurfaceReuseScope',
    'analyze_method_runtime_requirements',
    'build_rule_handlers',
    'compile_rule_program',
    'core_program_handlers',
    'plan_method_runtime_binding',
    'workflow_surface_id',
    'workflow_surface_reuse_scope',
    'BoundParticipant',
    'BoundParticipants',
    'CapabilityDescriptor',
    'CapabilityPort',
    'CapabilityRequest',
    'CapabilityResult',
    'ParticipantCheckpoint',
    'ParticipantCheckpointOperationsPort',
    'ParticipantCheckpointRef',
    'ParticipantImplementationIdentity',
    'ParticipantResolutionPort',
    'ParticipantRuntimeBinding',
    'ParticipantSessionBinding',
    'ParticipantSessionLifecyclePort',
    'ParticipantSessionRuntimeIdentity',
    'ProjectParticipantBinding',
    'capability_request_digest',
    'ArtifactContentIdentity',
    'ArtifactReference',
    'ArtifactReferencePort',
    'ArtifactRegistryPort',
    'BindingProof',
    'CompositionSubject',
    'ComputeLeaseGuardFactoryPort',
    'ComputeLeaseGuardPort',
    'ComputeRequirement',
    'ComputeSchedulerPort',
    'GpuSharingMode',
    'ProjectCapabilityRequirement',
    'ProjectConfigurationReference',
    'ProjectManifest',
    'ProjectMethodRequirement',
    'ProjectModelBinding',
    'ProjectModelBindingSet',
    'ProjectProviderBinding',
    'ProjectRequirementCardinality',
    'QualifiedModelEndpointBinding',
    'ResearchDimension',
    'ResearchDimensionKind',
    'ResearchQuerySourceError',
    'ResearchResultKind',
    'ResearchResultQuery',
    'ResearchResultRecord',
    'ResearchResultReference',
    'ResearchSourceDisposition',
    'ResearchSourceSnapshot',
    'ScopeIdentity',
    'ScopeKind',
    'ScopeRegistryPort',
    'is_absolute_target_path',
    'source_cut',
    'ActionKind',
    'ActionSpec',
    'AgentGoal',
    'AgentMethodSpec',
    'AgentPhaseSpec',
    'EmbodiedActionCommand',
    'EmbodimentKind',
    'EmbodimentSpec',
    'EnvironmentSpec',
    'ExecutionEnvironmentKind',
    'GuardDecision',
    'GuardVerdict',
    'MethodProgramBuilder',
    'MethodWorkflow',
    'SensorModality',
    'SensorSpec',
    'EnvironmentCapability',
    'EnvironmentProviderPort',
    'ExecutionContext',
    'JsonValue',
    'MethodIdentity',
    'MethodRuntimeIdentity',
]

from noetrium_platform.capabilities.api import (
    ActionRequest,
    ActionResult,
    CapabilitySelectionReference,
    CapabilitySelectionView,
    EmbodiedCaptureReceipt,
    EmbodiedEvent,
    EmbodiedEventKind,
    EnvironmentSession,
    MethodProgramIdentity,
    materialize_capability_selection_view,
)
from noetrium_platform.research.execution.machines.api import (
    ChildFailurePolicy,
    ChildResearchMachineBatchItem,
    ChildResearchMachineBatchPort,
    ChildResearchMachineBatchRequest,
    ChildResearchMachineExecution,
    ChildResearchMachineRequest,
    DomainProgramBuilder,
    EnvironmentConcern,
    EnvironmentProgramBuilder,
    EvaluationProgramBuilder,
    MemoryConcern,
    MemoryProgramBuilder,
    OptimizationConcern,
    OptimizationProgramBuilder,
    ParticipantConcern,
    ParticipantProgramBuilder,
    ProgramNode,
    ResearchProgram as MachineResearchProgram,
    ResearchProgramBuilder as MachineResearchProgramBuilder,
    ResearchRunProgramBuilder,
    RuntimeModule,
    RuntimeModuleBuilder,
)
from noetrium_platform.research.execution.workflow.api import (
    MethodAgentRequest,
    MethodAgentResult,
    MethodEvent,
    MethodExecutionClass,
    MethodNodeKind,
    MethodNodeRequest,
    MethodNodeResult,
    MethodNodeSpec,
    environment_action_capability_payload,
    environment_branch_action_spec,
    environment_fork_action_payload,
    environment_query_capability_payload,
    environment_replay_action_payload,
    environment_reset_capability_payload,
)

_EXECUTION_PRODUCT_AUTHORING_EXPORTS = (
    "ActionRequest",
    "ActionResult",
    "CapabilitySelectionReference",
    "CapabilitySelectionView",
    "ChildFailurePolicy",
    "ChildResearchMachineBatchItem",
    "ChildResearchMachineBatchPort",
    "ChildResearchMachineBatchRequest",
    "ChildResearchMachineExecution",
    "ChildResearchMachineRequest",
    "DomainProgramBuilder",
    "EmbodiedCaptureReceipt",
    "EmbodiedEvent",
    "EmbodiedEventKind",
    "EnvironmentConcern",
    "EnvironmentProgramBuilder",
    "EnvironmentSession",
    "EpisodeSpec",
    "EvaluationProgramBuilder",
    "MachineResearchProgram",
    "MachineResearchProgramBuilder",
    "MemoryConcern",
    "MemoryProgramBuilder",
    "MethodAgentRequest",
    "MethodAgentResult",
    "MethodEvent",
    "MethodExecutionClass",
    "MethodNodeKind",
    "MethodNodeRequest",
    "MethodNodeResult",
    "MethodNodeSpec",
    "MethodProgramIdentity",
    "OptimizationConcern",
    "OptimizationProgramBuilder",
    "ParticipantConcern",
    "ParticipantProgramBuilder",
    "ProgramNode",
    "ResearchRunProgramBuilder",
    "RuntimeModule",
    "RuntimeModuleBuilder",
    "environment_action_capability_payload",
    "environment_branch_action_spec",
    "environment_fork_action_payload",
    "environment_query_capability_payload",
    "environment_replay_action_payload",
    "environment_reset_capability_payload",
    "materialize_capability_selection_view",
)
__all__ = tuple(__all__) + _EXECUTION_PRODUCT_AUTHORING_EXPORTS

from .program_execution_authoring import program_execution_capability_payload
__all__ = tuple(__all__) + ("program_execution_capability_payload",)

from noetrium_platform.research.execution.graph.api import (
    ResearchGraphExecutionReport,
    ResearchGraphNode,
    ResearchGraphNodeExecutorPort,
    ResearchGraphNodeResult,
    ResearchGraphNodeState,
    ResearchGraphPlan,
)

__all__ = tuple(__all__) + (
    "ResearchGraphExecutionReport",
    "ResearchGraphNode",
    "ResearchGraphNodeExecutorPort",
    "ResearchGraphNodeResult",
    "ResearchGraphNodeState",
    "ResearchGraphPlan",
)

from .lineage import (
    ExecutionForkReceipt,
    ExecutionSourceCut,
    ExecutionStateAnchor,
    bind_execution_fork,
)
__all__ = tuple(__all__) + (
    "ExecutionForkReceipt",
    "ExecutionSourceCut",
    "ExecutionStateAnchor",
    "bind_execution_fork",
)
from noetrium_platform.capabilities.api import (
    EnvironmentForkReceipt,
    EnvironmentReplayError,
    EnvironmentReplayReceipt,
    EnvironmentSessionOpener,
    TensorContentRef,
    TensorContentStorePort,
    fork_environment_session,
    replay_environment_prefix,
)
__all__ = tuple(__all__) + (
    "EnvironmentForkReceipt",
    "EnvironmentReplayError",
    "EnvironmentReplayReceipt",
    "EnvironmentSessionOpener",
    "TensorContentRef",
    "TensorContentStorePort",
    "fork_environment_session",
    "replay_environment_prefix",
)
