"""Public parent-level Execution orchestration contracts."""

from .intent import ExecutionIntentPort, ExecutionIntentReceipt, ExecutionOperationIntent
from .program_execution import (
    ExecutableProgramIdentity,
    ExecutableProgramSourcePublicationPort,
    PublishedExecutableProgramSource,
    ProgramExecutionPort,
    ProgramExecutionRecoveryPort,
    ProgramExecutionReconciliationDisposition,
    ProgramExecutionReconciliationResult,
    ProgramExecutionReceipt,
    ProgramExecutionRequest,
    ProgramExecutionStatus,
)
from .status import DeploymentStatusIdentity

__all__ = [
    "DeploymentStatusIdentity",
    "ExecutionIntentPort",
    "ExecutionIntentReceipt",
    "ExecutionOperationIntent",
    "ExecutableProgramIdentity",
    "ExecutableProgramSourcePublicationPort",
    "PublishedExecutableProgramSource",
    "ProgramExecutionPort",
    "ProgramExecutionRecoveryPort",
    "ProgramExecutionReconciliationDisposition",
    "ProgramExecutionReconciliationResult",
    "ProgramExecutionReceipt",
    "ProgramExecutionRequest",
    "ProgramExecutionStatus",
]

# Parent-facing execution contracts. Higher layers import only this facade.
from noetrium_platform.research.execution.decision.cycle_identity import (
    DecisionCycleIdentity,
    DecisionCycleIdentityProvider,
)
from noetrium_platform.research.execution.decision.cycle_result import DecisionCycleResult
from noetrium_platform.research.execution.machines import (
    EvaluationConcern,
    ExperimentConcern,
    ExperimentProgramBuilder,
    MachineEvent,
    ProgramHandlerRegistry,
    ProgramNodeRequest,
    ProgramNodeResult,
    ProgramRule,
    ProgramRuleSet,
    ResearchHostOperation,
    ResearchMachineSession,
    ResearchProgram,
    ResearchProgramHost,
    RuleDispatchMode,
    RunConcern,
    RuntimeConcern,
    RuntimeProgramBuilder,
    UnhandledEventPolicy,
    build_rule_handlers,
    compile_rule_program,
    core_program_handlers,
)
from noetrium_platform.research.execution.operation.api import (
    EffectReconciliationOutcome,
    EffectReconciliationVerdict,
)
from noetrium_platform.research.execution.policy.api import ExecutionPriority
from noetrium_platform.research.execution.workflow.api import (
    AsyncOperationDispatchPort,
    EffectIntentOperationPort,
    MethodAgentLoopPort,
    MethodChildMachinePort,
    MethodMachinePort,
    MethodObservationPort,
    MethodProgram,
    MethodRunResult,
    MethodRunStatus,
    MethodRuntimeContext,
    plan_method_runtime_binding,
    MethodRuntimePortInventory,
    MethodRuntimePort,
    MethodSchemaPort,
    OperationDispatchPort,
    TrialCycleExecution,
    WorkflowSurfaceBindingContext,
    WorkflowSurfaceFactory,
    WorkflowSurfaceReuseScope,
    analyze_method_runtime_requirements,
    workflow_surface_id,
    workflow_surface_reuse_scope,
    ExecutionTrialProtocolKind,
    ExecutionTrialProtocolPort,
    require_execution_trial_protocol,
    MethodEvidenceFactoryPort,
    MethodRuntimeBinderPort,
)

_PARENT_FACADE_EXPORTS = (
    "MethodRuntimeBinderPort",
    "MethodEvidenceFactoryPort",
    "require_execution_trial_protocol",
    "ExecutionTrialProtocolPort",
    "ExecutionTrialProtocolKind",
    "AsyncOperationDispatchPort",
    "DecisionCycleIdentity",
    "DecisionCycleIdentityProvider",
    "DecisionCycleResult",
    "EffectIntentOperationPort",
    "EffectReconciliationOutcome",
    "EffectReconciliationVerdict",
    "EvaluationConcern",
    "ExecutionPriority",
    "ExperimentConcern",
    "ExperimentProgramBuilder",
    "MachineEvent",
    "MethodAgentLoopPort",
    "MethodChildMachinePort",
    "MethodMachinePort",
    "MethodObservationPort",
    "MethodProgram",
    "MethodRunResult",
    "MethodRunStatus",
    "MethodRuntimeContext",
    "MethodRuntimePort",
    "MethodRuntimePortInventory",
    "MethodSchemaPort",
    "OperationDispatchPort",
    "ProgramHandlerRegistry",
    "ProgramNodeRequest",
    "ProgramNodeResult",
    "ProgramRule",
    "ProgramRuleSet",
    "ResearchHostOperation",
    "ResearchMachineSession",
    "ResearchProgram",
    "ResearchProgramHost",
    "RuleDispatchMode",
    "RunConcern",
    "RuntimeConcern",
    "RuntimeProgramBuilder",
    "TrialCycleExecution",
    "UnhandledEventPolicy",
    "WorkflowSurfaceBindingContext",
    "WorkflowSurfaceFactory",
    "WorkflowSurfaceReuseScope",
    "analyze_method_runtime_requirements",
    "build_rule_handlers",
    "compile_rule_program",
    "core_program_handlers",
    "plan_method_runtime_binding",
    "workflow_surface_id",
    "workflow_surface_reuse_scope",
)

__all__ = tuple(__all__) + _PARENT_FACADE_EXPORTS

from .participants import (
    BoundParticipant,
    BoundParticipants,
    CapabilityDescriptor,
    CapabilityPort,
    CapabilityRequest,
    CapabilityResult,
    ParticipantCheckpoint,
    ParticipantCheckpointOperationsPort,
    ParticipantCheckpointRef,
    ParticipantImplementationIdentity,
    ParticipantResolutionPort,
    ParticipantRuntimeBinding,
    ParticipantSessionBinding,
    ParticipantSessionLifecyclePort,
    ParticipantSessionRuntimeIdentity,
    ProjectParticipantBinding,
    capability_request_digest,
)

_EXECUTION_PARTICIPANT_EXPORTS = (
    "BoundParticipant",
    "BoundParticipants",
    "CapabilityDescriptor",
    "CapabilityPort",
    "CapabilityRequest",
    "CapabilityResult",
    "ParticipantCheckpoint",
    "ParticipantCheckpointOperationsPort",
    "ParticipantCheckpointRef",
    "ParticipantImplementationIdentity",
    "ParticipantResolutionPort",
    "ParticipantRuntimeBinding",
    "ParticipantSessionBinding",
    "ParticipantSessionLifecyclePort",
    "ParticipantSessionRuntimeIdentity",
    "ProjectParticipantBinding",
    "capability_request_digest",
)

__all__ = tuple(__all__) + _EXECUTION_PARTICIPANT_EXPORTS

from .platform import (
    ArtifactContentIdentity,
    ArtifactReference,
    ArtifactReferencePort,
    ArtifactRegistryPort,
    BindingProof,
    CompositionSubject,
    ComputeLeaseGuardFactoryPort,
    ComputeLeaseGuardPort,
    ComputeRequirement,
    ComputeSchedulerPort,
    GpuSharingMode,
    ProjectCapabilityRequirement,
    ProjectConfigurationReference,
    ProjectManifest,
    ProjectMethodRequirement,
    ProjectModelBinding,
    ProjectModelBindingSet,
    ProjectProviderBinding,
    ProjectRequirementCardinality,
    QualifiedModelEndpointBinding,
    ResearchDimension,
    ResearchDimensionKind,
    ResearchQuerySourceError,
    ResearchResultKind,
    ResearchResultQuery,
    ResearchResultRecord,
    ResearchResultReference,
    ResearchSourceDisposition,
    ResearchSourceSnapshot,
    ScopeIdentity,
    ScopeKind,
    ScopeRegistryPort,
    is_absolute_target_path,
    source_cut,
)

_EXECUTION_PLATFORM_EXPORTS = ('ArtifactContentIdentity', 'ArtifactReference', 'ArtifactReferencePort', 'ArtifactRegistryPort', 'BindingProof', 'CompositionSubject', 'ComputeLeaseGuardFactoryPort', 'ComputeLeaseGuardPort', 'ComputeRequirement', 'ComputeSchedulerPort', 'GpuSharingMode', 'ProjectCapabilityRequirement', 'ProjectConfigurationReference', 'ProjectManifest', 'ProjectMethodRequirement', 'ProjectModelBinding', 'ProjectModelBindingSet', 'ProjectProviderBinding', 'ProjectRequirementCardinality', 'QualifiedModelEndpointBinding', 'ResearchDimension', 'ResearchDimensionKind', 'ResearchQuerySourceError', 'ResearchResultKind', 'ResearchResultQuery', 'ResearchResultRecord', 'ResearchResultReference', 'ResearchSourceDisposition', 'ResearchSourceSnapshot', 'ScopeIdentity', 'ScopeKind', 'ScopeRegistryPort', 'is_absolute_target_path', 'source_cut')
__all__ = tuple(__all__) + _EXECUTION_PLATFORM_EXPORTS

from noetrium_platform.research.execution.workflow.api import (
    AgentMethodSpec,
    AgentPhaseSpec,
    MethodProgramBuilder,
    MethodWorkflow,
)
from noetrium_platform.capabilities.api import (
    ActionKind,
    ActionSpec,
    AgentGoal,
    EmbodiedActionCommand,
    EmbodimentKind,
    EmbodimentSpec,
    EnvironmentSpec,
    ExecutionEnvironmentKind,
    GuardDecision,
    GuardVerdict,
    SensorModality,
    SensorSpec,
)

_EXECUTION_AUTHORING_EXPORTS = (
    "ActionKind",
    "ActionSpec",
    "AgentGoal",
    "AgentMethodSpec",
    "AgentPhaseSpec",
    "EmbodiedActionCommand",
    "EmbodimentKind",
    "EmbodimentSpec",
    "EnvironmentSpec",
    "ExecutionEnvironmentKind",
    "GuardDecision",
    "GuardVerdict",
    "MethodProgramBuilder",
    "MethodWorkflow",
    "SensorModality",
    "SensorSpec",
)
__all__ += _EXECUTION_AUTHORING_EXPORTS
# Canonical static layer ABI.
__all__ = ['DeploymentStatusIdentity', 'ExecutionIntentPort', 'ExecutionIntentReceipt', 'ExecutionOperationIntent', 'ExecutableProgramIdentity', 'ExecutableProgramSourcePublicationPort', 'PublishedExecutableProgramSource', 'ProgramExecutionPort', 'ProgramExecutionRecoveryPort', 'ProgramExecutionReconciliationDisposition', 'ProgramExecutionReconciliationResult', 'ProgramExecutionReceipt', 'ProgramExecutionRequest', 'ProgramExecutionStatus', 'MethodRuntimeBinderPort', 'MethodEvidenceFactoryPort', 'require_execution_trial_protocol', 'ExecutionTrialProtocolPort', 'ExecutionTrialProtocolKind', 'AsyncOperationDispatchPort', 'DecisionCycleIdentity', 'DecisionCycleIdentityProvider', 'DecisionCycleResult', 'EffectIntentOperationPort', 'EffectReconciliationOutcome', 'EffectReconciliationVerdict', 'EvaluationConcern', 'ExecutionPriority', 'ExperimentConcern', 'ExperimentProgramBuilder', 'MachineEvent', 'MethodAgentLoopPort', 'MethodChildMachinePort', 'MethodMachinePort', 'MethodObservationPort', 'MethodProgram', 'MethodRunResult', 'MethodRunStatus', 'MethodRuntimeContext', 'MethodRuntimePort', 'MethodRuntimePortInventory', 'MethodSchemaPort', 'OperationDispatchPort', 'ProgramHandlerRegistry', 'ProgramNodeRequest', 'ProgramNodeResult', 'ProgramRule', 'ProgramRuleSet', 'ResearchHostOperation', 'ResearchMachineSession', 'ResearchProgram', 'ResearchProgramHost', 'RuleDispatchMode', 'RunConcern', 'RuntimeConcern', 'RuntimeProgramBuilder', 'TrialCycleExecution', 'UnhandledEventPolicy', 'WorkflowSurfaceBindingContext', 'WorkflowSurfaceFactory', 'WorkflowSurfaceReuseScope', 'analyze_method_runtime_requirements', 'build_rule_handlers', 'compile_rule_program', 'core_program_handlers', 'plan_method_runtime_binding', 'workflow_surface_id', 'workflow_surface_reuse_scope', 'BoundParticipant', 'BoundParticipants', 'CapabilityDescriptor', 'CapabilityPort', 'CapabilityRequest', 'CapabilityResult', 'ParticipantCheckpoint', 'ParticipantCheckpointOperationsPort', 'ParticipantCheckpointRef', 'ParticipantImplementationIdentity', 'ParticipantResolutionPort', 'ParticipantRuntimeBinding', 'ParticipantSessionBinding', 'ParticipantSessionLifecyclePort', 'ParticipantSessionRuntimeIdentity', 'ProjectParticipantBinding', 'capability_request_digest', 'ArtifactContentIdentity', 'ArtifactReference', 'ArtifactReferencePort', 'ArtifactRegistryPort', 'BindingProof', 'CompositionSubject', 'ComputeLeaseGuardFactoryPort', 'ComputeLeaseGuardPort', 'ComputeRequirement', 'ComputeSchedulerPort', 'GpuSharingMode', 'ProjectCapabilityRequirement', 'ProjectConfigurationReference', 'ProjectManifest', 'ProjectMethodRequirement', 'ProjectModelBinding', 'ProjectModelBindingSet', 'ProjectProviderBinding', 'ProjectRequirementCardinality', 'QualifiedModelEndpointBinding', 'ResearchDimension', 'ResearchDimensionKind', 'ResearchQuerySourceError', 'ResearchResultKind', 'ResearchResultQuery', 'ResearchResultRecord', 'ResearchResultReference', 'ResearchSourceDisposition', 'ResearchSourceSnapshot', 'ScopeIdentity', 'ScopeKind', 'ScopeRegistryPort', 'is_absolute_target_path', 'source_cut', 'ActionKind', 'ActionSpec', 'AgentGoal', 'AgentMethodSpec', 'AgentPhaseSpec', 'EmbodiedActionCommand', 'EmbodimentKind', 'EmbodimentSpec', 'EnvironmentSpec', 'ExecutionEnvironmentKind', 'GuardDecision', 'GuardVerdict', 'MethodProgramBuilder', 'MethodWorkflow', 'SensorModality', 'SensorSpec']
