"""Platform contracts that Execution deliberately exposes to Experimentation.

Every symbol comes only from the direct lower Capability layer facade.  This
module is the recursive boundary that prevents Experimentation from knowing
Foundation/Substrate/Capability member topology.
"""

from noetrium_platform.capabilities.api import (
    ArtifactContentIdentity,
    ArtifactReference,
    ArtifactReferencePort,
    ArtifactRegistryPort,
    BindingProof,
    CompositionSubject,
    ComputeLeaseGuardFactoryPort,
    ComputeLeaseGuardPort,
    ComputeRequirement,
    ComputeSchedulerPort,
    GpuSharingMode,
    ProjectCapabilityRequirement,
    ProjectConfigurationReference,
    ProjectManifest,
    ProjectMethodRequirement,
    ProjectModelBinding,
    ProjectModelBindingSet,
    ProjectProviderBinding,
    ProjectRequirementCardinality,
    QualifiedModelEndpointBinding,
    ResearchDimension,
    ResearchDimensionKind,
    ResearchQuerySourceError,
    ResearchResultKind,
    ResearchResultQuery,
    ResearchResultRecord,
    ResearchResultReference,
    ResearchSourceDisposition,
    ResearchSourceSnapshot,
    ScopeIdentity,
    ScopeKind,
    ScopeRegistryPort,
    is_absolute_target_path,
    source_cut,
)

__all__ = [
    "ArtifactContentIdentity",
    "ArtifactReference",
    "ArtifactReferencePort",
    "ArtifactRegistryPort",
    "BindingProof",
    "CompositionSubject",
    "ComputeLeaseGuardFactoryPort",
    "ComputeLeaseGuardPort",
    "ComputeRequirement",
    "ComputeSchedulerPort",
    "GpuSharingMode",
    "ProjectCapabilityRequirement",
    "ProjectConfigurationReference",
    "ProjectManifest",
    "ProjectMethodRequirement",
    "ProjectModelBinding",
    "ProjectModelBindingSet",
    "ProjectProviderBinding",
    "ProjectRequirementCardinality",
    "QualifiedModelEndpointBinding",
    "ResearchDimension",
    "ResearchDimensionKind",
    "ResearchQuerySourceError",
    "ResearchResultKind",
    "ResearchResultQuery",
    "ResearchResultRecord",
    "ResearchResultReference",
    "ResearchSourceDisposition",
    "ResearchSourceSnapshot",
    "ScopeIdentity",
    "ScopeKind",
    "ScopeRegistryPort",
    "is_absolute_target_path",
    "source_cut",
]
