"""Frontier 2026 wave 08: paper-faithful executable authoring specifications.

Paper-private semantics stay here. Platform kernel remains generic.
"""
from __future__ import annotations
from dataclasses import dataclass
from noetrium_platform.research.execution.workflow.api import AgentMethodSpec, AgentPhaseSpec
from research.authoring.frontier_2026.study import PaperStudySpec

@dataclass(frozen=True)
class Reproduction:
    method_id:str; title:str; venue:str; paper_uri:str; benchmarks:tuple[str,...]; protocol:tuple[str,...]; metrics:tuple[str,...]; baselines:tuple[str,...]; ablations:tuple[str,...]; phases:tuple[tuple[str,str,str],...]
    def program(self):
        return AgentMethodSpec(method_id=self.method_id,implementation_version="2026-paper-protocol",schema_version=self.method_id+".phase-workflow.v1",phases=tuple(AgentPhaseSpec(*p) for p in self.phases),max_cycles=12,configuration={"paper_uri":self.paper_uri,"venue":self.venue,"benchmark_ids":self.benchmarks,"protocol":self.protocol,"baselines":self.baselines,"ablations":self.ablations},evidence_obligations=(self.method_id+".phase-transcript",self.method_id+".model-tool-receipts",self.method_id+".metric-artifacts",self.method_id+".result-table"),metric_names=self.metrics,artifact_kinds=(self.method_id+"_trajectory",self.method_id+"_experiment_manifest")).compile()
    def study(self):
        return PaperStudySpec(method_id=self.method_id,title=self.title,venue=self.venue,paper_uri=self.paper_uri,benchmark_ids=self.benchmarks,protocol=self.protocol,metrics=self.metrics,ablations=self.ablations)

def R(i,t,v,u,b,p,m,base,a,ph): return Reproduction(i,t,v,u,b,p,m,base,a,ph)
COMMON=("freeze benchmark/model/environment cuts and seeds","run paper method and matched baselines under identical budgets","persist per-episode Machine Journal receipts and aggregate result table","separate paper-reported reference results from Noetrium-measured results")
REPRODUCTIONS=(
R("mempo_findings_acl2026","MemPO: Self-Memory Policy Optimization for Long-Horizon Agents","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.1166/",("long-horizon-agent-suite",),COMMON+("train memory-effectiveness credit assignment and compare token/performance frontier",),("task_success","token_count","memory_effectiveness","return","context_length"),("full context","external retrieval memory","unoptimized summarization"),("no memory credit assignment","fixed summarization","no self-memory"),(("observe","mempo.observe","Consume task state and bounded context."),("summarize","mempo.memory","Policy chooses what to retain in self-memory."),("act","mempo.policy","Act using compact self-managed memory."),("score_memory","mempo.credit","Assign credit from downstream utility to memory decisions."),("optimize","mempo.rl","Optimize policy with memory-effectiveness credit."))),
R("webanchor_findings_acl2026","WebAnchor: Anchoring Agent Planning to Stabilize Long-Horizon Web Reasoning","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.2058/",("browsecomp","browsecomp-zh","gaia","xbench-deepsearch"),COMMON+("stage 1 optimizes first-step plan with calibrated rubrics; stage 2 aligns execution to anchor",),("pass_at_1","tool_calls","plan_score","execution_alignment","tokens"),("GRPO","First-step GRPO","base web agent"),("no anchor reward","no stage-2 alignment","uniform trajectory reward"),(("plan","webanchor.anchor","Produce first-step plan anchor."),("score_plan","webanchor.rubric","Score anchor using self-play/human-calibrated rubric."),("execute","webanchor.tools","Execute web tools conditioned on anchor."),("align","webanchor.reward","Reward execution consistency and task outcome."),("optimize","webanchor.grpo","Two-stage Anchor-GRPO update."))),
R("rig_iclr2026","RIG: Synergizing Reasoning and Imagination in End-to-End Generalist Policy","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/226af6fc5bda3a5d27b1b9686a2fa386-Abstract-Conference.html",("generalist-embodied-control",),COMMON+("evaluate reasoning+next-image imagination jointly and test-time scaling separately",),("task_success","sample_efficiency","robustness","generalization","self_correction_rate"),("reasoning-only policy","imagination-only policy","specialist agent system"),("no imagination","no reasoning","no self-correction"),(("reason","rig.reason","Reason about next action."),("propose","rig.action","Propose candidate action."),("imagine","rig.world_model","Predict visual outcome of candidate action."),("review","rig.review","Review imagined consequence and self-correct."),("act","rig.policy","Execute accepted action."))),
R("bibo_iclr2026","Endowing GPT-4 with a Humanoid Body: Building the Bridge Between Off-the-Shelf VLMs and the Physical World","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/d8af9a23bf25dedfb32433597c462045-Abstract-Conference.html",("humanoid-open-environment",),COMMON+("measure compiler and diffusion executor separately before end-to-end interaction",),("interaction_success","motion_precision","control_latency","collision_rate","completion_time"),("text-only motion control","compiler without VQA chain","prior motion executor"),("no visual QA chain","no physical feedback","no diffusion executor"),(("perceive","bibo.vlm","Observe scene and instruction."),("compile","bibo.compiler","Chain VQA into motion captions and spatial controls."),("generate_motion","bibo.diffusion","Extend future joints conditioned on controls."),("feedback","bibo.physics","Read real-time physical feedback."),("execute","bibo.executor","Execute and replan motion."))),
R("assomem_iclr2026","AssoMem: Scalable Memory QA with Multi-Signal Associative Retrieval","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/a921f335253add9996d5175ad30896ec-Abstract-Conference.html",("locomo","longmemeval","meetingqa"),COMMON+("rebuild associative clue graph and evaluate dense similarity regimes",),("qa_accuracy","recall_at_k","mrr","retrieval_latency","memory_tokens"),("semantic vector retrieval","temporal retrieval","graph retrieval"),("no clue graph","relevance only","no MI fusion"),(("extract_clues","assomem.clues","Extract associative clues from utterances."),("link","assomem.graph","Anchor utterances to clue graph."),("retrieve","assomem.retrieve","Retrieve by relevance importance and temporal alignment."),("fuse","assomem.mi","Adaptively fuse signals with mutual information."),("answer","assomem.qa","Answer from ranked evidence."))),
R("steem_acl2026","Controllable Memory Usage: Balancing Anchoring and Innovation in Long-Term Human-Agent Interaction","ACL 2026","https://aclanthology.org/2026.acl-long.670/",("long-term-human-agent-interaction",),COMMON+("sweep requested memory-dependence from fresh-start to high-fidelity modes",),("task_quality","memory_dependence","novelty","consistency","preference_accuracy"),("all-memory prompting","memory masking","retrieval augmented agent"),("fixed dependence","no dependence estimator","all memory"),(("measure","steem.metric","Estimate behavioral memory dependence."),("set_control","steem.control","Read requested reliance level."),("retrieve","steem.memory","Select memories consistent with reliance target."),("respond","steem.agent","Generate response balancing anchoring and innovation."),("audit","steem.audit","Measure achieved dependence and quality."))),
R("mem2actbench_acl2026","Mem2ActBench: Evaluating Long-Term Memory Utilization in Task-Oriented Autonomous Agents","ACL 2026","https://aclanthology.org/2026.acl-long.370/",("mem2actbench",),COMMON+("reproduce 400 tool-use tasks and memory-dependent parameter grounding evaluation",),("task_success","tool_selection_accuracy","parameter_grounding_accuracy","memory_use_rate","latency"),("seven paper memory frameworks","full context","no memory"),("remove persistent records","explicit preference only","oracle memory"),(("load_history","mem2act.history","Load interrupted persistent session."),("infer_memory","mem2act.memory","Recover implicit preference/task state."),("select_tool","mem2act.tool","Choose appropriate tool."),("ground","mem2act.ground","Ground parameters from memory chain."),("score","mem2act.eval","Score action and memory utilization."))),
R("mle_memory_findings_acl2026","Demystify the Role of Memory in Machine Learning Engineering Agents","Findings ACL 2026","https://aclanthology.org/2026.findings-acl.525/",("mle-agent-challenges",),COMMON+("compare sequential chain and parallel tree agents with identical dynamic coding memory",),("task_score","best_iteration_score","debug_reuse_rate","tokens","experiments"),("chain agent no memory","tree agent no memory","raw history"),("no coding memory","no error reuse","chain versus tree"),(("experiment","mlemem.runner","Run candidate ML solution."),("diagnose","mlemem.debug","Extract failure/debugging experience."),("store","mlemem.memory","Update dynamic coding memory."),("retrieve","mlemem.retrieve","Retrieve prior debugging experience."),("improve","mlemem.search","Refine sequentially or branch in parallel."))),
R("context_compression_acl2026","Beyond the Context Window: Scaling Agentic RL via End-to-end Optimized Context Compression","ACL 2026","https://aclanthology.org/2026.acl-long.966/",("long-horizon-tool-use",),COMMON+("jointly optimize tool policy and periodic summarization under matched context budgets",),("task_success","return","context_tokens","rollout_cost","instruction_following"),("uncompressed RL","heuristic summarization","truncation"),("fixed summarizer","no summary policy gradient","hard truncation"),(("act","ctxrl.tool","Execute tool action."),("monitor","ctxrl.context","Track context budget."),("compress","ctxrl.summary","Generate task-relevant history summary."),("continue","ctxrl.policy","Continue beyond native context window."),("optimize","ctxrl.pg","Joint policy-gradient update for action and summarization."))),
R("newt_iclr2026","Learning Massively Multitask World Models for Continuous Control","ICLR 2026","https://proceedings.iclr.cc/paper_files/paper/2026/hash/092359ce5cf60a80e882378944bf1be4-Abstract-Conference.html",("newt-200-task-control",),COMMON+("pretrain demonstrations then jointly optimize online interaction across 200 tasks and test unseen adaptation",),("multitask_return","sample_efficiency","open_loop_success","unseen_adaptation","task_success"),("single-task world models","offline multitask policy","behavior cloning"),("no language conditioning","no online joint RL","no demonstration pretraining"),(("encode","newt.task","Encode language task and observation."),("imagine","newt.world_model","Predict latent dynamics across embodiments."),("plan","newt.policy","Select continuous action from world model."),("interact","newt.env","Collect online transition."),("update","newt.rl","Jointly optimize world model and policy across tasks."))),
)
PROGRAMS={r.method_id:r.program() for r in REPRODUCTIONS}
STUDY_SPECS={r.method_id:r.study() for r in REPRODUCTIONS}
__all__=["REPRODUCTIONS","PROGRAMS","STUDY_SPECS"]
