from __future__ import annotations

from typing import Iterable, Protocol

from .contracts import PerformanceBaseline, PerformanceDocument, PerformanceFileAnalysis, PerformanceLanguage, PerformanceSnapshot


class PerformanceSourceInventoryPort(Protocol):
    def documents(self) -> Iterable[PerformanceDocument]: ...


class PerformanceLanguageAnalyzerPort(Protocol):
    @property
    def language(self) -> PerformanceLanguage: ...
    @property
    def revision(self) -> str: ...
    def analyze(self, document: PerformanceDocument) -> PerformanceFileAnalysis: ...


class PerformanceSnapshotStorePort(Protocol):
    def publish_current(self, snapshot: PerformanceSnapshot) -> None: ...
    def append_history(self, snapshot: PerformanceSnapshot) -> None: ...
    def load_baseline(self) -> PerformanceBaseline | None: ...
    def publish_baseline(self, baseline: PerformanceBaseline) -> None: ...
