from noetrium_platform.foundation.kernel.kernel import MachineCut
from .catalog import ExperimentationCatalogPort
from noetrium_platform.research.experimentation.identity import ModelRoleUsage, ReplayLevel
from noetrium_platform.research.experimentation.binding import (
    ResearchBindingContribution, ResearchBindingRequirements, ResearchCapabilityBinding,
    ResearchModelRoleBinding, ResearchModelRoleRequirement, ResearchParticipantBinding,
    ResearchParticipantRequirement, ResearchRequirementResolution,
)
from noetrium_platform.research.experimentation.lifecycle.api import (
    AgentStudySpec, AnalysisDefinition, AnalysisResult, BenchmarkAssignmentMode, BenchmarkCutSpec, BenchmarkTaskSet, BenchmarkSourceKind, BenchmarkSourcePort, BenchmarkSourceResolution, BenchmarkSourceSpec, InMemoryBenchmarkSource, FactorLevelSpec, FactorSelection, MeasurementContentReference, MeasurementCut, MeasurementDefinition, MeasurementProtocol,
    PostHocEvaluationDefinition, PostHocEvaluationResult, Study, StudyModel, StudyParticipant,
    MeasurementRecord, MeasurementValue, MeasurementValueKind, ParticipantSchedule, ResearchRevision, ResearchStudyDefinition, StudyExecutionPolicy, StudyFactorSpec, StudyIntervention,
    TaskArtifactSpec, TaskDefinition, TaskPackageSpec, TaskVerifierIsolation,
    TaskGraph, TaskGraphEdge, TaskGraphRelation, TaskSetSplit, TrialBudget,
    TaskVerifierArtifact, TaskVerifierPort, TaskVerifierReceipt, TaskVerifierRequest,
    TrialExecutionReceipt, TrialExecutionRequest, TrialExecutionStageReceipt,
    TrialMatrixExecutionReport, TrialProviderPort,
)
from .research_compiler import (
    CompiledResearchPlan, ResearchPlanDiff, compile_research_plan,
    diff_research_plans, resolve_research_requirements,
)
from .method_host import compile_research_method
from .sharding import (
    CompiledExperimentShardPlan,
    ExperimentBatchPlacement,
    ExperimentShard,
    compile_experiment_shard_plan,
)
from .program import (
    CompiledExperimentProgram,
    ExperimentBatch,
    ExperimentBatchKind,
    ExperimentProgramBinding,
    compile_experiment_program,
    experiment_report_from_data,
)
from .campaign import (
    CompiledResearchCampaign,
    CompiledResearchCampaignLane,
    ResearchCampaignCompilationUnit,
    ResearchCampaignPlan,
    ResearchCampaignStudy,
    compile_research_campaign,
)
from .construction import (
    ProjectIdentityProjection,
    ProjectManifestProjection,
    ProjectRunDefinition,
)
from noetrium_platform.research.experimentation.lifecycle.api import (
    RunControlAction,
    RunControlPort,
    RunControlPreparedOperation,
    RunControlReceipt,
    RunControlRequest,
    RunControlTarget,
    RunEvidenceValidity,
    RunExecutionOutcome,
    RunOutcomeProjection,
    RunScientificValidity,
    RunTaskOutcome,
)

__all__ = [
    "MachineCut",
    "ResearchBindingContribution",
    "ResearchCapabilityBinding",
    "ResearchModelRoleBinding",
    "ResearchModelRoleRequirement",
    "ResearchParticipantBinding",
    "ResearchBindingRequirements",
    "ResearchParticipantRequirement",
    "ResearchRequirementResolution",
    "resolve_research_requirements",
    "TaskVerifierArtifact",
    "TaskVerifierPort",
    "TaskVerifierReceipt",
    "TaskVerifierRequest",
    "TrialProviderPort",
    "TrialMatrixExecutionReport",
    "TrialExecutionRequest",
    "TrialExecutionReceipt",
    "TrialExecutionStageReceipt",
    "ModelRoleUsage",
    "ReplayLevel",
    "AnalysisDefinition",
    "AnalysisResult",
    "PostHocEvaluationDefinition",
    "PostHocEvaluationResult",
    "Study",
    "StudyModel",
    "StudyParticipant",
    "BenchmarkAssignmentMode",
    "BenchmarkCutSpec",
    "BenchmarkTaskSet",
    "BenchmarkSourceKind",
    "BenchmarkSourcePort",
    "BenchmarkSourceResolution",
    "BenchmarkSourceSpec",
    "InMemoryBenchmarkSource",
    "MeasurementContentReference",
    "MeasurementCut",
    "TaskArtifactSpec",
    "TaskDefinition",
    "TaskPackageSpec",
    "TaskVerifierIsolation",
    "TaskGraph",
    "TaskGraphEdge",
    "TaskGraphRelation",
    "TaskSetSplit",
    "TrialBudget",
    "diff_research_plans",
    "compile_research_plan",
    "ResearchPlanDiff",
    "CompiledResearchPlan",
    "compile_research_method",
    "CompiledExperimentShardPlan",
    "ExperimentBatchPlacement",
    "ExperimentShard",
    "compile_experiment_shard_plan",
    "CompiledExperimentProgram",
    "ExperimentBatch",
    "ExperimentBatchKind",
    "ExperimentProgramBinding",
    "compile_experiment_program",
    "experiment_report_from_data",
    "CompiledResearchCampaign",
    "CompiledResearchCampaignLane",
    "ResearchCampaignCompilationUnit",
    "compile_research_campaign",
    "",
    "",
    "",
    "",
    "ResearchCampaignPlan",
    "ResearchCampaignStudy",
    "",
    "StudyIntervention",
    "StudyFactorSpec",
    "ResearchStudyDefinition",
    "StudyExecutionPolicy",
    "ResearchRevision",
    "ParticipantSchedule",
    "MeasurementValueKind",
    "MeasurementValue",
    "MeasurementRecord",
    "MeasurementProtocol",
    "MeasurementDefinition",
    "FactorSelection",
    "FactorLevelSpec",
    "ProjectIdentityProjection",
    "ProjectManifestProjection",
    "ProjectRunDefinition",
    "RunControlAction",
    "RunControlPort",
    "RunControlPreparedOperation",
    "RunControlReceipt",
    "RunControlRequest",
    "RunControlTarget",
    "RunEvidenceValidity",
    "RunExecutionOutcome",
    "RunOutcomeProjection",
    "RunScientificValidity",
    "RunTaskOutcome",
]

from noetrium_platform.research.execution.api import (
    ActionKind,
    ActionSpec,
    AgentGoal,
    AgentMethodSpec,
    AgentPhaseSpec,
    EmbodiedActionCommand,
    EmbodimentKind,
    EmbodimentSpec,
    EnvironmentSpec,
    ExecutionEnvironmentKind,
    GuardDecision,
    GuardVerdict,
    MethodProgram,
    MethodProgramBuilder,
    MethodWorkflow,
    SensorModality,
    SensorSpec,
)

_EXPERIMENTATION_EXECUTION_AUTHORING_EXPORTS = (
    "ActionKind",
    "ActionSpec",
    "AgentGoal",
    "AgentMethodSpec",
    "AgentPhaseSpec",
    "EmbodiedActionCommand",
    "EmbodimentKind",
    "EmbodimentSpec",
    "EnvironmentSpec",
    "ExecutionEnvironmentKind",
    "GuardDecision",
    "GuardVerdict",
    "MethodProgram",
    "MethodProgramBuilder",
    "MethodWorkflow",
    "SensorModality",
    "SensorSpec",
)
__all__ += _EXPERIMENTATION_EXECUTION_AUTHORING_EXPORTS

from noetrium_platform.research.experimentation.workbench.api import (
    TableAggregateStep,
    TableDeriveStep,
    TableExpression,
    TableExpressionKind,
    TableFilterStep,
    TableJoinStep,
    TableProgram,
    TableProjectStep,
    TableStepKind,
)
_EXPERIMENTATION_TABLE_AUTHORING_EXPORTS = (
    "TableAggregateStep",
    "TableDeriveStep",
    "TableExpression",
    "TableExpressionKind",
    "TableFilterStep",
    "TableJoinStep",
    "TableProgram",
    "TableProjectStep",
    "TableStepKind",
)
__all__ += _EXPERIMENTATION_TABLE_AUTHORING_EXPORTS
# Canonical static layer ABI.
from noetrium_platform.research.execution.api import (
    CapabilityDescriptor,
    CapabilityRequest,
    EnvironmentCapability,
    EnvironmentProviderPort,
    ExecutionContext,
    JsonValue,
    MethodIdentity,
    MethodRuntimeIdentity,
)
from noetrium_platform.research.experimentation.workbench.api import (
    AggregationFunction,
    AggregationSpec,
    BaselineSpec,
    DataColumn,
    DataTable,
    EvaluationContext,
    EvaluationStage,
    FigureCell,
    FigureKind,
    FigureOutputFormat,
    FigurePoint,
    FigureSeries,
    FigureSpec,
    FigureStyle,
    MissingValuePolicy,
    MultipleComparisonMethod,
    SplitStrategy,
    StudyObservationTableAdapter,
)

__all__ = [
    'ExperimentationCatalogPort',
    'MachineCut',
    'ResearchBindingContribution',
    'ResearchCapabilityBinding',
    'ResearchModelRoleBinding',
    'ResearchModelRoleRequirement',
    'ResearchParticipantBinding',
    'ResearchBindingRequirements',
    'ResearchParticipantRequirement',
    'ResearchRequirementResolution',
    'resolve_research_requirements',
    'TaskVerifierArtifact',
    'TaskVerifierPort',
    'TaskVerifierReceipt',
    'TaskVerifierRequest',
    'TrialProviderPort',
    'TrialMatrixExecutionReport',
    'TrialExecutionRequest',
    'TrialExecutionReceipt',
    'TrialExecutionStageReceipt',
    'ModelRoleUsage',
    'ReplayLevel',
    'AnalysisDefinition',
    'AnalysisResult',
    'PostHocEvaluationDefinition',
    'PostHocEvaluationResult',
    'Study',
    'StudyModel',
    'StudyParticipant',
    'BenchmarkAssignmentMode',
    'BenchmarkCutSpec',
    'BenchmarkTaskSet',
    'BenchmarkSourceKind',
    'BenchmarkSourcePort',
    'BenchmarkSourceResolution',
    'BenchmarkSourceSpec',
    'InMemoryBenchmarkSource',
    'MeasurementContentReference',
    'MeasurementCut',
    'TaskArtifactSpec',
    'TaskDefinition',
    'TaskPackageSpec',
    'TaskVerifierIsolation',
    'TaskGraph',
    'TaskGraphEdge',
    'TaskGraphRelation',
    'TaskSetSplit',
    'TrialBudget',
    'diff_research_plans',
    'compile_research_plan',
    'ResearchPlanDiff',
    'CompiledResearchPlan',
    'compile_research_method',
    'CompiledExperimentShardPlan',
    'ExperimentBatchPlacement',
    'ExperimentShard',
    'compile_experiment_shard_plan',
    'CompiledExperimentProgram',
    'ExperimentBatch',
    'ExperimentBatchKind',
    'ExperimentProgramBinding',
    'compile_experiment_program',
    'experiment_report_from_data',
    'CompiledResearchCampaign',
    'CompiledResearchCampaignLane',
    'ResearchCampaignCompilationUnit',
    'compile_research_campaign',
    '',
    '',
    '',
    '',
    'ResearchCampaignPlan',
    'ResearchCampaignStudy',
    '',
    'StudyIntervention',
    'StudyFactorSpec',
    'ResearchStudyDefinition',
    'StudyExecutionPolicy',
    'ResearchRevision',
    'ParticipantSchedule',
    'MeasurementValueKind',
    'MeasurementValue',
    'MeasurementRecord',
    'MeasurementProtocol',
    'MeasurementDefinition',
    'FactorSelection',
    'FactorLevelSpec',
    'ProjectIdentityProjection',
    'ProjectManifestProjection',
    'ProjectRunDefinition',
    'RunControlAction',
    'RunControlPort',
    'RunControlPreparedOperation',
    'RunControlReceipt',
    'RunControlRequest',
    'RunControlTarget',
    'RunEvidenceValidity',
    'RunExecutionOutcome',
    'RunOutcomeProjection',
    'RunScientificValidity',
    'RunTaskOutcome',
    'ActionKind',
    'ActionSpec',
    'AgentGoal',
    'AgentMethodSpec',
    'AgentPhaseSpec',
    'EmbodiedActionCommand',
    'EmbodimentKind',
    'EmbodimentSpec',
    'EnvironmentSpec',
    'ExecutionEnvironmentKind',
    'GuardDecision',
    'GuardVerdict',
    'MethodProgram',
    'MethodProgramBuilder',
    'MethodWorkflow',
    'SensorModality',
    'SensorSpec',
    'TableAggregateStep',
    'TableDeriveStep',
    'TableExpression',
    'TableExpressionKind',
    'TableFilterStep',
    'TableJoinStep',
    'TableProgram',
    'TableProjectStep',
    'TableStepKind',
    'CapabilityDescriptor',
    'CapabilityRequest',
    'EnvironmentCapability',
    'EnvironmentProviderPort',
    'ExecutionContext',
    'JsonValue',
    'MethodIdentity',
    'MethodRuntimeIdentity',
    'AgentStudySpec',
    'AggregationFunction',
    'AggregationSpec',
    'BaselineSpec',
    'DataColumn',
    'DataTable',
    'EvaluationContext',
    'EvaluationStage',
    'FigureCell',
    'FigureKind',
    'FigureOutputFormat',
    'FigurePoint',
    'FigureSeries',
    'FigureSpec',
    'FigureStyle',
    'MissingValuePolicy',
    'MultipleComparisonMethod',
    'SplitStrategy',
    'StudyObservationTableAdapter',
]

from noetrium_platform.research.experimentation.lifecycle.api import RunCheckpointManifest
__all__ = tuple(__all__) + ("RunCheckpointManifest",)

from noetrium_platform.research.experimentation.lifecycle.api import StudyVariantSpec
__all__ = tuple(__all__) + ("StudyVariantSpec",)

from noetrium_platform.research.experimentation.lifecycle.api import VariantKind
__all__ = tuple(__all__) + ("VariantKind",)


from noetrium_platform.research.experimentation.lifecycle.api import (
    StudyProtocol,
    StudyConcurrencyPolicy,
    VariantBinding,
    StudyAssignment,
    StudyExecutionPlan,
    ExperimentPlan,
)
__all__ = tuple(__all__) + (
    "StudyProtocol",
    "StudyConcurrencyPolicy",
    "VariantBinding",
    "StudyAssignment",
    "ExperimentPlan",
)
