from noetrium_platform.foundation.kernel.kernel import MachineCut
from .catalog import ExperimentationCatalogPort
from noetrium_platform.research.experimentation.identity import ModelRoleUsage, ReplayLevel
from noetrium_platform.research.experimentation.binding import (
    ResearchBindingAssuranceGap, ResearchBindingContribution, ResearchBindingRequirements, ResearchCapabilityBinding,
    ResearchModelRoleBinding, ResearchModelRoleRequirement, ResearchParticipantBinding,
    ResearchParticipantRequirement, ResearchRequirementResolution,
)
from noetrium_platform.research.experimentation.lifecycle.api import (
    materialize_research_study_spec, AgentStudySpec, AnalysisDefinition, AnalysisResult, AssignmentWorkload, BenchmarkCutRequirement, BenchmarkCutSpec, BenchmarkTaskSet, benchmark_cut_requirements, requires_benchmark_cut, BenchmarkSourceKind, BenchmarkSourcePort, BenchmarkSourceResolution, BenchmarkSourceSpec, InMemoryBenchmarkSource, FactorLevelSpec, FactorSelection, MeasurementContentReference, MeasurementCut, MeasurementDefinition, MeasurementProtocol,
    PostHocEvaluationDefinition, PostHocEvaluationResult, Study, StudyModel, StudyParticipant,
    MeasurementRecord, MeasurementValue, MeasurementValueKind, ParticipantSchedule, ResearchRevision, ResearchStudyDefinition, StudyExecutionPolicy, StudyFactorSpec, StudyIntervention,
    TaskArtifactSpec, TaskDefinition, TaskPackageSpec, TaskVerifierIsolation,
    TaskGraph, TaskGraphEdge, TaskGraphRelation, TaskSetSplit, TrialBudget,
    TaskVerifierArtifact, TaskVerifierPort, TaskVerifierReceipt, TaskVerifierRequest,
    TrialExecutionReceipt, TrialExecutionRequest, TrialExecutionStageReceipt,
    TrialMatrixExecutionReport, TrialProviderPort,
)
from .research_compiler import (
    CompiledResearchPlan, ResearchManifestRequirementKeys,
    ResearchManifestRequirementsUnresolved, ResearchPlanDiff,
    compile_research_plan, diff_research_plans,
    research_manifest_requirement_keys, resolve_research_requirements,
)
from .method_host import compile_research_method
from .sharding import (
    CompiledExperimentShardPlan,
    ExperimentBatchPlacement,
    ExperimentShard,
    compile_experiment_shard_plan,
)
from .program import (
    CompiledExperimentProgram,
    ExperimentBatch,
    ExperimentBatchKind,
    ExperimentProgramBinding,
    compile_experiment_program,
    experiment_report_from_data,
)
from .campaign import (
    CompiledResearchCampaign,
    CompiledResearchCampaignLane,
    ResearchCampaignCompilationUnit,
    ResearchCampaignPlan,
    ResearchCampaignStudy,
    compile_research_campaign,
)
from .construction import (
    ProjectIdentityProjection,
    ProjectManifestProjection,
    ProjectRunDefinition,
)

__all__ = [
    "MachineCut",
    "ResearchBindingAssuranceGap",
    "ResearchBindingContribution",
    "ResearchCapabilityBinding",
    "ResearchModelRoleBinding",
    "ResearchModelRoleRequirement",
    "ResearchParticipantBinding",
    "ResearchBindingRequirements",
    "ResearchParticipantRequirement",
    "ResearchRequirementResolution",
    "ResearchManifestRequirementKeys",
    "ResearchManifestRequirementsUnresolved",
    "research_manifest_requirement_keys",
    "resolve_research_requirements",
    "TaskVerifierArtifact",
    "TaskVerifierPort",
    "TaskVerifierReceipt",
    "TaskVerifierRequest",
    "TrialProviderPort",
    "TrialMatrixExecutionReport",
    "TrialExecutionRequest",
    "TrialExecutionReceipt",
    "TrialExecutionStageReceipt",
    "ModelRoleUsage",
    "ReplayLevel",
    "AnalysisDefinition",
    "AnalysisResult",
    "PostHocEvaluationDefinition",
    "PostHocEvaluationResult",
    "Study",
    "StudyModel",
    "StudyParticipant",
    "AssignmentWorkload",
    "BenchmarkCutRequirement",
    "BenchmarkCutRequirement",
    "BenchmarkCutSpec",
    "benchmark_cut_requirements",
    "requires_benchmark_cut",
    "benchmark_cut_requirements",
    "requires_benchmark_cut",
    "BenchmarkTaskSet",
    "BenchmarkSourceKind",
    "BenchmarkSourcePort",
    "BenchmarkSourceResolution",
    "BenchmarkSourceSpec",
    "InMemoryBenchmarkSource",
    "MeasurementContentReference",
    "MeasurementCut",
    "TaskArtifactSpec",
    "TaskDefinition",
    "TaskPackageSpec",
    "TaskVerifierIsolation",
    "TaskGraph",
    "TaskGraphEdge",
    "TaskGraphRelation",
    "TaskSetSplit",
    "TrialBudget",
    "diff_research_plans",
    "compile_research_plan",
    "ResearchPlanDiff",
    "CompiledResearchPlan",
    "compile_research_method",
    "CompiledExperimentShardPlan",
    "ExperimentBatchPlacement",
    "ExperimentShard",
    "compile_experiment_shard_plan",
    "CompiledExperimentProgram",
    "ExperimentBatch",
    "ExperimentBatchKind",
    "ExperimentProgramBinding",
    "compile_experiment_program",
    "experiment_report_from_data",
    "CompiledResearchCampaign",
    "CompiledResearchCampaignLane",
    "ResearchCampaignCompilationUnit",
    "compile_research_campaign",
    "ResearchCampaignPlan",
    "ResearchCampaignStudy",
    "StudyIntervention",
    "StudyFactorSpec",
    "ResearchStudyDefinition",
    "StudyExecutionPolicy",
    "ResearchRevision",
    "ParticipantSchedule",
    "MeasurementValueKind",
    "MeasurementValue",
    "MeasurementRecord",
    "MeasurementProtocol",
    "MeasurementDefinition",
    "FactorSelection",
    "FactorLevelSpec",
    "ProjectIdentityProjection",
    "ProjectManifestProjection",
    "ProjectRunDefinition",
]

from noetrium_platform.research.execution.api import (
    ActionKind,
    ActionSpec,
    AgentGoal,
    AgentMethodSpec,
    AgentPhaseSpec,
    EmbodiedActionCommand,
    EmbodimentKind,
    EmbodimentSpec,
    EnvironmentSpec,
    ExecutionEnvironmentKind,
    GuardDecision,
    GuardVerdict,
    MethodProgram,
    MethodProgramBuilder,
    MethodWorkflow,
    SensorModality,
    SensorSpec,
)

_EXPERIMENTATION_EXECUTION_AUTHORING_EXPORTS = (
    "ActionKind",
    "ActionSpec",
    "AgentGoal",
    "AgentMethodSpec",
    "AgentPhaseSpec",
    "EmbodiedActionCommand",
    "EmbodimentKind",
    "EmbodimentSpec",
    "EnvironmentSpec",
    "ExecutionEnvironmentKind",
    "GuardDecision",
    "GuardVerdict",
    "MethodProgram",
    "MethodProgramBuilder",
    "MethodWorkflow",
    "SensorModality",
    "SensorSpec",
)
__all__ += _EXPERIMENTATION_EXECUTION_AUTHORING_EXPORTS

from noetrium_platform.research.experimentation.workbench.api import (
    TableAggregateStep,
    TableDeriveStep,
    TableExpression,
    TableExpressionKind,
    TableFilterStep,
    TableJoinStep,
    TableProgram,
    TableProjectStep,
    TableStepKind,
)
_EXPERIMENTATION_TABLE_AUTHORING_EXPORTS = (
    "TableAggregateStep",
    "TableDeriveStep",
    "TableExpression",
    "TableExpressionKind",
    "TableFilterStep",
    "TableJoinStep",
    "TableProgram",
    "TableProjectStep",
    "TableStepKind",
)
__all__ += _EXPERIMENTATION_TABLE_AUTHORING_EXPORTS
# Canonical static layer ABI.
from noetrium_platform.research.execution.api import (
    CapabilityDescriptor,
    CapabilityRequest,
    EnvironmentCapability,
    EnvironmentProviderPort,
    ExecutionContext,
    JsonValue,
    MethodIdentity,
    MethodRuntimeIdentity,
)
from noetrium_platform.research.experimentation.workbench.api import (
    AggregationFunction,
    AggregationSpec,
    BaselineSpec,
    DataColumn,
    DataTable,
    EvaluationContext,
    EvaluationStage,
    FigureCell,
    FigureKind,
    FigureOutputFormat,
    FigurePoint,
    FigureSeries,
    FigureSpec,
    FigureStyle,
    MissingValuePolicy,
    MultipleComparisonMethod,
    SplitStrategy,
    StudyObservationTableAdapter,
)

__all__ = [
    'ExperimentationCatalogPort',
    'MachineCut',
    'ResearchBindingContribution',
    'ResearchCapabilityBinding',
    'ResearchModelRoleBinding',
    'ResearchModelRoleRequirement',
    'ResearchParticipantBinding',
    'ResearchBindingRequirements',
    'ResearchParticipantRequirement',
    'ResearchRequirementResolution',
    'resolve_research_requirements',
    'TaskVerifierArtifact',
    'TaskVerifierPort',
    'TaskVerifierReceipt',
    'TaskVerifierRequest',
    'TrialProviderPort',
    'TrialMatrixExecutionReport',
    'TrialExecutionRequest',
    'TrialExecutionReceipt',
    'TrialExecutionStageReceipt',
    'ModelRoleUsage',
    'ReplayLevel',
    'AnalysisDefinition',
    'AnalysisResult',
    'PostHocEvaluationDefinition',
    'PostHocEvaluationResult',
    'Study',
    'StudyModel',
    'StudyParticipant',
    'AssignmentWorkload',
    'BenchmarkCutRequirement',
    'BenchmarkCutRequirement',
    'BenchmarkCutSpec',
    'benchmark_cut_requirements',
    'requires_benchmark_cut',
    'benchmark_cut_requirements',
    'requires_benchmark_cut',
    'BenchmarkTaskSet',
    'BenchmarkSourceKind',
    'BenchmarkSourcePort',
    'BenchmarkSourceResolution',
    'BenchmarkSourceSpec',
    'InMemoryBenchmarkSource',
    'MeasurementContentReference',
    'MeasurementCut',
    'TaskArtifactSpec',
    'TaskDefinition',
    'TaskPackageSpec',
    'TaskVerifierIsolation',
    'TaskGraph',
    'TaskGraphEdge',
    'TaskGraphRelation',
    'TaskSetSplit',
    'TrialBudget',
    'diff_research_plans',
    'compile_research_plan',
    'ResearchPlanDiff',
    'CompiledResearchPlan',
    'compile_research_method',
    'CompiledExperimentShardPlan',
    'ExperimentBatchPlacement',
    'ExperimentShard',
    'compile_experiment_shard_plan',
    'CompiledExperimentProgram',
    'ExperimentBatch',
    'ExperimentBatchKind',
    'ExperimentProgramBinding',
    'compile_experiment_program',
    'experiment_report_from_data',
    'CompiledResearchCampaign',
    'CompiledResearchCampaignLane',
    'ResearchCampaignCompilationUnit',
    'compile_research_campaign',
    'ResearchCampaignPlan',
    'ResearchCampaignStudy',
    'StudyIntervention',
    'StudyFactorSpec',
    'ResearchStudyDefinition',
    'StudyExecutionPolicy',
    'ResearchRevision',
    'ParticipantSchedule',
    'MeasurementValueKind',
    'MeasurementValue',
    'MeasurementRecord',
    'MeasurementProtocol',
    'MeasurementDefinition',
    'FactorSelection',
    'FactorLevelSpec',
    'ProjectIdentityProjection',
    'ProjectManifestProjection',
    'ProjectRunDefinition',
    'ActionKind',
    'ActionSpec',
    'AgentGoal',
    'AgentMethodSpec',
    'AgentPhaseSpec',
    'EmbodiedActionCommand',
    'EmbodimentKind',
    'EmbodimentSpec',
    'EnvironmentSpec',
    'ExecutionEnvironmentKind',
    'GuardDecision',
    'GuardVerdict',
    'MethodProgram',
    'MethodProgramBuilder',
    'MethodWorkflow',
    'SensorModality',
    'SensorSpec',
    'TableAggregateStep',
    'TableDeriveStep',
    'TableExpression',
    'TableExpressionKind',
    'TableFilterStep',
    'TableJoinStep',
    'TableProgram',
    'TableProjectStep',
    'TableStepKind',
    'CapabilityDescriptor',
    'CapabilityRequest',
    'EnvironmentCapability',
    'EnvironmentProviderPort',
    'ExecutionContext',
    'JsonValue',
    'MethodIdentity',
    'MethodRuntimeIdentity',
    'AgentStudySpec',
    'AggregationFunction',
    'AggregationSpec',
    'BaselineSpec',
    'DataColumn',
    'DataTable',
    'EvaluationContext',
    'EvaluationStage',
    'FigureCell',
    'FigureKind',
    'FigureOutputFormat',
    'FigurePoint',
    'FigureSeries',
    'FigureSpec',
    'FigureStyle',
    'MissingValuePolicy',
    'MultipleComparisonMethod',
    'SplitStrategy',
    'StudyObservationTableAdapter',
]

from noetrium_platform.research.experimentation.lifecycle.api import RunCheckpointManifest
__all__ = tuple(__all__) + ("RunCheckpointManifest",)

from noetrium_platform.research.experimentation.lifecycle.api import StudyVariantSpec
__all__ = tuple(__all__) + ("StudyVariantSpec",)

from noetrium_platform.research.experimentation.lifecycle.api import VariantKind
__all__ = tuple(__all__) + ("VariantKind",)


from noetrium_platform.research.experimentation.lifecycle.api import (
    StudyProtocol,
    StudyConcurrencyPolicy,
    VariantBinding,
    StudyAssignment,
    StudyExecutionPlan,
    ExperimentPlan,
)
__all__ = tuple(__all__) + (
    "StudyProtocol",
    "StudyConcurrencyPolicy",
    "VariantBinding",
    "StudyAssignment",
    "ExperimentPlan",
)


# Adjacent-layer authoring surface consumed by the Product Research OS.
from noetrium_platform.research.execution.api import (
    ActionRequest,
    ActionResult,
    CapabilityPort,
    CapabilityResult,
    CapabilitySelectionReference,
    CapabilitySelectionView,
    ChildFailurePolicy,
    ChildResearchMachineBatchItem,
    ChildResearchMachineBatchPort,
    ChildResearchMachineBatchRequest,
    ChildResearchMachineExecution,
    ChildResearchMachineRequest,
    DomainProgramBuilder,
    EmbodiedCaptureReceipt,
    EmbodiedEvent,
    EmbodiedEventKind,
    EnvironmentConcern,
    EnvironmentProgramBuilder,
    EnvironmentSession,
    EpisodeSpec,
    EvaluationConcern,
    EvaluationProgramBuilder,
    ExperimentConcern,
    ExperimentProgramBuilder,
    MachineResearchProgram,
    MachineResearchProgramBuilder,
    MemoryConcern,
    MemoryProgramBuilder,
    MethodAgentRequest,
    MethodAgentResult,
    MethodEvent,
    MethodExecutionClass,
    MethodNodeKind,
    MethodNodeRequest,
    MethodNodeResult,
    MethodNodeSpec,
    MethodProgramIdentity,
    MethodRunResult,
    MethodRunStatus,
    MethodRuntimeContext,
    MethodRuntimePort,
    OptimizationConcern,
    OptimizationProgramBuilder,
    ParticipantConcern,
    ParticipantProgramBuilder,
    ProgramNode,
    ProgramNodeRequest,
    ProgramNodeResult,
    ProgramRule,
    ProgramRuleSet,
    ResearchHostOperation,
    ResearchProgramHost,
    ResearchRunProgramBuilder,
    RunConcern,
    RuntimeConcern,
    RuntimeModule,
    RuntimeModuleBuilder,
    RuntimeProgramBuilder,
    environment_action_capability_payload,
    environment_branch_action_spec,
    environment_fork_action_payload,
    environment_query_capability_payload,
    environment_replay_action_payload,
    environment_reset_capability_payload,
    materialize_capability_selection_view,
    program_execution_capability_payload,
)
from noetrium_platform.research.experimentation.lifecycle.api import (
    ExperimentTrialProtocolIdentity,
)

_EXPERIMENTATION_PRODUCT_AUTHORING_EXPORTS = (
    "ActionRequest",
    "ActionResult",
    "CapabilityPort",
    "CapabilityResult",
    "CapabilitySelectionReference",
    "CapabilitySelectionView",
    "ChildFailurePolicy",
    "ChildResearchMachineBatchItem",
    "ChildResearchMachineBatchPort",
    "ChildResearchMachineBatchRequest",
    "ChildResearchMachineExecution",
    "ChildResearchMachineRequest",
    "DomainProgramBuilder",
    "EmbodiedCaptureReceipt",
    "EmbodiedEvent",
    "EmbodiedEventKind",
    "EnvironmentConcern",
    "EnvironmentProgramBuilder",
    "EnvironmentSession",
    "EpisodeSpec",
    "EvaluationConcern",
    "EvaluationProgramBuilder",
    "ExperimentConcern",
    "ExperimentProgramBuilder",
    "ExperimentTrialProtocolIdentity",
    "MachineResearchProgram",
    "MachineResearchProgramBuilder",
    "MemoryConcern",
    "MemoryProgramBuilder",
    "MethodAgentRequest",
    "MethodAgentResult",
    "MethodEvent",
    "MethodExecutionClass",
    "MethodNodeKind",
    "MethodNodeRequest",
    "MethodNodeResult",
    "MethodNodeSpec",
    "MethodProgramIdentity",
    "MethodRunResult",
    "MethodRunStatus",
    "MethodRuntimeContext",
    "MethodRuntimePort",
    "OptimizationConcern",
    "OptimizationProgramBuilder",
    "ParticipantConcern",
    "ParticipantProgramBuilder",
    "ProgramNode",
    "ProgramNodeRequest",
    "ProgramNodeResult",
    "ProgramRule",
    "ProgramRuleSet",
    "ResearchHostOperation",
    "ResearchProgramHost",
    "ResearchRunProgramBuilder",
    "RunConcern",
    "RuntimeConcern",
    "RuntimeModule",
    "RuntimeModuleBuilder",
    "RuntimeProgramBuilder",
    "materialize_capability_selection_view",
    "program_execution_capability_payload",
)
__all__ = tuple(__all__) + _EXPERIMENTATION_PRODUCT_AUTHORING_EXPORTS

# Adjacent-layer branch/replay authoring semantics.
from noetrium_platform.research.execution.api import (
    EnvironmentForkReceipt,
    EnvironmentReplayError,
    EnvironmentReplayReceipt,
    EnvironmentSessionOpener,
    ExecutionForkReceipt,
    ExecutionSourceCut,
    ExecutionStateAnchor,
    bind_execution_fork,
    fork_environment_session,
    replay_environment_prefix,
)
__all__ = tuple(__all__) + (
    "EnvironmentForkReceipt",
    "EnvironmentReplayError",
    "EnvironmentReplayReceipt",
    "EnvironmentSessionOpener",
    "fork_environment_session",
    "replay_environment_prefix",
    "ExecutionForkReceipt",
    "ExecutionSourceCut",
    "ExecutionStateAnchor",
    "bind_execution_fork",
)
from noetrium_platform.research.execution.api import (
    TensorContentRef,
    TensorContentStorePort,
)
__all__ = tuple(__all__) + (
    "TensorContentRef",
    "TensorContentStorePort",
)

# Adjacent execution-layer contracts surfaced to the Product Research OS.
from noetrium_platform.research.execution.api import (
    ArtifactBlobRef,
    EmbodiedSimulatorBackendPort,
    SemanticProjectionSnapshot,
    SemanticSimilarityQuery,
    SemanticSimilarityQueryPort,
    SimulatorObservation,
    SimulatorStep,
    SoftwareActionKind,
    SoftwareActionTimeoutError,
    SoftwareWorldPort,
)
__all__ = tuple(__all__) + (
    "ArtifactBlobRef",
    "EmbodiedSimulatorBackendPort",
    "SemanticProjectionSnapshot",
    "SemanticSimilarityQuery",
    "SemanticSimilarityQueryPort",
    "SimulatorObservation",
    "SimulatorStep",
    "SoftwareActionKind",
    "SoftwareActionTimeoutError",
    "SoftwareWorldPort",
)
from noetrium_platform.research.experimentation.workbench.api import (
    candidate_program_capability_payload,
)
__all__ = tuple(__all__) + ("candidate_program_capability_payload",)

# Adjacent Execution-layer Method aggregate absorbed by Experimentation.
from noetrium_platform.research.execution.api import (
    ResearchComponent,
    ResearchComponentBuilder,
    ResearchComponentCall,
    ResearchComponentResult,
    ResearchComponentTransition,
    ResearchEvent,
    ResearchMethod,
    ResearchMethodBuilder,
    ResearchMethodCall,
    ResearchMethodTransition,
)

__all__ = tuple(__all__) + (
    "ResearchComponent",
    "ResearchComponentBuilder",
    "ResearchComponentCall",
    "ResearchComponentResult",
    "ResearchComponentTransition",
    "ResearchEvent",
    "ResearchMethod",
    "ResearchMethodBuilder",
    "ResearchMethodCall",
    "ResearchMethodTransition",
)

__all__ = tuple(__all__) + ("materialize_research_study_spec",)
