from __future__ import annotations
from collections.abc import Callable
from typing import Protocol, runtime_checkable
from .contracts import SystemDescriptor, SystemIdentity, SystemRegistryChange


SystemRegistryObserver = Callable[[SystemRegistryChange], None]

@runtime_checkable
class SystemRegistryPort(Protocol):
    """Read-mostly topology authority shared by composition and observation.

    The registry owns identity and topology metadata. It does not own business
    behavior, mutable domain state, or authorization decisions.
    """

    @property
    def generation(self) -> int: ...

    @property
    def topology_digest(self) -> str: ...

    def register(self, descriptor: SystemDescriptor) -> None: ...
    def register_many(self, descriptors: tuple[SystemDescriptor, ...]) -> tuple[SystemDescriptor, ...]: ...
    def subscribe(self, observer: SystemRegistryObserver) -> Callable[[], None]: ...
    def get(self, key: str) -> SystemDescriptor: ...
    def validate(self, identity: SystemIdentity) -> SystemDescriptor: ...
    def contains(self, key: str) -> bool: ...
    def list(self) -> tuple[SystemDescriptor, ...]: ...
    def children(self, key: str) -> tuple[SystemDescriptor, ...]: ...
    def descendants(self, key: str) -> tuple[SystemDescriptor, ...]: ...
    def ancestors(self, key: str) -> tuple[SystemDescriptor, ...]: ...
    def owner_for_module(self, module: str) -> SystemDescriptor | None: ...

__all__=["SystemRegistryObserver", "SystemRegistryPort"]
