"""Regenerate development-only architecture and source snapshot evidence.

This is intentionally separate from the frozen release-evidence workflow. It
records the current worktree without claiming a complete regression or a
release qualification.
"""

from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from noetrium_platform.foundation.governance.architecture.report import build_architecture_report
from noetrium_platform.foundation.governance.release.runtime.manifest import (
    EXCLUDED_DIRS,
    EXCLUDED_NAME_MARKERS,
    EXCLUDED_SUFFIXES,
)
from noetrium_platform.foundation.kernel.kernel.project_root import discover_project_root


SNAPSHOT_MANIFEST = "DEVELOPMENT_SNAPSHOT_MANIFEST.sha256"
SNAPSHOT_METADATA = "DEVELOPMENT_SNAPSHOT_METADATA.json"
SNAPSHOT_REPORT = "DEVELOPMENT_ARCHITECTURE_REPORT.json"
RELEASE_MANIFEST = "RELEASE_MANIFEST.json"


def _hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _snapshot_files(root: Path) -> tuple[Path, ...]:
    paths: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        if any(part in EXCLUDED_DIRS or part.endswith(".egg-info") for part in relative.parts):
            continue
        if path.suffix in EXCLUDED_SUFFIXES or relative.as_posix() in {
            SNAPSHOT_MANIFEST,
            RELEASE_MANIFEST,
        }:
            continue
        if any(marker in path.name for marker in EXCLUDED_NAME_MARKERS):
            continue
        paths.append(path)
    return tuple(paths)


def _write_json(path: Path, value: object) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    root = discover_project_root(__file__)
    metadata_document = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    project_metadata = metadata_document.get("project", {})
    platform_version = str(project_metadata.get("version", "")).strip()
    if not platform_version:
        raise RuntimeError("pyproject.toml project.version is required for a snapshot")
    report = build_architecture_report(root)
    _write_json(root / SNAPSHOT_REPORT, asdict(report))

    files = _snapshot_files(root)
    python_files = tuple(path for path in files if path.suffix == ".py")
    test_files = tuple(path for path in files if path.parent.name == "tests" and path.name.startswith("test_"))
    docs_files = tuple(path for path in files if path.suffix == ".md")
    metadata = {
        "architecture_import_edges": report.import_edges,
        "architecture_report_sha256": report.report_sha256,
        "architecture_summary_document": "docs/architecture/CURRENT_ARCHITECTURE_EVOLUTION_20260820.md",
        "capability_graph_edges": len(report.capability_graph),
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "docs_file_count": len(docs_files),
        "event_graph_edges": len(report.event_graph),
        "file_count": len(files),
        "focused_migration_regression": "must be regenerated by the current validation command; not inherited from a prior tree",
        "latest_complete_development_regression": "not claimed by development snapshot",
        "operation_graph_edges": len(report.operation_graph),
        "platform_version": platform_version,
        "post_packaging_source_checks": {
            "architecture_gate": "PASS (focused migration revalidation)",
            "codegraph_cycles": "0 (one-shot graph-only; persistent database unavailable)",
            "python_compileall": "PASS",
            "full_regression": "NOT_CLAIMED_BY_SNAPSHOT",
        },
        "python_file_count": len(python_files),
        "release_artifacts_note": (
            "RELEASE_MANIFEST.json binds this snapshot tree; RELEASE_EVIDENCE.json is present and binds the "
            "complete static quality and pytest regression evidence. External live-runtime evidence remains separate."
            if (root / "RELEASE_EVIDENCE.json").is_file()
            else "RELEASE_MANIFEST.json binds this snapshot tree; RELEASE_EVIDENCE.json is absent until the complete pytest regression is available."
        ),
        "schema_version": 2,
        "snapshot_kind": "development",
        "snapshot_manifest_note": "DEVELOPMENT_SNAPSHOT_MANIFEST.sha256 is the byte-level authority for this development snapshot; it excludes itself but includes DEVELOPMENT_SNAPSHOT_METADATA.json.",
        "source_root_name": f"noetrium-snapshot-{platform_version}",
        "test_file_count": len(test_files),
        "tests_collected": None,
    }
    _write_json(root / SNAPSHOT_METADATA, metadata)

    manifest_lines = [
        f"{_hash_file(path)}  {path.relative_to(root).as_posix()}"
        for path in _snapshot_files(root)
    ]
    (root / SNAPSHOT_MANIFEST).write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    print(f"DEVELOPMENT_SNAPSHOT_PASS files={len(files)} python={len(python_files)} tests={len(test_files)} report={report.report_sha256}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
