#!/usr/bin/env python3
"""Generate the complete downstream contract catalog and system facades.

The canonical inputs are the system registry and each registered package's
public API modules. Generated files are deliberately boring: they contain
explicit imports, stable system metadata, and no provider/runtime lookup.
"""
from __future__ import annotations

import argparse
import ast
from dataclasses import asdict, dataclass
import hashlib
import json
from pathlib import Path
import re
import sys
from typing import Any

SCHEMA = "noetrium-downstream-contracts.v1"
_MARKER = "AUTO-GENERATED by scripts/generate_downstream_contracts.py"
_SAFE = re.compile(r"[^A-Za-z0-9_.-]+")


@dataclass(frozen=True)
class ApiModuleSurface:
    module: str
    source: str
    symbols: tuple[str, ...]


@dataclass(frozen=True)
class SystemSurface:
    system_key: str
    package_prefix: str
    authority: str
    owns: str
    must_not_own: str
    requires: tuple[str, ...]
    provides: tuple[str, ...]
    api_modules: tuple[ApiModuleSurface, ...]
    facade_module: str | None


def _literal_all(tree: ast.AST) -> tuple[str, ...] | None:
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(target, ast.Name) and target.id == "__all__"
                   for target in node.targets):
            continue
        try:
            value = ast.literal_eval(node.value)
        except (ValueError, TypeError):
            return None
        if isinstance(value, (list, tuple)) and all(isinstance(item, str) for item in value):
            return tuple(value)
        return None
    return None


def _public_symbols(path: Path) -> tuple[str, ...]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    declared = _literal_all(tree)
    if declared is not None:
        return tuple(dict.fromkeys(declared))
    names: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                names.append(node.name)
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            if module == "__future__":
                continue
            if node.level == 0 and not (
                module.startswith("noetrium_platform")
                or module.startswith("components")
                or module.startswith("orchestration")
            ):
                continue
            for alias in node.names:
                if alias.name == "*":
                    continue
                name = alias.asname or alias.name.split(".")[-1]
                if not name.startswith("_"):
                    names.append(name)
    return tuple(dict.fromkeys(names))


def _package_dir(root: Path, package_prefix: str) -> Path:
    return root.joinpath(*package_prefix.split("."))


def _module_name(package_prefix: str, api_root: Path, path: Path) -> str:
    relative = path.relative_to(api_root)
    parts = list(relative.parts)
    if parts[-1] == "__init__.py":
        parts = parts[:-1]
    else:
        parts[-1] = Path(parts[-1]).stem
    suffix = ".".join(part for part in parts if part)
    return f"{package_prefix}.api" + (f".{suffix}" if suffix else "")


def _api_modules(root: Path, package_prefix: str) -> tuple[ApiModuleSurface, ...]:
    package = _package_dir(root, package_prefix)
    api_root = package / "api"
    candidates: list[Path] = []
    if (package / "api.py").is_file():
        candidates.append(package / "api.py")
    if api_root.is_dir():
        candidates.extend(sorted(api_root.rglob("*.py")))
    rows: list[ApiModuleSurface] = []
    seen: set[str] = set()
    for path in candidates:
        module = (
            f"{package_prefix}.api"
            if path.name == "api.py"
            else _module_name(package_prefix, api_root, path)
        )
        if module in seen:
            continue
        seen.add(module)
        symbols = _public_symbols(path)
        if symbols:
            rows.append(ApiModuleSurface(module, path.relative_to(root).as_posix(), symbols))
    return tuple(rows)


def _facade_slug(system_key: str) -> str:
    return _SAFE.sub("__", system_key).strip("_.") or "system"


def _digest(value: object) -> str:
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def build_surfaces(root: Path) -> tuple[SystemSurface, ...]:
    registry_path = root / "noetrium_platform/foundation/governance/system_registry/catalog.json"
    catalog = json.loads(registry_path.read_text(encoding="utf-8"))
    if not isinstance(catalog, dict):
        raise ValueError("canonical system registry must be an object")
    rows: list[SystemSurface] = []
    for system_key, descriptor in catalog.items():
        if not isinstance(descriptor, dict):
            raise ValueError(f"invalid system descriptor: {system_key}")
        modules = _api_modules(root, descriptor["package_prefix"])
        rows.append(SystemSurface(
            system_key=system_key,
            package_prefix=descriptor["package_prefix"],
            authority=descriptor["authority"],
            owns=descriptor["owns"],
            must_not_own=descriptor["must_not_own"],
            requires=tuple(descriptor["requires"]),
            provides=tuple(descriptor["provides"]),
            api_modules=modules,
            facade_module=(
                f"noetrium.contracts.systems.{_facade_slug(system_key)}"
                if modules else None
            ),
        ))
    return tuple(rows)


def _aliased_symbols(surface: SystemSurface) -> list[tuple[str, str, str]]:
    """Return (module, source_name, facade_name), preserving collisions."""
    result: list[tuple[str, str, str]] = []
    used: set[str] = set()
    for api in surface.api_modules:
        module_slug = _SAFE.sub("_", api.module.rsplit(".", 1)[-1])
        for name in api.symbols:
            facade_name = name
            if facade_name in used:
                facade_name = f"{module_slug}__{name}"
                serial = 2
                while facade_name in used:
                    facade_name = f"{module_slug}{serial}__{name}"
                    serial += 1
            used.add(facade_name)
            result.append((api.module, name, facade_name))
    return result


def render_facade(surface: SystemSurface) -> str:
    imports: dict[str, list[tuple[str, str]]] = {}
    for module, source_name, facade_name in _aliased_symbols(surface):
        imports.setdefault(module, []).append((source_name, facade_name))
    lines = [
        f'""" {_MARKER}.',
        f"System: {surface.system_key}",
        f"Authority: {surface.authority}",
        "This module is regenerated from the canonical registry and API exports.",
        '"""',
        "",
    ]
    for module in sorted(imports):
        lines.append(f"from {module} import (")
        for source_name, facade_name in imports[module]:
            suffix = "" if source_name == facade_name else f" as {facade_name}"
            lines.append(f"    {source_name}{suffix},")
        lines.extend((")", ""))
    names = [facade_name for _, _, facade_name in _aliased_symbols(surface)]
    lines.append(f"SYSTEM_KEY = {surface.system_key!r}")
    lines.append(f"PACKAGE_PREFIX = {surface.package_prefix!r}")
    lines.append(f"__all__ = {tuple(names)!r}")
    lines.append("")
    return "\n".join(lines)


def render_init(surfaces: tuple[SystemSurface, ...]) -> str:
    mapping = {
        surface.system_key: surface.facade_module
        for surface in surfaces if surface.facade_module is not None
    }
    lines = [
        f'""" {_MARKER}.',
        "One generated typed facade exists for every registered system with API exports.",
        '"""',
        "",
        f"SYSTEM_FACADES = {mapping!r}",
        f"SYSTEM_KEYS = {tuple(surface.system_key for surface in surfaces)!r}",
        "",
        '__all__ = ["SYSTEM_FACADES", "SYSTEM_KEYS"]',
        "",
    ]
    return "\n".join(lines)


def render_catalog(root: Path, surfaces: tuple[SystemSurface, ...]) -> bytes:
    registry = json.loads(
        (root / "noetrium_platform/foundation/governance/system_registry/catalog.json")
        .read_text(encoding="utf-8")
    )
    topology_digest = _digest(registry)
    document: dict[str, Any] = {
        "schema": SCHEMA,
        "generator": "scripts/generate_downstream_contracts.py",
        "topology_digest": topology_digest,
        "systems": [],
    }
    for surface in surfaces:
        document["systems"].append({
            "system_key": surface.system_key,
            "package_prefix": surface.package_prefix,
            "authority": surface.authority,
            "owns": surface.owns,
            "must_not_own": surface.must_not_own,
            "requires": list(surface.requires),
            "provides": list(surface.provides),
            "facade_module": surface.facade_module,
            "api_modules": [
                {"module": api.module, "source": api.source, "symbols": list(api.symbols)}
                for api in surface.api_modules
            ],
        })
    return (json.dumps(document, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")


def render_markdown(root: Path, surfaces: tuple[SystemSurface, ...]) -> bytes:
    registry = json.loads(
        (root / "noetrium_platform/foundation/governance/system_registry/catalog.json")
        .read_text(encoding="utf-8")
    )
    lines = [
        "# Noetrium downstream capability catalog",
        "",
        "This file is generated from the canonical system registry and public API exports.",
        "Do not edit it manually; run `python scripts/generate_downstream_contracts.py`.",
        "",
        f"- Registered systems: {len(surfaces)}",
        f"- Systems with typed facades: {sum(surface.facade_module is not None for surface in surfaces)}",
        f"- Registry digest: `{_digest(registry)}`",
        "",
    ]
    for surface in surfaces:
        requires = ", ".join(f"`{item}`" for item in surface.requires) or "none"
        provides = ", ".join(f"`{item}`" for item in surface.provides) or "none"
        lines.extend([
            f"## `{surface.system_key}`",
            "",
            f"- Package: `{surface.package_prefix}`",
            f"- Authority: `{surface.authority}`",
            f"- Owns: {surface.owns}",
            f"- Must not own: {surface.must_not_own}",
            f"- Requires: {requires}",
            f"- Provides: {provides}",
            f"- Facade: `{surface.facade_module}`" if surface.facade_module else "- Facade: none (no exported API symbols)",
            "",
        ])
        if surface.api_modules:
            lines.append("### API modules")
            lines.append("")
            for api in surface.api_modules:
                symbols = ", ".join(f"`{name}`" for name in api.symbols)
                lines.append(f"- `{api.module}` — {symbols}")
            lines.append("")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _write_or_check(path: Path, content: bytes, check: bool) -> bool:
    current = path.read_bytes() if path.is_file() else None
    if check:
        return current == content
    path.parent.mkdir(parents=True, exist_ok=True)
    if current != content:
        path.write_bytes(content)
    return True


def generate(root: Path, *, check: bool = False) -> int:
    surfaces = build_surfaces(root)
    facade_root = root / "noetrium/contracts/systems"
    catalog_path = root / "noetrium/contracts/downstream_capability_catalog.json"
    markdown_path = root / "docs/architecture/DOWNSTREAM_CAPABILITY_CATALOG.md"
    topology_path = root / "docs/architecture/VNEXT_SYSTEM_CATALOG.json"
    topology_source = root / "noetrium_platform/foundation/governance/system_registry/catalog.json"
    expected: dict[Path, bytes] = {
        facade_root / "__init__.py": render_init(surfaces).encode("utf-8"),
        catalog_path: render_catalog(root, surfaces),
        markdown_path: render_markdown(root, surfaces),
        topology_path: topology_source.read_bytes(),
    }
    for surface in surfaces:
        if surface.facade_module is None:
            continue
        slug = surface.facade_module.rsplit(".", 1)[-1]
        expected[facade_root / f"{slug}.py"] = render_facade(surface).encode("utf-8")
    if not check:
        facade_root.mkdir(parents=True, exist_ok=True)
        for path in facade_root.glob("*.py"):
            if path.name == "__init__.py":
                continue
            try:
                if _MARKER not in path.read_text(encoding="utf-8"):
                    continue
            except OSError:
                continue
            if path not in expected:
                path.unlink()
    ok = True
    for path, content in expected.items():
        if not _write_or_check(path, content, check):
            ok = False
            if check:
                print(f"generated contract drift: {path.relative_to(root)}", file=sys.stderr)
    print(json.dumps({
        "schema": SCHEMA,
        "system_count": len(surfaces),
        "facade_count": sum(surface.facade_module is not None for surface in surfaces),
        "api_module_count": sum(len(surface.api_modules) for surface in surfaces),
        "api_symbol_count": sum(
            len(api.symbols) for surface in surfaces for api in surface.api_modules
        ),
        "catalog_digest": hashlib.sha256(expected[catalog_path]).hexdigest(),
        "check": check,
        "clean": ok,
    }, sort_keys=True))
    return 0 if ok else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(args.root.resolve(), check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
