#!/usr/bin/env python3
"""Generate machine-readable schemas for every public downstream interface."""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from generate_downstream_contracts import build_surfaces  # noqa: E402

SCHEMA = "noetrium-interface-catalog.v1"
INTERFACE_SCHEMA_ID = "noetrium.interface-schema"
INTERFACE_SCHEMA_VERSION = "1"
OUTPUT = "noetrium/contracts/interface_schema.json"
_MARKER = "AUTO-GENERATED by scripts/generate_interface_schemas.py"


def _annotation(node: ast.AST | None) -> str | None:
    return None if node is None else ast.unparse(node)


def _safe_default(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    try:
        return repr(ast.literal_eval(node))
    except (ValueError, TypeError, SyntaxError):
        return ast.unparse(node)


def _parameters(args: ast.arguments) -> list[dict[str, Any]]:
    positional = [*args.posonlyargs, *args.args]
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    rows: list[dict[str, Any]] = []
    for argument, default in zip(positional, defaults):
        rows.append({
            "name": argument.arg,
            "annotation": _annotation(argument.annotation),
            "default": _safe_default(default),
            "required": default is None and argument.arg not in {"self", "cls"},
            "receiver": argument.arg in {"self", "cls"},
            "kind": "positional_only" if argument in args.posonlyargs else "positional_or_keyword",
        })
    if args.vararg is not None:
        rows.append({
            "name": args.vararg.arg,
            "annotation": _annotation(args.vararg.annotation),
            "default": None,
            "required": False,
            "receiver": False,
            "kind": "var_positional",
        })
    for argument, default in zip(args.kwonlyargs, args.kw_defaults):
        rows.append({
            "name": argument.arg,
            "annotation": _annotation(argument.annotation),
            "default": _safe_default(default),
            "required": default is None,
            "receiver": False,
            "kind": "keyword_only",
        })
    if args.kwarg is not None:
        rows.append({
            "name": args.kwarg.arg,
            "annotation": _annotation(args.kwarg.annotation),
            "default": None,
            "required": False,
            "receiver": False,
            "kind": "var_keyword",
        })
    return rows


def _callable(node: ast.FunctionDef | ast.AsyncFunctionDef, kind: str) -> dict[str, Any]:
    return {
        "schema_id": INTERFACE_SCHEMA_ID,
        "schema_version": INTERFACE_SCHEMA_VERSION,
        "name": node.name,
        "kind": kind,
        "signature": ast.unparse(node).splitlines()[0],
        "parameters": _parameters(node.args),
        "return_annotation": _annotation(node.returns),
        "decorators": [ast.unparse(value) for value in node.decorator_list],
        "doc": ast.get_docstring(node),
    }


def _class(node: ast.ClassDef) -> dict[str, Any]:
    methods: list[dict[str, Any]] = []
    fields: list[dict[str, Any]] = []
    members: list[str] = []
    for child in node.body:
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            methods.append(_callable(child, "method"))
        elif isinstance(child, ast.AnnAssign) and isinstance(child.target, ast.Name):
            fields.append({
                "name": child.target.id,
                "annotation": _annotation(child.annotation),
                "default": _safe_default(child.value),
            })
        elif isinstance(child, ast.Assign):
            for target in child.targets:
                if isinstance(target, ast.Name) and not target.id.startswith("_"):
                    members.append(target.id)
    return {
        "schema_id": INTERFACE_SCHEMA_ID,
        "schema_version": INTERFACE_SCHEMA_VERSION,
        "name": node.name,
        "kind": "class",
        "bases": [ast.unparse(value) for value in node.bases],
        "decorators": [ast.unparse(value) for value in node.decorator_list],
        "fields": fields,
        "members": members,
        "methods": methods,
        "doc": ast.get_docstring(node),
    }


def _reexport_source(root: Path, source: Path, module: str) -> Path | None:
    if module.startswith("."):
        level = len(module) - len(module.lstrip("."))
        suffix = module[level:]
        base = source.parent
        for _ in range(level - 1):
            base = base.parent
        target = base.joinpath(*suffix.split(".")) if suffix else base
    else:
        target = root.joinpath(*module.split("."))
    file_path = target.with_suffix(".py")
    if file_path.is_file():
        return file_path
    init_path = target / "__init__.py"
    return init_path if init_path.is_file() else None


def _symbols(
    root: Path,
    path: Path,
    names: tuple[str, ...],
    *,
    seen: frozenset[tuple[Path, str]] = frozenset(),
) -> tuple[dict[str, Any], ...]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    definitions: dict[str, ast.AST] = {}
    reexports: dict[str, tuple[str, str]] = {}
    star_reexports: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            definitions[node.name] = node
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else (node.target,)
            for target in targets:
                if isinstance(target, ast.Name):
                    definitions[target.id] = node
        elif isinstance(node, ast.ImportFrom):
            module = "." * node.level + (node.module or "")
            for alias in node.names:
                if alias.name == "*":
                    star_reexports.append(module)
                else:
                    reexports[alias.asname or alias.name] = (module, alias.name)

    result: list[dict[str, Any]] = []
    for name in names:
        node = definitions.get(name)
        if isinstance(node, ast.ClassDef):
            result.append(_class(node))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            result.append(_callable(node, "async_function" if isinstance(node, ast.AsyncFunctionDef) else "function"))
        elif node is not None:
            result.append({
                "schema_id": INTERFACE_SCHEMA_ID,
                "schema_version": INTERFACE_SCHEMA_VERSION,
                "name": name,
                "kind": "value",
                "annotation": _annotation(node.annotation) if isinstance(node, ast.AnnAssign) else None,
                "value": _safe_default(node.value),
                "doc": None,
            })
        elif name in reexports:
            module, origin_name = reexports[name]
            row: dict[str, Any] = {
                "schema_id": INTERFACE_SCHEMA_ID,
                "schema_version": INTERFACE_SCHEMA_VERSION,
                "name": name,
                "kind": "reexport",
                "origin_module": module,
                "origin_name": origin_name,
                "doc": None,
            }
            source = _reexport_source(root, path, module)
            key = (source.resolve(), origin_name) if source is not None else None
            if source is not None and key not in seen:
                row["resolved_schema"] = _symbols(
                    root,
                    source,
                    (origin_name,),
                    seen=seen | {key},
                )[0]
            result.append(row)
        else:
            resolved_star: dict[str, Any] | None = None
            for module in star_reexports:
                source = _reexport_source(root, path, module)
                key = (
                    (source.resolve(), name)
                    if source is not None
                    else None
                )
                if source is None or key in seen:
                    continue
                candidate = _symbols(
                    root,
                    source,
                    (name,),
                    seen=seen | {key},
                )[0]
                if candidate.get("kind") != "unknown":
                    resolved_star = {
                        "schema_id": INTERFACE_SCHEMA_ID,
                        "schema_version": INTERFACE_SCHEMA_VERSION,
                        "name": name,
                        "kind": "reexport",
                        "origin_module": module,
                        "origin_name": name,
                        "resolved_schema": candidate,
                        "doc": None,
                    }
                    break
            if resolved_star is not None:
                result.append(resolved_star)
            else:
                result.append({
                    "schema_id": INTERFACE_SCHEMA_ID,
                    "schema_version": INTERFACE_SCHEMA_VERSION,
                    "name": name,
                    "kind": "unknown",
                    "doc": None,
                })
    return tuple(result)


def _literal_all(path: Path) -> tuple[str, ...]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            continue
        raw = ast.literal_eval(node.value)
        if not isinstance(raw, (tuple, list)) or any(not isinstance(item, str) for item in raw):
            raise RuntimeError(f"{path}: __all__ must be a literal string sequence")
        return tuple(raw)
    raise RuntimeError(f"{path}: missing literal __all__")


def _digest(value: object) -> str:
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(raw).hexdigest()


def build_document(root: Path) -> dict[str, Any]:
    surfaces = build_surfaces(root)
    registry = json.loads(
        (root / "noetrium_platform/foundation/governance/system_registry/catalog.json").read_text(encoding="utf-8")
    )
    systems: list[dict[str, Any]] = []
    for surface in surfaces:
        modules: list[dict[str, Any]] = []
        for api in surface.api_modules:
            source = root / api.source
            modules.append({
                "module": api.module,
                "source": api.source,
                "symbols": list(api.symbols),
                "symbol_schemas": list(_symbols(root, source, api.symbols)),
            })
        systems.append({
            "system_key": surface.system_key,
            "package_prefix": surface.package_prefix,
            "facade_module": surface.facade_module,
            "api_modules": modules,
        })
    public_source = root / "noetrium/api/__init__.py"
    public_symbols = _literal_all(public_source)
    public_api = {
        "module": "noetrium.api",
        "source": public_source.relative_to(root).as_posix(),
        "symbols": list(public_symbols),
        "symbol_schemas": list(_symbols(root, public_source, public_symbols)),
    }

    product_source = root / "noetrium_platform/product/research_os.py"
    method_source = root / "noetrium_platform/research/execution/method/authoring.py"
    runtime_source = root / "noetrium/_research_os_runtime.py"
    reachable_dsl = {
        "program": _symbols(root, product_source, ("ResearchProgramBuilder",))[0],
        "method": _symbols(root, method_source, ("ResearchMethodBuilder",))[0],
        "memory": _symbols(root, method_source, ("ResearchComponentBuilder",))[0],
        "runtime": _symbols(root, runtime_source, ("ResearchOS",))[0],
    }

    document = {
        "schema": SCHEMA,
        "generator": "scripts/generate_interface_schemas.py",
        "topology_digest": _digest(registry),
        "interface_schema": {
            "schema_id": INTERFACE_SCHEMA_ID,
            "schema_version": INTERFACE_SCHEMA_VERSION,
            "description": (
                "The single downstream Research Portfolio / Research OS API plus "
                "schema-only DSL types reachable from those roots."
            ),
        },
        "public_api": public_api,
        "reachable_dsl": reachable_dsl,
        "authoring_inspection": {
            "entrypoint": "noetrium.api",
            "public_roots": list(public_symbols),
            "authoring_root": "ResearchPortfolioBuilder",
            "portfolio_type": "ResearchPortfolio",
            "program_dsl": "ResearchPortfolioBuilder.program -> ResearchProgramBuilder",
            "method_dsl": "ResearchProgramBuilder.method(configure) -> ResearchMethodBuilder callback",
            "memory_dsl": "ResearchMethodBuilder.memory -> ResearchComponentBuilder",
            "runtime_root": "ResearchOS",
            "project_opener": "open_project",
            "boundary": (
                "Only noetrium.api is downstream-importable. Program/Method/Memory "
                "DSL types are schema-reachable implementation contracts; provider "
                "selection, deployment, resources, Docker, model/environment lifecycle "
                "and recovery remain platform-owned."
            ),
        },
        "systems": systems,
    }
    document["interface_digest"] = _digest(document)
    return document


def generate(root: Path, *, check: bool = False) -> int:
    document = build_document(root)
    expected = (json.dumps(document, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode()
    path = root / OUTPUT
    clean = path.is_file() and path.read_bytes() == expected
    if not check and not clean:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected)
        clean = True
    result = {
        "schema": SCHEMA,
        "system_count": len(document["systems"]),
        "api_module_count": sum(len(row["api_modules"]) for row in document["systems"]),
        "api_symbol_count": sum(len(api["symbols"]) for row in document["systems"] for api in row["api_modules"]),
        "interface_digest": hashlib.sha256(expected).hexdigest(),
        "check": check,
        "clean": clean,
    }
    print(json.dumps(result, sort_keys=True))
    return 0 if clean else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(args.root.resolve(), check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
