from __future__ import annotations

from noetrium_platform.research.reproduction import (
    ReferenceBaseline,
    ReportedResult,
    ReproductionAssetKind,
    ReproductionAssetRef,
    ReproductionCatalog,
    ReproductionDefinition,
    ReproductionDelta,
    ReproductionDeltaKind,
    ReproductionIdentity,
    ReproductionLifecycle,
)

REPRODUCTION = ReproductionDefinition(
    package='react_alfworld',
    lifecycle=ReproductionLifecycle('protocol_bound'),
    identity=ReproductionIdentity(
        method_id='react',
        title='ReAct: Synergizing Reasoning and Acting in Language Models',
        paper_uri='https://openreview.net/forum?id=WE_vluYUL-X',
        year=2023,
        paper_revision='arXiv:2210.03629v3 / ICLR 2023',
    ),
    catalog=ReproductionCatalog(
        domains=('agent-loop', 'reasoning', 'tool-use'),
        families=('reasoning', 'tool_use', 'agent_loop'),
        priority=1,
        benchmark_ids=('alfworld', 'webshop'),
        platform_pressure=('participant/agent', 'model/request', 'environment/text_world', 'experimentation/study', 'observability/telemetry'),
        method_owned=('thought-action interleaving policy', 'reasoning trace policy'),
        platform_owned=('agent loop lifecycle', 'model invocation', 'environment binding', 'evidence and metrics'),
    ),
    assets=(
        ReproductionAssetRef(
            kind=ReproductionAssetKind('fidelity'),
            path='research/reproductions/react_alfworld/fidelity.py',
        ),
        ReproductionAssetRef(
            kind=ReproductionAssetKind('method_program'),
            path='research/reproductions/react_alfworld/program.py',
        ),
        ReproductionAssetRef(
            kind=ReproductionAssetKind('semantics'),
            path='research/reproductions/react_alfworld/semantics.py',
        ),
        ReproductionAssetRef(
            kind=ReproductionAssetKind('study'),
            path='research/reproductions/react_alfworld/study.py',
        ),
        ReproductionAssetRef(
            kind=ReproductionAssetKind('support'),
            path='research/reproductions/react_alfworld/trajectory.py',
        ),
    ),
    reported_results=(
        ReportedResult(
            claim_id='react_palm_mean',
            metric_id='success_rate',
            value=57,
            qualifiers={'aggregation': 'mean_of_6_trials',
 'condition': 'ReAct',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='react_palm_best',
            metric_id='success_rate',
            value=71,
            qualifiers={'aggregation': 'best_of_6_trials',
 'condition': 'ReAct',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='act_palm_best',
            metric_id='success_rate',
            value=45,
            qualifiers={'aggregation': 'best_of_6_trials',
 'condition': 'Act',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='react_im_palm_mean',
            metric_id='success_rate',
            value=48,
            qualifiers={'aggregation': 'mean_of_6_trials',
 'condition': 'ReAct-IM',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='react_im_palm_best',
            metric_id='success_rate',
            value=53,
            qualifiers={'aggregation': 'best_of_6_trials',
 'condition': 'ReAct-IM',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='butler_best',
            metric_id='success_rate',
            value=37,
            qualifiers={'aggregation': 'reported_best_of_8',
 'condition': 'BUTLER',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='butler_g_best',
            metric_id='success_rate',
            value=22,
            qualifiers={'aggregation': 'reported_best_of_8',
 'condition': 'BUTLERg',
 'model_lane_id': 'paper',
 'reported_model_lane': {'kind': 'paper_reported',
                         'lane_id': 'paper',
                         'roles': [{'availability': 'historical_not_publicly_reproducible',
                                    'decoding': {'strategy': 'greedy'},
                                    'model': 'PaLM-540B',
                                    'role': 'action'}]}},
        ),
        ReportedResult(
            claim_id='released_code_davinci002',
            metric_id='success_rate',
            value=78.4,
            qualifiers={'aggregation': 'single_released_code_sweep',
 'condition': 'ReAct',
 'model_lane_id': 'official_code',
 'reported_model_lane': {'kind': 'released_code',
                         'lane_id': 'official_code',
                         'roles': [{'availability': 'historical_decommissioned',
                                    'decoding': {'frequency_penalty': 0,
                                                 'max_output_tokens': 100,
                                                 'presence_penalty': 0,
                                                 'stop_sequences': ['\\n'],
                                                 'temperature': 0,
                                                 'top_p': 1},
                                    'model': 'text-davinci-002',
                                    'role': 'action'}]}},
        ),
    ),
    reference_baselines=(
        ReferenceBaseline(
            baseline_id='act',
            description='environment interaction without ReAct reasoning traces',
            qualifiers={},
        ),
        ReferenceBaseline(
            baseline_id='react-im',
            description='dense external-feedback thought-pattern ablation reported by ReAct',
            qualifiers={},
        ),
        ReferenceBaseline(
            baseline_id='butler',
            description='ALFWorld imitation-learning baseline cited by the ReAct paper',
            qualifiers={},
        ),
        ReferenceBaseline(
            baseline_id='butler-g',
            description='ALFWorld BUTLERg baseline cited by the ReAct paper',
            qualifiers={},
        ),
    ),
    deltas=(
        ReproductionDelta(
            kind=ReproductionDeltaKind('unresolved'),
            description='paper PaLM-540B model identity cannot currently be rebound exactly',
        ),
        ReproductionDelta(
            kind=ReproductionDeltaKind('unresolved'),
            description='paper table aggregates six PaLM trials while the released GPT-3 notebook encodes a distinct single-sweep lane',
        ),
    ),
    blockers=('the PaLM-540B paper lane is not publicly reproducible as an exact model cut', 'text-davinci-002 used by the released notebook is decommissioned', 'the exact ALFWorld json_2.1.1 dataset/environment must be deployment-bound before matched execution'),
    evidence_refs=(),
    scientific_tests=('tests/test_scientific_react_alfworld_fidelity_v1.py', 'tests/test_scientific_react_alfworld_method_program_v1.py', 'tests/test_scientific_react_alfworld_protocol_v1.py'),
)

__all__ = ["REPRODUCTION"]
