""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
Static typing projection for the single noetrium.api downstream entrypoint.
"""
from typing import Any

from noetrium.contracts.discovery import (
    DownstreamCapabilityCatalog as DownstreamCapabilityCatalog,
    DownstreamSystemSurface as DownstreamSystemSurface,
)

class ApiSymbolMatch:
    symbol: str
    owners: tuple[str, ...]

def catalog() -> DownstreamCapabilityCatalog: ...
def system(system_key: str) -> Any: ...
def resolve(symbol: str) -> Any: ...
def owners(symbol: str) -> tuple[str, ...]: ...
def search(query: str, *, limit: int = 50) -> tuple[ApiSymbolMatch, ...]: ...
def describe(symbol: str) -> tuple[dict[str, Any], ...]: ...
def interface_schema() -> dict[str, Any]: ...
def symbol_schema(system_key: str, module: str, symbol: str) -> dict[str, Any]: ...

from components.api import (
    EpisodicMemoryStore as EpisodicMemoryStore,
    JsonlReferenceAgentProgress as JsonlReferenceAgentProgress,
    MemoryEdgeRecord as MemoryEdgeRecord,
    MemoryEmbedderPort as MemoryEmbedderPort,
    MemoryGraphConflict as MemoryGraphConflict,
    MemoryGraphIntegrityError as MemoryGraphIntegrityError,
    MemoryGraphLedgerEntry as MemoryGraphLedgerEntry,
    MemoryGraphOperation as MemoryGraphOperation,
    MemoryGraphPort as MemoryGraphPort,
    MemoryGraphSnapshot as MemoryGraphSnapshot,
    MemoryGraphTransaction as MemoryGraphTransaction,
    MemoryItem as MemoryItem,
    MemoryNodeRecord as MemoryNodeRecord,
    MemoryPersistencePort as MemoryPersistencePort,
    NullReferenceAgentProgress as NullReferenceAgentProgress,
    PlatformCapabilityToolPort as PlatformCapabilityToolPort,
    ReferenceAgentAction as ReferenceAgentAction,
    ReferenceAgentActionKind as ReferenceAgentActionKind,
    ReferenceAgentActionToolPort as ReferenceAgentActionToolPort,
    ReferenceAgentDecision as ReferenceAgentDecision,
    ReferenceAgentDecisionPort as ReferenceAgentDecisionPort,
    ReferenceAgentEvent as ReferenceAgentEvent,
    ReferenceAgentMessage as ReferenceAgentMessage,
    ReferenceAgentObservation as ReferenceAgentObservation,
    ReferenceAgentPlannerPort as ReferenceAgentPlannerPort,
    ReferenceAgentProgressPort as ReferenceAgentProgressPort,
    ReferenceAgentReflectionPort as ReferenceAgentReflectionPort,
    ReferenceAgentRunResult as ReferenceAgentRunResult,
    ReferenceAgentSolverPort as ReferenceAgentSolverPort,
    ReferenceAgentState as ReferenceAgentState,
    ReferenceAgentStatus as ReferenceAgentStatus,
    ReferenceAgentToolPort as ReferenceAgentToolPort,
    ReferencePlanAndSolveMethod as ReferencePlanAndSolveMethod,
    ReferenceReActMethod as ReferenceReActMethod,
    ReferenceReflexionMethod as ReferenceReflexionMethod,
    ReferenceToolRegistryPort as ReferenceToolRegistryPort,
    SQLiteMemoryPersistence as SQLiteMemoryPersistence,
    ToolArguments as ToolArguments,
    ToolAuditPort as ToolAuditPort,
    ToolAuthorization as ToolAuthorization,
    ToolAuthorizationPort as ToolAuthorizationPort,
    ToolDefinition as ToolDefinition,
    ToolHandler as ToolHandler,
    ToolRegistry as ToolRegistry,
    ToolResult as ToolResult,
    ToolRiskClass as ToolRiskClass,
    VectorMemoryStore as VectorMemoryStore,
    VersionedMemoryGraph as VersionedMemoryGraph,
    WorkingMemory as WorkingMemory,
)

from noetrium.contracts.json import (
    CanonicalDecodingError as CanonicalDecodingError,
    CanonicalDecodingFailureKind as CanonicalDecodingFailureKind,
    CanonicalEncodingError as CanonicalEncodingError,
    DigestValidationError as DigestValidationError,
)

from noetrium_platform.capabilities.environment.api import (
    EffectCertainty as EffectCertainty,
)

from noetrium_platform.capabilities.model.asset.api.contracts import (
    ManagedModelAsset as ManagedModelAsset,
    ModelAcquisitionReceipt as ModelAcquisitionReceipt,
    ModelAssetMode as ModelAssetMode,
    ModelAssetOrigin as ModelAssetOrigin,
    ModelAssetStats as ModelAssetStats,
    ModelAssetUsage as ModelAssetUsage,
    ModelConfigSummary as ModelConfigSummary,
    ModelSourceSpec as ModelSourceSpec,
    ModelStoragePoolStatus as ModelStoragePoolStatus,
)

from noetrium_platform.capabilities.model.asset.api.ports import (
    ModelAssetLookupPort as ModelAssetLookupPort,
    ModelAssetManagementPort as ModelAssetManagementPort,
    ModelAssetStoragePort as ModelAssetStoragePort,
    ModelAssetUsagePort as ModelAssetUsagePort,
    ModelSourceBackend as ModelSourceBackend,
)

from noetrium_platform.capabilities.model.assignment.api.contracts import (
    ModelAssignment as ModelAssignment,
    ResolvedModelAssignment as ResolvedModelAssignment,
)

from noetrium_platform.capabilities.model.assignment.api.ports import (
    ModelAssignmentPort as ModelAssignmentPort,
)

from noetrium_platform.capabilities.model.deployment.api.contracts import (
    ModelControlSnapshot as ModelControlSnapshot,
    ModelControllerPhase as ModelControllerPhase,
    ModelControllerState as ModelControllerState,
    ModelDeploymentLogs as ModelDeploymentLogs,
    ModelDeploymentSelector as ModelDeploymentSelector,
    ModelDeploymentSpec as ModelDeploymentSpec,
    ModelDeploymentStatus as ModelDeploymentStatus,
    ModelDesiredState as ModelDesiredState,
    ModelEnvironmentUsage as ModelEnvironmentUsage,
    ModelGpuAllocation as ModelGpuAllocation,
    ModelGpuConflict as ModelGpuConflict,
    ModelGpuProcessBinding as ModelGpuProcessBinding,
    ModelLogTail as ModelLogTail,
    ModelReconcileCycle as ModelReconcileCycle,
    ModelRuntimeState as ModelRuntimeState,
)

from noetrium_platform.capabilities.model.deployment.api.ports import (
    ModelControllerStatePort as ModelControllerStatePort,
    ModelControllerStopPort as ModelControllerStopPort,
    ModelDeploymentCatalogPort as ModelDeploymentCatalogPort,
    ModelDeploymentLogPort as ModelDeploymentLogPort,
    ModelDeploymentRuntimePort as ModelDeploymentRuntimePort,
    ModelFleetRuntimePort as ModelFleetRuntimePort,
    ModelReconcileControllerPort as ModelReconcileControllerPort,
    ModelResourceViewPort as ModelResourceViewPort,
    ModelServiceRuntimeFactoryPort as ModelServiceRuntimeFactoryPort,
)

from noetrium_platform.capabilities.model.qualification.api.qualification import (
    BackendCandidatePlan as BackendCandidatePlan,
    CandidateDecision as CandidateDecision,
    CudaFacts as CudaFacts,
    DEFAULT_DEPLOYMENT_PROBE_TIMEOUT_SECONDS as DEFAULT_DEPLOYMENT_PROBE_TIMEOUT_SECONDS,
    DEFAULT_PACKAGE_INDEX_URL as DEFAULT_PACKAGE_INDEX_URL,
    DeploymentCapabilityFacts as DeploymentCapabilityFacts,
    DeploymentCapabilityProbePort as DeploymentCapabilityProbePort,
    DeploymentQualificationApplicationPort as DeploymentQualificationApplicationPort,
    DeploymentQualificationApplicationReceipt as DeploymentQualificationApplicationReceipt,
    DeploymentQualificationApplicationRequest as DeploymentQualificationApplicationRequest,
    DeploymentQualificationApplicationStorePort as DeploymentQualificationApplicationStorePort,
    DeploymentQualificationEvidenceRecord as DeploymentQualificationEvidenceRecord,
    DeploymentQualificationEvidenceStorePort as DeploymentQualificationEvidenceStorePort,
    DeploymentQualificationPlan as DeploymentQualificationPlan,
    DeploymentQualificationPort as DeploymentQualificationPort,
    DeploymentQualificationRequest as DeploymentQualificationRequest,
    DeploymentQualificationRuntimePort as DeploymentQualificationRuntimePort,
    DeploymentQualificationRuntimeReceipt as DeploymentQualificationRuntimeReceipt,
    DeploymentQualificationRuntimeRequest as DeploymentQualificationRuntimeRequest,
    DeploymentQualificationRuntimeStorePort as DeploymentQualificationRuntimeStorePort,
    DeploymentRuntimeQualificationStatus as DeploymentRuntimeQualificationStatus,
    GpuCapabilityFacts as GpuCapabilityFacts,
    GpuFabricFacts as GpuFabricFacts,
    HostExecutionFacts as HostExecutionFacts,
    InstallPackage as InstallPackage,
    ModelArtifactFacts as ModelArtifactFacts,
    OperatingSystemFacts as OperatingSystemFacts,
    PackageArtifactFacts as PackageArtifactFacts,
    PackageDependencyNodeFacts as PackageDependencyNodeFacts,
    PackageIndexFacts as PackageIndexFacts,
    PythonRuntimeFacts as PythonRuntimeFacts,
    QualificationCommandReceipt as QualificationCommandReceipt,
    QualificationMaterializationStatus as QualificationMaterializationStatus,
    QualificationPackageInstallerPort as QualificationPackageInstallerPort,
    QualificationRuntimeProbePort as QualificationRuntimeProbePort,
    RuntimeCheckReceipt as RuntimeCheckReceipt,
    StorageCapabilityFacts as StorageCapabilityFacts,
    native_cuda_runtime_package_names as native_cuda_runtime_package_names,
)

from noetrium_platform.capabilities.model.request.api import (
    ImmutableModelIdentity as ImmutableModelIdentity,
)

from noetrium_platform.capabilities.participant.binding.api.contracts import (
    ParticipantBindingResolverPort as ParticipantBindingResolverPort,
    ParticipantConfigurationCatalogPort as ParticipantConfigurationCatalogPort,
    ParticipantImplementationRegistration as ParticipantImplementationRegistration,
    ParticipantRuntimeEndpointFactory as ParticipantRuntimeEndpointFactory,
    ParticipantSessionRuntimeRegistration as ParticipantSessionRuntimeRegistration,
)

from noetrium_platform.capabilities.participant.core.api.checkpoint import (
    ParticipantCheckpoint as ParticipantCheckpoint,
    ParticipantCheckpointIdentityMismatch as ParticipantCheckpointIdentityMismatch,
    ParticipantCheckpointRef as ParticipantCheckpointRef,
)

from noetrium_platform.capabilities.participant.core.api.contracts import (
    ParticipantRuntimeBinding as ParticipantRuntimeBinding,
)

from noetrium_platform.capabilities.participant.core.api.frozen_manifests import (
    ParticipantImplementationInventory as ParticipantImplementationInventory,
    ParticipantRuntimeBindingManifest as ParticipantRuntimeBindingManifest,
    ParticipantRuntimeInventory as ParticipantRuntimeInventory,
)

from noetrium_platform.capabilities.participant.core.api.lifecycle import (
    ParticipantIdentityMismatch as ParticipantIdentityMismatch,
    ParticipantLifecycleAdapter as ParticipantLifecycleAdapter,
    ParticipantLifecycleAdapterRegistry as ParticipantLifecycleAdapterRegistry,
)

from noetrium_platform.capabilities.participant.core.api.runtime import (
    ParticipantResolverPort as ParticipantResolverPort,
    ParticipantRuntimeHandle as ParticipantRuntimeHandle,
)

from noetrium_platform.capabilities.participant.core.api.runtime_operations import (
    PARTICIPANT_OPERATION_VERBS as PARTICIPANT_OPERATION_VERBS,
    ParticipantOperationContractError as ParticipantOperationContractError,
    participant_operation_type as participant_operation_type,
    participant_operation_verb as participant_operation_verb,
    validate_participant_kind as validate_participant_kind,
)

from noetrium_platform.capabilities.participant.core.api.runtime_ports import (
    ParticipantCheckpointOperationsPort as ParticipantCheckpointOperationsPort,
    ParticipantResolutionPort as ParticipantResolutionPort,
)

from noetrium_platform.evidence.data.query.api.identity import (
    input_cut_digest as input_cut_digest,
    query_document as query_document,
    record_document as record_document,
    research_query_digest as research_query_digest,
    source_cut as source_cut,
)

from noetrium_platform.foundation.governance.release.api import (
    ReleaseQualityEvidence as ReleaseQualityEvidence,
)

from noetrium_platform.foundation.governance.system_registry.api.contracts import (
    STANDARD_SYSTEM_SHAPE as STANDARD_SYSTEM_SHAPE,
)

from noetrium_platform.foundation.kernel.concurrency.api.ports import (
    CpuWorkerPoolProviderPort as CpuWorkerPoolProviderPort,
    ExecutionAuthorityProviderPort as ExecutionAuthorityProviderPort,
    ExecutorProviderPort as ExecutorProviderPort,
    SerialExecutionLaneFactoryProviderPort as SerialExecutionLaneFactoryProviderPort,
    SerialExecutionLaneProviderPort as SerialExecutionLaneProviderPort,
    TimerSchedulerProviderPort as TimerSchedulerProviderPort,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api import (
    ServerRemoteProfile as ServerRemoteProfile,
)

from noetrium_platform.platform import (
    AgentObservationPartSourcePort as AgentObservationPartSourcePort,
    DirectoryRunArtifactBinding as DirectoryRunArtifactBinding,
    ExperimentBinding as ExperimentBinding,
    MinecraftEnvironmentBinding as MinecraftEnvironmentBinding,
    MultimodalAgentObservationPort as MultimodalAgentObservationPort,
    ProjectTestStage as ProjectTestStage,
    ProjectTestStageReceipt as ProjectTestStageReceipt,
    QualifiedProjectModelBinding as QualifiedProjectModelBinding,
    ResearchAction as ResearchAction,
    ResearchApplicationPort as ResearchApplicationPort,
    ResearchCampaignBinding as ResearchCampaignBinding,
    ResearchFacade as ResearchFacade,
    ResearchOperationFailure as ResearchOperationFailure,
    ResearchRequest as ResearchRequest,
    ResearchResult as ResearchResult,
    ResearchWorkbenchBinding as ResearchWorkbenchBinding,
    bind_bundled_minecraft_environment as bind_bundled_minecraft_environment,
    bind_directory_run_artifact_store as bind_directory_run_artifact_store,
    bind_durable_run_control as bind_durable_run_control,
    bind_environment_category_catalog as bind_environment_category_catalog,
    bind_experiment_execution as bind_experiment_execution,
    bind_experiment_resources as bind_experiment_resources,
    bind_method_checkpoint_store as bind_method_checkpoint_store,
    bind_method_endpoint as bind_method_endpoint,
    bind_minecraft_environment as bind_minecraft_environment,
    bind_qualified_project_model as bind_qualified_project_model,
    bind_research_campaign as bind_research_campaign,
    bind_research_execution_pool as bind_research_execution_pool,
    bind_research_workbench as bind_research_workbench,
    bind_run_control_application as bind_run_control_application,
    bind_universal_method_machine as bind_universal_method_machine,
    build_basic_study_metric_aggregation as build_basic_study_metric_aggregation,
    build_deterministic_study_assignment as build_deterministic_study_assignment,
    build_project_run_checkpoint_store as build_project_run_checkpoint_store,
    complete_project_model as complete_project_model,
    invoke_multimodal_model as invoke_multimodal_model,
    run_local_command as run_local_command,
    run_local_shell_command as run_local_shell_command,
    run_method_program as run_method_program,
    run_method_program_async as run_method_program_async,
)

from noetrium_platform.research.execution.machines.api import (
    BatchCapableRegisteredChildResearchMachineExecutor as BatchCapableRegisteredChildResearchMachineExecutor,
    CapabilityMediationDenied as CapabilityMediationDenied,
    CapabilityMediationRequest as CapabilityMediationRequest,
    CapabilityMediationResult as CapabilityMediationResult,
    CapabilityMediationStage as CapabilityMediationStage,
    CapabilityMediationVerdict as CapabilityMediationVerdict,
    CapabilityMediator as CapabilityMediator,
    CapabilityMediatorRegistry as CapabilityMediatorRegistry,
    CapabilityMediatorRegistryPort as CapabilityMediatorRegistryPort,
    CapabilityProgram as CapabilityProgram,
    CapabilityRuleProgram as CapabilityRuleProgram,
    CapabilityRuntimeBinding as CapabilityRuntimeBinding,
    ChildBatchExecutionMode as ChildBatchExecutionMode,
    ChildFailurePolicy as ChildFailurePolicy,
    ChildResearchBindingFactory as ChildResearchBindingFactory,
    ChildResearchHostRegistry as ChildResearchHostRegistry,
    ChildResearchHostRegistryPort as ChildResearchHostRegistryPort,
    ChildResearchMachineBatchExecution as ChildResearchMachineBatchExecution,
    ChildResearchMachineBatchExecutor as ChildResearchMachineBatchExecutor,
    ChildResearchMachineBatchItem as ChildResearchMachineBatchItem,
    ChildResearchMachineBatchMechanicsPort as ChildResearchMachineBatchMechanicsPort,
    ChildResearchMachineBatchMechanicsResult as ChildResearchMachineBatchMechanicsResult,
    ChildResearchMachineBatchPort as ChildResearchMachineBatchPort,
    ChildResearchMachineBatchRequest as ChildResearchMachineBatchRequest,
    ChildResearchMachineExecution as ChildResearchMachineExecution,
    ChildResearchMachineExecutor as ChildResearchMachineExecutor,
    ChildResearchMachineRequest as ChildResearchMachineRequest,
    CommunicationRuntimeSpec as CommunicationRuntimeSpec,
    ContextBlockProgram as ContextBlockProgram,
    ContextBudgetExceeded as ContextBudgetExceeded,
    ContextProgram as ContextProgram,
    ContextProjection as ContextProjection,
    ContextRenderRequest as ContextRenderRequest,
    ContextRenderResult as ContextRenderResult,
    ContextRenderer as ContextRenderer,
    ContextRendererRegistry as ContextRendererRegistry,
    ContextRendererRegistryPort as ContextRendererRegistryPort,
    ContextRuntimeBinding as ContextRuntimeBinding,
    DomainProgramBuilder as DomainProgramBuilder,
    EnvironmentConcern as EnvironmentConcern,
    EnvironmentMachineSpec as EnvironmentMachineSpec,
    EnvironmentProgramBuilder as EnvironmentProgramBuilder,
    EvaluationConcern as EvaluationConcern,
    EvaluationProgramBuilder as EvaluationProgramBuilder,
    ExperimentConcern as ExperimentConcern,
    ExperimentProgramBuilder as ExperimentProgramBuilder,
    FunctionalModelInvocationRequestFactory as FunctionalModelInvocationRequestFactory,
    InterventionDecider as InterventionDecider,
    InterventionDeciderRegistry as InterventionDeciderRegistry,
    InterventionDeciderRegistryPort as InterventionDeciderRegistryPort,
    InterventionDecision as InterventionDecision,
    InterventionKind as InterventionKind,
    InterventionPolicyRequest as InterventionPolicyRequest,
    InterventionProgram as InterventionProgram,
    InterventionResponse as InterventionResponse,
    InterventionRuntimeBinding as InterventionRuntimeBinding,
    InterventionTrigger as InterventionTrigger,
    LogicalSchedulingCandidate as LogicalSchedulingCandidate,
    LogicalSchedulingProgram as LogicalSchedulingProgram,
    LogicalSchedulingRequest as LogicalSchedulingRequest,
    LogicalSchedulingRuntimeBinding as LogicalSchedulingRuntimeBinding,
    LogicalSchedulingSelection as LogicalSchedulingSelection,
    LogicalSchedulingSelector as LogicalSchedulingSelector,
    LogicalSchedulingSelectorRegistry as LogicalSchedulingSelectorRegistry,
    LogicalSchedulingSelectorRegistryPort as LogicalSchedulingSelectorRegistryPort,
    MachineEvent as MachineEvent,
    MemoryConcern as MemoryConcern,
    MemoryPresetSpec as MemoryPresetSpec,
    MemoryProgramBuilder as MemoryProgramBuilder,
    MemoryRecord as MemoryRecord,
    ModelInvocationCandidate as ModelInvocationCandidate,
    ModelInvocationMode as ModelInvocationMode,
    ModelInvocationOutcome as ModelInvocationOutcome,
    ModelInvocationProgram as ModelInvocationProgram,
    ModelInvocationRequestFactoryPort as ModelInvocationRequestFactoryPort,
    ModelInvocationRuntime as ModelInvocationRuntime,
    ModelInvocationRuntimeBinding as ModelInvocationRuntimeBinding,
    ModelResponseSelector as ModelResponseSelector,
    ModelResponseSelectorRegistry as ModelResponseSelectorRegistry,
    ModelResponseSelectorRegistryPort as ModelResponseSelectorRegistryPort,
    ModelSelectionRequest as ModelSelectionRequest,
    ObjectiveDirection as ObjectiveDirection,
    OptimizationConcern as OptimizationConcern,
    OptimizationObjective as OptimizationObjective,
    OptimizationPresetSpec as OptimizationPresetSpec,
    OptimizationProgramBuilder as OptimizationProgramBuilder,
    PARTICIPANT_TURN_FACT_KINDS as PARTICIPANT_TURN_FACT_KINDS,
    PARTICIPANT_TURN_FACT_WIRE_SCHEMA as PARTICIPANT_TURN_FACT_WIRE_SCHEMA,
    ParticipantConcern as ParticipantConcern,
    ParticipantMessageKind as ParticipantMessageKind,
    ParticipantProgramBuilder as ParticipantProgramBuilder,
    ProgramHandlerRegistry as ProgramHandlerRegistry,
    ProgramHandlerRegistryPort as ProgramHandlerRegistryPort,
    ProgramNode as ProgramNode,
    ProgramNodeRequest as ProgramNodeRequest,
    ProgramNodeResult as ProgramNodeResult,
    ProgramOperationHandler as ProgramOperationHandler,
    ProgramRule as ProgramRule,
    ProgramRuleSet as ProgramRuleSet,
    RecoveryDecider as RecoveryDecider,
    RecoveryDeciderRegistry as RecoveryDeciderRegistry,
    RecoveryDeciderRegistryPort as RecoveryDeciderRegistryPort,
    RecoveryDecision as RecoveryDecision,
    RecoveryProgram as RecoveryProgram,
    RecoveryRequest as RecoveryRequest,
    RecoveryRuntimeBinding as RecoveryRuntimeBinding,
    RecoverySignal as RecoverySignal,
    RegisteredChildResearchHost as RegisteredChildResearchHost,
    RegisteredChildResearchMachineExecutor as RegisteredChildResearchMachineExecutor,
    RegisteredSerialChildResearchBatchMechanics as RegisteredSerialChildResearchBatchMechanics,
    ResearchHostBindingRestorer as ResearchHostBindingRestorer,
    ResearchHostExecution as ResearchHostExecution,
    ResearchHostHandler as ResearchHostHandler,
    ResearchHostOperation as ResearchHostOperation,
    ResearchProgram as ResearchProgram,
    ResearchProgramBuilder as ResearchProgramBuilder,
    ResearchProgramHost as ResearchProgramHost,
    ResearchRunProgramBuilder as ResearchRunProgramBuilder,
    RuleDispatchMode as RuleDispatchMode,
    RunConcern as RunConcern,
    RuntimeConcern as RuntimeConcern,
    RuntimeModule as RuntimeModule,
    RuntimeModuleBuilder as RuntimeModuleBuilder,
    RuntimeModuleLink as RuntimeModuleLink,
    RuntimeModuleNode as RuntimeModuleNode,
    RuntimeProgramBuilder as RuntimeProgramBuilder,
    RuntimeProgramComposer as RuntimeProgramComposer,
    SynchronizationAction as SynchronizationAction,
    SynchronizationDecider as SynchronizationDecider,
    SynchronizationDeciderRegistry as SynchronizationDeciderRegistry,
    SynchronizationDeciderRegistryPort as SynchronizationDeciderRegistryPort,
    SynchronizationDecision as SynchronizationDecision,
    SynchronizationMode as SynchronizationMode,
    SynchronizationPoint as SynchronizationPoint,
    SynchronizationPresetSpec as SynchronizationPresetSpec,
    SynchronizationProgram as SynchronizationProgram,
    SynchronizationRequest as SynchronizationRequest,
    SynchronizationRuntimeBinding as SynchronizationRuntimeBinding,
    ThreadPoolChildResearchBatchMechanics as ThreadPoolChildResearchBatchMechanics,
    UnhandledEventPolicy as UnhandledEventPolicy,
    VisibilityDecider as VisibilityDecider,
    VisibilityDeciderRegistry as VisibilityDeciderRegistry,
    VisibilityDeciderRegistryPort as VisibilityDeciderRegistryPort,
    VisibilityDecision as VisibilityDecision,
    VisibilityDisposition as VisibilityDisposition,
    VisibilityProgram as VisibilityProgram,
    VisibilityRequest as VisibilityRequest,
    VisibilityResource as VisibilityResource,
    VisibilityRuntimeBinding as VisibilityRuntimeBinding,
    VisibilitySubject as VisibilitySubject,
    build_rule_handlers as build_rule_handlers,
    capability_mediator_binding_digest as capability_mediator_binding_digest,
    capability_program_from_policy as capability_program_from_policy,
    capability_runtime_module as capability_runtime_module,
    communication_initial_data as communication_initial_data,
    communication_rule_set as communication_rule_set,
    compile_communication_runtime_program as compile_communication_runtime_program,
    compile_context as compile_context,
    compile_environment_program as compile_environment_program,
    compile_memory_program as compile_memory_program,
    compile_optimization_program as compile_optimization_program,
    compile_rule_program as compile_rule_program,
    context_projection_payload as context_projection_payload,
    context_renderer_binding_digest as context_renderer_binding_digest,
    context_runtime_module as context_runtime_module,
    context_runtime_operation as context_runtime_operation,
    environment_initial_data as environment_initial_data,
    environment_rule_set as environment_rule_set,
    execution_context_from_payload as execution_context_from_payload,
    execution_context_payload as execution_context_payload,
    intervention_initial_data as intervention_initial_data,
    intervention_runtime_module as intervention_runtime_module,
    logical_scheduling_initial_data as logical_scheduling_initial_data,
    logical_scheduling_runtime_module as logical_scheduling_runtime_module,
    memory_initial_data as memory_initial_data,
    memory_rule_set as memory_rule_set,
    model_invocation_runtime_module as model_invocation_runtime_module,
    optimization_initial_data as optimization_initial_data,
    optimization_rule_set as optimization_rule_set,
    participant_turn_initial_data as participant_turn_initial_data,
    participant_turn_program as participant_turn_program,
    program_handler_binding_digest as program_handler_binding_digest,
    recovery_initial_data as recovery_initial_data,
    recovery_runtime_module as recovery_runtime_module,
    standard_synchronization_decider as standard_synchronization_decider,
    synchronization_initial_data as synchronization_initial_data,
    synchronization_program_from_preset as synchronization_program_from_preset,
    synchronization_runtime_module as synchronization_runtime_module,
    visibility_initial_data as visibility_initial_data,
    visibility_runtime_module as visibility_runtime_module,
)

from noetrium_platform.research.execution.workflow.api import (
    MethodAgentTargetHandler as MethodAgentTargetHandler,
    MethodAgentViewHandler as MethodAgentViewHandler,
    MethodCapabilityTargetHandler as MethodCapabilityTargetHandler,
)

from noetrium_platform.research.execution.workflow.api.method_machine import (
    MethodAuthoritativeState as MethodAuthoritativeState,
    MethodControlRecord as MethodControlRecord,
    MethodSchemaPort as MethodSchemaPort,
    MethodTransitionAuthorityPort as MethodTransitionAuthorityPort,
    MethodTransitionRecord as MethodTransitionRecord,
)

from noetrium_platform.research.experimentation.api import (
    CompiledTrialExperimentProgram as CompiledTrialExperimentProgram,
    ModelRoleUsage as ModelRoleUsage,
    ResearchBindingContribution as ResearchBindingContribution,
    ResearchBindingRequirements as ResearchBindingRequirements,
    ResearchCapabilityBinding as ResearchCapabilityBinding,
    ResearchModelRoleBinding as ResearchModelRoleBinding,
    ResearchModelRoleRequirement as ResearchModelRoleRequirement,
    ResearchParticipantBinding as ResearchParticipantBinding,
    ResearchParticipantRequirement as ResearchParticipantRequirement,
    ResearchRequirementResolution as ResearchRequirementResolution,
    TrialExperimentProgramBinding as TrialExperimentProgramBinding,
    compile_trial_experiment_program as compile_trial_experiment_program,
    trial_report_from_data as trial_report_from_data,
)

from noetrium_platform.research.experimentation.experiment.api.contracts import (
    ExperimentDoctorPort as ExperimentDoctorPort,
    FindingSeverity as FindingSeverity,
    ObservationEnvelope as ObservationEnvelope,
    ObservationKind as ObservationKind,
    ObservationSinkPort as ObservationSinkPort,
    UnitOutcome as UnitOutcome,
    UnitOutcomeState as UnitOutcomeState,
)

from noetrium_platform.research.experimentation.study.api.analysis import (
    DatasetVersionProjection as DatasetVersionProjection,
    EvidenceManifestProjection as EvidenceManifestProjection,
)

from noetrium_platform.research.experimentation.study.api.materialization import (
    MaterializedTaskVerifierArchive as MaterializedTaskVerifierArchive,
    TaskVerifierArchiveMaterializationPort as TaskVerifierArchiveMaterializationPort,
)

from noetrium_platform.research.experimentation.study.runtime import (
    BasicStudyMetricAggregator as BasicStudyMetricAggregator,
    DeterministicStudyAssignment as DeterministicStudyAssignment,
    DoctorReport as DoctorReport,
    ExperimentDoctor as ExperimentDoctor,
    InMemoryObservationProjection as InMemoryObservationProjection,
    MetricEngine as MetricEngine,
    StudyMatrixUniversalProjection as StudyMatrixUniversalProjection,
    TrialVerifierOrchestrator as TrialVerifierOrchestrator,
    UniversalExperimentKernel as UniversalExperimentKernel,
    project_experiment_run_report as project_experiment_run_report,
)

from noetrium_platform.research.experimentation.workbench.api.table_program import (
    TableAggregateStep as TableAggregateStep,
    TableDeriveStep as TableDeriveStep,
    TableExecutionReceipt as TableExecutionReceipt,
    TableExecutionResult as TableExecutionResult,
    TableExpression as TableExpression,
    TableExpressionKind as TableExpressionKind,
    TableFilterStep as TableFilterStep,
    TableJoinStep as TableJoinStep,
    TableProgram as TableProgram,
    TableProgramExecutionPort as TableProgramExecutionPort,
    TableProgramStep as TableProgramStep,
    TableProjectStep as TableProjectStep,
    TableStepKind as TableStepKind,
)

from noetrium_platform.research.experimentation.workbench.providers import (
    CsvTableReader as CsvTableReader,
    JsonlTableReader as JsonlTableReader,
    PdfFigureRenderer as PdfFigureRenderer,
    PublicationFigureRenderer as PublicationFigureRenderer,
    StandardTableRenderer as StandardTableRenderer,
    SvgFigureRenderer as SvgFigureRenderer,
)

from noetrium_platform.research.experimentation.workbench.runtime import (
    CandidateProgramCapabilityBinding as CandidateProgramCapabilityBinding,
    InMemoryBaselineRegistry as InMemoryBaselineRegistry,
    ResearchFigureFactory as ResearchFigureFactory,
    ResearchLifecycle as ResearchLifecycle,
    ScientificStatistics as ScientificStatistics,
    TablePipeline as TablePipeline,
    candidate_program_capability_payload as candidate_program_capability_payload,
)

from orchestration.api import (
    CommunicationEdge as CommunicationEdge,
    CommunicationTopology as CommunicationTopology,
    MultiAgentCancellationPort as MultiAgentCancellationPort,
    MultiAgentDeliveryReceipt as MultiAgentDeliveryReceipt,
    MultiAgentDeliveryStatus as MultiAgentDeliveryStatus,
    MultiAgentMembershipPort as MultiAgentMembershipPort,
    MultiAgentMessage as MultiAgentMessage,
    MultiAgentNodePort as MultiAgentNodePort,
    MultiAgentRunResult as MultiAgentRunResult,
    MultiAgentRunStatus as MultiAgentRunStatus,
    MultiAgentRuntime as MultiAgentRuntime,
    MultiAgentTransportPort as MultiAgentTransportPort,
    TransportBackedMultiAgentRuntime as TransportBackedMultiAgentRuntime,
    compile_multi_agent_runtime_program as compile_multi_agent_runtime_program,
    debate_initial_message as debate_initial_message,
    group_chat_initial_messages as group_chat_initial_messages,
    hierarchical_initial_message as hierarchical_initial_message,
    multi_agent_initial_data as multi_agent_initial_data,
    multi_agent_rule_set as multi_agent_rule_set,
)

def __getattr__(name: str) -> Any: ...
