"""Static typing projection for the single Noetrium Research OS API."""

from noetrium_platform.product.api import (
    ResearchBranch as ResearchBranch,
    ResearchControlAction as ResearchControlAction,
    ResearchControlReceipt as ResearchControlReceipt,
    ResearchControlRequest as ResearchControlRequest,
    ResearchDefinition as ResearchDefinition,
    ResearchDefinitionKind as ResearchDefinitionKind,
    ResearchDependency as ResearchDependency,
    ResearchGraphRevision as ResearchGraphRevision,
    ResearchImpactState as ResearchImpactState,
    ResearchImplementation as ResearchImplementation,
    ResearchInputBinding as ResearchInputBinding,
    ResearchNode as ResearchNode,
    ResearchNodeImpact as ResearchNodeImpact,
    ResearchNodeKind as ResearchNodeKind,
    ResearchOS as ResearchOS,
    ResearchOSPort as ResearchOSPort,
    ResearchOutputSpec as ResearchOutputSpec,
    ResearchPortfolio as ResearchPortfolio,
    ResearchProgram as ResearchProgram,
    ResearchProgramBuilder as ResearchProgramBuilder,
    ResearchRevisionDiff as ResearchRevisionDiff,
    ResearchTag as ResearchTag,
    ResearchValueKind as ResearchValueKind,
)
