""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
Static typing projection for the single Noetrium Research OS API.
"""

from noetrium_platform.product.api import (
    ResearchBranch as ResearchBranch,
    ResearchControlAction as ResearchControlAction,
    ResearchControlReceipt as ResearchControlReceipt,
    ResearchControlRequest as ResearchControlRequest,
    ResearchDefinition as ResearchDefinition,
    ResearchDefinitionKind as ResearchDefinitionKind,
    ResearchDependency as ResearchDependency,
    ResearchExecutionTarget as ResearchExecutionTarget,
    ResearchGraphRevision as ResearchGraphRevision,
    ResearchImpactState as ResearchImpactState,
    ResearchImplementation as ResearchImplementation,
    ResearchInputBinding as ResearchInputBinding,
    ResearchMethodProgramBindingKind as ResearchMethodProgramBindingKind,
    ResearchMethodProgramImplementation as ResearchMethodProgramImplementation,
    ResearchNode as ResearchNode,
    ResearchNodeImpact as ResearchNodeImpact,
    ResearchNodeKind as ResearchNodeKind,
    ResearchNodeRef as ResearchNodeRef,
    ResearchOS as ResearchOS,
    ResearchOutputSpec as ResearchOutputSpec,
    ResearchPortfolio as ResearchPortfolio,
    ResearchPortfolioBuilder as ResearchPortfolioBuilder,
    ResearchPortfolioDependency as ResearchPortfolioDependency,
    ResearchProgram as ResearchProgram,
    ResearchProgramBuilder as ResearchProgramBuilder,
    ResearchRevisionDiff as ResearchRevisionDiff,
    ResearchTag as ResearchTag,
    ResearchValueKind as ResearchValueKind,
)
