"""Fourth 2025 frontier reproduction wave.

Paper-private semantics stay downstream. This campaign freezes method semantics,
benchmark/environment cuts, experimental protocols, metrics, baselines, reported
results, provenance URIs, and matched-execution requirements for ten published
2025 agent papers spanning memory, embodied agents, web agents, evaluation,
knowledge reasoning, and multi-agent scientific workflows.
"""
from __future__ import annotations

FRONTIER_2025_WAVE_04 = (
    {
        "id": "awm_icml2025",
        "paper": "Agent Workflow Memory",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/wang25bx.html",
        "family": ("memory", "web-agent", "long-horizon", "workflow-induction"),
        "method": ("workflow induction from successful trajectories", "selective workflow retrieval", "offline workflow memory", "online workflow induction", "workflow-conditioned action generation"),
        "benchmarks": ("Mind2Web", "WebArena"),
        "protocol": ("reproduce offline and online AWM separately", "preserve benchmark task/domain splits", "match base-agent/model context", "workflow-memory ablation", "cross-domain workflow reuse analysis"),
        "metrics": ("task success", "step success", "workflow retrieval/use rate", "trajectory length", "token cost", "ablation delta"),
        "baselines": ("base web agent without workflow memory", "paper web-agent baselines", "offline-vs-online AWM"),
        "reported": ("paper evaluates AWM on Mind2Web and WebArena covering 1000+ tasks from 200+ domains",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EnvironmentMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze released AWM code/data revision, Mind2Web/WebArena cuts, website state, prompts and model revisions",),
    },
    {
        "id": "wormi_icml2025",
        "paper": "World Model Implanting for Test-time Adaptation of Embodied Agents",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/yoo25a.html",
        "family": ("embodied", "world-model", "test-time-adaptation", "retrieval"),
        "method": ("domain-specific world-model bank", "trajectory prototype representation", "prototype-based world-model retrieval", "test-time model implantation/removal", "world-wise compound attention", "reasoning/world-model representation alignment"),
        "benchmarks": ("VirtualHome", "ALFWorld"),
        "protocol": ("zero-shot unseen-domain evaluation", "few-shot unseen-domain evaluation", "matched reasoning model", "world-model retrieval ablation", "compound-attention ablation", "implantation/removal study"),
        "metrics": ("task success", "zero-shot adaptation", "few-shot adaptation", "retrieval quality", "ablation delta"),
        "baselines": ("LLM embodied-agent baselines in final paper", "no-implantation control", "retrieval/attention ablations"),
        "reported": ("final ICML paper reports superior zero-shot and few-shot performance across unseen VirtualHome and ALFWorld domains",),
        "noetrium_host": ("MethodProgram", "EnvironmentMachine", "ModelInvocationMachine", "EvaluationMachine", "ExperimentMachine"),
        "execution_blockers": ("freeze world-model checkpoints, trajectory prototypes, VirtualHome/ALFWorld revisions, unseen-domain splits and reasoning-model revision",),
    },
    {
        "id": "embodiedbench_icml2025",
        "paper": "EmbodiedBench: Comprehensive Benchmarking Multi-modal Large Language Models for Vision-Driven Embodied Agents",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/yang25f.html",
        "family": ("embodied", "multimodal", "benchmark", "evaluation"),
        "method": ("vision-driven embodied-agent evaluation", "four-environment task unification", "six-capability subset decomposition", "standardized MLLM action/evaluation interface"),
        "benchmarks": ("EmbodiedBench 1,128-task final test set across four environments",),
        "protocol": ("run all four environments", "report six capability subsets", "preserve action spaces and visual observations", "evaluate proprietary/open MLLMs under matched agent wrapper", "failure-mode analysis"),
        "metrics": ("average task success", "environment success", "capability-subset success", "failure distribution"),
        "baselines": ("24 MLLMs evaluated in final paper", "GPT-4o reference"),
        "reported": ("1,128 testing tasks across four environments", "six capability subsets", "best evaluated model GPT-4o averages 28.9%"),
        "noetrium_host": ("BenchmarkMachine", "EnvironmentMachine", "PerceptionMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze released benchmark/environment revisions, assets, action wrappers, evaluated model revisions and evaluator configuration",),
    },
    {
        "id": "up_vla_icml2025",
        "paper": "UP-VLA: A Unified Understanding and Prediction Model for Embodied Agent",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/zhang25w.html",
        "family": ("embodied", "vision-language-action", "multimodal", "prediction"),
        "method": ("unified VLA training", "multimodal understanding objective", "future prediction objective", "high-level semantic and low-level spatial feature learning", "action generation"),
        "benchmarks": ("CALVIN ABC-D", "paper real-world manipulation suite"),
        "protocol": ("CALVIN ABC-D matched evaluation", "understanding-objective ablation", "prediction-objective ablation", "combined-objective evaluation", "real-world manipulation evaluation"),
        "metrics": ("CALVIN success", "task-chain success", "real-world manipulation success", "objective-ablation delta"),
        "baselines": ("previous VLA state of the art in final paper", "understanding-only/prediction-only ablations"),
        "reported": ("paper reports 33% improvement on CALVIN ABC-D over previous state of the art", "improved real-world manipulation success particularly for spatially precise tasks"),
        "noetrium_host": ("MethodProgram", "PerceptionMachine", "EnvironmentMachine", "ModelInvocationMachine", "EvaluationMachine"),
        "execution_blockers": ("freeze training/checkpoint revision, CALVIN environment/data revision, real-world protocol and action normalization",),
    },
    {
        "id": "pae_icml2025",
        "paper": "Proposer-Agent-Evaluator (PAE): Autonomous Skill Discovery For Foundation Model Internet Agents",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/zhou25ah.html",
        "family": ("web-agent", "skill-discovery", "self-improvement", "multimodal-evaluation"),
        "method": ("context-aware task proposer", "internet-agent practice loop", "autonomous VLM success evaluator", "accepted-skill trajectory accumulation", "iterative skill repertoire expansion"),
        "benchmarks": ("paper internet-agent training websites", "paper held-out internet-agent evaluation"),
        "protocol": ("propose tasks from current website context", "execute tasks in live/snapshotted web environment", "score trajectories with frozen VLM evaluator", "accumulate accepted skills", "compare before/after autonomous practice"),
        "metrics": ("task success", "accepted skill count/diversity", "evaluator agreement", "held-out transfer", "practice efficiency"),
        "baselines": ("foundation agent before PAE practice", "human-instruction/fixed-task training controls", "paper internet-agent baselines"),
        "reported": ("final paper demonstrates autonomous discovery and practice of internet skills without requiring each skill to be manually specified",),
        "noetrium_host": ("ResearchProgram", "EnvironmentMachine", "OptimizationMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze website snapshots or reproducible web state, proposer/agent/evaluator model revisions, acceptance thresholds and practice budgets",),
    },
    {
        "id": "agent_as_judge_icml2025",
        "paper": "Agent-as-a-Judge: Evaluate Agents with Agents",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/zhuge25a.html",
        "family": ("agent-evaluation", "judge-agent", "software-agent", "process-evaluation"),
        "method": ("agentic evaluator", "intermediate trajectory inspection", "tool-enabled evidence gathering", "process-plus-outcome judgment", "structured evaluator feedback"),
        "benchmarks": ("final-paper code-generation agent evaluation suite",),
        "protocol": ("evaluate complete solving trajectories", "compare final-outcome-only and agentic process evaluation", "measure agreement with reference/human judgments", "judge capability ablations"),
        "metrics": ("evaluation agreement", "process-error detection", "final-result assessment", "evaluation cost", "feedback usefulness"),
        "baselines": ("LLM-as-a-Judge", "final-outcome-only evaluation", "human/reference evaluation"),
        "reported": ("paper extends LLM-as-a-Judge with agentic capabilities and intermediate feedback over the full task-solving process",),
        "noetrium_host": ("EvaluationMachine", "CapabilityMachine", "EnvironmentMachine", "MachineJournal", "EvidenceBundle"),
        "execution_blockers": ("freeze code-agent benchmark, judged trajectories, judge model/tool configuration and human/reference labels",),
    },
    {
        "id": "kg_agent_acl2025",
        "paper": "KG-Agent: An Efficient Autonomous Agent Framework for Complex Reasoning over Knowledge Graph",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.468/",
        "family": ("tool-agent", "knowledge-graph", "memory", "reasoning"),
        "method": ("autonomous tool selection", "multifunctional KG toolbox", "KG executor", "knowledge memory update", "iterative multi-hop reasoning", "program-form reasoning traces", "code-based instruction tuning"),
        "benchmarks": ("final-paper in-domain KGQA suite", "final-paper out-of-domain KGQA suite"),
        "protocol": ("fine-tune base LLM with released 10K code-based instruction samples", "run autonomous tool-memory loop", "evaluate in-domain and out-of-domain separately", "tool/memory/training-data ablations"),
        "metrics": ("KGQA accuracy", "in-domain score", "out-of-domain score", "tool-call efficiency", "ablation delta"),
        "baselines": ("larger-LLM KG reasoning methods", "more-data tuning baselines", "tool/memory ablations"),
        "reported": ("paper reports LLaMA2-7B tuned with only 10K samples outperforming competitive methods using larger LLMs or more data on in- and out-of-domain datasets",),
        "noetrium_host": ("MethodProgram", "CapabilityMachine", "MemoryMachine", "EnvironmentMachine", "EvaluationMachine"),
        "execution_blockers": ("freeze released KG snapshots, 10K instruction dataset, executor/tool schemas, checkpoint and exact benchmark splits",),
    },
    {
        "id": "agent_rewardbench_acl2025",
        "paper": "Agent-RewardBench: Towards a Unified Benchmark for Reward Modeling across Perception, Planning, and Safety in Real-World Multimodal Agents",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.857/",
        "family": ("multimodal-agent", "reward-model", "benchmark", "evaluation"),
        "method": ("agent-specific reward-model evaluation", "perception/planning/safety decomposition", "step-level multimodal trajectory judgment", "real-world scenario coverage"),
        "benchmarks": ("Agent-RewardBench final ACL release",),
        "protocol": ("evaluate reward models on perception, planning and safety separately", "preserve real-world agent scenarios", "step-level scoring", "cross-model comparison", "dimension-wise error analysis"),
        "metrics": ("reward-model accuracy", "perception score", "planning score", "safety score", "scenario-wise score", "step-level agreement"),
        "baselines": ("reward MLLMs evaluated in final paper", "general-purpose MLLM judges"),
        "reported": ("final paper introduces unified reward-model evaluation across perception, planning and safety in real-world multimodal-agent scenarios",),
        "noetrium_host": ("BenchmarkMachine", "EvaluationMachine", "PerceptionMachine", "MachineJournal", "EvidenceBundle"),
        "execution_blockers": ("freeze released benchmark revision, multimodal trajectory assets, labels, reward-model revisions and scoring code",),
    },
    {
        "id": "memoryos_emnlp2025",
        "paper": "Memory OS of AI Agent",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.1318/",
        "family": ("memory", "long-term-memory", "hierarchical-memory", "personalization"),
        "method": ("hierarchical memory integration", "dynamic memory updating", "long-conversation memory retention", "contextual memory retrieval", "personalized response conditioning"),
        "benchmarks": ("LoCoMo",),
        "protocol": ("matched LoCoMo split", "GPT-4o-mini evaluation", "baseline memory systems", "hierarchy/update ablations", "long-conversation analysis"),
        "metrics": ("F1", "BLEU-1", "contextual coherence", "personalized memory retention", "ablation delta"),
        "baselines": ("memory baselines in final EMNLP paper", "hierarchy/update ablations"),
        "reported": ("average +48.36% F1 over baselines on GPT-4o-mini", "average +46.18% BLEU-1 over baselines on GPT-4o-mini"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EvaluationMachine", "ExperimentMachine", "MachineJournal"),
        "execution_blockers": ("freeze released MemoryOS revision, LoCoMo cut, prompts, memory-update policy and GPT-4o-mini model snapshot/configuration",),
    },
    {
        "id": "automl_agent_icml2025",
        "paper": "AutoML-Agent: A Multi-Agent LLM Framework for Full-Pipeline AutoML",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/trirat25a.html",
        "family": ("multi-agent", "software-agent", "automl", "tool-use"),
        "method": ("full-pipeline task decomposition", "specialized AutoML agents", "tool-mediated data/model operations", "inter-agent coordination", "pipeline synthesis from natural-language request"),
        "benchmarks": ("final-paper full-pipeline AutoML evaluation suite",),
        "protocol": ("execute complete pipeline from data retrieval through deployment", "compare specialist multi-agent and simpler LLM/AutoML baselines", "component/agent ablations", "measure end-task quality and pipeline cost"),
        "metrics": ("task/model performance", "pipeline completion", "human-effort reduction", "tool/agent cost", "ablation delta"),
        "baselines": ("traditional AutoML systems in final paper", "single/general LLM controls", "multi-agent component ablations"),
        "reported": ("final ICML paper evaluates an LLM multi-agent framework spanning the full AutoML pipeline from data retrieval to model deployment",),
        "noetrium_host": ("ResearchProgram", "ParticipantMachine", "CommunicationMachine", "CapabilityMachine", "EnvironmentMachine", "EvaluationMachine"),
        "execution_blockers": ("freeze datasets/tasks, external AutoML tools, execution images, agent prompts/models, resource budgets and deployment target",),
    },
)


def by_id() -> dict[str, dict[str, object]]:
    return {str(item["id"]): item for item in FRONTIER_2025_WAVE_04}
