"""Second 2025 frontier reproduction wave.

Paper-private semantics stay downstream. Entries freeze method semantics, benchmark
cuts, experiment protocol, metrics, baselines, reported results, platform hosting
boundaries, and the remaining requirements for matched execution.
"""
from __future__ import annotations

FRONTIER_2025_WAVE_02 = (
    {
        "id": "vistawise_emnlp2025",
        "paper": "VistaWise: Building Cost-Effective Agent with Cross-Modal Knowledge Graph for Minecraft",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.1111/",
        "family": ("minecraft", "embodied", "multimodal-memory", "knowledge-graph"),
        "method": ("cross-modal knowledge graph", "visual object detector", "visual-textual dependency integration", "knowledge-grounded action selection"),
        "benchmarks": ("Minecraft embodied tasks used by the final paper",),
        "protocol": ("final-paper Minecraft task cut", "few-hundred-sample detector training regime", "cross-modal KG ablation", "matched action/model budget"),
        "metrics": ("task success rate", "development/training data cost", "visual recognition quality", "KG contribution"),
        "baselines": ("paper Minecraft agents using large-scale domain-specific training", "knowledge/multimodal ablations"),
        "reported": ("reduces domain-specific training-data requirement from millions of samples to a few hundred",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "PerceptionMachine", "EnvironmentMachine", "MachineJournal"),
        "execution_blockers": ("freeze final Minecraft runtime/task assets, detector data/checkpoint, model identities and KG construction inputs",),
    },
    {
        "id": "metagent_p_acl2025",
        "paper": "Metagent-P: A Neuro-Symbolic Planning Agent with Metacognition for Open Worlds",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.1169/",
        "family": ("minecraft", "planning", "multimodal-memory", "reflection", "neuro-symbolic"),
        "method": ("planning-verification-execution-reflection loop", "multimodal memory integration", "neural-symbolic hierarchical plan representation", "metacognitive monitoring/evaluation/regulation", "open-world self-evolution"),
        "benchmarks": ("Minecraft open-world tasks from the final paper",),
        "protocol": ("paper long-horizon task cut", "matched planner/model configuration", "replanning accounting", "memory/metacognition ablations", "step-by-step exploration study"),
        "metrics": ("task success rate", "average replanning count", "human-relative success", "exploration progress"),
        "baselines": ("paper open-world Minecraft agents", "human performance", "component ablations"),
        "reported": ("34% reduction in average replanning count on long-term tasks", "18.96% above average human success rate"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EvaluationMachine", "EnvironmentMachine", "MachineJournal"),
        "execution_blockers": ("freeze exact Minecraft task/world cut, multimodal observations, model services and paper planner prompts",),
    },
    {
        "id": "cfgm_emnlp2025",
        "paper": "Coarse-to-Fine Grounded Memory for LLM Agent Planning",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.659/",
        "family": ("memory", "planning", "experience-learning"),
        "method": ("coarse environmental focus-point grounding", "experience collection guided by focus points", "hybrid-grained actionable tip grounding", "coarse-to-fine memory retrieval", "memory-conditioned planning"),
        "benchmarks": ("final-paper planning benchmark suite",),
        "protocol": ("paper training/test task split", "offline/online experience construction cut", "memory granularity ablations", "matched model and interaction budgets"),
        "metrics": ("task success", "planning performance", "memory retrieval utility", "cross-scenario adaptation"),
        "baselines": ("single-granularity memory agents", "paper planning-agent baselines", "memory ablations"),
        "reported": ("final paper reports consistent gains from grounded coarse-to-fine memories across diverse planning scenarios",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EnvironmentMachine", "EvaluationMachine"),
        "execution_blockers": ("transcribe final table values and freeze exact benchmark instances, experience corpus, prompts and model revisions",),
    },
    {
        "id": "meminsight_emnlp2025",
        "paper": "MemInsight: Autonomous Memory Augmentation for LLM Agents",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.1683/",
        "family": ("memory", "long-term-memory", "retrieval", "autonomous-augmentation"),
        "method": ("autonomous augmentation of historical interactions", "semantic memory representation", "augmented memory retrieval", "task-conditioned contextual response generation"),
        "benchmarks": ("LLM-REDIAL", "LoCoMo", "paper event-summarization task"),
        "protocol": ("paper conversational-recommendation evaluation", "paper QA/retrieval evaluation", "event-summarization evaluation", "RAG and augmentation ablations"),
        "metrics": ("recommendation persuasiveness", "retrieval recall", "QA/contextual quality", "event summarization quality"),
        "baselines": ("RAG baseline", "paper memory-agent baselines", "augmentation ablations"),
        "reported": ("up to 14% persuasiveness gain on LLM-REDIAL", "34% recall improvement over RAG on LoCoMo retrieval"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EvaluationMachine", "ExperimentMachine"),
        "execution_blockers": ("freeze LLM-REDIAL/LoCoMo cuts, summarization data, evaluator prompts and model revisions",),
    },
    {
        "id": "hiagent_acl2025",
        "paper": "HiAgent: Hierarchical Working Memory Management for Solving Long-Horizon Agent Tasks with Large Language Model",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.1575/",
        "family": ("memory", "working-memory", "long-horizon", "planning"),
        "method": ("hierarchical working-memory organization", "in-trial action-observation history compression", "subgoal-aligned memory management", "memory-conditioned long-horizon action generation"),
        "benchmarks": ("final-paper long-horizon agent benchmark suite",),
        "protocol": ("paper task splits", "matched interaction/context budgets", "full-history versus hierarchical-memory comparison", "memory ablations"),
        "metrics": ("task success", "long-horizon progress", "context/token efficiency", "memory ablation delta"),
        "baselines": ("full action-observation history agents", "paper memory baselines", "hierarchy ablations"),
        "reported": ("final ACL study reports hierarchical working-memory gains on long-horizon tasks",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "ContextMachine", "EnvironmentMachine"),
        "execution_blockers": ("transcribe final result tables and freeze benchmark cuts, context limits, prompts and model revisions",),
    },
    {
        "id": "openwebvoyager_acl2025",
        "paper": "OpenWebVoyager: Building Multimodal Web Agents via Iterative Real-World Exploration, Feedback and Optimization",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.1336/",
        "family": ("web-agent", "multimodal", "self-improvement", "exploration"),
        "method": ("imitation-learned base policy", "real-world web exploration", "feedback acquisition", "iterative trajectory optimization", "multimodal action policy improvement"),
        "benchmarks": ("final-paper real-world web-navigation evaluation suite",),
        "protocol": ("paper imitation-data cut", "iterative exploration rounds", "feedback/optimization loop", "matched website/task snapshots", "component ablations"),
        "metrics": ("task success rate", "iteration improvement", "trajectory/action quality", "generalization"),
        "baselines": ("paper multimodal web agents", "base imitation policy", "exploration/feedback ablations"),
        "reported": ("final ACL paper reports iterative real-world exploration and feedback improve the multimodal web agent",),
        "noetrium_host": ("MethodProgram", "PerceptionMachine", "EnvironmentMachine", "OptimizationMachine", "MachineJournal"),
        "execution_blockers": ("freeze website/task snapshots, imitation corpus, feedback model, browser runtime and model revisions",),
    },
    {
        "id": "webexpert_acl2025",
        "paper": "Browsing Like Human: A Multimodal Web Agent with Experiential Fast-and-Slow Thinking",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.697/",
        "family": ("web-agent", "multimodal", "planning", "reflection", "experience-memory"),
        "method": ("fast-and-slow instruction decomposition", "multimodal web perception", "experiential failure reflection", "experience-conditioned replanning", "continuous planning refinement"),
        "benchmarks": ("final-paper web-navigation benchmark suite",),
        "protocol": ("paper website/task cut", "fast/slow planning comparison", "experience accumulation protocol", "reflection and memory ablations", "matched action budget"),
        "metrics": ("task success rate", "navigation efficiency", "experience/reflection gain", "planning quality"),
        "baselines": ("paper multimodal web-agent baselines", "fast/slow and experiential-learning ablations"),
        "reported": ("final ACL study reports gains from experiential fast-and-slow planning over prior multimodal web agents",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "PerceptionMachine", "EnvironmentMachine"),
        "execution_blockers": ("transcribe final result tables and freeze website state, benchmark cut, prompts and model revisions",),
    },
    {
        "id": "adaptagent_acl2025",
        "paper": "AdaptAgent: Adapting Multimodal Web Agents with Few-Shot Learning from Human Demonstrations",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.1008/",
        "family": ("web-agent", "multimodal", "few-shot-adaptation", "demonstration-memory"),
        "method": ("few-shot human-demonstration ingestion", "demonstration-conditioned adaptation", "multimodal GUI perception", "cross-website/domain transfer"),
        "benchmarks": ("unseen websites/domains from the final paper",),
        "protocol": ("zero-shot versus up-to-two-demonstration comparison", "proprietary/open-weight agent comparison", "cross-domain adaptation", "matched GUI/action budgets"),
        "metrics": ("task success rate", "few-shot adaptation gain", "cross-domain generalization", "demonstration efficiency"),
        "baselines": ("zero-shot multimodal web agents", "paper prompting/fine-tuning baselines"),
        "reported": ("paper demonstrates adaptation to unseen websites/domains using at most two human demonstrations",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "PerceptionMachine", "EnvironmentMachine", "ExperimentMachine"),
        "execution_blockers": ("freeze final unseen-site task set, demonstrations, browser/application versions and model revisions",),
    },
    {
        "id": "plangen_emnlp2025",
        "paper": "PlanGEN: A Multi-Agent Framework for Generating Planning and Reasoning Trajectories for Complex Problem Solving",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.1042/",
        "family": ("multi-agent", "planning", "search", "verification", "routing"),
        "method": ("constraint agent", "iterative verification agent", "selection agent", "instance-complexity-conditioned inference algorithm selection", "Best-of-N/Tree-of-Thought/REBASE integration"),
        "benchmarks": ("NATURAL PLAN", "OlympiadBench", "DocFinQA", "GPQA"),
        "protocol": ("paper benchmark cuts", "constraint-guided verification", "adaptive algorithm selection", "fixed-algorithm and verification ablations", "matched model budgets"),
        "metrics": ("benchmark accuracy", "planning validity", "verification gain", "adaptive-selection gain"),
        "baselines": ("strongest paper baseline", "Best-of-N", "Tree-of-Thought", "REBASE", "component ablations"),
        "reported": ("approximately +8% on NATURAL PLAN", "approximately +4% on OlympiadBench", "approximately +7% on DocFinQA", "approximately +1% on GPQA over strongest baseline"),
        "noetrium_host": ("MethodProgram", "ParticipantMachine", "OptimizationMachine", "EvaluationMachine", "LogicalSchedulingMachine"),
        "execution_blockers": ("freeze exact benchmark versions, inference algorithms, prompts, verifier/selector models and compute budgets",),
    },
    {
        "id": "anymac_emnlp2025",
        "paper": "AnyMAC: Cascading Flexible Multi-Agent Collaboration via Next-Agent Prediction",
        "venue": "EMNLP 2025",
        "paper_uri": "https://aclanthology.org/2025.emnlp-main.584/",
        "family": ("multi-agent", "dynamic-topology", "communication", "routing"),
        "method": ("sequential collaboration topology", "next-agent prediction", "next-context selection", "dynamic role routing", "selective access to prior-step context"),
        "benchmarks": ("final-paper multi-agent benchmark suite",),
        "protocol": ("paper role pools", "dynamic versus static/graph topology comparison", "next-agent and next-context ablations", "matched model/token budgets"),
        "metrics": ("task performance", "communication efficiency", "token/context cost", "routing contribution"),
        "baselines": ("static multi-agent topologies", "graph-based collaboration methods", "routing/context-selection ablations"),
        "reported": ("final EMNLP study reports improved flexible collaboration from next-agent prediction and selective context access",),
        "noetrium_host": ("MethodProgram", "ParticipantMachine", "CommunicationMachine", "LogicalSchedulingMachine", "MetricsMachine"),
        "execution_blockers": ("transcribe final table values and freeze benchmark instances, role definitions, prompts, models and token accounting",),
    },
)

BY_ID = {entry["id"]: entry for entry in FRONTIER_2025_WAVE_02}

__all__ = ["FRONTIER_2025_WAVE_02", "BY_ID"]
