"""Frontier 2025 reproduction wave: paper-authoritative execution specifications.

This module is intentionally downstream research data, not kernel policy.  Each entry
freezes the paper method semantics, benchmark cut, experiment protocol, metrics,
reported results/baselines, and the Noetrium systems that should host the semantics.
Paper-private concepts remain here; benchmark/environment bindings may use adapters.
"""
from __future__ import annotations

FRONTIER_2025_WAVE_01 = (
    {
        "id": "mrsteve_iclr2025",
        "paper": "MrSteve: Instruction-Following Agents in Minecraft with What-Where-When Memory",
        "venue": "ICLR 2025",
        "paper_uri": "https://openreview.net/forum?id=6O4Z4P2yP7",
        "family": ("minecraft", "embodied", "episodic-memory"),
        "method": ("hierarchical instruction following", "Place Event Memory (PEM)", "what-where-when event storage", "memory-conditioned low-level control"),
        "benchmarks": ("Minecraft instruction-following tasks from the paper",),
        "protocol": ("paper task split", "paper controller/checkpoint cut", "episodic-memory ablation", "matched episode budget"),
        "metrics": ("task success rate", "low-level controller success", "memory retrieval contribution"),
        "baselines": ("Steve-1-family controller without PEM", "paper hierarchical baselines"),
        "reported": ("PEM improves instruction-following by recalling task-relevant what/where/when events",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EnvironmentMachine", "MachineJournal"),
        "execution_blockers": ("paper-era Minecraft runtime/checkpoints and task assets must be content-addressed",),
    },
    {
        "id": "m2pa_acl2025",
        "paper": "M2PA: A Multi-Memory Planning Agent for Open Worlds Inspired by Cognitive Theory",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.1191/",
        "family": ("minecraft", "planning", "multi-memory", "lifelong-learning"),
        "method": ("LLM planner", "multi-memory system", "situation awareness", "experience generalization", "lifelong memory update"),
        "benchmarks": ("50 Minecraft zero-shot tasks", "ObtainDiamond lifelong-learning task"),
        "protocol": ("zero-shot 50-task evaluation", "exploratory lifelong-learning evaluation", "paper memory configuration"),
        "metrics": ("task success rate", "ObtainDiamond success rate"),
        "baselines": ("paper open-world planning agents",),
        "reported": ("38.33% ObtainDiamond lifelong-learning success rate", "significant gains across 50 zero-shot Minecraft tasks"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EnvironmentMachine", "ExperimentMachine"),
        "execution_blockers": ("exact Minecraft task/world cut and model-service behavior must be frozen",),
    },
    {
        "id": "mcdml_iclr2025",
        "paper": "MC-DML: Monte Carlo Dynamic Memory Learning for Language Agents",
        "venue": "ICLR 2025",
        "family": ("search", "planning", "memory", "interactive-fiction"),
        "method": ("Monte-Carlo tree search", "in-trial dynamic memory", "cross-trial memory", "experience-backed action selection"),
        "benchmarks": ("Jericho interactive-fiction games used by the paper",),
        "protocol": ("paper game set", "paper interaction budget", "cross-trial carryover", "memory/search ablations"),
        "metrics": ("normalized game score", "success/progress", "sample efficiency"),
        "baselines": ("paper Jericho language-agent baselines", "memory ablations", "search ablations"),
        "reported": ("paper table results must be transcribed from the final ICLR artifact before claim matching",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "OptimizationMachine", "EnvironmentMachine"),
        "execution_blockers": ("freeze final-paper Jericho game subset and exact model configuration",),
    },
    {
        "id": "aop_iclr2025",
        "paper": "Agent-Oriented Planning in Multi-Agent Systems",
        "venue": "ICLR 2025",
        "paper_uri": "https://proceedings.iclr.cc/paper_files/paper/2025/hash/31610e68fe41a62e460e044216a10766-Abstract-Conference.html",
        "family": ("multi-agent", "planning", "routing"),
        "method": ("fast task decomposition", "agent allocation", "reward-model evaluation", "subtask adjustment", "feedback loop", "solvability/completeness/non-redundancy objectives"),
        "benchmarks": ("real-world problem suites reported by the paper",),
        "protocol": ("paper agent pool", "paper decomposition/allocation settings", "single-agent and planning-strategy comparisons", "principle ablations"),
        "metrics": ("task performance", "planning quality", "efficiency"),
        "baselines": ("single-agent systems", "existing multi-agent planning strategies"),
        "reported": ("AOP outperforms single-agent and prior multi-agent planning strategies in the final ICLR study",),
        "noetrium_host": ("MethodProgram", "ParticipantMachine", "CommunicationMachine", "EvaluationMachine"),
        "execution_blockers": ("freeze exact benchmark instances, reward model and agent/model identities",),
    },
    {
        "id": "agentdropout_acl2025",
        "paper": "AgentDropout: Dynamic Agent Elimination for Token-Efficient and High-Performance LLM-Based Multi-Agent Collaboration",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.1170/",
        "family": ("multi-agent", "communication", "topology-optimization"),
        "method": ("round-wise communication graph", "adjacency-matrix optimization", "redundant-agent elimination", "redundant-edge elimination"),
        "benchmarks": ("paper multi-agent task suite",),
        "protocol": ("paper communication rounds", "token accounting", "domain-transfer experiments", "structure-robustness experiments"),
        "metrics": ("task score", "prompt tokens", "completion tokens", "transfer robustness"),
        "baselines": ("paper SOTA multi-agent collaboration methods",),
        "reported": ("21.6% average prompt-token reduction", "18.4% average completion-token reduction", "+1.14 task-performance improvement"),
        "noetrium_host": ("CommunicationMachine", "ParticipantMachine", "OptimizationMachine", "MetricsMachine"),
        "execution_blockers": ("freeze paper model/API versions and all benchmark-specific graph initializations",),
    },
    {
        "id": "infantagent_next_neurips2025",
        "paper": "InfantAgent-Next: A Multimodal Generalist Agent for Automated Computer Interaction",
        "venue": "NeurIPS 2025",
        "paper_uri": "https://neurips.cc/virtual/2025/poster/118379",
        "family": ("computer-use", "multimodal", "software-agent"),
        "method": ("modular multimodal agent", "tool-based agent", "pure-vision agent", "model collaboration over decoupled subtasks"),
        "benchmarks": ("OSWorld", "GAIA", "SWE-bench"),
        "protocol": ("paper benchmark cuts", "paper model routing", "vision/tool modality comparisons", "matched action budgets"),
        "metrics": ("OSWorld success rate", "GAIA accuracy", "SWE-bench resolved rate"),
        "baselines": ("Claude Computer Use", "paper computer-use/generalist baselines"),
        "reported": ("7.27 percentage-point accuracy gain over Claude Computer Use on OSWorld",),
        "noetrium_host": ("MethodProgram", "ModelInvocationMachine", "CapabilityMachine", "EnvironmentMachine"),
        "execution_blockers": ("OSWorld VM image, proprietary model revisions and supplementary evaluation scripts must be frozen",),
    },
    {
        "id": "affordbot_neurips2025",
        "paper": "AffordBot: 3D Fine-grained Embodied Reasoning via Multimodal Large Language Models",
        "venue": "NeurIPS 2025",
        "paper_uri": "https://proceedings.neurips.cc/paper_files/paper/2025/hash/cd51b67dcb19db4e9f0022f500076b00-Abstract-Conference.html",
        "family": ("embodied", "3d", "multimodal-reasoning"),
        "method": ("surround-view rendering", "3D candidate projection", "active viewpoint selection", "instruction-conditioned chain-of-thought", "location/motion-type/motion-axis prediction"),
        "benchmarks": ("SceneFun3D",),
        "protocol": ("paper SceneFun3D split", "point-cloud-only input", "active-perception and reasoning ablations"),
        "metrics": ("fine-grained affordance localization", "motion-type accuracy", "motion-axis accuracy", "paper aggregate score"),
        "baselines": ("paper 3D affordance and MLLM baselines",),
        "reported": ("paper reports state-of-the-art SceneFun3D performance",),
        "noetrium_host": ("MethodProgram", "PerceptionMachine", "ModelInvocationMachine", "EvaluationMachine"),
        "execution_blockers": ("SceneFun3D data/version and paper MLLM/checkpoint identities must be frozen",),
    },
    {
        "id": "megaagent_acl2025",
        "paper": "MegaAgent: A Large-Scale Autonomous LLM-based Multi-Agent System Without Predefined SOPs",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.259/",
        "family": ("multi-agent", "dynamic-topology", "parallel-execution"),
        "method": ("task-complexity-conditioned agent generation", "dynamic task decomposition", "parallel execution", "communication", "system monitoring", "no predefined SOP"),
        "benchmarks": ("Gobang software-development task", "national-policy simulation"),
        "protocol": ("paper task prompts", "wall-clock efficiency study", "large-scale agent-count scaling study", "MetaGPT comparison"),
        "metrics": ("task completion", "wall-clock time", "agent scalability", "quality"),
        "baselines": ("MetaGPT", "paper MAS baselines"),
        "reported": ("Gobang completed within 800 seconds", "policy simulation scales to 590 agents"),
        "noetrium_host": ("ParticipantMachine", "CommunicationMachine", "LogicalSchedulingMachine", "MethodProgram"),
        "execution_blockers": ("paper model endpoints and compute/concurrency environment must be frozen for timing claims",),
    },
    {
        "id": "crab_acl2025",
        "paper": "CRAB: Cross-environment Agent Benchmark for Multimodal Language Model Agents",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.1113/",
        "family": ("benchmark", "computer-use", "multimodal", "cross-environment"),
        "method": ("cross-device task graph", "desktop/mobile environment abstraction", "single- and multi-agent configurations"),
        "benchmarks": ("CRAB Benchmark-v0: 120 desktop/mobile tasks",),
        "protocol": ("120-task v0 cut", "six advanced MLMs", "single-vs-multi-agent configurations", "paper device environments"),
        "metrics": ("completion ratio", "subtask completion", "cross-environment performance"),
        "baselines": ("six paper MLM configurations",),
        "reported": ("GPT-4o single-agent completion ratio 38.01%",),
        "noetrium_host": ("BenchmarkMachine", "EnvironmentMachine", "ParticipantMachine", "EvaluationMachine"),
        "execution_blockers": ("paper desktop/mobile images and application versions must be reproduced",),
    },
    {
        "id": "agent_s2_colm2025",
        "paper": "Agent S2: A Compositional Generalist-Specialist Framework for Computer Use Agents",
        "venue": "COLM 2025",
        "paper_uri": "https://arxiv.org/abs/2504.00906",
        "family": ("computer-use", "multimodal", "planning", "grounding"),
        "method": ("Mixture-of-Grounding", "generalist/specialist model composition", "Proactive Hierarchical Planning", "multi-timescale plan refinement"),
        "benchmarks": ("OSWorld 15-step", "OSWorld 50-step", "WindowsAgentArena", "AndroidWorld"),
        "protocol": ("screenshot-only OSWorld", "15/50-step budgets", "cross-platform evaluation", "MoG/PHP ablations"),
        "metrics": ("task success rate", "relative improvement", "grounding/planning ablation delta"),
        "baselines": ("UI-TARS", "Claude Computer Use", "OpenAI CUA", "NAVI"),
        "reported": ("OSWorld-15 27.0%", "OSWorld-50 34.5%", "WindowsAgentArena 29.8%", "AndroidWorld 54.3%"),
        "noetrium_host": ("MethodProgram", "ModelInvocationMachine", "PerceptionMachine", "EnvironmentMachine"),
        "execution_blockers": ("freeze COLM paper cut, GUI environment images and proprietary model revisions",),
    },
)

BY_ID = {entry["id"]: entry for entry in FRONTIER_2025_WAVE_01}

__all__ = ["FRONTIER_2025_WAVE_01", "BY_ID"]
