"""Third 2025 frontier reproduction wave.

Paper-private semantics remain downstream. This campaign freezes method semantics,
benchmark/environment cuts, experiment protocols, metrics, baselines, reported
results and the remaining matched-execution requirements for ten recent published
agent papers/benchmarks.
"""
from __future__ import annotations

FRONTIER_2025_WAVE_03 = (
    {
        "id": "membench_acl2025",
        "paper": "MemBench: Towards More Comprehensive Evaluation on the Memory of LLM-based Agents",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.989/",
        "family": ("memory", "benchmark", "evaluation"),
        "method": ("factual-memory evaluation", "reflective-memory evaluation", "participation scenario", "observation scenario", "effectiveness-efficiency-capacity decomposition"),
        "benchmarks": ("MemBench final ACL dataset",),
        "protocol": ("evaluate factual and reflective memory separately", "run participation and observation settings", "matched model/context budgets", "report effectiveness, efficiency and capacity"),
        "metrics": ("memory effectiveness", "memory efficiency", "memory capacity"),
        "baselines": ("memory-agent systems evaluated in the final paper", "no/limited-memory controls"),
        "reported": ("final ACL paper establishes a multi-level, multi-scenario benchmark rather than a single retrieval score",),
        "noetrium_host": ("BenchmarkMachine", "MemoryMachine", "EvaluationMachine", "ExperimentMachine", "MachineJournal"),
        "execution_blockers": ("freeze released dataset revision, evaluated agent/model revisions and evaluator configuration",),
    },
    {
        "id": "tremu_acl2025",
        "paper": "TReMu: Towards Neuro-Symbolic Temporal Reasoning for LLM-Agents with Memory in Multi-Session Dialogues",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.972/",
        "family": ("memory", "temporal-reasoning", "neuro-symbolic", "dialogue"),
        "method": ("multi-session memory extraction", "symbolic temporal representation", "neuro-symbolic temporal reasoning", "memory-conditioned answer generation"),
        "benchmarks": ("TReMu final multi-session temporal-reasoning benchmark",),
        "protocol": ("final benchmark split", "standard prompting baseline", "matched base model", "component ablations", "multi-session memory evaluation"),
        "metrics": ("temporal reasoning score", "answer accuracy", "component ablation delta"),
        "baselines": ("GPT-4o standard prompting", "paper temporal/memory baselines"),
        "reported": ("GPT-4o standard prompting 29.83", "TReMu approach 77.67"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EvaluationMachine", "ExperimentMachine"),
        "execution_blockers": ("freeze final benchmark files, symbolic transformation rules, prompts and exact model revision",),
    },
    {
        "id": "r2d2_acl2025",
        "paper": "R2D2: Remembering, Replaying and Dynamic Decision Making with a Reflective Agentic Memory",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.1464/",
        "family": ("web-agent", "memory", "reflection", "experience-replay"),
        "method": ("reflective agentic memory", "experience remembering", "experience replay", "dynamic decision making", "memory-enhanced navigation"),
        "benchmarks": ("WebArena",),
        "protocol": ("final-paper WebArena task cut", "matched web environment and model", "navigation-error accounting", "memory/replay ablations"),
        "metrics": ("task completion", "navigation error rate", "memory ablation delta"),
        "baselines": ("paper WebArena baselines", "memory/replay ablations"),
        "reported": ("50% reduction in navigation errors", "threefold increase in task completion rates"),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "EnvironmentMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze WebArena revision/site state, model identity, prompts and replay-memory initialization",),
    },
    {
        "id": "reflectool_acl2025",
        "paper": "ReflecTool: Towards Reflection-Aware Tool-Augmented Clinical Agents",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.663/",
        "family": ("tool-agent", "reflection", "memory", "clinical"),
        "method": ("tool-augmented clinical reasoning", "successful-process memory", "tool-wise experience memory", "reflection-aware optimization", "two-stage experience use"),
        "benchmarks": ("ClinicalAgent Bench (CAB), 18 tasks across five clinical dimensions",),
        "protocol": ("CAB final task cut", "tiny predefined training set for experience accumulation", "tool/memory/reflection ablations", "matched clinical tool interfaces"),
        "metrics": ("task performance", "tool-use quality", "cross-scenario generalization", "memory/reflection contribution"),
        "baselines": ("paper clinical-agent baselines", "tool-only and memory/reflection ablations"),
        "reported": ("final ACL paper evaluates holistic clinical-agent performance across 18 CAB tasks and five dimensions",),
        "noetrium_host": ("MethodProgram", "CapabilityMachine", "MemoryMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze CAB assets, clinical tools, training examples, evaluator and model revisions",),
    },
    {
        "id": "agentrm_acl2025",
        "paper": "AgentRM: Enhancing Agent Generalization with Reward Modeling",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.945/",
        "family": ("reward-model", "generalization", "test-time-scaling", "agent-evaluation"),
        "method": ("agent reward modeling", "cross-task reward generalization", "weak-to-strong policy improvement", "test-time candidate scoring/scaling"),
        "benchmarks": ("nine-task generalization suite from the final paper", "three held-in specialization tasks"),
        "protocol": ("cross-task generalization evaluation", "held-in specialization evaluation", "weak-to-strong study", "test-time scaling study", "matched policy candidates"),
        "metrics": ("task score", "average point improvement", "specialization improvement", "test-time scaling curve"),
        "baselines": ("base policy agents", "specialized agents", "paper reward/scoring baselines"),
        "reported": ("paper reports generalization improvements across nine tasks", "finetuned policy exceeds the top specialized agent by 11.4 points on three held-in tasks"),
        "noetrium_host": ("EvaluationMachine", "OptimizationMachine", "ResearchProgram", "ExperimentMachine", "MachineJournal"),
        "execution_blockers": ("freeze released AgentRM checkpoint/data, nine-task benchmark cuts, policy models and sampling budgets",),
    },
    {
        "id": "metaagent_icml2025",
        "paper": "MetaAgent: Automatically Constructing Multi-Agent Systems Based on Finite State Machines",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/zhang25bc.html",
        "family": ("multi-agent", "architecture-search", "finite-state-machine", "optimization"),
        "method": ("task-conditioned MAS synthesis", "finite-state-machine controller", "agent/action/state-transition generation", "iterative MAS polishing/optimization", "tool-aware generated systems"),
        "benchmarks": ("final ICML multi-agent benchmark suite",),
        "protocol": ("generate MAS from task description", "optimize generated FSM", "deploy under FSM control", "compare with human-designed and automated-design baselines", "tool-integration study"),
        "metrics": ("task performance", "construction quality", "tool-use performance", "optimization gain", "cost"),
        "baselines": ("human-designed MAS frameworks", "automated agent-design baselines", "unoptimized generated FSM"),
        "reported": ("final ICML study reports competitive automatically generated multi-agent systems without requiring external training data",),
        "noetrium_host": ("MethodProgram", "ParticipantMachine", "CommunicationMachine", "OptimizationMachine", "ResearchProgram"),
        "execution_blockers": ("transcribe final benchmark/result tables and freeze generation prompts, optimizer, tools and model revisions",),
    },
    {
        "id": "kabb_icml2025",
        "paper": "KABB: Knowledge-Aware Bayesian Bandits for Dynamic Expert Coordination in Multi-Agent Systems",
        "venue": "ICML 2025",
        "paper_uri": "https://proceedings.mlr.press/v267/zhang25aa.html",
        "family": ("multi-agent", "coordination", "bandit", "expert-routing"),
        "method": ("knowledge-distance modeling", "dual adaptation", "knowledge-aware Thompson sampling", "dynamic expert selection"),
        "benchmarks": ("final ICML expert-coordination benchmark suite",),
        "protocol": ("matched expert pools", "dynamic coordination evaluation", "cost-performance comparison", "knowledge-distance/dual-adaptation/Thompson-sampling ablations"),
        "metrics": ("task performance", "coordination cost", "token/compute demand", "cost-performance tradeoff"),
        "baselines": ("static expert coordination", "paper routing/selection baselines", "component ablations"),
        "reported": ("final ICML study reports high performance with relatively low computational demand and improved cost-performance balance",),
        "noetrium_host": ("MethodProgram", "ParticipantMachine", "CommunicationMachine", "OptimizationMachine", "EvaluationMachine"),
        "execution_blockers": ("transcribe final tables and freeze expert/model pool, knowledge encoder, priors and evaluation budgets",),
    },
    {
        "id": "idea_acl2025",
        "paper": "IDEA: Enhancing the Rule Learning Ability of Large Language Model Agent through Induction, Deduction, and Abduction",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.698/",
        "family": ("reasoning", "interactive-agent", "rule-learning", "planning"),
        "method": ("abductive hypothesis generation", "deductive hypothesis testing/planning", "inductive hypothesis refinement", "dynamic rule establishment and application"),
        "benchmarks": ("RULEARN",),
        "protocol": ("interactive environment exploration", "observation collection", "rule induction/evaluation", "induction-deduction-abduction ablations", "matched interaction budget"),
        "metrics": ("rule-learning performance", "task success", "sample/interaction efficiency", "reasoning-component contribution"),
        "baselines": ("standard LLM-agent reasoning baselines", "individual reasoning-mode ablations"),
        "reported": ("final ACL study introduces RULEARN and reports gains from jointly integrating induction, deduction and abduction",),
        "noetrium_host": ("MethodProgram", "EnvironmentMachine", "EvaluationMachine", "MachineJournal"),
        "execution_blockers": ("freeze RULEARN release, environment simulator, prompts, model revisions and interaction limits",),
    },
    {
        "id": "x_webagentbench_acl2025",
        "paper": "X-WebAgentBench: A Multilingual Interactive Web Benchmark for Evaluating Global Agentic System",
        "venue": "ACL 2025 Findings",
        "paper_uri": "https://aclanthology.org/2025.findings-acl.988/",
        "family": ("web-agent", "multilingual", "benchmark", "cross-lingual"),
        "method": ("multilingual interactive web evaluation", "cross-lingual alignment evaluation", "language-conditioned agent assessment"),
        "benchmarks": ("X-WebAgentBench final release",),
        "protocol": ("final multilingual task/language cut", "evaluate multiple LLM agents", "cross-lingual alignment variants", "matched web state and action budget"),
        "metrics": ("task success", "language-wise success", "cross-lingual transfer gain", "failure distribution"),
        "baselines": ("GPT-4o", "paper LLM-agent baselines", "cross-lingual alignment methods"),
        "reported": ("final paper finds even GPT-4o with cross-lingual techniques remains unsatisfactory on the multilingual interactive benchmark",),
        "noetrium_host": ("BenchmarkMachine", "EnvironmentMachine", "EvaluationMachine", "ExperimentMachine"),
        "execution_blockers": ("freeze benchmark release, website state, language/task cut, alignment prompts and model revisions",),
    },
    {
        "id": "reflective_personal_memory_acl2025",
        "paper": "In Prospect and Retrospect: Reflective Memory Management for Long-term Personalized Dialogue Agents",
        "venue": "ACL 2025",
        "paper_uri": "https://aclanthology.org/2025.acl-long.413/",
        "family": ("memory", "personalization", "reflection", "long-term-dialogue"),
        "method": ("prospective memory management", "retrospective reflection", "long-term personalized memory maintenance", "memory-conditioned response generation"),
        "benchmarks": ("final-paper long-term personalized dialogue benchmark suite",),
        "protocol": ("long-term multi-session dialogue evaluation", "personalization evaluation", "prospect/retrospect component ablations", "matched base model/context budget"),
        "metrics": ("personalization quality", "memory consistency", "dialogue quality", "long-term retention", "ablation delta"),
        "baselines": ("paper long-term-memory dialogue agents", "retrieval-only memory", "prospect/retrospect ablations"),
        "reported": ("final ACL paper reports improved long-term personalized dialogue from joint prospective and retrospective memory management",),
        "noetrium_host": ("MethodProgram", "MemoryMachine", "ContextMachine", "EvaluationMachine"),
        "execution_blockers": ("transcribe final tables and freeze dialogue datasets, evaluator prompts, memory initialization and model revisions",),
    },
)

FRONTIER_2025_WAVE_03_IDS = tuple(item["id"] for item in FRONTIER_2025_WAVE_03)
