from __future__ import annotations

from typing import Protocol
from noetrium_platform.infrastructure.lifecycle.service.api.ports import ExactServiceRuntimePort, ServiceStartOutcome, ServiceStopOutcome
from noetrium_platform.infrastructure.lifecycle.service.api.contracts import ServiceLaunchContract
from noetrium_platform.infrastructure.resources.compute.api import GpuDeviceStatus, GpuRuntimeSnapshot
from .contracts import (
    ModelControlSnapshot, ModelControllerState, ModelDeploymentLogs, ModelDeploymentSelector,
    ModelDeploymentSpec, ModelDeploymentStatus, ModelDesiredState, ModelEnvironmentUsage,
    ModelGpuAllocation, ModelGpuConflict, ModelGpuProcessBinding, ModelLogTail,
)

class ModelServiceRuntimeFactoryPort(Protocol):
    def open(self, contract: ServiceLaunchContract, *, environment: tuple[tuple[str, str], ...], readiness_url: str | None) -> ExactServiceRuntimePort: ...
    def logs(self, contract: ServiceLaunchContract, *, deployment_id: str) -> ModelDeploymentLogs: ...

class ModelDeploymentCatalogPort(Protocol):
    def put_deployment(self, spec: ModelDeploymentSpec) -> ModelDeploymentSpec: ...
    def deployment(self, deployment_id: str) -> ModelDeploymentSpec: ...
    def deployments(self) -> tuple[ModelDeploymentSpec, ...]: ...
    def select(self, selector: ModelDeploymentSelector = ModelDeploymentSelector()) -> tuple[ModelDeploymentSpec, ...]: ...
    def set_desired_state_selected(self, selector: ModelDeploymentSelector, state: ModelDesiredState) -> tuple[ModelDeploymentSpec, ...]: ...
    def set_desired_state(self, deployment_id: str, state: ModelDesiredState) -> ModelDeploymentSpec: ...
    def set_gpu_devices(self, deployment_id: str, gpu_devices: tuple[str, ...]) -> ModelDeploymentSpec: ...
    def set_python_environment(self, deployment_id: str, environment_id: str | None) -> ModelDeploymentSpec: ...
    def remove(self, deployment_id: str) -> bool: ...

class ModelDeploymentRuntimePort(Protocol):
    def start(self, deployment_id: str) -> ModelDeploymentStatus: ...
    def stop(self, deployment_id: str) -> ModelDeploymentStatus: ...
    def restart(self, deployment_id: str) -> ModelDeploymentStatus: ...
    def status(self, deployment_id: str) -> ModelDeploymentStatus: ...
    def remove_deployment(self, deployment_id: str) -> bool: ...

class ModelFleetRuntimePort(Protocol):
    def status_all(self) -> tuple[ModelDeploymentStatus, ...]: ...
    def reconcile(self) -> tuple[ModelDeploymentStatus, ...]: ...
    def start_all(self) -> tuple[ModelDeploymentStatus, ...]: ...
    def stop_all(self) -> tuple[ModelDeploymentStatus, ...]: ...

class ModelDeploymentLogPort(Protocol):
    def logs(self, deployment_id: str) -> ModelDeploymentLogs: ...
    def tail_logs(self, deployment_id: str, *, stream: str = "stderr", max_bytes: int = 8192) -> ModelLogTail: ...

class ModelControllerStatePort(Protocol):
    def read(self) -> ModelControllerState | None: ...
    def write(self, state: ModelControllerState) -> ModelControllerState: ...

class ModelControllerStopPort(Protocol):
    def wait(self, timeout: float | None = None) -> bool: ...

class ModelReconcileControllerPort(Protocol):
    def run(self, *, interval_seconds: float, stop: ModelControllerStopPort, max_cycles: int | None = None) -> ModelControllerState: ...
    def snapshot(self) -> ModelControllerState | None: ...

class ModelResourceViewPort(Protocol):
    def environment_usage(self) -> tuple[ModelEnvironmentUsage, ...]: ...
    def gpu_allocations(self) -> tuple[ModelGpuAllocation, ...]: ...
    def gpu_conflicts(self) -> tuple[ModelGpuConflict, ...]: ...
    def gpu_runtime(self) -> GpuRuntimeSnapshot: ...
    def gpu_candidates(self, *, count: int = 1, min_free_memory_mb: int = 0, max_utilization_percent: int = 100) -> tuple[GpuDeviceStatus, ...]: ...
    def gpu_process_bindings(self) -> tuple[ModelGpuProcessBinding, ...]: ...
    def snapshot(self) -> ModelControlSnapshot: ...

__all__ = [
    "ModelControllerStatePort", "ModelControllerStopPort", "ModelDeploymentCatalogPort", "ModelDeploymentLogPort",
    "ModelDeploymentRuntimePort", "ModelFleetRuntimePort", "ModelReconcileControllerPort", "ModelResourceViewPort",
    "ModelServiceRuntimeFactoryPort",
]
