""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: artifact/retention
Authority: None
Canonical authority: artifact
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.artifact.retention.api import (
    ArtifactRetentionConflict,
    ArtifactRetentionCorruptionError,
    ArtifactRetentionNotFound,
    ArtifactRetentionPort,
    ArtifactRetentionState,
)

from noetrium_platform.evidence.artifact.retention.api.contracts import (
    ArtifactRetentionConflict as contracts__ArtifactRetentionConflict,
    ArtifactRetentionCorruptionError as contracts__ArtifactRetentionCorruptionError,
    ArtifactRetentionNotFound as contracts__ArtifactRetentionNotFound,
    ArtifactRetentionState as contracts__ArtifactRetentionState,
)

from noetrium_platform.evidence.artifact.retention.api.ports import (
    ArtifactRetentionPort as ports__ArtifactRetentionPort,
)

SYSTEM_KEY = 'artifact/retention'
PACKAGE_PREFIX = 'noetrium_platform.evidence.artifact.retention'
__all__ = ('ArtifactRetentionConflict', 'ArtifactRetentionCorruptionError', 'ArtifactRetentionNotFound', 'ArtifactRetentionPort', 'ArtifactRetentionState', 'contracts__ArtifactRetentionConflict', 'contracts__ArtifactRetentionCorruptionError', 'contracts__ArtifactRetentionNotFound', 'contracts__ArtifactRetentionState', 'ports__ArtifactRetentionPort')
