""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: artifact
Authority: artifact_identity
Canonical authority: artifact
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'artifact'
PACKAGE_PREFIX = 'noetrium_platform.evidence.artifact'
__all__ = ()
