""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: artifact/catalog
Authority: artifact_catalog
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.artifact.catalog.api import (
    ArtifactKind,
    ArtifactNotFound,
    ArtifactQuery,
    ArtifactRecord,
    ArtifactRegistryConflict,
    ArtifactRegistryCorruptionError,
    ArtifactRegistryPort,
    ArtifactRetention,
)

from noetrium_platform.evidence.artifact.catalog.api.contracts import (
    ArtifactKind as contracts__ArtifactKind,
    ArtifactQuery as contracts__ArtifactQuery,
    ArtifactRecord as contracts__ArtifactRecord,
    ArtifactRetention as contracts__ArtifactRetention,
)

from noetrium_platform.evidence.artifact.catalog.api.errors import (
    ArtifactNotFound as errors__ArtifactNotFound,
    ArtifactRegistryConflict as errors__ArtifactRegistryConflict,
    ArtifactRegistryCorruptionError as errors__ArtifactRegistryCorruptionError,
)

from noetrium_platform.evidence.artifact.catalog.api.ports import (
    ArtifactRegistryPort as ports__ArtifactRegistryPort,
)

SYSTEM_KEY = 'artifact/catalog'
PACKAGE_PREFIX = 'noetrium_platform.evidence.artifact.catalog'
__all__ = ('ArtifactKind', 'ArtifactNotFound', 'ArtifactQuery', 'ArtifactRecord', 'ArtifactRegistryConflict', 'ArtifactRegistryCorruptionError', 'ArtifactRegistryPort', 'ArtifactRetention', 'contracts__ArtifactKind', 'contracts__ArtifactQuery', 'contracts__ArtifactRecord', 'contracts__ArtifactRetention', 'errors__ArtifactNotFound', 'errors__ArtifactRegistryConflict', 'errors__ArtifactRegistryCorruptionError', 'ports__ArtifactRegistryPort')
