""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: artifact/lineage/relation
Authority: None
Canonical authority: artifact
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.artifact.lineage.relation.api import (
    ArtifactLineageConflict,
    ArtifactLineageCorruptionError,
    ArtifactLineageCycle,
    ArtifactLineageEdge,
    ArtifactLineageRelationPort,
)

from noetrium_platform.evidence.artifact.lineage.relation.api.contracts import (
    ArtifactLineageConflict as contracts__ArtifactLineageConflict,
    ArtifactLineageCorruptionError as contracts__ArtifactLineageCorruptionError,
    ArtifactLineageCycle as contracts__ArtifactLineageCycle,
    ArtifactLineageEdge as contracts__ArtifactLineageEdge,
)

from noetrium_platform.evidence.artifact.lineage.relation.api.ports import (
    ArtifactLineageRelationPort as ports__ArtifactLineageRelationPort,
)

SYSTEM_KEY = 'artifact/lineage/relation'
PACKAGE_PREFIX = 'noetrium_platform.evidence.artifact.lineage.relation'
__all__ = ('ArtifactLineageConflict', 'ArtifactLineageCorruptionError', 'ArtifactLineageCycle', 'ArtifactLineageEdge', 'ArtifactLineageRelationPort', 'contracts__ArtifactLineageConflict', 'contracts__ArtifactLineageCorruptionError', 'contracts__ArtifactLineageCycle', 'contracts__ArtifactLineageEdge', 'ports__ArtifactLineageRelationPort')
