""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: components
Authority: reference_component_library
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'components'
PACKAGE_PREFIX = 'components'
__all__ = ()
