""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: components/reference
Authority: reference_component_namespace
Downstream surface: public
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'components/reference'
PACKAGE_PREFIX = 'components.reference'
__all__ = ()
