""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: data
Authority: data_authority
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'data'
PACKAGE_PREFIX = 'noetrium_platform.evidence.data'
__all__ = ()
