""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: data/projection
Authority: projection_authority
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.data.projection.api import (
    ProjectionCheckpoint,
    ProjectionCheckpointStorePort,
    ProjectionCursor,
    ProjectionReducerPort,
    ProjectionTail,
)

from noetrium_platform.evidence.data.projection.api.contracts import (
    ProjectionCheckpoint as contracts__ProjectionCheckpoint,
    ProjectionCheckpointStorePort as contracts__ProjectionCheckpointStorePort,
    ProjectionCursor as contracts__ProjectionCursor,
    ProjectionReducerPort as contracts__ProjectionReducerPort,
    ProjectionTail as contracts__ProjectionTail,
)

SYSTEM_KEY = 'data/projection'
PACKAGE_PREFIX = 'noetrium_platform.evidence.data.projection'
__all__ = ('ProjectionCheckpoint', 'ProjectionCheckpointStorePort', 'ProjectionCursor', 'ProjectionReducerPort', 'ProjectionTail', 'contracts__ProjectionCheckpoint', 'contracts__ProjectionCheckpointStorePort', 'contracts__ProjectionCursor', 'contracts__ProjectionReducerPort', 'contracts__ProjectionTail')
