""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: data/fact
Authority: fact_authority
Canonical authority: data/fact
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'data/fact'
PACKAGE_PREFIX = 'noetrium_platform.evidence.data.fact'
__all__ = ()
