""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment
Authority: environment_state
Canonical authority: environment
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'environment'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment'
__all__ = ()
