""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/resolution
Authority: environment_resolution
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.environment.resolution.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'environment/resolution'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.resolution'
__all__ = ('SystemLeafContract', 'contract')
