""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/specification
Authority: environment_spec
Downstream surface: public
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'environment/specification'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.specification'
__all__ = ()
