""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/web
Authority: web_environment
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.environment.web.api import (
    WebActionKind,
    WebEnvironmentSpec,
    WebWorldPort,
)

from noetrium_platform.capabilities.environment.web.api.contracts import (
    WebActionKind as contracts__WebActionKind,
    WebEnvironmentSpec as contracts__WebEnvironmentSpec,
)

from noetrium_platform.capabilities.environment.web.api.ports import (
    WebWorldPort as ports__WebWorldPort,
)

SYSTEM_KEY = 'environment/web'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.web'
__all__ = ('WebActionKind', 'WebEnvironmentSpec', 'WebWorldPort', 'contracts__WebActionKind', 'contracts__WebEnvironmentSpec', 'ports__WebWorldPort')
