""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/text_world
Authority: text_world_environment
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.environment.text_world.api import (
    TextWorldActionKind,
    TextWorldEnvironmentSpec,
    TextWorldPort,
)

from noetrium_platform.capabilities.environment.text_world.api.contracts import (
    TextWorldActionKind as contracts__TextWorldActionKind,
    TextWorldEnvironmentSpec as contracts__TextWorldEnvironmentSpec,
)

from noetrium_platform.capabilities.environment.text_world.api.ports import (
    TextWorldPort as ports__TextWorldPort,
)

SYSTEM_KEY = 'environment/text_world'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.text_world'
__all__ = ('TextWorldActionKind', 'TextWorldEnvironmentSpec', 'TextWorldPort', 'contracts__TextWorldActionKind', 'contracts__TextWorldEnvironmentSpec', 'ports__TextWorldPort')
