""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/instance/identity
Authority: None
Canonical authority: environment
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'environment/instance/identity'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.instance.identity'
__all__ = ()
