""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/text_world
Authority: None
Canonical authority: environment
Node kind: provider
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'environment/text_world'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.text_world'
__all__ = ()
