""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/software
Authority: None
Canonical authority: environment
Node kind: provider
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'environment/software'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.software'
__all__ = ()
