""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: environment/instance/readiness
Authority: environment_readiness
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.environment.instance.readiness.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'environment/instance/readiness'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.environment.instance.readiness'
__all__ = ('SystemLeafContract', 'contract')
