""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: execution/command
Authority: command_intent
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.research.execution.command.api import (
    CONTRACT,
    CommandConflict,
    CommandCorruption,
    CommandDeduplicationKey,
    CommandId,
    CommandIntentPort,
    CommandStorePort,
    ExecutionCommand,
    contract,
)

from noetrium_platform.research.execution.command.api.boundary import (
    SystemLeafContract,
    contract as boundary__contract,
)

from noetrium_platform.research.execution.command.api.contracts import (
    CommandDeduplicationKey as contracts__CommandDeduplicationKey,
    CommandId as contracts__CommandId,
    ExecutionCommand as contracts__ExecutionCommand,
)

from noetrium_platform.research.execution.command.api.ports import (
    CommandConflict as ports__CommandConflict,
    CommandCorruption as ports__CommandCorruption,
    CommandIntentPort as ports__CommandIntentPort,
    CommandStorePort as ports__CommandStorePort,
)

SYSTEM_KEY = 'execution/command'
PACKAGE_PREFIX = 'noetrium_platform.research.execution.command'
__all__ = ('CONTRACT', 'CommandConflict', 'CommandCorruption', 'CommandDeduplicationKey', 'CommandId', 'CommandIntentPort', 'CommandStorePort', 'ExecutionCommand', 'contract', 'SystemLeafContract', 'boundary__contract', 'contracts__CommandDeduplicationKey', 'contracts__CommandId', 'contracts__ExecutionCommand', 'ports__CommandConflict', 'ports__CommandCorruption', 'ports__CommandIntentPort', 'ports__CommandStorePort')
