""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: execution
Authority: execution_operations
Canonical authority: execution
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'execution'
PACKAGE_PREFIX = 'noetrium_platform.research.execution'
__all__ = ()
