""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: execution
Authority: execution_operations
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.research.execution.api import (
    DeploymentStatusIdentity,
    ExecutionIntentPort,
    ExecutionIntentReceipt,
    ExecutionOperationIntent,
)

from noetrium_platform.research.execution.api.intent import (
    ExecutionIntentPort as intent__ExecutionIntentPort,
    ExecutionIntentReceipt as intent__ExecutionIntentReceipt,
    ExecutionOperationIntent as intent__ExecutionOperationIntent,
)

from noetrium_platform.research.execution.api.status import (
    DeploymentStatusIdentity as status__DeploymentStatusIdentity,
)

SYSTEM_KEY = 'execution'
PACKAGE_PREFIX = 'noetrium_platform.research.execution'
__all__ = ('DeploymentStatusIdentity', 'ExecutionIntentPort', 'ExecutionIntentReceipt', 'ExecutionOperationIntent', 'intent__ExecutionIntentPort', 'intent__ExecutionIntentReceipt', 'intent__ExecutionOperationIntent', 'status__DeploymentStatusIdentity')
