""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/catalog
Authority: None
Canonical authority: experimentation
Node kind: projection
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'experimentation/catalog'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.catalog'
__all__ = ()
