""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/variant
Authority: variant_state
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.research.experimentation.variant.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'experimentation/variant'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.variant'
__all__ = ('SystemLeafContract', 'contract')
