""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/workload
Authority: experiment_workload_execution_contract
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.research.experimentation.workload.api import (
    WorkloadActionAdapterPort,
    WorkloadBatchCloseError,
    WorkloadBatchResult,
    WorkloadBatchBindingPort,
    WorkloadBatchExecutorPort,
    WorkloadBoundaryPort,
    WorkloadCompletionPort,
    WorkloadCompletionReceipt,
    WorkloadDecision,
    WorkloadDiagnosticsPort,
    WorkloadExecutionCutObserverPort,
    WorkloadEnvironmentPort,
    WorkloadEvidencePort,
    WorkloadFailurePolicyPort,
    WorkloadPlannerPort,
    WorkloadStatePort,
    WorkloadTaskResult,
    WorkloadTaskRunnerPort,
    WorkloadTaskRunError,
)

from noetrium_platform.research.experimentation.workload.api.contracts import (
    WorkloadBatchCloseError as contracts__WorkloadBatchCloseError,
    WorkloadBatchResult as contracts__WorkloadBatchResult,
    WorkloadCompletionReceipt as contracts__WorkloadCompletionReceipt,
    WorkloadDecision as contracts__WorkloadDecision,
    WorkloadTaskResult as contracts__WorkloadTaskResult,
    WorkloadTaskRunError as contracts__WorkloadTaskRunError,
)

from noetrium_platform.research.experimentation.workload.api.ports import (
    WorkloadActionAdapterPort as ports__WorkloadActionAdapterPort,
    WorkloadBatchBindingPort as ports__WorkloadBatchBindingPort,
    WorkloadBatchExecutorPort as ports__WorkloadBatchExecutorPort,
    WorkloadBoundaryPort as ports__WorkloadBoundaryPort,
    WorkloadCompletionPort as ports__WorkloadCompletionPort,
    WorkloadDiagnosticsPort as ports__WorkloadDiagnosticsPort,
    WorkloadExecutionCutObserverPort as ports__WorkloadExecutionCutObserverPort,
    WorkloadEnvironmentPort as ports__WorkloadEnvironmentPort,
    WorkloadEvidencePort as ports__WorkloadEvidencePort,
    WorkloadFailurePolicyPort as ports__WorkloadFailurePolicyPort,
    WorkloadPlannerPort as ports__WorkloadPlannerPort,
    WorkloadStatePort as ports__WorkloadStatePort,
    WorkloadTaskRunnerPort as ports__WorkloadTaskRunnerPort,
)

SYSTEM_KEY = 'experimentation/workload'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.workload'
__all__ = ('WorkloadActionAdapterPort', 'WorkloadBatchCloseError', 'WorkloadBatchResult', 'WorkloadBatchBindingPort', 'WorkloadBatchExecutorPort', 'WorkloadBoundaryPort', 'WorkloadCompletionPort', 'WorkloadCompletionReceipt', 'WorkloadDecision', 'WorkloadDiagnosticsPort', 'WorkloadExecutionCutObserverPort', 'WorkloadEnvironmentPort', 'WorkloadEvidencePort', 'WorkloadFailurePolicyPort', 'WorkloadPlannerPort', 'WorkloadStatePort', 'WorkloadTaskResult', 'WorkloadTaskRunnerPort', 'WorkloadTaskRunError', 'contracts__WorkloadBatchCloseError', 'contracts__WorkloadBatchResult', 'contracts__WorkloadCompletionReceipt', 'contracts__WorkloadDecision', 'contracts__WorkloadTaskResult', 'contracts__WorkloadTaskRunError', 'ports__WorkloadActionAdapterPort', 'ports__WorkloadBatchBindingPort', 'ports__WorkloadBatchExecutorPort', 'ports__WorkloadBoundaryPort', 'ports__WorkloadCompletionPort', 'ports__WorkloadDiagnosticsPort', 'ports__WorkloadExecutionCutObserverPort', 'ports__WorkloadEnvironmentPort', 'ports__WorkloadEvidencePort', 'ports__WorkloadFailurePolicyPort', 'ports__WorkloadPlannerPort', 'ports__WorkloadStatePort', 'ports__WorkloadTaskRunnerPort')
