""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation
Authority: experimentation_state
Canonical authority: experimentation
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'experimentation'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation'
__all__ = ()
