""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/resource
Authority: None
Canonical authority: experimentation
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.research.experimentation.resource.api import (
    ComputeDemand,
    ModelCapacityMode,
    ResourceAllocationReceipt,
    ResourcePolicy,
    ExperimentResourceBinderPort,
    ResourceAllocationLeasePort,
)

from noetrium_platform.research.experimentation.resource.api.contracts import (
    ComputeDemand as contracts__ComputeDemand,
    ModelCapacityMode as contracts__ModelCapacityMode,
    ResourceAllocationReceipt as contracts__ResourceAllocationReceipt,
    ResourcePolicy as contracts__ResourcePolicy,
)

from noetrium_platform.research.experimentation.resource.api.ports import (
    ExperimentResourceBinderPort as ports__ExperimentResourceBinderPort,
    ResourceAllocationLeasePort as ports__ResourceAllocationLeasePort,
)

SYSTEM_KEY = 'experimentation/resource'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.resource'
__all__ = ('ComputeDemand', 'ModelCapacityMode', 'ResourceAllocationReceipt', 'ResourcePolicy', 'ExperimentResourceBinderPort', 'ResourceAllocationLeasePort', 'contracts__ComputeDemand', 'contracts__ModelCapacityMode', 'contracts__ResourceAllocationReceipt', 'contracts__ResourcePolicy', 'ports__ExperimentResourceBinderPort', 'ports__ResourceAllocationLeasePort')
