""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/variant
Authority: None
Canonical authority: experimentation
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'experimentation/variant'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.variant'
__all__ = ()
