""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: experimentation/branch
Authority: None
Canonical authority: experimentation
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'experimentation/branch'
PACKAGE_PREFIX = 'noetrium_platform.research.experimentation.branch'
__all__ = ()
