""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: governance/algorithm
Authority: algorithm_governance
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.governance.algorithm.api.contracts import (
    AlgorithmBaselineApproval,
    AlgorithmComplexityMigrationApproval,
    AlgorithmDiff,
    AlgorithmGovernanceApprovalSet,
    AlgorithmFinding,
    AlgorithmGateReport,
    AlgorithmLanguage,
    AlgorithmMetrics,
    AlgorithmPriority,
    AlgorithmSnapshot,
    AlgorithmSymbol,
    FileAnalysis,
    LanguageCoverage,
    SourceDocument,
    SymbolDelta,
)

from noetrium_platform.foundation.governance.algorithm.api.ports import (
    AlgorithmSnapshotStorePort,
    FileAnalysisCachePort,
    LanguageAnalyzerPort,
    SourceInventoryPort,
)

SYSTEM_KEY = 'governance/algorithm'
PACKAGE_PREFIX = 'noetrium_platform.foundation.governance.algorithm'
__all__ = ('AlgorithmBaselineApproval', 'AlgorithmComplexityMigrationApproval', 'AlgorithmDiff', 'AlgorithmGovernanceApprovalSet', 'AlgorithmFinding', 'AlgorithmGateReport', 'AlgorithmLanguage', 'AlgorithmMetrics', 'AlgorithmPriority', 'AlgorithmSnapshot', 'AlgorithmSymbol', 'FileAnalysis', 'LanguageCoverage', 'SourceDocument', 'SymbolDelta', 'AlgorithmSnapshotStorePort', 'FileAnalysisCachePort', 'LanguageAnalyzerPort', 'SourceInventoryPort')
