""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: governance/concurrency
Authority: None
Canonical authority: None
Node kind: tool
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'governance/concurrency'
PACKAGE_PREFIX = 'noetrium_platform.foundation.governance.concurrency'
__all__ = ()
