""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: governance/performance
Authority: performance_governance
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.governance.performance.api.contracts import (
    PerformanceLanguage,
    PerformancePriority,
    PerformanceFinding,
    PerformanceMetrics,
    PerformanceHotspot,
    PerformanceCoverage,
    PerformanceSnapshot,
    PerformanceBaseline,
    PerformanceGateReport,
    PerformanceDocument,
    PerformanceFileAnalysis,
)

from noetrium_platform.foundation.governance.performance.api.ports import (
    PerformanceBaseline as ports__PerformanceBaseline,
    PerformanceDocument as ports__PerformanceDocument,
    PerformanceFileAnalysis as ports__PerformanceFileAnalysis,
    PerformanceLanguage as ports__PerformanceLanguage,
    PerformanceSnapshot as ports__PerformanceSnapshot,
    PerformanceSourceInventoryPort,
    PerformanceLanguageAnalyzerPort,
    PerformanceSnapshotStorePort,
)

SYSTEM_KEY = 'governance/performance'
PACKAGE_PREFIX = 'noetrium_platform.foundation.governance.performance'
__all__ = ('PerformanceLanguage', 'PerformancePriority', 'PerformanceFinding', 'PerformanceMetrics', 'PerformanceHotspot', 'PerformanceCoverage', 'PerformanceSnapshot', 'PerformanceBaseline', 'PerformanceGateReport', 'PerformanceDocument', 'PerformanceFileAnalysis', 'ports__PerformanceBaseline', 'ports__PerformanceDocument', 'ports__PerformanceFileAnalysis', 'ports__PerformanceLanguage', 'ports__PerformanceSnapshot', 'PerformanceSourceInventoryPort', 'PerformanceLanguageAnalyzerPort', 'PerformanceSnapshotStorePort')
