""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: governance/evolution
Authority: system_evolution
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.governance.evolution.api import (
    DiscoveryReport,
    DriftKind,
    EvolutionAssessment,
    EvolutionProposal,
    EvolutionStage,
    EvolutionStateStorePort,
    EvolutionTransition,
    ImprovementSignal,
    ObservationOutcome,
    SignalKind,
    SystemEvolutionPort,
    TopologyDrift,
    TopologyObservation,
)

from noetrium_platform.foundation.governance.evolution.api.contracts import (
    DiscoveryReport as contracts__DiscoveryReport,
    DriftKind as contracts__DriftKind,
    EvolutionAssessment as contracts__EvolutionAssessment,
    EvolutionProposal as contracts__EvolutionProposal,
    EvolutionStage as contracts__EvolutionStage,
    EvolutionTransition as contracts__EvolutionTransition,
    ImprovementSignal as contracts__ImprovementSignal,
    ObservationOutcome as contracts__ObservationOutcome,
    SignalKind as contracts__SignalKind,
    TopologyDrift as contracts__TopologyDrift,
    TopologyObservation as contracts__TopologyObservation,
)

from noetrium_platform.foundation.governance.evolution.api.ports import (
    EvolutionStateStorePort as ports__EvolutionStateStorePort,
    SystemEvolutionPort as ports__SystemEvolutionPort,
)

SYSTEM_KEY = 'governance/evolution'
PACKAGE_PREFIX = 'noetrium_platform.foundation.governance.evolution'
__all__ = ('DiscoveryReport', 'DriftKind', 'EvolutionAssessment', 'EvolutionProposal', 'EvolutionStage', 'EvolutionStateStorePort', 'EvolutionTransition', 'ImprovementSignal', 'ObservationOutcome', 'SignalKind', 'SystemEvolutionPort', 'TopologyDrift', 'TopologyObservation', 'contracts__DiscoveryReport', 'contracts__DriftKind', 'contracts__EvolutionAssessment', 'contracts__EvolutionProposal', 'contracts__EvolutionStage', 'contracts__EvolutionTransition', 'contracts__ImprovementSignal', 'contracts__ObservationOutcome', 'contracts__SignalKind', 'contracts__TopologyDrift', 'contracts__TopologyObservation', 'ports__EvolutionStateStorePort', 'ports__SystemEvolutionPort')
