""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: governance/system_registry
Authority: system_topology
Canonical authority: governance/system_registry
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'governance/system_registry'
PACKAGE_PREFIX = 'noetrium_platform.foundation.governance.system_registry'
__all__ = ()
