""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/catalog/family
Authority: model_family
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.model.catalog.family.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'model/catalog/family'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.catalog.family'
__all__ = ('SystemLeafContract', 'contract')
