""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/request
Authority: model_request
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.model.request.api import (
    ContentAddressedStorePort,
    ContentRef,
    ExecutionContext,
    ImmutableModelIdentity,
    ModelRequestEnvelope,
    ModelRequestLedgerPort,
    ModelRequestRecorderPort,
    ReconstructedModelRequest,
)

from noetrium_platform.capabilities.model.request.api.contracts import (
    ContentAddressedStorePort as contracts__ContentAddressedStorePort,
    ContentRef as contracts__ContentRef,
    ExecutionContext as contracts__ExecutionContext,
    ImmutableModelIdentity as contracts__ImmutableModelIdentity,
    ModelRequestEnvelope as contracts__ModelRequestEnvelope,
    ModelRequestLedgerPort as contracts__ModelRequestLedgerPort,
    ModelRequestRecorderPort as contracts__ModelRequestRecorderPort,
    ReconstructedModelRequest as contracts__ReconstructedModelRequest,
)

SYSTEM_KEY = 'model/request'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.request'
__all__ = ('ContentAddressedStorePort', 'ContentRef', 'ExecutionContext', 'ImmutableModelIdentity', 'ModelRequestEnvelope', 'ModelRequestLedgerPort', 'ModelRequestRecorderPort', 'ReconstructedModelRequest', 'contracts__ContentAddressedStorePort', 'contracts__ContentRef', 'contracts__ExecutionContext', 'contracts__ImmutableModelIdentity', 'contracts__ModelRequestEnvelope', 'contracts__ModelRequestLedgerPort', 'contracts__ModelRequestRecorderPort', 'contracts__ReconstructedModelRequest')
