""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/request
Authority: None
Canonical authority: model
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.model.request.api import (
    ExecutionContext,
    ImmutableModelIdentity,
    ModelRequestEnvelope,
    ModelRequestLedgerPort,
    ModelRequestRecorderPort,
    ReconstructedModelRequest,
)

from noetrium_platform.capabilities.model.request.api.contracts import (
    ModelRequestEnvelope as contracts__ModelRequestEnvelope,
    ModelRequestLedgerPort as contracts__ModelRequestLedgerPort,
    ModelRequestRecorderPort as contracts__ModelRequestRecorderPort,
    ReconstructedModelRequest as contracts__ReconstructedModelRequest,
)

SYSTEM_KEY = 'model/request'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.request'
__all__ = ('ExecutionContext', 'ImmutableModelIdentity', 'ModelRequestEnvelope', 'ModelRequestLedgerPort', 'ModelRequestRecorderPort', 'ReconstructedModelRequest', 'contracts__ModelRequestEnvelope', 'contracts__ModelRequestLedgerPort', 'contracts__ModelRequestRecorderPort', 'contracts__ReconstructedModelRequest')
