""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/catalog/family
Authority: None
Canonical authority: model
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'model/catalog/family'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.catalog.family'
__all__ = ()
