""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/catalog/revision
Authority: model_revision
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.model.catalog.revision.api import (
    CONTRACT,
    contract,
    ModelPromotionDecision,
    ModelPromotionDisposition,
    ModelPromotionReceipt,
    ModelRevisionAuthorityPort,
    ModelRevisionAuthoritySnapshot,
    ModelRevisionCommit,
    ModelRevisionConflictError,
    ModelRevisionEvidence,
    ModelRevisionEvidenceKind,
    ModelRevisionIdentity,
    ModelRevisionIntegrityError,
    ModelRevisionStateError,
    ModelRollbackReceipt,
    ModelUpdateProducerPort,
    ModelUpdateProposal,
    PreparedModelRevision,
)

from noetrium_platform.capabilities.model.catalog.revision.api.boundary import (
    SystemLeafContract,
    contract as boundary__contract,
)

from noetrium_platform.capabilities.model.catalog.revision.api.contracts import (
    ModelPromotionDecision as contracts__ModelPromotionDecision,
    ModelPromotionDisposition as contracts__ModelPromotionDisposition,
    ModelPromotionReceipt as contracts__ModelPromotionReceipt,
    ModelRevisionAuthorityPort as contracts__ModelRevisionAuthorityPort,
    ModelRevisionAuthoritySnapshot as contracts__ModelRevisionAuthoritySnapshot,
    ModelRevisionCommit as contracts__ModelRevisionCommit,
    ModelRevisionConflictError as contracts__ModelRevisionConflictError,
    ModelRevisionEvidence as contracts__ModelRevisionEvidence,
    ModelRevisionEvidenceKind as contracts__ModelRevisionEvidenceKind,
    ModelRevisionIdentity as contracts__ModelRevisionIdentity,
    ModelRevisionIntegrityError as contracts__ModelRevisionIntegrityError,
    ModelRevisionStateError as contracts__ModelRevisionStateError,
    ModelRollbackReceipt as contracts__ModelRollbackReceipt,
    ModelUpdateProposal as contracts__ModelUpdateProposal,
    PreparedModelRevision as contracts__PreparedModelRevision,
)

from noetrium_platform.capabilities.model.catalog.revision.api.update import (
    ModelUpdateBuildEvidence,
    ModelUpdateBuildReceipt,
    ModelUpdatePlan,
    ModelUpdateProducerPort as update__ModelUpdateProducerPort,
    ModelUpdateSource,
)

SYSTEM_KEY = 'model/catalog/revision'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.catalog.revision'
__all__ = ('CONTRACT', 'contract', 'ModelPromotionDecision', 'ModelPromotionDisposition', 'ModelPromotionReceipt', 'ModelRevisionAuthorityPort', 'ModelRevisionAuthoritySnapshot', 'ModelRevisionCommit', 'ModelRevisionConflictError', 'ModelRevisionEvidence', 'ModelRevisionEvidenceKind', 'ModelRevisionIdentity', 'ModelRevisionIntegrityError', 'ModelRevisionStateError', 'ModelRollbackReceipt', 'ModelUpdateProducerPort', 'ModelUpdateProposal', 'PreparedModelRevision', 'SystemLeafContract', 'boundary__contract', 'contracts__ModelPromotionDecision', 'contracts__ModelPromotionDisposition', 'contracts__ModelPromotionReceipt', 'contracts__ModelRevisionAuthorityPort', 'contracts__ModelRevisionAuthoritySnapshot', 'contracts__ModelRevisionCommit', 'contracts__ModelRevisionConflictError', 'contracts__ModelRevisionEvidence', 'contracts__ModelRevisionEvidenceKind', 'contracts__ModelRevisionIdentity', 'contracts__ModelRevisionIntegrityError', 'contracts__ModelRevisionStateError', 'contracts__ModelRollbackReceipt', 'contracts__ModelUpdateProposal', 'contracts__PreparedModelRevision', 'ModelUpdateBuildEvidence', 'ModelUpdateBuildReceipt', 'ModelUpdatePlan', 'update__ModelUpdateProducerPort', 'ModelUpdateSource')
