""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: model/assignment
Authority: model_assignment
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.capabilities.model.assignment.api.contracts import (
    ModelAssignment,
    ResolvedModelAssignment,
)

from noetrium_platform.capabilities.model.assignment.api.ports import (
    ModelAssignmentPort,
)

SYSTEM_KEY = 'model/assignment'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.model.assignment'
__all__ = ('ModelAssignment', 'ResolvedModelAssignment', 'ModelAssignmentPort')
