""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/status/lifecycle_view
Authority: lifecycle_projection
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.status.lifecycle_view.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'observability/status/lifecycle_view'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.status.lifecycle_view'
__all__ = ('SystemLeafContract', 'contract')
