""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/telemetry
Authority: telemetry_observation
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/telemetry'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.telemetry'
__all__ = ()
