""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/diagnostic/query
Authority: diagnostic_query
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.diagnostic.query.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'observability/diagnostic/query'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.diagnostic.query'
__all__ = ('SystemLeafContract', 'contract')
