""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/query
Authority: log_query
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.query.api import (
    LogQueryPort,
)

from noetrium_platform.evidence.observability.logging.query.api.ports import (
    LogQueryPort as ports__LogQueryPort,
)

SYSTEM_KEY = 'observability/logging/query'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.query'
__all__ = ('LogQueryPort', 'ports__LogQueryPort')
