""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/telemetry/event
Authority: None
Canonical authority: None
Node kind: projection
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/telemetry/event'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.telemetry.event'
__all__ = ()
