""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/storage
Authority: log_storage
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.storage.api import (
    LogStorageWriteActorPort,
)

from noetrium_platform.evidence.observability.logging.storage.api.ports import (
    LogStorageWriteActorPort as ports__LogStorageWriteActorPort,
)

SYSTEM_KEY = 'observability/logging/storage'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.storage'
__all__ = ('LogStorageWriteActorPort', 'ports__LogStorageWriteActorPort')
