""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/context
Authority: log_context
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.context.api import (
    DiagnosticAddress,
)

from noetrium_platform.evidence.observability.logging.context.api.contracts import (
    DiagnosticAddress as contracts__DiagnosticAddress,
)

SYSTEM_KEY = 'observability/logging/context'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.context'
__all__ = ('DiagnosticAddress', 'contracts__DiagnosticAddress')
