""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging
Authority: log_observation
Downstream surface: public
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/logging'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging'
__all__ = ()
