""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/record
Authority: log_record_schema
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.record.api import (
    ExceptionDescriptorPort,
    LoggingSystemBinding,
    LogBatch,
    LogLevel,
    LogRecord,
    LogWriterPort,
    LoggingSystemPort,
    ObservationBindingPort,
    ObservationFactoryPort,
)

from noetrium_platform.evidence.observability.logging.record.api.binding import (
    LoggingSystemBinding as binding__LoggingSystemBinding,
)

from noetrium_platform.evidence.observability.logging.record.api.contracts import (
    LogBatch as contracts__LogBatch,
    LogLevel as contracts__LogLevel,
    LogRecord as contracts__LogRecord,
)

from noetrium_platform.evidence.observability.logging.record.api.ports import (
    ExceptionDescriptorPort as ports__ExceptionDescriptorPort,
    LogWriterPort as ports__LogWriterPort,
    LoggingSystemPort as ports__LoggingSystemPort,
)

SYSTEM_KEY = 'observability/logging/record'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.record'
__all__ = ('ExceptionDescriptorPort', 'LoggingSystemBinding', 'LogBatch', 'LogLevel', 'LogRecord', 'LogWriterPort', 'LoggingSystemPort', 'ObservationBindingPort', 'ObservationFactoryPort', 'binding__LoggingSystemBinding', 'contracts__LogBatch', 'contracts__LogLevel', 'contracts__LogRecord', 'ports__ExceptionDescriptorPort', 'ports__LogWriterPort', 'ports__LoggingSystemPort')
