""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/sink
Authority: log_sink_delivery
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.sink.api import (
    LogSinkPort,
)

from noetrium_platform.evidence.observability.logging.sink.api.ports import (
    LogSinkPort as ports__LogSinkPort,
)

SYSTEM_KEY = 'observability/logging/sink'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.sink'
__all__ = ('LogSinkPort', 'ports__LogSinkPort')
