""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/routing
Authority: None
Canonical authority: None
Node kind: projection
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/logging/routing'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.routing'
__all__ = ()
