""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/status
Authority: status_observation
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.status.api import (
    HealthState,
    PlatformStatus,
    SubsystemSnapshot,
    SubsystemStatusProbePort,
    StatusEvent,
    StatusEventReaderPort,
    StatusEventSinkPort,
)

from noetrium_platform.evidence.observability.status.api.contracts import (
    HealthState as contracts__HealthState,
    PlatformStatus as contracts__PlatformStatus,
    SubsystemSnapshot as contracts__SubsystemSnapshot,
)

from noetrium_platform.evidence.observability.status.api.events import (
    StatusEvent as events__StatusEvent,
    StatusEventReaderPort as events__StatusEventReaderPort,
    StatusEventSinkPort as events__StatusEventSinkPort,
)

from noetrium_platform.evidence.observability.status.api.ports import (
    SubsystemStatusProbePort as ports__SubsystemStatusProbePort,
)

SYSTEM_KEY = 'observability/status'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.status'
__all__ = ('HealthState', 'PlatformStatus', 'SubsystemSnapshot', 'SubsystemStatusProbePort', 'StatusEvent', 'StatusEventReaderPort', 'StatusEventSinkPort', 'contracts__HealthState', 'contracts__PlatformStatus', 'contracts__SubsystemSnapshot', 'events__StatusEvent', 'events__StatusEventReaderPort', 'events__StatusEventSinkPort', 'ports__SubsystemStatusProbePort')
