""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/diagnostic
Authority: diagnostic_view_contract
Downstream surface: public
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/diagnostic'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.diagnostic'
__all__ = ()
