""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/status/health
Authority: health_observation
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.status.health.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'observability/status/health'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.status.health'
__all__ = ('SystemLeafContract', 'contract')
