""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/logging/retention
Authority: log_retention
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.logging.retention.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'observability/logging/retention'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.logging.retention'
__all__ = ('SystemLeafContract', 'contract')
