""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/tracing/storage
Authority: None
Canonical authority: None
Node kind: provider
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'observability/tracing/storage'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.tracing.storage'
__all__ = ()
