""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: observability/telemetry/metric
Authority: telemetry_metric
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.evidence.observability.telemetry.metric.api import (
    ContextualMetricRow,
    MetricDefinition,
    MetricKind,
    MetricObservation,
    PendingMetric,
    PendingMetricWriteSessionPort,
    TelemetryBatchStorePort,
    TelemetryMetricCorruptionError,
    TelemetryPersistencePort,
    TelemetryPersistenceWriteSessionPort,
    TelemetryStorageReadRow,
    TelemetryStorageWriteRow,
    TelemetryWriteActorPort,
)

from noetrium_platform.evidence.observability.telemetry.metric.api.contracts import (
    MetricDefinition as contracts__MetricDefinition,
    MetricKind as contracts__MetricKind,
    MetricObservation as contracts__MetricObservation,
)

from noetrium_platform.evidence.observability.telemetry.metric.api.errors import (
    TelemetryMetricCorruptionError as errors__TelemetryMetricCorruptionError,
)

from noetrium_platform.evidence.observability.telemetry.metric.api.json_contract import (
    decode_string_map,
)

from noetrium_platform.evidence.observability.telemetry.metric.api.ports import (
    PendingMetricWriteSessionPort as ports__PendingMetricWriteSessionPort,
    TelemetryBatchStorePort as ports__TelemetryBatchStorePort,
    TelemetryPersistencePort as ports__TelemetryPersistencePort,
    TelemetryPersistenceWriteSessionPort as ports__TelemetryPersistenceWriteSessionPort,
    TelemetryStorageReadRow as ports__TelemetryStorageReadRow,
    TelemetryStorageWriteRow as ports__TelemetryStorageWriteRow,
    TelemetryWriteActorPort as ports__TelemetryWriteActorPort,
)

from noetrium_platform.evidence.observability.telemetry.metric.api.rows import (
    ContextualMetricRow as rows__ContextualMetricRow,
    PendingMetric as rows__PendingMetric,
)

SYSTEM_KEY = 'observability/telemetry/metric'
PACKAGE_PREFIX = 'noetrium_platform.evidence.observability.telemetry.metric'
__all__ = ('ContextualMetricRow', 'MetricDefinition', 'MetricKind', 'MetricObservation', 'PendingMetric', 'PendingMetricWriteSessionPort', 'TelemetryBatchStorePort', 'TelemetryMetricCorruptionError', 'TelemetryPersistencePort', 'TelemetryPersistenceWriteSessionPort', 'TelemetryStorageReadRow', 'TelemetryStorageWriteRow', 'TelemetryWriteActorPort', 'contracts__MetricDefinition', 'contracts__MetricKind', 'contracts__MetricObservation', 'errors__TelemetryMetricCorruptionError', 'decode_string_map', 'ports__PendingMetricWriteSessionPort', 'ports__TelemetryBatchStorePort', 'ports__TelemetryPersistencePort', 'ports__TelemetryPersistenceWriteSessionPort', 'ports__TelemetryStorageReadRow', 'ports__TelemetryStorageWriteRow', 'ports__TelemetryWriteActorPort', 'rows__ContextualMetricRow', 'rows__PendingMetric')
