""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: operator/audit
Authority: operator_audit
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'operator/audit'
PACKAGE_PREFIX = 'noetrium_platform.product.operator.audit'
__all__ = ()
