""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: operator/command/intent
Authority: operator_command_intent
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.product.operator.command.intent.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'operator/command/intent'
PACKAGE_PREFIX = 'noetrium_platform.product.operator.command.intent'
__all__ = ('SystemLeafContract', 'contract')
