""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: operator/command
Authority: operator_commands
Downstream surface: public
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'operator/command'
PACKAGE_PREFIX = 'noetrium_platform.product.operator.command'
__all__ = ()
