""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: participant/definition
Authority: participant_definition
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'participant/definition'
PACKAGE_PREFIX = 'noetrium_platform.capabilities.participant.definition'
__all__ = ()
