""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: platform/identity
Authority: None
Canonical authority: platform
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.kernel.identity.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'platform/identity'
PACKAGE_PREFIX = 'noetrium_platform.foundation.kernel.identity'
__all__ = ('SystemLeafContract', 'contract')
