""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: platform/lifecycle
Authority: platform_lifecycle
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.kernel.lifecycle.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'platform/lifecycle'
PACKAGE_PREFIX = 'noetrium_platform.foundation.kernel.lifecycle'
__all__ = ('SystemLeafContract', 'contract')
