""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: platform/configuration
Authority: platform_configuration
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.kernel.configuration.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'platform/configuration'
PACKAGE_PREFIX = 'noetrium_platform.foundation.kernel.configuration'
__all__ = ('SystemLeafContract', 'contract')
