""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: portfolio/program
Authority: program_metadata
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.portfolio.program.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'portfolio/program'
PACKAGE_PREFIX = 'noetrium_platform.foundation.portfolio.program'
__all__ = ('SystemLeafContract', 'contract')
