""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: portfolio/membership
Authority: None
Canonical authority: portfolio
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'portfolio/membership'
PACKAGE_PREFIX = 'noetrium_platform.foundation.portfolio.membership'
__all__ = ()
