""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: portfolio/membership
Authority: portfolio_membership
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.portfolio.membership.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'portfolio/membership'
PACKAGE_PREFIX = 'noetrium_platform.foundation.portfolio.membership'
__all__ = ('SystemLeafContract', 'contract')
