""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: reliability/recovery/execution
Authority: recovery_execution
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'reliability/recovery/execution'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.reliability.recovery.execution'
__all__ = ()
