""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: reliability/effect
Authority: effect_authority
Canonical authority: reliability/effect
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'reliability/effect'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.reliability.effect'
__all__ = ()
