""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: reliability/diagnostics
Authority: None
Canonical authority: None
Node kind: projection
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'reliability/diagnostics'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.reliability.diagnostics'
__all__ = ()
