""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: research_os
Authority: None
Canonical authority: None
Node kind: product_surface
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.product.api import (
    ResearchBranch,
    ResearchControlAction,
    ResearchControlReceipt,
    ResearchControlRequest,
    ResearchDefinition,
    ResearchDefinitionKind,
    ResearchDependency,
    ResearchExecutionTarget,
    ResearchGraphRevision,
    ResearchImpactState,
    ResearchImplementation,
    ResearchMethodProgramBindingKind,
    ResearchMethodProgramImplementation,
    ResearchInputBinding,
    ResearchNode,
    ResearchNodeImpact,
    ResearchNodeKind,
    ResearchPortfolioDependency,
    ResearchPortfolioBuilder,
    ResearchNodeRef,
    ResearchOS,
    ResearchOutputSpec,
    ResearchPortfolio,
    ResearchProgram,
    ResearchProgramBuilder,
    ResearchRevisionDiff,
    ResearchTag,
    ResearchValueKind,
)

SYSTEM_KEY = 'research_os'
PACKAGE_PREFIX = 'noetrium_platform.product'
__all__ = ('ResearchBranch', 'ResearchControlAction', 'ResearchControlReceipt', 'ResearchControlRequest', 'ResearchDefinition', 'ResearchDefinitionKind', 'ResearchDependency', 'ResearchExecutionTarget', 'ResearchGraphRevision', 'ResearchImpactState', 'ResearchImplementation', 'ResearchMethodProgramBindingKind', 'ResearchMethodProgramImplementation', 'ResearchInputBinding', 'ResearchNode', 'ResearchNodeImpact', 'ResearchNodeKind', 'ResearchPortfolioDependency', 'ResearchPortfolioBuilder', 'ResearchNodeRef', 'ResearchOS', 'ResearchOutputSpec', 'ResearchPortfolio', 'ResearchProgram', 'ResearchProgramBuilder', 'ResearchRevisionDiff', 'ResearchTag', 'ResearchValueKind')
