""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource
Authority: resource_inventory
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'resource'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources'
__all__ = ()
