""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource/compute
Authority: compute_inventory
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.resources.compute.api import (
    ComputeAllocation,
    ComputeCandidatePort,
    ComputeCluster,
    ComputeGPU,
    ComputeHost,
    ComputeRequirement,
    ComputeInventoryPort,
    ComputeSchedulerPort,
    GpuDeviceStatus,
    GpuProcessStatus,
    GpuRuntimeObserverPort,
    GpuRuntimeSnapshot,
)

from noetrium_platform.infrastructure.resources.compute.api.contracts import (
    ComputeAllocation as contracts__ComputeAllocation,
    ComputeCluster as contracts__ComputeCluster,
    ComputeGPU as contracts__ComputeGPU,
    ComputeHost as contracts__ComputeHost,
    ComputeRequirement as contracts__ComputeRequirement,
)

from noetrium_platform.infrastructure.resources.compute.api.ports import (
    ComputeCandidatePort as ports__ComputeCandidatePort,
    ComputeInventoryPort as ports__ComputeInventoryPort,
    ComputeSchedulerPort as ports__ComputeSchedulerPort,
)

from noetrium_platform.infrastructure.resources.compute.api.runtime_status import (
    GpuDeviceStatus as runtime_status__GpuDeviceStatus,
    GpuProcessStatus as runtime_status__GpuProcessStatus,
    GpuRuntimeObserverPort as runtime_status__GpuRuntimeObserverPort,
    GpuRuntimeSnapshot as runtime_status__GpuRuntimeSnapshot,
)

SYSTEM_KEY = 'resource/compute'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources.compute'
__all__ = ('ComputeAllocation', 'ComputeCandidatePort', 'ComputeCluster', 'ComputeGPU', 'ComputeHost', 'ComputeRequirement', 'ComputeInventoryPort', 'ComputeSchedulerPort', 'GpuDeviceStatus', 'GpuProcessStatus', 'GpuRuntimeObserverPort', 'GpuRuntimeSnapshot', 'contracts__ComputeAllocation', 'contracts__ComputeCluster', 'contracts__ComputeGPU', 'contracts__ComputeHost', 'contracts__ComputeRequirement', 'ports__ComputeCandidatePort', 'ports__ComputeInventoryPort', 'ports__ComputeSchedulerPort', 'runtime_status__GpuDeviceStatus', 'runtime_status__GpuProcessStatus', 'runtime_status__GpuRuntimeObserverPort', 'runtime_status__GpuRuntimeSnapshot')
