""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource/allocation
Authority: resource_allocation
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.resources.allocation.api import (
    AtomicEndpointReservationPort,
    DEFAULT_ENDPOINT_LEASE_POLICY,
    EndpointAllocation,
    EndpointAllocationPort,
    EndpointAllocationRequest,
    EndpointBindingProof,
    EndpointAllocationState,
    EndpointLeaseGuardFactoryPort,
    EndpointLeaseGuardPort,
    EndpointLeasePolicy,
    EndpointProbePort,
    EndpointProbeResult,
    EndpointProtocol,
    EndpointReservationResult,
    EndpointReservationStatus,
    NetworkEndpoint,
)

from noetrium_platform.infrastructure.resources.allocation.api.contracts import (
    EndpointAllocation as contracts__EndpointAllocation,
    EndpointBindingProof as contracts__EndpointBindingProof,
    EndpointAllocationRequest as contracts__EndpointAllocationRequest,
    EndpointAllocationState as contracts__EndpointAllocationState,
    EndpointLeasePolicy as contracts__EndpointLeasePolicy,
    DEFAULT_ENDPOINT_LEASE_POLICY as contracts__DEFAULT_ENDPOINT_LEASE_POLICY,
    EndpointReservationResult as contracts__EndpointReservationResult,
    EndpointReservationStatus as contracts__EndpointReservationStatus,
    EndpointProbeResult as contracts__EndpointProbeResult,
    EndpointProtocol as contracts__EndpointProtocol,
    NetworkEndpoint as contracts__NetworkEndpoint,
)

from noetrium_platform.infrastructure.resources.allocation.api.ports import (
    AtomicEndpointReservationPort as ports__AtomicEndpointReservationPort,
    EndpointAllocationPort as ports__EndpointAllocationPort,
    EndpointLeaseGuardFactoryPort as ports__EndpointLeaseGuardFactoryPort,
    EndpointLeaseGuardPort as ports__EndpointLeaseGuardPort,
    EndpointProbePort as ports__EndpointProbePort,
)

SYSTEM_KEY = 'resource/allocation'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources.allocation'
__all__ = ('AtomicEndpointReservationPort', 'DEFAULT_ENDPOINT_LEASE_POLICY', 'EndpointAllocation', 'EndpointAllocationPort', 'EndpointAllocationRequest', 'EndpointBindingProof', 'EndpointAllocationState', 'EndpointLeaseGuardFactoryPort', 'EndpointLeaseGuardPort', 'EndpointLeasePolicy', 'EndpointProbePort', 'EndpointProbeResult', 'EndpointProtocol', 'EndpointReservationResult', 'EndpointReservationStatus', 'NetworkEndpoint', 'contracts__EndpointAllocation', 'contracts__EndpointBindingProof', 'contracts__EndpointAllocationRequest', 'contracts__EndpointAllocationState', 'contracts__EndpointLeasePolicy', 'contracts__DEFAULT_ENDPOINT_LEASE_POLICY', 'contracts__EndpointReservationResult', 'contracts__EndpointReservationStatus', 'contracts__EndpointProbeResult', 'contracts__EndpointProtocol', 'contracts__NetworkEndpoint', 'ports__AtomicEndpointReservationPort', 'ports__EndpointAllocationPort', 'ports__EndpointLeaseGuardFactoryPort', 'ports__EndpointLeaseGuardPort', 'ports__EndpointProbePort')
