""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource/resolution
Authority: resource_resolution
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.resources.resolution.api import (
    ResourceResolutionPort,
    ResourceResolutionRequest,
    ResolvedResourceBinding,
)

from noetrium_platform.infrastructure.resources.resolution.api.contracts import (
    ResourceResolutionRequest as contracts__ResourceResolutionRequest,
    ResolvedResourceBinding as contracts__ResolvedResourceBinding,
)

from noetrium_platform.infrastructure.resources.resolution.api.ports import (
    ResourceResolutionPort as ports__ResourceResolutionPort,
)

SYSTEM_KEY = 'resource/resolution'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources.resolution'
__all__ = ('ResourceResolutionPort', 'ResourceResolutionRequest', 'ResolvedResourceBinding', 'contracts__ResourceResolutionRequest', 'contracts__ResolvedResourceBinding', 'ports__ResourceResolutionPort')
