""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource/compute
Authority: None
Canonical authority: resource
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.resources.compute.api import (
    ComputeAllocation,
    ComputeCandidatePort,
    ComputeCluster,
    ComputeGPU,
    ComputeHost,
    ComputePlacementUnavailable,
    ComputeRequirement,
    ComputeLeasePolicy,
    DEFAULT_COMPUTE_LEASE_POLICY,
    ComputeInventoryPort,
    ComputeLeaseGuardFactoryPort,
    ComputeLeaseGuardPort,
    ComputeSchedulerPort,
    GpuSharingMode,
    GpuDeviceStatus,
    GpuProcessStatus,
    GpuRuntimeObserverPort,
    GpuRuntimeSnapshot,
    HostRuntimeObserverPort,
    HostRuntimeSnapshot,
    HostRuntimeStatus,
    CommandProbeError,
    CommandProbePort,
    CommandProbeResult,
)

from noetrium_platform.infrastructure.resources.compute.api.contracts import (
    ComputeAllocation as contracts__ComputeAllocation,
    ComputeCluster as contracts__ComputeCluster,
    ComputeGPU as contracts__ComputeGPU,
    ComputeHost as contracts__ComputeHost,
    ComputePlacementUnavailable as contracts__ComputePlacementUnavailable,
    ComputeRequirement as contracts__ComputeRequirement,
    ComputeLeasePolicy as contracts__ComputeLeasePolicy,
    DEFAULT_COMPUTE_LEASE_POLICY as contracts__DEFAULT_COMPUTE_LEASE_POLICY,
    GpuSharingMode as contracts__GpuSharingMode,
)

from noetrium_platform.infrastructure.resources.compute.api.ports import (
    ComputeCandidatePort as ports__ComputeCandidatePort,
    ComputeInventoryPort as ports__ComputeInventoryPort,
    ComputeLeaseGuardFactoryPort as ports__ComputeLeaseGuardFactoryPort,
    ComputeLeaseGuardPort as ports__ComputeLeaseGuardPort,
    ComputeSchedulerPort as ports__ComputeSchedulerPort,
)

from noetrium_platform.infrastructure.resources.compute.api.probe import (
    CommandProbeError as probe__CommandProbeError,
    CommandProbePort as probe__CommandProbePort,
    CommandProbeResult as probe__CommandProbeResult,
)

from noetrium_platform.infrastructure.resources.compute.api.runtime_status import (
    GpuDeviceStatus as runtime_status__GpuDeviceStatus,
    GpuProcessStatus as runtime_status__GpuProcessStatus,
    GpuRuntimeObserverPort as runtime_status__GpuRuntimeObserverPort,
    GpuRuntimeSnapshot as runtime_status__GpuRuntimeSnapshot,
    HostRuntimeObserverPort as runtime_status__HostRuntimeObserverPort,
    HostRuntimeSnapshot as runtime_status__HostRuntimeSnapshot,
    HostRuntimeStatus as runtime_status__HostRuntimeStatus,
)

SYSTEM_KEY = 'resource/compute'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources.compute'
__all__ = ('ComputeAllocation', 'ComputeCandidatePort', 'ComputeCluster', 'ComputeGPU', 'ComputeHost', 'ComputePlacementUnavailable', 'ComputeRequirement', 'ComputeLeasePolicy', 'DEFAULT_COMPUTE_LEASE_POLICY', 'ComputeInventoryPort', 'ComputeLeaseGuardFactoryPort', 'ComputeLeaseGuardPort', 'ComputeSchedulerPort', 'GpuSharingMode', 'GpuDeviceStatus', 'GpuProcessStatus', 'GpuRuntimeObserverPort', 'GpuRuntimeSnapshot', 'HostRuntimeObserverPort', 'HostRuntimeSnapshot', 'HostRuntimeStatus', 'CommandProbeError', 'CommandProbePort', 'CommandProbeResult', 'contracts__ComputeAllocation', 'contracts__ComputeCluster', 'contracts__ComputeGPU', 'contracts__ComputeHost', 'contracts__ComputePlacementUnavailable', 'contracts__ComputeRequirement', 'contracts__ComputeLeasePolicy', 'contracts__DEFAULT_COMPUTE_LEASE_POLICY', 'contracts__GpuSharingMode', 'ports__ComputeCandidatePort', 'ports__ComputeInventoryPort', 'ports__ComputeLeaseGuardFactoryPort', 'ports__ComputeLeaseGuardPort', 'ports__ComputeSchedulerPort', 'probe__CommandProbeError', 'probe__CommandProbePort', 'probe__CommandProbeResult', 'runtime_status__GpuDeviceStatus', 'runtime_status__GpuProcessStatus', 'runtime_status__GpuRuntimeObserverPort', 'runtime_status__GpuRuntimeSnapshot', 'runtime_status__HostRuntimeObserverPort', 'runtime_status__HostRuntimeSnapshot', 'runtime_status__HostRuntimeStatus')
