""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: resource/lease
Authority: resource_lease
Canonical authority: resource/lease
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'resource/lease'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.resources.lease'
__all__ = ()
