""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/server/lifecycle
Authority: server_lifecycle
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api import (
    ServerReleaseDeploymentError,
    ServerReleaseLayoutError,
    ServerReleaseDeploymentPort,
    ServerReleaseDirectoryPort,
    ServerRepositorySyncError,
    ServerRepositorySyncPort,
    ServerRepositorySyncReceipt,
    ServerRepositorySyncRequest,
    ServerRepositoryStatus,
    ServerRepositoryCommandPort,
    ServerRepositoryCommandReceipt,
    ServerRepositoryCommandRequest,
    ServerReleaseDeploymentReceipt,
    ServerReleaseDeploymentRequest,
    ServerReleaseLayout,
    ServerRemoteProfile,
    ServerRuntimeLaunchManifestPort,
    ServerRuntimeLaunchManifestMismatch,
    ServerSessionPolicyMismatch,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api.command import (
    ServerRepositoryCommandReceipt as command__ServerRepositoryCommandReceipt,
    ServerRepositoryCommandRequest as command__ServerRepositoryCommandRequest,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api.contracts import (
    ServerReleaseDeploymentError as contracts__ServerReleaseDeploymentError,
    ServerReleaseDeploymentReceipt as contracts__ServerReleaseDeploymentReceipt,
    ServerReleaseDeploymentRequest as contracts__ServerReleaseDeploymentRequest,
    ServerReleaseLayout as contracts__ServerReleaseLayout,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api.errors import (
    ServerReleaseLayoutError as errors__ServerReleaseLayoutError,
    ServerRuntimeLaunchManifestMismatch as errors__ServerRuntimeLaunchManifestMismatch,
    ServerSessionPolicyMismatch as errors__ServerSessionPolicyMismatch,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api.ports import (
    ServerReleaseDeploymentPort as ports__ServerReleaseDeploymentPort,
    ServerReleaseDirectoryPort as ports__ServerReleaseDirectoryPort,
    ServerRepositorySyncPort as ports__ServerRepositorySyncPort,
    ServerRepositoryCommandPort as ports__ServerRepositoryCommandPort,
    ServerRuntimeLaunchManifestPort as ports__ServerRuntimeLaunchManifestPort,
)

from noetrium_platform.infrastructure.lifecycle.server.lifecycle.api.repository import (
    ServerRepositorySyncError as repository__ServerRepositorySyncError,
    ServerRepositorySyncReceipt as repository__ServerRepositorySyncReceipt,
    ServerRepositorySyncRequest as repository__ServerRepositorySyncRequest,
    ServerRepositoryStatus as repository__ServerRepositoryStatus,
)

SYSTEM_KEY = 'runtime/server/lifecycle'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.server.lifecycle'
__all__ = ('ServerReleaseDeploymentError', 'ServerReleaseLayoutError', 'ServerReleaseDeploymentPort', 'ServerReleaseDirectoryPort', 'ServerRepositorySyncError', 'ServerRepositorySyncPort', 'ServerRepositorySyncReceipt', 'ServerRepositorySyncRequest', 'ServerRepositoryStatus', 'ServerRepositoryCommandPort', 'ServerRepositoryCommandReceipt', 'ServerRepositoryCommandRequest', 'ServerReleaseDeploymentReceipt', 'ServerReleaseDeploymentRequest', 'ServerReleaseLayout', 'ServerRemoteProfile', 'ServerRuntimeLaunchManifestPort', 'ServerRuntimeLaunchManifestMismatch', 'ServerSessionPolicyMismatch', 'command__ServerRepositoryCommandReceipt', 'command__ServerRepositoryCommandRequest', 'contracts__ServerReleaseDeploymentError', 'contracts__ServerReleaseDeploymentReceipt', 'contracts__ServerReleaseDeploymentRequest', 'contracts__ServerReleaseLayout', 'errors__ServerReleaseLayoutError', 'errors__ServerRuntimeLaunchManifestMismatch', 'errors__ServerSessionPolicyMismatch', 'ports__ServerReleaseDeploymentPort', 'ports__ServerReleaseDirectoryPort', 'ports__ServerRepositorySyncPort', 'ports__ServerRepositoryCommandPort', 'ports__ServerRuntimeLaunchManifestPort', 'repository__ServerRepositorySyncError', 'repository__ServerRepositorySyncReceipt', 'repository__ServerRepositorySyncRequest', 'repository__ServerRepositoryStatus')
