""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/python
Authority: None
Canonical authority: runtime
Node kind: provider
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'runtime/python'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.python'
__all__ = ()
