""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/service
Authority: service_state
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.lifecycle.service.api import (
    ExactServiceRuntimePort,
    ServiceContractDrift,
    ServiceLaunchContract,
    ServiceProcessIdentity,
    ServiceReadyObservation,
    ServiceReconcileObservation,
    ServiceStartOutcome,
    ServiceStopOutcome,
)

from noetrium_platform.infrastructure.lifecycle.service.api.contracts import (
    ServiceContractDrift as contracts__ServiceContractDrift,
    ServiceLaunchContract as contracts__ServiceLaunchContract,
    ServiceProcessIdentity as contracts__ServiceProcessIdentity,
)

from noetrium_platform.infrastructure.lifecycle.service.api.ports import (
    ExactServiceRuntimePort as ports__ExactServiceRuntimePort,
    ServiceReadyObservation as ports__ServiceReadyObservation,
    ServiceReconcileObservation as ports__ServiceReconcileObservation,
    ServiceStartOutcome as ports__ServiceStartOutcome,
    ServiceStopOutcome as ports__ServiceStopOutcome,
)

from noetrium_platform.infrastructure.lifecycle.service.api.runtime import (
    ExactServiceRuntimePort as runtime__ExactServiceRuntimePort,
    ServiceReadyObservation as runtime__ServiceReadyObservation,
    ServiceReconcileObservation as runtime__ServiceReconcileObservation,
    ServiceStartOutcome as runtime__ServiceStartOutcome,
    ServiceStopOutcome as runtime__ServiceStopOutcome,
)

SYSTEM_KEY = 'runtime/service'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.service'
__all__ = ('ExactServiceRuntimePort', 'ServiceContractDrift', 'ServiceLaunchContract', 'ServiceProcessIdentity', 'ServiceReadyObservation', 'ServiceReconcileObservation', 'ServiceStartOutcome', 'ServiceStopOutcome', 'contracts__ServiceContractDrift', 'contracts__ServiceLaunchContract', 'contracts__ServiceProcessIdentity', 'ports__ExactServiceRuntimePort', 'ports__ServiceReadyObservation', 'ports__ServiceReconcileObservation', 'ports__ServiceStartOutcome', 'ports__ServiceStopOutcome', 'runtime__ExactServiceRuntimePort', 'runtime__ServiceReadyObservation', 'runtime__ServiceReconcileObservation', 'runtime__ServiceStartOutcome', 'runtime__ServiceStopOutcome')
