""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/session
Authority: runtime_session
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.lifecycle.session.api import (
    PersistentSessionBackendConfig,
    PersistentSessionBinding,
    PersistentSessionBindingStorePort,
    PersistentSessionLaunchManifestPort,
    PersistentSessionControlPort,
    PersistentSessionHostPort,
    PersistentSessionDrift,
    PersistentSessionReasonCode,
    PersistentSessionEffectUncertain,
    PersistentSessionObservation,
    PersistentSessionObservationState,
    PersistentSessionReport,
    PersistentSessionRuntimePort,
    PersistentSessionSnapshot,
    PersistentSessionSpec,
    process_environment_digest,
    PersistentSessionStatusConfig,
    PersistentSessionStatusProbePort,
    ServerSessionPolicy,
    RuntimeControllerCommand,
)

from noetrium_platform.infrastructure.lifecycle.session.api.binding import (
    PersistentSessionBinding as binding__PersistentSessionBinding,
    PersistentSessionBindingStorePort as binding__PersistentSessionBindingStorePort,
)

from noetrium_platform.infrastructure.lifecycle.session.api.contracts import (
    PersistentSessionDrift as contracts__PersistentSessionDrift,
    PersistentSessionReasonCode as contracts__PersistentSessionReasonCode,
    PersistentSessionEffectUncertain as contracts__PersistentSessionEffectUncertain,
    PersistentSessionObservation as contracts__PersistentSessionObservation,
    PersistentSessionObservationState as contracts__PersistentSessionObservationState,
    PersistentSessionReport as contracts__PersistentSessionReport,
    PersistentSessionSnapshot as contracts__PersistentSessionSnapshot,
    PersistentSessionSpec as contracts__PersistentSessionSpec,
    process_environment_digest as contracts__process_environment_digest,
    ServerSessionPolicy as contracts__ServerSessionPolicy,
)

from noetrium_platform.infrastructure.lifecycle.session.api.controller import (
    PersistentSessionLaunchManifestPort as controller__PersistentSessionLaunchManifestPort,
    RuntimeControllerCommand as controller__RuntimeControllerCommand,
)

from noetrium_platform.infrastructure.lifecycle.session.api.ports import (
    PersistentSessionControlPort as ports__PersistentSessionControlPort,
    PersistentSessionRuntimePort as ports__PersistentSessionRuntimePort,
    PersistentSessionStatusProbePort as ports__PersistentSessionStatusProbePort,
    PersistentSessionHostPort as ports__PersistentSessionHostPort,
)

from noetrium_platform.infrastructure.lifecycle.session.api.status_config import (
    PersistentSessionBackendConfig as status_config__PersistentSessionBackendConfig,
    PersistentSessionStatusConfig as status_config__PersistentSessionStatusConfig,
)

SYSTEM_KEY = 'runtime/session'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.session'
__all__ = ('PersistentSessionBackendConfig', 'PersistentSessionBinding', 'PersistentSessionBindingStorePort', 'PersistentSessionLaunchManifestPort', 'PersistentSessionControlPort', 'PersistentSessionHostPort', 'PersistentSessionDrift', 'PersistentSessionReasonCode', 'PersistentSessionEffectUncertain', 'PersistentSessionObservation', 'PersistentSessionObservationState', 'PersistentSessionReport', 'PersistentSessionRuntimePort', 'PersistentSessionSnapshot', 'PersistentSessionSpec', 'process_environment_digest', 'PersistentSessionStatusConfig', 'PersistentSessionStatusProbePort', 'ServerSessionPolicy', 'RuntimeControllerCommand', 'binding__PersistentSessionBinding', 'binding__PersistentSessionBindingStorePort', 'contracts__PersistentSessionDrift', 'contracts__PersistentSessionReasonCode', 'contracts__PersistentSessionEffectUncertain', 'contracts__PersistentSessionObservation', 'contracts__PersistentSessionObservationState', 'contracts__PersistentSessionReport', 'contracts__PersistentSessionSnapshot', 'contracts__PersistentSessionSpec', 'contracts__process_environment_digest', 'contracts__ServerSessionPolicy', 'controller__PersistentSessionLaunchManifestPort', 'controller__RuntimeControllerCommand', 'ports__PersistentSessionControlPort', 'ports__PersistentSessionRuntimePort', 'ports__PersistentSessionStatusProbePort', 'ports__PersistentSessionHostPort', 'status_config__PersistentSessionBackendConfig', 'status_config__PersistentSessionStatusConfig')
