""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime
Authority: runtime_state
Canonical authority: runtime
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'runtime'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle'
__all__ = ()
