""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/service
Authority: None
Canonical authority: runtime
Node kind: facet
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.infrastructure.lifecycle.service.api import (
    ExactServiceRuntimePort,
    ServiceEnvironmentPort,
    ServiceLaunchPreflightPort,
    ServiceLaunchPreflightReport,
    ServiceContractDrift,
    ServiceLaunchContract,
    ServiceProcessIdentity,
    ServiceReadyObservation,
    ServiceReconcileObservation,
    ServiceStartOutcome,
    ServiceStopOutcome,
)

from noetrium_platform.infrastructure.lifecycle.service.api.contracts import (
    ServiceContractDrift as contracts__ServiceContractDrift,
    ServiceLaunchContract as contracts__ServiceLaunchContract,
    ServiceProcessIdentity as contracts__ServiceProcessIdentity,
)

from noetrium_platform.infrastructure.lifecycle.service.api.ports import (
    ExactServiceRuntimePort as ports__ExactServiceRuntimePort,
    ServiceEnvironmentPort as ports__ServiceEnvironmentPort,
    ServiceLaunchPreflightReport as ports__ServiceLaunchPreflightReport,
    ServiceLaunchPreflightPort as ports__ServiceLaunchPreflightPort,
    ServiceReadyObservation as ports__ServiceReadyObservation,
    ServiceReconcileObservation as ports__ServiceReconcileObservation,
    ServiceStartOutcome as ports__ServiceStartOutcome,
    ServiceStopOutcome as ports__ServiceStopOutcome,
)

SYSTEM_KEY = 'runtime/service'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.service'
__all__ = ('ExactServiceRuntimePort', 'ServiceEnvironmentPort', 'ServiceLaunchPreflightPort', 'ServiceLaunchPreflightReport', 'ServiceContractDrift', 'ServiceLaunchContract', 'ServiceProcessIdentity', 'ServiceReadyObservation', 'ServiceReconcileObservation', 'ServiceStartOutcome', 'ServiceStopOutcome', 'contracts__ServiceContractDrift', 'contracts__ServiceLaunchContract', 'contracts__ServiceProcessIdentity', 'ports__ExactServiceRuntimePort', 'ports__ServiceEnvironmentPort', 'ports__ServiceLaunchPreflightReport', 'ports__ServiceLaunchPreflightPort', 'ports__ServiceReadyObservation', 'ports__ServiceReconcileObservation', 'ports__ServiceStartOutcome', 'ports__ServiceStopOutcome')
