""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: runtime/toolchain
Authority: None
Canonical authority: runtime
Node kind: provider
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'runtime/toolchain'
PACKAGE_PREFIX = 'noetrium_platform.infrastructure.lifecycle.toolchain'
__all__ = ()
