""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/membership
Authority: scope_membership
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.scope.membership.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'scope/membership'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.membership'
__all__ = ('SystemLeafContract', 'contract')
