""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/hierarchy
Authority: scope_hierarchy
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.scope.hierarchy.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'scope/hierarchy'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.hierarchy'
__all__ = ('SystemLeafContract', 'contract')
