""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/ownership
Authority: scope_ownership
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.scope.ownership.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'scope/ownership'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.ownership'
__all__ = ('SystemLeafContract', 'contract')
