""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/identity
Authority: scope_identity
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.scope.identity.api.boundary import (
    SystemLeafContract,
    contract,
)

SYSTEM_KEY = 'scope/identity'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.identity'
__all__ = ('SystemLeafContract', 'contract')
