""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/path
Authority: scope_path
Downstream surface: public
API exports: available
This module is regenerated from the canonical registry and API exports.
"""

from noetrium_platform.foundation.scope.path.api import (
    PathFlavor,
    ScopePathPort,
    is_absolute_target_path,
    require_absolute_target_path,
)

from noetrium_platform.foundation.scope.path.api.contracts import (
    PathFlavor as contracts__PathFlavor,
    is_absolute_target_path as contracts__is_absolute_target_path,
    require_absolute_target_path as contracts__require_absolute_target_path,
)

from noetrium_platform.foundation.scope.path.api.ports import (
    ScopePathPort as ports__ScopePathPort,
)

SYSTEM_KEY = 'scope/path'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.path'
__all__ = ('PathFlavor', 'ScopePathPort', 'is_absolute_target_path', 'require_absolute_target_path', 'contracts__PathFlavor', 'contracts__is_absolute_target_path', 'contracts__require_absolute_target_path', 'ports__ScopePathPort')
