""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope/ownership
Authority: None
Canonical authority: scope
Node kind: facet
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'scope/ownership'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope.ownership'
__all__ = ()
