""" AUTO-GENERATED by scripts/generate_downstream_contracts.py.
System: scope
Authority: scope_tree
Canonical authority: scope
Node kind: authority
Downstream surface: metadata_only
API exports: none (metadata-only facade)
This module is regenerated from the canonical registry and API exports.
"""

SYSTEM_KEY = 'scope'
PACKAGE_PREFIX = 'noetrium_platform.foundation.scope'
__all__ = ()
