from __future__ import annotations

from .source_authority_contracts import SourceAuthorityRule
from .source_authority_matchers import exact_call, suffix_call


DEFAULT_SOURCE_AUTHORITY_RULES: tuple[_AuthorityRule, ...] = (
    SourceAuthorityRule(
        "storage.sqlite_connection",
        "sqlite3.connect",
        ("noetrium_platform.foundation.kernel.kernel.durability.sqlite",),
        exact_call("sqlite3.connect"),
    ),
    SourceAuthorityRule(
        "concurrency.thread_pool",
        "concurrent.futures.ThreadPoolExecutor",
        ("noetrium_platform.foundation.kernel.concurrency.providers.executors",),
        exact_call("concurrent.futures.ThreadPoolExecutor"),
    ),
    SourceAuthorityRule(
        "concurrency.process_pool",
        "concurrent.futures.ProcessPoolExecutor",
        ("noetrium_platform.foundation.kernel.concurrency.providers.executors",),
        exact_call("concurrent.futures.ProcessPoolExecutor"),
    ),
    SourceAuthorityRule(
        "concurrency.thread",
        "threading.Thread",
        (
            "noetrium_platform.foundation.kernel.concurrency.providers.async_io",
            "noetrium_platform.foundation.kernel.concurrency.providers.serial_lane",
            "noetrium_platform.foundation.kernel.concurrency.providers.timer",
        ),
        exact_call("threading.Thread"),
    ),
    SourceAuthorityRule(
        "concurrency.asyncio_task",
        "asyncio.create_task",
        ("noetrium_platform.foundation.kernel.concurrency.providers.async_io",),
        exact_call("asyncio.create_task"),
    ),
    SourceAuthorityRule(
        "concurrency.event_loop_task",
        "_loop.create_task",
        ("noetrium_platform.foundation.kernel.concurrency.providers.async_io",),
        suffix_call("_loop.create_task"),
    ),
    SourceAuthorityRule(
        "filesystem.atomic_replace",
        "os.replace",
        ("noetrium_platform.foundation.kernel.kernel.durability.durable_file",),
        exact_call("os.replace"),
    ),
    SourceAuthorityRule(
        "filesystem.interprocess_flock",
        "fcntl.flock",
        ("noetrium_platform.foundation.kernel.kernel.durability.file_lock",),
        exact_call("fcntl.flock"),
    ),
    SourceAuthorityRule(
        "filesystem.interprocess_windows_lock",
        "msvcrt.locking",
        ("noetrium_platform.foundation.kernel.kernel.durability.file_lock",),
        exact_call("msvcrt.locking"),
    ),
    SourceAuthorityRule(
        "concurrency.blocking_sleep",
        "time.sleep",
        ("noetrium_platform.foundation.kernel.concurrency.runtime.execution",),
        exact_call("time.sleep"),
    ),
    SourceAuthorityRule(
        "artifact.http_transport",
        "urllib.request.urlopen",
        ("noetrium_platform.evidence.artifact.content.providers.download",),
        exact_call("urllib.request.urlopen"),
    ),
    SourceAuthorityRule(
        "process.async_command_spawn",
        "asyncio.create_subprocess_exec",
        ("noetrium_platform.infrastructure.lifecycle.process.supervision.runtime.command_runner",),
        exact_call("asyncio.create_subprocess_exec"),
    ),
    SourceAuthorityRule(
        "service.process_spawn",
        "subprocess.Popen",
        ("noetrium_platform.infrastructure.lifecycle.service.runtime.linux_spawn",),
        exact_call("subprocess.Popen"),
    ),
    SourceAuthorityRule(
        "process.process_group_signal",
        "os.killpg",
        (
            "noetrium_platform.infrastructure.lifecycle.process.supervision.runtime.command_runner",
            "noetrium_platform.infrastructure.lifecycle.service.runtime.linux_signal",
        ),
        exact_call("os.killpg"),
    ),
    SourceAuthorityRule(
        "environment.external_action",
        "_environment_session.act",
        ("noetrium_platform.composition.workflows.context_action.action_effect_provider",),
        suffix_call("_environment_session.act"),
    ),
    SourceAuthorityRule(
        "environment.prepared_external_action",
        "_environment_session.execute_prepared_action",
        ("noetrium_platform.composition.workflows.context_action.action_effect_provider",),
        suffix_call("_environment_session.execute_prepared_action"),
    ),
    SourceAuthorityRule(
        "environment.effect_reconcile",
        "_environment_session.reconcile",
        ("noetrium_platform.composition.workflows.context_action.action_effect_provider",),
        suffix_call("_environment_session.reconcile"),
    ),
    SourceAuthorityRule(
        "environment.action_recovery_prepare",
        "_environment_session.prepare_action_recovery",
        ("noetrium_platform.composition.workflows.context_action.action_authorization",),
        suffix_call("_environment_session.prepare_action_recovery"),
    ),
    SourceAuthorityRule(
        "environment.action_recovery_reconcile",
        "_environment_session.reconcile_prepared_action",
        ("noetrium_platform.composition.workflows.context_action.action_effect_provider",),
        suffix_call("_environment_session.reconcile_prepared_action"),
    ),
    SourceAuthorityRule(
        "participant.checkpoint_capture",
        "adapter.checkpoint",
        ("noetrium_platform.capabilities.participant.session.runtime.checkpoint_runtime",),
        suffix_call("adapter.checkpoint"),
    ),
    SourceAuthorityRule(
        "participant.checkpoint_restore",
        "adapter.restore",
        ("noetrium_platform.capabilities.participant.session.runtime.checkpoint_runtime",),
        suffix_call("adapter.restore"),
    ),
    SourceAuthorityRule(
        "study.checkpoint_publish",
        "store.publish",
        ("noetrium_platform.research.experimentation.lifecycle.checkpoint.runtime.capture",),
        suffix_call("store.publish", "_store.publish"),
    ),
    SourceAuthorityRule(
        "effect_journal.prepare",
        "_effect_journal.prepare",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.prepare"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_result",
        "_effect_journal.record_result",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_result"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_reconciled",
        "_effect_journal.record_reconciled",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_reconciled"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_consumed",
        "_effect_journal.record_consumed",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_consumed"),
    ),
    SourceAuthorityRule(
        "effect_journal.record_not_applied",
        "_effect_journal.record_not_applied",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.record_not_applied"),
    ),
    SourceAuthorityRule(
        "effect_journal.pending_scope_read",
        "_effect_journal.unresolved_for_scope",
        ("noetrium_platform.research.execution.workflow.runtime.effect_intents",),
        suffix_call("_effect_journal.unresolved_for_scope"),
    ),
    SourceAuthorityRule(
        "capability.effect_prepare",
        "prepare_capability_effect",
        ("noetrium_platform.composition.workflows.agent_turn.capability_effect_provider",),
        suffix_call("prepare_capability_effect"),
    ),
    SourceAuthorityRule(
        "capability.effect_execute",
        "execute_prepared_capability",
        ("noetrium_platform.composition.workflows.agent_turn.capability_effect_provider",),
        suffix_call("execute_prepared_capability"),
    ),
    SourceAuthorityRule(
        "capability.effect_reconcile",
        "reconcile_prepared_capability",
        ("noetrium_platform.composition.workflows.agent_turn.capability_effect_provider",),
        suffix_call("reconcile_prepared_capability"),
    ),

)

__all__ = ["DEFAULT_SOURCE_AUTHORITY_RULES"]
